### ISSUE TITLE
Radiobuttons

### ISSUE THREAD

**Issue by buluthil** [JirkaDellOro/EIA2-Inverted#101]
Hallo :)

Warum kann ich bei den Radio buttons unten bei Geld Abheben/Einzahlen beide buttons anklicken, sollte nach meinem wissen nur eins angeklickt werden oder nicht ? was mache ich da falsch ?
<img width="1284" alt="Bildschirmfoto 2020-05-08 um 17 38 46" src="https://user-images.githubusercontent.com/43846406/81424239-ed6fdb80-9155-11ea-8a55-6bf35f4eec55.png">

hier der html code
view-source:file:///Users/hilalbulut/Documents/GitRepos/EIA-2/Aufgabe3/Aufgabe3.html

**Comment by Plagiatus** [comment]
Der Link den du da gepostet hast, ist ein Link auf deinen Computer, da können wir leider nicht drauf zugreifen. Du solltest deinen Code auf GitHub hochladen und den Link zum repository hier angeben, sowie den Link zur ausführbaren Datei.

Bis dahin könnte dieser Link dir weiterhelfen: https://wiki.selfhtml.org/wiki/HTML/Formulare/input/Radio-Buttons_und_Checkboxen

**Comment by JirkaDellOro** [comment]
Vielleicht noch mundgerechter hier, es ist in einem Satz erklärt und gehört uns...:
https://github.com/JirkaDellOro/EIA2-Inverted/tree/master/L03_FormElements#radiobutton

**Comment by buluthil** [comment]
Habe das Problem gelöst. Es lag daran das ich andere Werte im Attribut name hatte.
Vielen Dank :)
