### ISSUE TITLE
Steckbrief: Aufgaben öffnen sich nicht in einem extra TAB

### ISSUE THREAD

**Issue by weiberta** [JirkaDellOro/EIA2-Inverted#102]
Mir ist aufgefallen, dass wenn ich meine Aufgaben hochlade, sich meine Ergebnisse nicht in einem  externen Ladefenster öffnen, sondern auf der Seite in meinem Steckbrief laden. Das ist zum einen nervig als auch ungewollt. 
Gibt es eine Möglichkeit das zu beheben? Meine Links müssten _theoretisch_ richtig sein. 
Zwar geht es um die Abgabe, dennoch nervt es sehr ¯\_(ツ)_/¯

Liebe Grüße!

**Comment by Plagiatus** [comment]
Du musst dem Link sagen, dass er in einem neuen Tab geöffnet werden soll, siehe hier: https://www.w3schools.com/tags/att_a_target.asp

PS: ich glaube du hast das hier fallen gelassen: \

**Comment by weiberta** [comment]
Tatsache!! Vielen lieben Dank - wurde gefixt 
Und nochmal Danke für den Lacher haha :D

**Comment by Plagiatus** [comment]
Dann bitte den Issue schließen wenn es jetzt geht :)
