### ISSUE TITLE
Neuen Artikel hinzufügen 

### ISSUE THREAD

**Issue by luziagu** [JirkaDellOro/EIA2-Inverted#103]
Hallo Zusammen, 
ich würde gerne mit Hilfe eines Buttons eine neue Zeile bei meiner Einkaufsliste hinzufügen, sodass der User bei klick auf einen Button die Erste Zeile erweitern kann und so einen neuen Artikel hinzufügen kann. Allerdings komme ich nicht weiter, da ich nicht genau weiß wie ich die einzelnen Elemente (was, wie, wo) zusammenbringen kann. 
Um einen Schubs in die richtige Richtung wäre ich sehr dankbar. 
-Luzia 

https://github.com/luziagu/EIA2/tree/master/Formular
https://github.com/luziagu/EIA2/blob/master/Formular/Formular.pdf

**Comment by luziagu** [comment]
Besser formuliert vielleicht: Was muss in der Funktion passieren und macht der Aufbau in meinem HTML-Element so sinn, damit das funktioniert.

**Comment by JirkaDellOro** [comment]
Gut, dass Du dein Konzept zur Verfügung gestellt hast, da kann ich sehen was Du vorhast.

- Der Button zum Hinzufügen einer Zeile fehlt noch, korrekt?
- Wenn dynamisch Zeilen hinzugefügt oder entfernt werden können, muss Du sie auch dynamisch erzeugen, also in mit Hilfe deines Typescript-Codes.
- Du kannst sie also ganz aus dem HTML rauslassen, oder Du hast eine Zeile standardmäßig drin und erzeugst bei Programmstart einen Klon davon, siehe https://www.w3schools.com/jsref/met_node_clonenode.asp oder besser https://developer.mozilla.org/en-US/docs/Web/API/Node/cloneNode
-  Den Klon kannst Du dann immer weiter Klonen und die Klone deinem Formular an der richtigen Stelle anhängen. Das wäre recht effizient, zumal Du die Gestaltung weiter in HTML machen und leicht überprüfen kannst.

**Comment by luziagu** [comment]
Super, hat geklappt. Aber wie kann ich jetzt auf die einzelnen Klone zugreifen damit ich die Werte in die Bestellübersicht bekomme?  

Hier die neue Version: 
https://github.com/luziagu/EIA2/tree/master/Formular

**Comment by JirkaDellOro** [comment]
Sehr gut. Ich würde deinen Code gerne laufen lassen und wünsche mir einen Link zur App, dann kann ich mir anschauen, wie er sich verhält.

Ein Problem, das ich erwarte ist, dass die Klone natürlich alle dieselben Werte in den name-Attributen tragen und da FormData dir Namen-Wert-Paare liefert keine eindeutige Zuordnung mehr möglich ist. Du musst dann die Klone entsprechend manipulieren.

Bei Betrachtung deines Codes ist mir noch aufgefallen, dass Du zu Beginn deines Programms dir Referenzen auf bestimmte HTMLElemente zusammensuchst
```typescript
    cloneDiv = document.querySelector("#cloneDiv"); 
    householdTask = document.querySelector("#householdTask");
    cloneDivTask = document.querySelector("#cloneDivTask");
```
später dann aber sie doch immer wieder erneut suchen lässt anstatt mit diesen Referenzen zu arbeiten.

**Comment by luziagu** [comment]
Hallo Jirka, 
Hier der Link zur App: https://luziagu.github.io/EIA2/Formular/formular.html
Genau an dem Problem mit den selben Werten hänge ich jetzt fest. Wie kann ich die Klone einzelne manipulieren? 

Das mit den Referenzen werde ich mir mal anschauen. Danke für die Ausführliche Antwort und die Tipps. 
- Luzia :)

**Comment by JirkaDellOro** [comment]
Toll, wie Du das mit den Klonen hinbekommen hast. Diese sind ja wieder ein Stück DOM, darin liegt unter anderem ein Select für die Ware  (was noch keinen Namen hat!) und ein Slider für die Menge. Du kannst auf jedem Klon beispielsweise wieder `querySelector` ausführen um an diese Elemente heranzukommen und die Namen zu ändern, vielleicht indem Du einfach eine fortlaufende Nummer dranhängst.
