### ISSUE TITLE
Haushaltshelfer FehlerMeldung Uncaught

### ISSUE THREAD

**Issue by FrankeSa** [JirkaDellOro/EIA2-Inverted#104]
Hallo,

ich habe leider ein paar Baustellen:

1.) Ich habe den Code weitestgehend von der Übung Cocktailbar übernommen. 
Meine Code-Zeile sieht so aus: 
![image](https://user-images.githubusercontent.com/56167839/81472662-e26e8700-91f9-11ea-90f9-9e46f7907260.png)
Wenn ich nun einen Artikel auswählen möchte erscheint er mir nicht auf der rechten Seite, sondern es gibt eine Fehlermeldung. 
![image](https://user-images.githubusercontent.com/56167839/81472690-0a5dea80-91fa-11ea-9e3d-b2834abb0024.png)
Ich habe, meiner Meinung nach, alle relevanten Preise in HTML als Attribut Price hinterlegt. Wie kann ich die Ausgabe so gestalten, dass mir z.B. Artikel: Brot, Menge: 1 Liter 0.40 € Einzelhandel: Edeka ausgegeben wir?

2.) Ich habe für jedes Fieldset einen Button vorgesehen, der bei Klick die einzelnen Werte des jeweiligen Fieldsets wieder zurück setzen (löschen) soll. Zur Probe sollte bei Klicken der erste Butten "Halloo" ausgeben. Das erscheint auch kurz in der Console, verschwindet dann aber wieder. Es werden die Werte sogar wirklich gelöscht (und zwar von jedem Fieldset), obwohl ich hierzu noch nichts programmiert habe.  Ich kann mir das nur so vorstellen, dass das hiermit zu tun hat 
![image](https://user-images.githubusercontent.com/56167839/81472915-404f9e80-91fb-11ea-8d6c-0bc2f3a47eea.png). 
Wenn ich den Button aber nicht innerhalb des Div-Elements habe, dann müsste ich pro Fieldset ein Butten unten einfügen und dem eine Löschfunktion pro gewünschtes Fieldset geben. Kann ich die Button in dem Div bzw. im Fieldset lassen?

3.) Wie kann ich bei der Ausgabe auch den Fieldset-Name bei mir z.B. Einkäufe ausgeben lassen?

Link zum Repo: https://github.com/FrankeSa/EA2-Inverted/tree/master/L03_FormElements/Haushaltshelfer
Link zur Page: https://frankesa.github.io/EA2-Inverted/L03_FormElements/Haushaltshelfer/index_HH_Helfer.html
Link zum UI PDF: https://github.com/FrankeSa/EA2-Inverted/blob/master/L03_FormElements/Haushaltshelfer/UserInterface_Haushaltshilfe.pdf

Ich hoffe die Fragen

**Comment by JirkaDellOro** [comment]
1. Ich hatte mich gewundert, wieso handleChange aufgerufen wird, obwohl noch keine Interaktions kam. Nachdem ich einen Breakpoint auf Zeile 17 gesetzt hatte konnte ich schauen, wo der Aufruf herkommt. Du hast in Zeile 38 einen expliziten Aufruf drin der ausgeführt wird noch bevor überhaupt das Formular existiert.
2. Ich vermute, Du bist hier auf eine fiese Eigenheit der HTML-Formulare gestoßen. Buttons darin sind standardmäßig "Submit"-Buttons und der Browser versucht bei Betätigung das Formular abzuschicken. Da es aber dafür nicht vorgesehen ist, ruft er die Seite erneut auf. Du musst bei den Buttons explizit das `type`-Attribut mit "button" definieren.
3. Die kriegst Du nicht durch FormData, da es keine Formularelemente sind. Was Du vielleicht machen könntest, wären versteckte Formularfelder einzubauen, die existieren aber nicht angezeigt werden. Siehe https://www.w3schools.com/tags/att_input_type_hidden.asp

**Comment by FrankeSa** [comment]
Hallo,

ich habe das Problem, dass er mein Senden-Button einfach nicht findet.
Ich lege ihn an und möchte eine console.log Ausgabe aber er gibt mir null zurück.
![image](https://user-images.githubusercontent.com/56167839/82342311-c33dd980-99f1-11ea-99c5-5e48e892bcb1.png)

Deswegen kommt in der Konsole eine Fehlermeldung.

Außerdem findet er keine Preis, wenn ich einen Artikel auswähle, obwohl ich im Interface einen Preis hinterlegt habe.
![image](https://user-images.githubusercontent.com/56167839/82342680-347d8c80-99f2-11ea-9e54-070f75c728df.png)

Ich finde den Grund nicht, warum Submit null ist bzw. die Fehlermeldung zu ts Zeile 39 auftaucht.

Link zum Repo: Link zum Repo: https://github.com/FrankeSa/EA2-Inverted/tree/master/L05_Client/L05_Haushaltshelfer
 Link zur Seite:
https://frankesa.github.io/EA2-Inverted/L05_Client/L05_Haushaltshelfer/index_HH_Helfer.html

**Comment by JirkaDellOro** [comment]
- "button [type=button]" enthält ein Leerzeichen, da könnte ein Problem liegen.
- beim Auswerten des Formulares schickst Du alle Elemente durch den gleichen Schleifenrumpf, obwohl sie sehr unterschiedlich sind. Der Fehler tritt bei "Geld einzahlen" auf, hat das einen Preis?
