### ISSUE TITLE
L03 formData undefined

### ISSUE THREAD

**Issue by Matej-Sulfrian** [JirkaDellOro/EIA2-Inverted#105]
Ich habe ein Problem mit dem übernehmen der Daten aus meinem Form.
Im Debugger werden item, price usw. als undefined angegeben und dem entsprechend wird in der Bestellliste nichts ausgegeben. Eben so wenig in der Konsole (nach console.log(formData)). Allerdings werden auch keine Fehlermeldungen in der Konsole angegeben. Daher weis ich leider nicht wie ich dem Problem auf den Grund gehen kann.
Hier der Link zu dem entsprechenden Ordner in meinem Repo.:
https://github.com/Matej-Sulfrian/Matej-Sulfrian/tree/master/EIA2/L03_Hilfsformular
![Bildschirmfoto 2020-05-09 um 14 52 41](https://user-images.githubusercontent.com/56194456/81474736-b0fcb800-9207-11ea-9dc3-19adee43729a.png)

**Comment by JirkaDellOro** [comment]
Siehe #97
