### ISSUE TITLE
Aufgabe Haushaltshilfe

### ISSUE THREAD

**Issue by klinkewitzn** [JirkaDellOro/EIA2-Inverted#106]
Hallo, ich habe einige Probleme beim coden gehabt und trotz viel herumprobieren vieles nicht lösen können. Warum werden meine Funktionen handleChangeBanking und submitOrder nicht aufgerufen? Außerdem habe ich auch große Probleme beim Zugreifen auf die Werte der checked-Boxen gehabt. Bei Aufruf der Funktion handleChangeChores wollte ich mir die gecheckten Werte in der Konsole anzeigen lassen, jedoch wird ausschließlich das FormData Array aus der Funktion handleChangeGrocery angezeigt.
Weitere Probleme und meine Vermutungen: Dass der Wert bei Grocery bei der Menge(1) 4mal angezeigt wird, liegt daran, dass ich eine Schleife benutzten sollte, richtig?
Dass es Probleme im Debugger gibt sobald ich die Menge in Grocery ändere, hat damit zu tun, dass Amount ein Input-Feld vom Typ String ist, statt number?

Link zum Code: https://klinkewitzn.github.io/EIA2/Lektion3/haushaltshilfe.html
Repository: https://github.com/klinkewitzn/EIA2/blob/master/Lektion3/haushaltshilfe.html

**Comment by JirkaDellOro** [comment]
Dein Javascript-Kompilat entspricht nicht deinem TypeScript-Code, offensichtlich wurde nicht kompiliert. Das müsstest Du als erstes beheben, dann kann man schauen, welches deiner Probleme noch übrig bleibt.

**Comment by klinkewitzn** [comment]
Tatsächlich. Habe es gerade erneut kompililiert und die Probleme aus dem oberen Absatz haben sich erledigt (mit Ausnahme, dass ich es nicht hinbekomme mir die Werte der gecheckten Boxen ausgeben zu lassen). 
Wenn Sie mir außerdem noch Hilfestellung zu den Problemen im 2. Absatz geben könnten wäre das toll. :)

**Comment by JirkaDellOro** [comment]
Ich denke, Du hast dich ein wenig verrannt und dein Diagramm ist an der Stelle leider etwas zu grob, als dass ich erkennen könnte, was genau Du vorhast. Du schriebst
```typescript
    let fd: FormData = new FormData();
    fd.append("Article", article.value);
    fd.append("Amount", amount.value);
    fd.append("Unit", unit.value);
    fd.append("Shop", shop.value);
    console.log(Array.from(fd));

    for (let obj of fd) {
        console.log(obj);
        let amount: number = Number(fd.get("Amount"));
        let item: HTMLInputElement = <HTMLInputElement>document.querySelector("[value='" + obj[1] + "']");
        let price: number = Number(item.getAttribute("price"));
        displayGroceries.innerHTML += article.value + ", " + amount + " " + unit.value + ",  " + shop.value + ",  " + price + "€" + "<br>";
    }
```
Davor hast Du dir per `querySelector` Referenzen zu den HTML-Elementen `article`, `amount`, `unit` und `shop` im DOM geholt. Nun füllst Du ein FormData-Objekt mit den `value`-Attributen dieser Elemente. Damit scheinst Du es genau umgekehrt zu machen, als es eigentlich gedacht ist. Mit FormData kannst Du dir bequem die Daten aus einem Formular holen und weiter verarbeiten, der Vorteil ist ja, dass es automatisch befüllt wird. 

Bei deinem Ansatz kann ich mir vorstellen, dass Du eine Struktur suchst, mit der Du bei Klick auf den Add-Button den Inhalt des aktuell angezeigten "Groceries"-Abschnitts speichern kannst, um die Sammlung derselben in deiner Bestellübersicht anzuzeigen. Liege ich da richtig? Gerne tüftele ich das mit dir weiter aus, da sollten wir zunächst nochmal ans Konzept.

**Comment by klinkewitzn** [comment]
> Bei deinem Ansatz kann ich mir vorstellen, dass Du eine Struktur suchst, mit der Du bei Klick auf den Add-Button den Inhalt des aktuell angezeigten "Groceries"-Abschnitts speichern kannst, um die Sammlung derselben in deiner Bestellübersicht anzuzeigen. Liege ich da richtig?

 Ja, genau so war es gedacht. Vielen Dank für das Angebot! Leider komme ich mit der Zeit nicht mehr hin, um mich weiter mit dieser Aufgabe zu beschäftigen/zu vertiefen.

**Comment by JirkaDellOro** [comment]
Die Aufgabe läuft noch eine Weile, Du wirst Gelegenheit haben.
