### ISSUE TITLE
Radio-Input

### ISSUE THREAD

**Issue by luziagu** [JirkaDellOro/EIA2-Inverted#107]
Ich habe ein Problem bei der Auswahl von den Radio-Input-Feldern. Wenn ich eine neue Zeile aufrufe und die Zeile mit Wöchentlich-Täglich usw. auswählen möchte springt die Auswahl der Zeile davor weg und es ist dort nichts mehr ausgewählt. Auch wenn ich die Auswahl beim Einkaufen tätige und danach bei den Haushaltsaufgaben wird der Wert bei den Einkaufen null und es ist nichts ausgewählt. Woran liegt dies? 

Repository: https://github.com/luziagu/EIA2
Link zur App: https://luziagu.github.io/EIA2/Formular/formular.html

-Luzia

**Comment by Plagiatus** [comment]
Radiobuttons die das gleiche NamensAttribut haben, gehören der selben Gruppe an. Bei dir haben alle Radiobuttons den gleichen Namen, dadurch gehören sie alle zur selben Gruppe.
