### ISSUE TITLE
Viele Nachkommastellen;Endkosten stimmen nicht

### ISSUE THREAD

**Issue by vschwan** [JirkaDellOro/EIA2-Inverted#108]
Hi! 
Ich habe ein paar Issues zur letzten Aufgabe,  ich glaube, die hängen teilweise zusammen. 

1. Zum einen verstehe ich nicht, wie ich diese Fehlermeldung hier bekomme, da ich Zugriff auf das Attribut price habe. Kann ja immerhin damit auch rechnen. Außerdem ist der DOM ja geladen, oder?
![WhatsApp Image 2020-05-11 at 17 02 08](https://user-images.githubusercontent.com/56428408/81577705-0ffa3280-93aa-11ea-968f-77543d68f64f.jpeg)

2. Die Zahlen werden mir teilweise mit mehreren Nachkommastellen ausgegeben, obwohl nach meiner Erwartung zum Beispiel bei einer Rechnung von 0.3*4.5 das Ergebnis nur 1.35 sein dürfte. stattdessen bekomme ich 1.3499999999...ausgegeben. Math.round hilft nicht. Oder ich setze es an die falsche Stelle....
![WhatsApp Image 2020-05-11 at 17 01 47](https://user-images.githubusercontent.com/56428408/81577736-1c7e8b00-93aa-11ea-989c-9cb6966f1feb.jpeg)

3. Die Endkosten stimmten teilweise nicht, ich konnte das Problem lösen, indem ich statt totalcost.toFixed(2), totalcost.toFixed(10) (ts:216) geschrieben habe. 
Wenn ich aber ein span im "order" div  lösche, habe ich teilweise das Problem, dass die Endkosten sich nicht entsprechend anpassen. Selbst wenn alle spans gelöscht sind, stehen noch Endkosten da.
Woran liegt das? 

![WhatsApp Image 2020-05-11 at 17 01 24](https://user-images.githubusercontent.com/56428408/81577764-299b7a00-93aa-11ea-93c7-ca4746ef94c8.jpeg)

Würde mich freuen, wenn man mir da weiterhelfen könnte! 

Valentina Schwan 

Code:  https://vschwan.github.io/EIA2/03/haushaltshilfe/haushaltshilfe.html
Konzept: https://vschwan.github.io/EIA2/03/haushaltshilfe/Haushaltshilfe%20diagramme.pdf
repository: https://github.com/vschwan/vschwan.github.io/tree/master/EIA2/03/haushaltshilfe

**Comment by JirkaDellOro** [comment]
1.  Du musst schauen, ob Du nicht noch mehr Elemente findest als Du brauchst, oder mehr suchst als Du finden kannst. Wenn querySelector kein Element findet, ist der Wert von `item` null und Du solltest nicht damit arbeiten sondern ggf. die Schleife gleich in die nächste Iteration schicken.
2. nutze toFixed(...)
3. wann berechnest Du die Kosten?

**Comment by vschwan** [comment]
1. Vielleicht steh ich gerade auf dem Schlauch, aber ich versteh den letzten Satz nicht. Ich hol mir ja das Attribut am Anfang in der for-Schleife, damit ich darauf in den folgenden Schleifen zugreifen kann. Wie soll ich da eine Schleife ggf. gleich in die nächste Iteration schicken? 
2. Yes, funktioniert! 
3. Hab das Problem grad gefunden! Hat sich also erledigt 🥳 
Danke für die Antwort 😄

**Comment by JirkaDellOro** [comment]
zu 1.
FormData gibt dir die name-value-Paare, Damit gehst Du auf die Suche nach den Items, indem Du nach jenen suchst, deren value-Attribute dem von FormData gelieferten value entsprechen. Das hat bei der Cocktailbar noch ganz gut funktioniert, wird hier aber mittelfristig nicht ausreichen, weil Du mehrere Items mit gleichen Value haben wirst. Aber das ist derzeit nicht so problematisch.
Dein akuter Fehler hängt aber damit zusammen, denn FormData liefert dir auch die Informattion für die "amount"-Elemente, die Du aber mit der Suche nach dem value-Attribut nicht bekommst, da deren Wert sich ändert. In der Cocktailbar hatte ich den Slider auch extra abgefangen, da er nicht in das Schema passt.
Eine kurzfristige Lösung für dich könnte also sein zu prüfen, ob querySelector erfolgreich war und ein item geliefert hat. Wenn das Ergebnis aber den Wert `null` hat, also kein item gefunden wurde, kannst Du mit der Anweisung continue die nächste Iteration ausführen und also das nächste name-value-Paar aus FormData untersuchen lassen.

**Comment by vschwan** [comment]
da bin ich wieder, hat etwas gebraucht bei mir 😅 
Also ich habe das Problem gelöst mit  if (item === null) { continue; } in der for schleife. Die Fehlermeldung erscheint jetzt nicht mehr. 
Das eigentliche Problem und die Lösung dazu habe ich aber verstanden, ich denke, ich setze das auch noch um.
Danke für deine Hilfe 😃

**Comment by JirkaDellOro** [comment]
Schließe bitte den Issue, wenn er geklärt ist. Der Titel scheint ja nicht mehr relevant zu sein....
