### ISSUE TITLE
Marktnamen werden nicht gefunden

### ISSUE THREAD

**Issue by k-poschmann** [JirkaDellOro/EIA2-Inverted#109]
Hallo, 
bei mir funktioniert jetzt fast alles aber die Marktnamen werden nicht gefunden und ich weiß nicht genau wo der Fehler liegt. Bei der Ausgabe wird mir 'null' angezeigt...vielleicht könnt ihr mir helfen :)

Link zum Repository:  https://github.com/k-poschmann/poschmannEia2/tree/master/Aufgabe_4
Link zum Konzept: https://github.com/k-poschmann/poschmannEia2/blob/master/Aufgabe_4/HH_Data.pdf

Liebe Grüße, Kristin

**Comment by JirkaDellOro** [comment]
```typscript
    let market: string = String(formData.get("Ort"));
```
Formdata sammelt die Informationen for Formularelementen als name-value-Paare. Du erwartest offensichtlich einen Wert zu dem Namen "Ort". Wo ist das Namensattribut "Ort" zu finden? Derzeit sehe ich nur ein id-Attribut "Ort" an einem Fieldset.

**Comment by k-poschmann** [comment]
Das Namensattribut wurde im Interface gespeichert....oder verstehe ich das falsch?

**Comment by JirkaDellOro** [comment]
FormData sammelt aus den HTMLElementen im DOM, es muss also dort auftauchen, wenn es in die Sammlung mit rein soll.

**Comment by k-poschmann** [comment]
Achso.. alles klar :)
Problem hat sich gelöst. Vielen Dank!
ich werde den Issue dann schließen.
