### ISSUE TITLE
Probleme mit Linter

### ISSUE THREAD

**Issue by DominikWieck** [JirkaDellOro/EIA2-Inverted#110]
![image](https://user-images.githubusercontent.com/56441910/82038125-5c43bc00-96a3-11ea-9f0d-0df787d5da99.png)

Komme grade mit dem Linter nicht klar, obwohl ich die aus EIA 2 nutze. Irgendwas scheint nicht zu stimmen.

Folgende Fehlermeldung erscheint: 

![image](https://user-images.githubusercontent.com/56441910/82038221-81382f00-96a3-11ea-88d0-90ff87321e92.png)

Link zu Repo: https://github.com/DominikWieck/dominikwieck.github.io/tree/master/EIA2
Link zu Codes: https://github.com/DominikWieck/dominikwieck.github.io/tree/master/EIA2/Lektion04

**Comment by JirkaDellOro** [comment]
Zwei Dinge fallen mir auf
- der Ordner hat einen sonderbaren und unschönen Namen mit Leerzeichen und Bindestrichen. Im Repository finde ich den nicht. Sehen wir denselben Code?
- Du hast das interface Item mit den zwingenden Attributen name und price definiert, nutzt in data aber Einträge ohne price. Da soll der Linter motzen. Wenn das Attribut optional sein soll, deklariere es im Interface mit einem Fragezeichen.
```typescript
    interface Item {
        name: string;
        price?: number;
    }
```

**Comment by Plagiatus** [comment]
da fehlt vorallem ein`=` hinter dem `let data: Data` in der ersten Zeile..

Immer beim ersten Fehler anfangen.

**Comment by JirkaDellOro** [comment]
...und der ist mir nicht aufgefallen 🤦

**Comment by DominikWieck** [comment]
Uh, okay war wirkich nur das = 

Danke euch 💯
