### ISSUE TITLE
Dynamische Generierung des Formulars

### ISSUE THREAD

**Issue by luziagu** [JirkaDellOro/EIA2-Inverted#111]
Guten Morgen, 
ich habe versucht mein Formular dynamisch zu generieren. Jetzt klemmt es aber ein klein bisschen. Bei meinen Hausarbeiten (householdtasks) werden Checkboxen generiert. Hier wird aber der Preis nicht in die Bestellungsliste übernommen und auch manchmal nur die zuvor ausgewählte Arbeit (z.B. Gassi gehen). Ich habe versucht mit Hilfe des Debuggers die Fehler zu finden, aber komme nicht weiter. 
Offensichtlich wird ja an einer Stelle der Wert (Preis) nicht mehr weiter übergeben bzw. übernommen, oder? Müsste ich auch die einzelnen Span-Elemente die für die Bestellübersicht (in der script.ts-Datei  erzeugt werden) in meiner genervteContent ts.Datei dynamisch erstellt werden oder müsste dies dort aufgerufen werden? 
Die eigentliche Script-Datei ist ja für den generellen Ablauf meiner Seite verantwortlich, oder? Die generateContent nur für die dynamische Generierung?

Danke schonmal im Voraus, Luzia :)

https://luziagu.github.io/EIA2/Haushaltshilfe-Update%20/haushaltshilfe.html
https://github.com/luziagu/EIA2/tree/master/Haushaltshilfe-Update%20

**Comment by JirkaDellOro** [comment]
Sprichst Du von diesem Fehler?
```
caught TypeError: Cannot read property 'getAttribute' of null
    at HTMLButtonElement.handleChange (script.ts:96)
```

**Comment by JirkaDellOro** [comment]
> Die eigentliche Script-Datei ist ja für den generellen Ablauf meiner Seite verantwortlich, oder? Die generateContent nur für die dynamische Generierung?  

Diese Trennung erscheint mir jedenfalls sehr sinnvoll.

**Comment by luziagu** [comment]
Ja genau das ist der Fehler. An dem hänge ich irgendwie immer noch. Dem Einkauf wird der Preis NaN zugewiesen. Heißt das er findet den Preis der dem Produkt zuvor in der Data.ts Datei zugewiesen wurde nicht?

**Comment by obiwan1337** [comment]
Das NaN bedeutet _Not a Number_ und weist also auf einen Wert hin, der keine Nummer ist. Eventuell hilft hier eine Abfrage des Wertes, den du zuweist.

**Comment by luziagu** [comment]
<img width="460" alt="Bildschirmfoto 2020-05-18 um 20 39 11" src="https://user-images.githubusercontent.com/56430460/82248049-c8dee500-9947-11ea-883c-ee51fbac9f71.png">

Ja, also meine Idee war es jetzt hier aus dem Array ein neues Attribute "Price" zumachen. Dann könnte ich damit in meiner Datei generateContent durch setAttribute den Preis anzeigen lassen und der Fehler NaN würde nicht mehr erscheinen. Allerdings wäre dies jetzt relativ aufwendig alles umzustrukturieren. Gibt es eine einfachere Variante wie ich auf den Preis direkt zugreifen kann, sodass er erkannt wird? Irgendwie stehe ich auf dem Schlauch. 

Grüße, Luzia

**Comment by JirkaDellOro** [comment]
Zunächst ein paar Hinweise am Rande:
- deine Checkboxen haben alle die gleiche id, deswegen funktionieren die Label nicht. Ids sollen eindeutig sein, sonst sind es keine ids.
- für die interne Verarbeitung sollte man immer englische Begriffe wählen, also nicht "Wäsche waschen". Umlaute und Leerzeichen machen of Probleme. Das musst Du jetzt nicht ändern, wenn es funktionieren sollte, aber bitte merken


Zum Problem:
Die Konsole meldet mir den Fehler in Zeile 98, also setze ich im Debugger einen Breakpoint in Zeile 98. Dann kann ich zuschauen, mit welchen entries und items dein Programm hier ankommt. 
- zuerst kommt "HouseholdTasks", da habe ich mich schon gefragt, ob es Sinn ergibt, hier den Preis abzufragen
- dann kommt ein Item mit der id "Household", die haben aber leider einige, in entry kann ich aber sehen, dass "Gassi gehen" gemeint ist. Das ist auch die angewählte Checkbox
- dann kommt ein `null`, es wurde also kein item gefunden. In entry sehe ich, dass gerade das Feld mit dem Namen "Amount" untersucht wird. 

Das Formularelement "Amount" aber möchtest Du in Zeile 99 offensichtlich ohnehin selbst suchen und auswerten, es wird also anders behandelt. Daher solltest Du es vorher schon abfangen und nicht durch den gleichen Algorithmus schicken wie die anderen...

Bitte passe nicht die Datenstrukturen dem möglicherweise ungeeignetem Algorithmus an, das ist der falsche Weg. Deswegen gibt es auch das eigene Kapitel zu Datenstrukturen. Datenstrukturen bestimmen den Algorithmus, der mit ihnen umgehen soll, nicht umgekehrt.

**Comment by luziagu** [comment]
Vielen Dank Jirka! 
Die Eindeutigkeit der id's werde ich in Zukunft beachten und auch die interne Verarbeitung werde ich beherzigen. 
Die Fehler in der Konsole kann ich bestätigen, dass war bei mir ebenso der Fall. Ich werde versuchen den Fehler mit deinen Tipps zu verbessern, aber mich jetzt erstmal auf die nächste Aufgabe konzentrieren, so wie du es im Workshop gesagt hattest. 
Gruß, Luzia
