### ISSUE TITLE
Input type: number log falsche werte + Frage zu Textarea + Checkbox

### ISSUE THREAD

**Issue by Lum7n** [JirkaDellOro/EIA2-Inverted#113]
1. der Stepper (mit dem die Anzahl der Artikel eingestellt werden sollte/kann, sowie der der für Haushaltsaufgaben zuständig ist) loggt in der Tabelle darunter entweder garnicht oder nur wenn der Wert 0 ist und dann die eingestellte Zahl auf dem Slider, welcher nichts mit den jeweiligen anderen Sektionen zu tun hat.
Ich finde nichts welches diese Inputs in Verbindung setzt... help
![zu_1](https://user-images.githubusercontent.com/56406099/82125205-b6787600-97a4-11ea-8902-173b3d1bf46e.png)

2. außerdem würde ich gerne in Sektion 4: Anderes, das vom Kunden eingetippte abgreifen und darunter in die Tabelle schreiben, ich hab schon einiges probiert aber nichts funktioniert.
script.ts ab Z112

3. ich würde in Sektion 3: Haushalt, wenn mehrere Checkboxen angeklickt sind die Werte zusammen in eine Tabellen-Zelle schreiben, ich bekomme sie aber lediglich in mehrere hintereinander.
script.ts ab Z157

https://github.com/Lum7n/EIA2/blob/master/L04_DataStructure/script.ts

**Comment by JirkaDellOro** [comment]
Bitte poste hier einen Link auf die Browser-App

**Comment by Lum7n** [comment]
https://lum7n.github.io/EIA2/L04_DataStructure/Index.html

**Comment by JirkaDellOro** [comment]
1. Du musst schauen, ob querySelector überhaupt erfolgreich war und dir ein Item geliefert hat
   1. möglicherweise ist der Wert der Variable item kein Verweis auf ein HTMLElement, sondern einfach `null`
   2. es ist auch möglich, dass ein Item gefunden wird, es aber nicht das von dir gesuchte Attribut (z.B. price) enthält. Auch das sollte abgefangen werden, wenn es keine Fehler geben soll
1. Diese einfache Datenbehandlung aus der Cocktailbar, in dem über das FormData-Objekt iteriert wird, ist nicht für alle Anwendungsfälle sinnvoll und praktikabel. In deinem Fall ist es sicher besser, gezielt auf die Information zuzugreifen. Also entweder direkt im DOM nach dem Element zu suchen um die Werte auszulesen, oder wenn Du FormData nutzt dort mit `get` den gesuchten Wert abzufragen. Schleifen sind kein Allheilmittel...
1. auch hier musst Du einen eigenen Algorithmus entwerfen.
