### ISSUE TITLE
Datastruktur geändert

### ISSUE THREAD

**Issue by Cari1512** [JirkaDellOro/EIA2-Inverted#114]
Hallo,

ich habe mein Interface für die Data.ts geändert, aber jetzt zeigt er mir an, dass das Interface von Data nicht mehr gefunden wird(?). Ich weiß nicht was schief gelaufen ist, ob ich irgendwelche Klammern o.ä. falsch gesetzt habe etc.. Auf jeden Fall kommt jetzt bei Data folgende Fehlermeldung: "'Data' refers to a value, but is being used as a type here.". 
![Screenshot (88)](https://user-images.githubusercontent.com/56436935/82304148-39bfe480-99bc-11ea-8966-7dbe9076b96a.png)
![Screenshot (89)](https://user-images.githubusercontent.com/56436935/82304152-3af11180-99bc-11ea-9cb9-dee7f6acc558.png)

Außerdem wird bei meiner Data Datei der namespace Haushaltshilfe nicht mehr gelesen(?)"'Haushaltshilfe' is declared but its value is never read". Ich dachte der namespace beschreibt einfach nur wozu diese Datei gehört...

Vielen Dank schonmal für die Hilfe!

**Comment by JirkaDellOro** [comment]
- Schicke bitte die Fehlermeldungen mit. 
- Variablennamen in camelCase schreiben! 
- sämtliche Namen in englisch schreiben! also nicht "Haushaltshilfe" für einen Namespace. Deutsch darfst Du nur verwenden für Texte, die dem Nutzer präsentiert werden.
