### ISSUE TITLE
Fehler "Fesch API cannot Load" erscheint nicht. 

### ISSUE THREAD

**Issue by luziagu** [JirkaDellOro/EIA2-Inverted#115]
Heute in dem Workshop wurde das Thema schon kurz angesprochen. Ich weiß nicht mehr ganz was das Problem, weshalb dieser Fehler erscheint nicht erscheint. Wenn ich es richtig in Erinnerung habe war die Rede davon, dass der Browser(?) gehackt wurde. Ich bin mir da jetzt aber überhaupt nicht mehr sicher und wollte deswegen jetzt noch einmal nachfragen. Woran liegt es, dass der Fehler in meinem Programm nicht erscheint? Mit was hängt dies zusammen? Und, wie kann ich das Problem beheben. 

Der Fehler von dem ich spreche der bei Jirka angezeigt wird. 
<img width="640" alt="Bildschirmfoto 2020-05-19 um 22 27 52" src="https://user-images.githubusercontent.com/56430460/82374888-0151f200-9a20-11ea-93a8-9a6412362f9a.png">

Meine Funktion. Der Fehler wird in der Konsole nicht angezeigt. 
<img width="827" alt="Bildschirmfoto 2020-05-19 um 22 28 46" src="https://user-images.githubusercontent.com/56430460/82374962-20508400-9a20-11ea-801c-168fb7a3c625.png">

Link zu meiner App: https://luziagu.github.io/EIA2/Haushaltshilfe-Update%20/haushaltshilfe.html
Link zu meinem Ordner im Repository: https://github.com/luziagu/EIA2/tree/master/Haushaltshilfe-Update%20

-Luzia

**Comment by AionixX** [comment]
Hi Luzia,

zuallererst, du arbeitest auf einem Mac oder? Ich hatte Probleme dein Repository zu öffnen da du Systemdateien mit hoch geladen hast. Bitte mache folgendes:

- Ziehe die .DS_Store Datei in einen anderen Ordner
- Erstelle einen commit und pushe dein Repository (jetzt ohne die Systemdatei) auf Github
- Füge deinem Ordner eine .gitignore Datei hinzu
- In der Datei solltest du sicher stellen dass .DS_Store Dateien nicht mit auf Github hochgeladen werden
- Falls die Datei in dem Ordner gebraucht wird kannst du sie jetzt wieder in deinen Ordner ziehen
- Nun kannst du wieder ganz normale commit machen ohne dass die Datei erneut mit hochgeladen wird

Kurz zu .gitignore Dateien: 
.gitignore Dateien sagen deinem System welche Dateien er auf github hochladen soll und welche nicht. Das ist ziemlich nützlich damit nicht auch alle temporären Dateien oder Dateien die nur für versuche gemacht worden auf github landen.
Es gibt eine [Website](https://www.gitignore.io/) auf der du dir solche Dateien runter laden kannst. Gib dort einfach an dass du mit macOS arbeitest und speicher die Datei die er dir ausspuckt in der obersten Ebene deines Repositorys. Du kannst auch weitere Angaben machen wie zum Beispiel Visual Studio Code, dann werden temporäre Dateien von VSC auch nicht mit hochgeladen.


Nun zu deiner Frage.

Ich habe deinen Code ausprobiert und bei mir spuckt die Console die "gewünschte" Fehlermeldung aus. Hast du auch Auf "Senden" geklickt?

Du kannst mir gerne eine Email schreiben, dann treffen wir uns in Alfaview und können dem Problem auf den Grund gehen falls der Fehler bei dir weiterhin besteht.

**Comment by luziagu** [comment]
Ja ich arbeite auf einem Mac. Das mit den Dateien werde ich machen. 

Zu meiner Frage. 
Ja genau ich habe auf "Fertig/Abschicken" geklickt. Bei mir kommt die Fehlermeldung nicht. Sehr gerne können wir das in Alfaview besprechen. Wo finde ich den deine E-Mail Adresse?

**Comment by luziagu** [comment]
Die .DS_Store Datei finde ich nicht auf meinem lokalen Ordner.

**Comment by AionixX** [comment]
Meine Email Adresse: dennis.hawran@hs-furtwangen.de

**Comment by AionixX** [comment]
Ich bin jetzt aber auch im Alfaview Raum DM-16
Kannst also einfach vorbei kommen

**Comment by JirkaDellOro** [comment]
Wenn ihr fertig seid, bitte den Issue schließen
