### ISSUE TITLE
Lektion 5 cocktail bar 

### ISSUE THREAD

**Issue by klinkewitzn** [JirkaDellOro/EIA2-Inverted#116]
![20200520_103140](https://user-images.githubusercontent.com/56318063/82428545-f1bbc300-9a8a-11ea-9b63-8167b07fb170.jpg)

![20200520_103232](https://user-images.githubusercontent.com/56318063/82428614-07c98380-9a8b-11ea-8f01-2f30d3916500.jpg)

Hallo, 
Wenn ich den Code der Lektion 5 cocktail bar öffne werden mir keine Auswahlmöglichkeiten angezeigt (also alles was dynamisch generiert wird.)  Woran liegt das? 
Ich habe es mit und ohne eingebundener data.json Datei ausprobiert.

**Comment by AionixX** [comment]
Verlinke bitte dein Repository und deine Pages Seite damit ich mir das anschauen kann

**Comment by JirkaDellOro** [comment]
Und schicke auch die Konsolenausgaben des Browsers mit

**Comment by klinkewitzn** [comment]
Repository: https://github.com/klinkewitzn/EIA2/tree/master/Lektion5/CocktailBar
Pages: https://klinkewitzn.github.io/EIA2/Lektion5/CocktailBar/index.html

Konsolenausgabe: 
![Konsolenausgabe](https://user-images.githubusercontent.com/56318063/82547111-7d038a00-9b59-11ea-9f59-f7cb85221abb.PNG)

**Comment by klinkewitzn** [comment]
Das any ist das was wir schon mehrmals in der Lektion angesprochen hatten (was man als Deklaration für formData braucht).

**Comment by JirkaDellOro** [comment]
Schreibe bitte noch dazu, was das Problem war
