### ISSUE TITLE
HTML_Datei funktioniert nicht beim Steckbrief, aber lokal?

### ISSUE THREAD

**Issue by DominikWieck** [JirkaDellOro/EIA2-Inverted#117]
Hallo zusammen,

ich habe gerade die Aufgabe 05 hochgeladen. Wenn ich in VS Code die HTML-Datei öffne, funktioniert diese bei mir einwandfrei und habe keine Fehlermeldung in der Console.

Wenn ich diese aber im Steckbrief öffne bekomme ich folgende Fehlermeldung in der Konsole.

![image](https://user-images.githubusercontent.com/56441910/82605284-f761f780-9bb5-11ea-995b-cfe9980e9394.png)

 Was kann man da machen?

Link zur Aufgabe : https://github.com/DominikWieck/dominikwieck.github.io/tree/master/EIA2/Aufgabe05__

Link zu HTML Datei:
https://dominikwieck.github.io/EIA2//Aufgabe05__/Haushaltshilfe.html

**Comment by JirkaDellOro** [comment]
Man könnte die Datei Data.json, mit richtiger Namensschreibung, mitliefern, so dass sie geladen werden kann.

**Comment by DominikWieck** [comment]
Hat funktioniert, danke 👍
