### ISSUE TITLE
Fehlermeldung beim Pushen. 

### ISSUE THREAD

**Issue by luziagu** [JirkaDellOro/EIA2-Inverted#118]
Hallo, 
ich habe vorhin aus meinem Github-Repository eine Datei gelöscht (.DS_Store). Dies habe ich auch committed. Nun zeigt es mir aber beim Pushen anderer Dateien folgende Fehlermeldung an: 

<img width="994" alt="Bildschirmfoto 2020-05-22 um 13 54 20" src="https://user-images.githubusercontent.com/56430460/82665290-c3c5b280-9c33-11ea-9580-346139bfd690.png">

Da ich meine Änderungen auf GitHub selbst committed habe weiß ich nicht wie ich diesen Fehler beheben kann.  Auch bei Github wird mir angezeigt, dass ich die Datei erfolgreich gelöscht habe.
Um meine Abgabe pushen können würde ich diesen Fehler gerne beheben. 

Groß, Luzia

**Comment by luziagu** [comment]
![Bildschirmfoto 2020-05-22 um 13 58 30](https://user-images.githubusercontent.com/56430460/82665563-5a926f00-9c34-11ea-8c2e-d90a0c20323e.png)

**Comment by luziagu** [comment]
Der Link zu meinem Repository: https://github.com/luziagu/EIA2/tree/b91e875f506b4065b17825d47d37a3ae55f2baa5

**Comment by luziagu** [comment]
Hat sich erledigt.

**Comment by JirkaDellOro** [comment]
Anmerkung: oft hilft es, zunächst zu pullen, damit auf dem lokalen System das Repository auf dem jüngsten Stand ist.
