### ISSUE TITLE
npx serve fehlgeschlagen

### ISSUE THREAD

**Issue by schneine** [JirkaDellOro/EIA2-Inverted#119]
Hallo, 

der Befehl npx serve funktioniert bei mir im Terminal nicht. Es erscheint die Meldung: 
Die Installation von serve@latest ist mit dem Code 243 fehlgeschlagen

https://github.com/schneine/EIA2

**Comment by JirkaDellOro** [comment]
Hat's doch geklappt? Was war das Problem?

**Comment by schneine** [comment]
musste node aktualisieren, dann hat es geklappt
