### ISSUE TITLE
Haushaltshilfe funktioniert Lokal und auch mit pnx Serve aber nicht auf dem Steckbrief

### ISSUE THREAD

**Issue by luziagu** [JirkaDellOro/EIA2-Inverted#120]
Hallo nochmal, 

Ich habe gerade gemerkt, dass beim Öffnen meiner Datei auf dem Steckbrief folgende Fehlermeldungen erscheinen: 
![Bildschirmfoto 2020-05-22 um 18 07 47](https://user-images.githubusercontent.com/56430460/82687376-82df9500-9c57-11ea-8657-074a17ddabfa.png)

Bei mir Lokal scheint alles ohne Fehler zu laufen. Ich habe auch noch einmal die Schritte aus der Lektion überprüft. 
Woran liegt er Fehler? 

Gruß und Danke schon mal im Voraus, Luzia 

Link zum Repository: https://github.com/luziagu/EIA2/tree/master/Haushaltshilfe-Update%20

Link zu App: https://luziagu.github.io/EIA2/Haushaltshilfe-Update%20/haushaltshilfe.html

**Comment by luziagu** [comment]
Jetzt zeigt es mir nur noch folgende Fehlermeldung an. 

![Bildschirmfoto 2020-05-22 um 18 52 39](https://user-images.githubusercontent.com/56430460/82691041-8fff8280-9c5d-11ea-9474-0b44eba4259d.png)

Ich bin mir auch relativ sicher, dass als ich es gestern gepusht habe, alles soweit funktioniert hat. Ich bin jetzt ein wenig verwirrt. :D

**Comment by luziagu** [comment]
Okay, ich weiß nicht was ich gemacht habe, aber es scheint wieder zu funktionieren. Woran kann das gelegen haben?

**Comment by JirkaDellOro** [comment]
Zumindest die Meldung im zweiten Screenshot hatte ich kürzlich schonmal gesehen. Siehe #117
