### ISSUE TITLE
form ist "undefined"

### ISSUE THREAD

**Issue by schuchte** [JirkaDellOro/EIA2-Inverted#121]
Hallo Jirka,

mein Problem ist Folgendes.
Obwohl ich eigentlich alles nach deinen Anweisungen gecoded habe funktioniert bei mir die Zusammenstellung des query Strings nicht. 
Ich schätze es liegt am **form** Element.
Denn wenn ich den Code im Debugger bei Klicken des "Submit Data" Buttons verfolge, heißt es bei **form** ständig  "undefined". (Siehe Screenshots)
Woran liegt das?

Ich habe schon vieles versucht und auch bei anderen Codes reingeschnuppert, aber finde den Fehler leider nicht.
Viele Grüße,
Tanja 

![Screenshot_2](https://user-images.githubusercontent.com/56271810/82735815-d5d34e00-9d24-11ea-9aff-71fae7256de8.png)

![Screenshot_3](https://user-images.githubusercontent.com/56271810/82735822-e08de300-9d24-11ea-961a-87aa4792c9de.png)

**Comment by JirkaDellOro** [comment]
Bitte Links zum Repository und zu App schicken, ich will auch den Debugger starten...

**Comment by JirkaDellOro** [comment]
Da ich gleich weg muss, hier schnell ein paar Hinweise.

Gehen wir davon aus, dass der Debugger dir korrekt anzeigt, dass die Variable `form` den Wert `undefined` trägt, also nicht definiert wurde. Dann gibt es mehrere Möglichkeiten:
- Du hast die Variable nie angelegt, dass sollte dir aber TypeScript schon beim Schreiben melden
- Du hast sie global angelegt, aber nie definiert, also nie z.B. mit querySelector das Formular aus dem DOM gefischt
- Du hast sie global angelegt und auch das Formular gefischt, das Ergebnis aber einer anderen Variablen zugewiesen, beispielsweise einer anderen Variablen mit Namen `form` die aber in einer anderen Funktion lokal deklariert ist.

Vielleicht ist ja ein Treffer dabei...

**Comment by schuchte** [comment]
Habe den Fehler tatsächlich noch gefunden, es kann doch so einfach sein. (Nr. 3)
Vielen Dank ! 

Besser spät als nie :-)

**Comment by JirkaDellOro** [comment]
Super! Bitte den Issue schließen, wenn er durch ist.
