### ISSUE TITLE
Cannot find name process

### ISSUE THREAD

**Issue by beliema** [JirkaDellOro/EIA2-Inverted#122]
Hallo, 
Ich bin gerade dabei Lektion 06 durchzuarbeiten und Beim Video zu NodeAPI angelangt. Beim Mitmachen zum Video, Teil Variable Process, wird mir angezeigt, dass Process nicht gefunden wird. 
<img width="1311" alt="Bildschirmfoto 2020-05-25 um 11 33 51" src="https://user-images.githubusercontent.com/48830827/82800500-1b565f00-9e7c-11ea-844f-5e60c103aeda.png">

Nachdem ich im Terminal dann den Befehl eingegeben habe erscheint folgendes: 

<img width="528" alt="Bildschirmfoto 2020-05-25 um 11 34 54" src="https://user-images.githubusercontent.com/48830827/82800543-2f9a5c00-9e7c-11ea-9687-b19f2d8dda1e.png">

Was bedeutet das und wie bringe ich es zum Laufen? 

LG Alina

**Comment by AionixX** [comment]
Hallo Alina,

kannst du bitte den Link zur pages Seite und deinem Repo posten?

**Comment by beliema** [comment]
Pages: https://github.com/beliema/beliema.github.io/tree/master/Semester2/NodeAPI

Repo:https://github.com/beliema/beliema.github.io

**Comment by AionixX** [comment]
Ich habe mir deinen Code gerade angeschaut. Bei mir funktioniert es.

1. Bei deinen Links ist kein github.io Link dabei
2. in deinem Bild hast du "npm i @node/node" in die Befehlszeile eingegeben. Es sollte aber "npm i @types/node" sein siehe [hier](https://jirkadelloro.github.io/EIA2-Inverted/L06_Server/#entwickeln-mit-nodejs)

Versuche die Typescript types nochmal richtig zu installieren und melde dich wenn es dann immer noch nicht geht. Ansonsten kannst du mir auch eine Email schreiben (dennis.hawran@hs-furtwangen.de) dann treffen wir uns in einem Alfaview Raum und schauen nochmal drüber.
