### ISSUE TITLE
Heroku - Fehlermeldung - Build Master

### ISSUE THREAD

**Issue by luziagu** [JirkaDellOro/EIA2-Inverted#123]
Hallo Jirka, 

ich habe folgendes Problem. Ich habe probiert den Schritt Deploy Master Branch durchzuführen. Allerdings erhielt ich eine Fehlermeldung. 
<img width="695" alt="Bildschirmfoto 2020-05-26 um 10 35 35" src="https://user-images.githubusercontent.com/56430460/82879035-abf47400-9f3c-11ea-9712-7716e1ea67da.png">

<img width="654" alt="Bildschirmfoto 2020-05-26 um 10 35 14" src="https://user-images.githubusercontent.com/56430460/82878993-9ed78500-9f3c-11ea-8452-714d58c41130.png">

Mir ist allerdings nicht ganz klar was dieser Fehler bedeutet und vor allen dingen wie ich ihn beheben kann. 
Ich habe dann einfach weiter gemacht und versucht die package.json Datei zu implementieren. Auch dies ist durch einen Error dann gescheitert. 

<img width="607" alt="Bildschirmfoto 2020-05-26 um 10 37 25" src="https://user-images.githubusercontent.com/56430460/82879216-ed851f00-9f3c-11ea-9fb9-76a6a71386ad.png">
<img width="346" alt="Bildschirmfoto 2020-05-26 um 10 37 34" src="https://user-images.githubusercontent.com/56430460/82879230-f249d300-9f3c-11ea-8268-ccd4d0ed9697.png">
Es heißt ja hier, dass er die Script Datei nicht findet. Allerdings liegt die auf einer Ebene zu der Package.Datei und so habe ich das oben auch angegeben, oder? 

Danke schonmal für die Hilfe im Voraus. -Luzia

**Comment by JirkaDellOro** [comment]
"scripts" innerhalb von "scripts" könnte ein Fehler sein, ich glaube es muss "start" heißen

**Comment by luziagu** [comment]
Ja mit "start" hat es jetzt geklappt, hatte das in der Lektion nicht richtig verstanden. 
Das Problem mit dem Pullen des Repository von GitHub zu Heroku klappt aber leider immer noch nicht und ich bekomme immer wieder die selbe Fehlermeldung. Muss ich vielleicht den Zugriff von Github aus erst erlauben?

**Comment by FrankeSa** [comment]
Hallo Jirka,

auch bei mir erscheint die gleiche Fehlermeldung
![image](https://user-images.githubusercontent.com/56167839/82897587-1b2b9180-9f58-11ea-8b4f-d29c39308794.png)
Mir zeugt es leider nicht, so wie in der Aufgabe beschrieben, meine Dateien oder Ordner an.
Die Package.json Datei kann ich erstellen. Dazu Klicke ich auf meinen Order 06 Cocktailbar und öffne diesen im Terminal.
![image](https://user-images.githubusercontent.com/56167839/82898014-dbb17500-9f58-11ea-9e8d-3d358b123b08.png)

Nachdem ich die Package.json Datei erstellt habe, liefert mir npm start nicht das gewünschte Ergebnis Sonder dieses hier
![image](https://user-images.githubusercontent.com/56167839/82899512-6abf8c80-9f5b-11ea-89ed-b15b540aaba2.png)
Sind die beiden rot unterstrichenen Angaben oben im Fenster korrekt? Die Angabe hinter url habe ich von deinem Code, Jirka. 
Es zeigt mir außerdem noch an, dass ein Modul fehlt. Die aktuelle Node version habe ich jedoch
![image](https://user-images.githubusercontent.com/56167839/82900408-c4748680-9f5c-11ea-95ce-02e649486283.png)

**Comment by JirkaDellOro** [comment]
Wichtig ist, dass die Datei package.json in der Wurzel eures Repositories liegt, wie vorhin besprochen. Ist das so bei euch? Heroku wird nicht danach suchen...

**Comment by FrankeSa** [comment]
Ich habe die Datei nun direkt in nach meinem Reposetory Ordner in Windows gespeichert. 
![image](https://user-images.githubusercontent.com/56167839/82927486-129b8100-9f81-11ea-8320-6b91756b8f71.png)
Und trotzdem kommt eine Fehlermeldung.
![image](https://user-images.githubusercontent.com/56167839/82927518-1f1fd980-9f81-11ea-9671-275421a383e0.png)

**Comment by JirkaDellOro** [comment]
Stimmt denn der Pfad, der bei "start" angegeben ist nach `node`?

**Comment by luziagu** [comment]
Hallo Jirka, 
Jetzt ist mein Issue etwas untergegangen. Muss ich den Pfad zur script Datei angeben oder zur Server-Datei? 
Die Package.Json Datei liegt bei mir ebenfalls in der Wurzel meines Repositories. 
Der Fehler der mir oben angezeigt wurde kam schon bei mir bevor man die Package.json Datei laut Lektion erstellen musste. Bzw. war das nicht der gewünschte Fehler der eigentlich kommen sollte. 
Um vorrangigst zukommen habe ich dann die nächsten Schritte gemacht, deswegen existiert bei mir schon die package.json Datei. 
Heißt das, das ich den zugriff von  Github aus erst erlauben oder bestätigen muss? Und wenn ja, wie mach ich das? 
Gruß, Luzia

**Comment by luziagu** [comment]
Und zu dir Sarah: du musst node_modules noch installieren. Dieser Fehler wird dir auch angezeigt, dass die Datei nicht vorhanden ist. Wie das geht wird auch in der Lektion ganz am Anfang erklärt. Das ist eine Datei die sich ganz einfach im Terminal installieren lässt. 
<img width="640" alt="Bildschirmfoto 2020-05-27 um 09 14 40" src="https://user-images.githubusercontent.com/56430460/82989178-8a59c200-9ffa-11ea-8c0c-7264cada8a72.png">

**Comment by JirkaDellOro** [comment]
@luziagu Die Verbindung von Heroku zu Github hast Du hergestellt?

**Comment by luziagu** [comment]
Hallo Jirka, 
Ja die Verbindung ist hergestellt. Das Deploy Branch hat geklappt! In dem rechten Fenster werden mir aber Fehler angezeigt. Diese sind folgende: 
<img width="761" alt="Bildschirmfoto 2020-05-27 um 21 12 25" src="https://user-images.githubusercontent.com/56430460/83062384-cfafdb00-a05e-11ea-8143-bc5c14054758.png">

<img width="734" alt="Bildschirmfoto 2020-05-27 um 21 13 41" src="https://user-images.githubusercontent.com/56430460/83062466-fcfc8900-a05e-11ea-8784-a045e6234f00.png">

Weißt du wie ich diesen Fehler beheben kann?

**Comment by luziagu** [comment]
https://dashboard.heroku.com/apps/haushaltshilfe-app/logs

**Comment by luziagu** [comment]
Er zeigt mir an, dass Meine node_modules fehlen. Aber die habe ich installiert, nur eben mit gitignore nicht auf GitHub mitgepusht.

**Comment by JirkaDellOro** [comment]
Lokal läuft dein Server auf deiner Maschine?

**Comment by JirkaDellOro** [comment]
Hab's gerade von dir gezogen und probiert, lokal scheint in Ordnung. Ich erkenne in deinen Screenshots auch nicht, dass eine Meldung bezüglich der Node-Modules ausgegeben wird. 

Fehlerpotential sehe ich in der Datei package.json, Du hast bei "main" den String "generateContent.js" eingetragen, was Heroku veranlassen wird zu versuchen diese Datei zu laden. Ich wundere mich, wie das da reinkommt. Trage mal einen leeren String ein, wie in meiner Vorlage.

**Comment by luziagu** [comment]
Hallo Jirka. Habe es mit einem leeren String probiert. Folgende Fehlermeldung bekomme ich.Es scheint auch erst zu funktionieren. Ich bekomme auf meiden Seiten Build succeed angezeigt. Aber nach einer kurzen Zeit erscheinen dann wieder folgende Fehlermeldungen: 
<img width="781" alt="Bildschirmfoto 2020-05-27 um 23 23 05" src="https://user-images.githubusercontent.com/56430460/83073797-54a3f000-a071-11ea-8a1c-0decc0489242.png">
<img width="779" alt="Bildschirmfoto 2020-05-27 um 23 23 16" src="https://user-images.githubusercontent.com/56430460/83073800-566db380-a071-11ea-9877-013e06be018c.png">

Gibt es einen Link den ich dir senden kann, damit du dir das bei Heroku selbst mal anschauen könntest?

**Comment by JirkaDellOro** [comment]
Ich denke, wir verdrücken uns im Praktikum mal in eine Gruppe und schauen wie wir das mit Online-Fernwartung hinbekommen

**Comment by JirkaDellOro** [comment]
Wenn man Heroku einrichtet, muss man angeben, welche Laufzeitumgebung man nutzen möchte. Bist Du sicher dort Node angegeben zu haben?

**Comment by luziagu** [comment]
Ja das ist ein guter Plan! Danke für die Möglichkeit.
Und Node habe ich sicher bei der Einrichtung angegeben.

**Comment by luziagu** [comment]
Danke nochmal!
