### ISSUE TITLE
Kein Alert auf localhost

### ISSUE THREAD

**Issue by FrankeSa** [JirkaDellOro/EIA2-Inverted#124]
Hallo Jirka,

in deinem Video Min. 3.31. Hast du schon die Cocktailbar auf localhost geöffnet.
![image](https://user-images.githubusercontent.com/56167839/82933696-9efe7180-9f8a-11ea-9750-b862df3d2422.png)
Ich hab in meinem Code auch den url zu locahost angegeben.
![image](https://user-images.githubusercontent.com/56167839/82933879-ee44a200-9f8a-11ea-8b5f-b9b467eaac95.png)

Aber ich bekomme den Schritt nicht hin, dass ich nun die CocktailBar auch auf localhost5001 sehe. :(

**Comment by JirkaDellOro** [comment]
Es ist gut möglich, dass Du gerade davon schreibst, was wir heute besprochen hatten. Ein Fileserver liefert die Clientsoftware, dein selbstgebauter Server unterhält sich dann mit ihr. Im Screenshot sehe ich einmal Port 5000 und einmal 5001.  Hast Du auch beide Server gestartet?
