### ISSUE TITLE
typescript Installation neuer Rechner

### ISSUE THREAD

**Issue by klinkewitzn** [JirkaDellOro/EIA2-Inverted#125]
Hallo, ich habe einen neuen Rechner und mir heute node.js, git und vs code heruntergeladen. Als ich jetzt Typescript installieren wollte, kam leider eine Fehlermeldung.
Fehlermeldung:
![screenshot typescript install fehlermeldung](https://user-images.githubusercontent.com/56318063/82948344-e47a6900-9fa1-11ea-83f0-5a243de53e47.PNG)
![screenshot typescript install fehlermeldung2](https://user-images.githubusercontent.com/56318063/82948349-e7755980-9fa1-11ea-90b5-4b7f2dded623.PNG)
heruntergeladene Dateien:
![screenshot typescript install fehlermeldung3](https://user-images.githubusercontent.com/56318063/82948440-14c20780-9fa2-11ea-91f0-4535ff426380.PNG)
Ich kann node auch öffnen, also eigentlich sollte es geklappt haben:
![node](https://user-images.githubusercontent.com/56318063/82948496-2c00f500-9fa2-11ea-89ea-b87cb2515b60.PNG)

**Comment by Plagiatus** [comment]
Mal den Rechner neu gestartet seit den Installationen?

**Comment by klinkewitzn** [comment]
Also  ich habe meinen Rechner jetzt neu hochgefahren und npm -v und die npm install typescript Anweisung funktionieren jetzt.  
Dann gibt es ja noch die Befehle tsc -v und tsc --version, um zu kontrollieren, ob typescript intalliert wurde. Da werden aber noch Fehlermeldungen angezeigt.
![screenshot typescript install fehlermeldung6](https://user-images.githubusercontent.com/56318063/82955242-b0f20b80-9fae-11ea-871e-e726ae906c91.PNG)

**Comment by Plagiatus** [comment]
Das ist weil die Powershell das TSC aus irgendwelchen Gründen blockiert. Schau Mal hier: https://github.com/JirkaDellOro/Prima/issues/17

**Comment by klinkewitzn** [comment]
Habe gemacht was da steht und jetzt scheint alles zu funktionieren. Vielen Dank! :)
