### ISSUE TITLE
Fehlermeldung auf Heroku

### ISSUE THREAD

**Issue by celine333** [JirkaDellOro/EIA2-Inverted#126]
Hallo,

Elena und ich haben diese Fehlermeldung auf Heroku bekommen und kommen da momentan nicht mehr weiter. Könnte das Problem evtl. an den node-modules liegen? 
Wir haben die package.json Datei schon am Rumpf des Repositorys und die Verlinkung bei "start" müsste auch passen.

Vielen Dank schonmal im Vorraus!

![Fehlermeldung_Heroku](https://user-images.githubusercontent.com/56337413/83005110-b7b16a80-a010-11ea-99f5-1135ac8b1c6a.jpeg)

Mein Repository: https://github.com/celine333/EIA_2

**Comment by JirkaDellOro** [comment]
Der Pfad, den ich bei dir in package.json sehe, entspricht nicht dem Pfad im Repository zur Datei Server.js

**Comment by celine333** [comment]
Danke! Hatte vergessen, meine json Datei wieder neu auf Github zu pushen. 
Allerdings bekomme ich jetzt einen Application Error, wenn ich die App öffne, obwohl das "builden" geklappt hat.

**Comment by JirkaDellOro** [comment]
Kleine Schritte, aber in die richtige Richtung. Schick' dein Log-File.

**Comment by celine333** [comment]
![Screenshot (139)](https://user-images.githubusercontent.com/56337413/83133528-4d1d2f00-a0e3-11ea-91ec-7d5a5aae68c7.png)
![Screenshot (140)](https://user-images.githubusercontent.com/56337413/83133553-54dcd380-a0e3-11ea-9c55-ceeff43b626d.png)

**Comment by JirkaDellOro** [comment]
Heroku teilt dir mit, dass es ein Problem mit dem Url-Modul gibt und Du hast die Einbindung auch anders gemacht als in meiner Vorlage.
```typescript
import * as Http from "http";
import { Url, UrlWithParsedQuery } from "url";
```

was passiert, wenn Du es so machst wie es in der auskommentierten Zeile steht?
```typescript
import * as Url from "url";
```

**Comment by celine333** [comment]
Ich habe die richtige Zeile jetzt wieder in Code gepackt und habe trotzdem noch das selbe Problem. 
Eine der Fehlermeldungen ist, dass die node modules nicht gefunden werden bzw. diese "missing" sind. Könnte es daran liegen, dass diese nicht in unserem Repository liegen sondern nur lokal auf unserem Rechner? Könnte Heroku denn auf .gitignore Ordner zugreifen, wenn es diese modules anscheinend braucht?

**Comment by JirkaDellOro** [comment]
Nein, die Modules sollte Heroku haben. Poste bitte wieder die aktuellen Fehlermeldungen von Heroku, ich möchte prüfen, ob sie wirklich identisch sind.

**Comment by celine333** [comment]
Wir haben unser Problem gelöst bekommen, vielen Dank nochmal!
Es lag letztendlich an response.setHeader, welches wir falsch platziert haben bzw. am Ende der Funktion gesetzt haben.

**Comment by JirkaDellOro** [comment]
Super! Ich hoffe, ihr musstet nicht zu viel Zeit dort versenken...
Schließt den Issue, wenn alles durch ist.
