### ISSUE TITLE
Weitere Fehlermeldung auf Heroku

### ISSUE THREAD

**Issue by Majoo44** [JirkaDellOro/EIA2-Inverted#128]
![image](https://user-images.githubusercontent.com/44026413/83201779-8e92f600-a146-11ea-9245-d3677e6b4346.png)
Wir Haben bei Heroku das Problem, dass wir an dieser Stelle nicht weiter kommen - Leider kein “Build succeeded” in Sicht.. Wir wissen aber nicht, woran es liegt. Kann jemand helfen? :) 

Link zur package.json: https://github.com/Majoo44/EIA2/blob/master/Aufgabe06/package.json

**Comment by Plagiatus** [comment]
Heroku sagt da, dass es keine Ahnung hat welche Art von Anwendung es sein soll. Habt ihr ihm gesagt dass es Node.js ist? Falls ihr keine Einstellung dafür finden könnt, versucht mal in der package.json eure engine anzugeben, wie z.B. hier (sehr alte node.js Version, ihr solltet die version hier reinschrieben die ihr auch selbst verwendet): https://github.com/JirkaDellOro/EIA2/blob/master/package.json

**Comment by JirkaDellOro** [comment]
Höchstwahrscheinlich liegt es eher daran, dass Heroku eure `package.json` gar nicht findet. Ihr habt sie nämlich tief in eurem Ordnersystem vor Heroku versteckt. Sie muss auf der obersten Ebene eures Repositories liegen!

**Comment by Majoo44** [comment]
Danke euch, habe die package.json abgeändert und in der Ordnerstruktur verschoben. Im Deploy Fenster funktioniert nun wohl alles so wie es soll. Im Logs Fenster nicht. :/ 
Hat es was mit der Platzierung des node Ordners in der Ordnerstruktur zu tun?
![image](https://user-images.githubusercontent.com/44026413/83251328-c5e6be80-a1a9-11ea-9b00-cf867e661c4b.png)

Link zur vollständigen Application Log Datei: https://github.com/Majoo44/EIA2/blob/master/Aufgabe06/knobelkind-logs-1590748276803.txt

Ich hoffe man versteht mein Problem..
Danke schon mal! 💯

**Comment by JirkaDellOro** [comment]
In Zeile 30 steht 
"2020-05-29T10:17:49.694845+00:00 app[web.1]: Error: Cannot find module '/app/js/L06_Server.js'"

Stimmt denn der in der `package.json` angegebene Pfad?

**Comment by sebifyy** [comment]
Habe genau das selbe Problem. Ständig steht im log "Cannot find module /app/js/L06_Server.js" obwohl ich den Pfad richtig angegeben habe. Noch eine weitere Idee?

**Comment by JirkaDellOro** [comment]
Na dann poste doch mal deine Links hier hin, damit ich mir das anschauen kann

**Comment by sebifyy** [comment]
Heroku Log Datei:
https://github.com/sebifyy/EIA2_4/blob/master/L06%20Server/logs/sebify-logs-1590862327940.txt

Meine package.json:
https://github.com/sebifyy/EIA2_4/blob/master/package.json

**Comment by JirkaDellOro** [comment]
Hmm,,, Heroku meint, er kann "js/L06_Server.js" nicht finden und in deiner `package.json` die ich mir gerade angeschaut habe steht "app/js/L06_Server.js"

In deinem Repository kann ich weder den einen noch den anderen Pfad finden, Herokus Meldung ergibt Sinn. Außerdem: nutze niemals Leerzeichen oder Sonderzeichen in Dateinamen! Und schreibe sie am Besten auf Englisch.

**Comment by JirkaDellOro** [comment]
Hilft das?

**Comment by sebifyy** [comment]
Sooo habe jetzt den Ordner umbenannt ohne Leerstelle und den Pfad (glaube ich?) richtig angegeben, werde aber mit weiteren Errors bombabiert, mit denen ich nichts anfangen kann:
https://github.com/sebifyy/EIA2_4/blob/master/L06_Server/logs/sebify-logs-1590863879702.txt

**Comment by JirkaDellOro** [comment]
Zumindest scheint Heroku nun deinen Code zu finden und versucht ihn auszuführen. Ich habe mir ihn auch angeschaut und habe keine Ahnung, wo Du den her hast. Deswegen kann ich dir dabei nicht helfen. Magst Du dich nicht einfach an die Lektion halten?
