### ISSUE TITLE
Heroku- Error: Cannot find module

### ISSUE THREAD

**Issue by vschwan** [JirkaDellOro/EIA2-Inverted#130]
Hi, ich hab hier auch so meine Probleme mit Heroku
Und zwar bekomme ich den Application Error und diese Fehlermeldungen im log:

![WhatsApp Image 2020-05-30 at 17 05 57](https://user-images.githubusercontent.com/56428408/83331830-92369200-a298-11ea-9dba-ddc45bda3a50.jpeg)
![WhatsApp Image 2020-05-30 at 17 00 36](https://user-images.githubusercontent.com/56428408/83331818-8a76ed80-a298-11ea-98fc-ffeba017a006.jpeg)

deploy branch ist erfolgreich
Habe definitiv Node.js gewählt
Der Pfad sollte in package.json richtig sein
package.json ist an der Wurzel des Repositories gespeichert

Habe keine Ahnung mehr was das Problem sein könnte.
Mir ist allerdings der Error: Cannot find module '/app/EIA2/06/Haushaltshilfe' aufgefallen. eigentlich müsste der Pfad doch weitergehen, oder?

Danke schonmal für Hilfe!
Repository: https://github.com/vschwan/vschwan.github.io

**Comment by JirkaDellOro** [comment]
Heroku meldet, dass er EIA2/06/Haushaltshilfe nicht finden kann. Immerhin weißt Du damit, dass er deine `package.json` interpretiert, sonst würde er gar nicht nach der Haushaltshilfe suchen. Allerdings sucht er nicht nach "Haushaltshilfe 6/Server/Server.js. "

Ich fürchte, dass das Leerzeichen das Problem darstellt. Eiserne Regel: niemals Leerzeichen in Dateinamen, keine Sonderzeichen, am besten Englisch! Probier's mal damit.

**Comment by JirkaDellOro** [comment]
PS: diese Regel gilt immer, nicht nur für Heroku...

**Comment by vschwan** [comment]
aaaaaaah. Alles klar, gut zu wissen. 
Hat funktioniert!
Dankeschön :)
