### ISSUE TITLE
npm Error

### ISSUE THREAD

**Issue by Cari1512** [JirkaDellOro/EIA2-Inverted#131]
![grafik](https://user-images.githubusercontent.com/56436935/83337528-71803380-a2bc-11ea-9412-d234f64543b2.png)
![grafik](https://user-images.githubusercontent.com/56436935/83338033-7e068b00-a2c0-11ea-86c2-eaf40ef997b9.png)

Hallo,

bei mir kommt die Fehlermeldung wenn ich "npm start" in mein Terminal eingebe.
Wie kann ich das beheben?

Link zum Aufgabenordner: https://github.com/Cari1512/EIA2/tree/master/L06

**Comment by JirkaDellOro** [comment]
Was ich deinem Post entnehme erscheint mir widersprüchlich. 

Heroku scheint ja loszulaufen, aber erscheint dann auch dort eine Fehlermeldung weiter unten? Ich kann in deinem Bild natürlich nicht runterscrollen... Du kannst so ein Log auch Speichern und verschicken.

Auch dein lokaler Server scheint loszulaufen, so wie ich im VSCode-Terminal sehe. Was tust Du genau um den Fehler zu provozieren? Die Eingabeaufforderung verweist auf den Server-Ordner. Hast Du da etwas gestartet?

**Comment by Cari1512** [comment]
Um den Fehler zu provozieren gebe ich npm start in mein Terminal ein um zu schauen ob das auch funktioniert, gehen dann auf meine Haushaltshilfe datei, wähle etwas aus und schicke die Bestellung ab und dann kommen die errors. Davor hatte ich glaube ich nur node server.js in meinem Server Ordner Terminal eingegeben.
Ich habe soeben versucht das ganze wieder zum Laufen zu bringen und folgendes war auf Heroku im Log zu sehen
[carianne-logs-1591006134149.txt](https://github.com/JirkaDellOro/EIA2-Inverted/files/4710698/carianne-logs-1591006134149.txt)

**Comment by JirkaDellOro** [comment]
Zwei Meldungen stechen mir dabei ins Auge:
- at=error code=H13 desc="Connection closed without response" method=GET 
- Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client

Ich kann aber beim ersten Hinschauen kein Fehler im Code entdecken. Ich ziehe mir dein Repository und schaue rein.

**Comment by JirkaDellOro** [comment]
Lokal kann ich keine Fehler provozieren. Natürlich musste ich im Client die Serveradresse anpassen, z.B. zu 
`  let url: string = "http://localhost:5001";`
damit ich denen Server lokal zusammen mit dem Client testen kann. Hattest Du das beachtet? Machst Du auch auf Heroku "deploys" wenn Du etwas verändert und auf Github gepusht hast?

PS: 
- bitte nimm die Warnungen des TypeScript-Compilers und -Linters ernst. Da gibt es ein paar faule Stellen in deinem Code.
- L04 musste ich rauslöschen, damit ich überhaupt kompilieren kann, da waren noch alte Fehler drin. Du erleichterst massiv die Hilfe, wenn Du darauf achtest, dass immer alles sauber ist.

**Comment by Cari1512** [comment]
Ich habe bisher immer deploys auf Heroku gemacht nach jedem push auf Github. Ich hatte
 let url: string = "http://localhost:5001";
zuerst drinnen stehen und habe dann den Link zu meiner Haushalthilfe geändert.
Mir fällt gerade auf, dass der Linter bei mir sich gar nicht beschwert obwohl dieser bei mir auch im aktuellen EIA2 Ordner (also auf oberer Ebene) drinne ist.....

**Comment by JirkaDellOro** [comment]
Ist die TS-Lint-Extension installiert in VSCode?

**Comment by KohlerAl** [comment]
Mir ist aufgefallen, dass der Linter bei mir auch nicht richtig zu funktionieren scheint. Als ich den Linter nochmal installieren wollte, kam im Terminal die Meldung, dass TSLint jetzt ESLint ist. 
![Screenshot (181)](https://user-images.githubusercontent.com/56314717/83489098-36dded00-a4ae-11ea-95a2-43fcc09fabfe.png)
Irgendwas scheint aber trotzdem passiert zu sein, zumindest steht da ja "updated 7 packages" ...

**Comment by JirkaDellOro** [comment]
OK, dann gibt es wieder Neuerungen... damit wird man nie fertig sein.

**Comment by Plagiatus** [comment]
ja genau, TSLint wurde Anfang des Jahres mit ESLint ersetzt, funktioniert aber für unsere Zwecke noch vollkommen ausreichend.

**Comment by Cari1512** [comment]
![grafik](https://user-images.githubusercontent.com/56436935/83509767-3fddb700-a4cc-11ea-8bcd-8a7e9c56f617.png)
Ich wollte nun auch TsLint neu intallieren und diese Fehlermeldungen kamen.
[2020-06-02T10_25_07_544Z-debug.log](https://github.com/JirkaDellOro/EIA2-Inverted/files/4716483/2020-06-02T10_25_07_544Z-debug.log)

**Comment by JirkaDellOro** [comment]
Ich meinte TSLint von Microsoft, nicht Palantir. Du auch Lukas?

**Comment by Plagiatus** [comment]
moment, das TSLint von Microsoft ist die _Erweiterung_, Das Node Modul war schon immer von Palantir: https://www.npmjs.com/package/tslint

**Comment by Plagiatus** [comment]
Und wegen dem eigentlichen Problem: Das ist nur ein checksum error, einfach nochmal versuchen und dann sollte es gehen. wenn dein Internet instabil ist, dann schau hier mal rein: https://stackoverflow.com/questions/47545940/when-i-run-npm-install-it-returns-with-err-code-eintegrity-npm-5-3-0

**Comment by Cari1512** [comment]
Habs gelöst, danke ^-^
