### ISSUE TITLE
Fehlermeldung in Heroku

### ISSUE THREAD

**Issue by s-wdh** [JirkaDellOro/EIA2-Inverted#132]
Hallo,
ich bekomme in Heroku folgende Fehlermeldung, versteh aber nicht woran das liegt.
![heroku](https://user-images.githubusercontent.com/56883358/83351297-04fc4780-a343-11ea-9f0c-d20fb43b81a3.jpg)
![heroku2](https://user-images.githubusercontent.com/56883358/83351299-09286500-a343-11ea-9441-f9c297ef49a7.jpg)

Repository: [https://github.com/s-wdh/EIA2/tree/master/L06/Haushaltshilfe](url)
Code: [https://s-wdh.github.io/EIA2/L06/Haushaltshilfe/Haushaltshilfe.html](url)

**Comment by AnnaLotz** [comment]
Du hast in deiner package.json dein Hauptscript verlinkt. Hier sollte aber das Serverscript hin!

**Comment by s-wdh** [comment]
Aaaahhh! Vielen Dank jetzt funktioniert es 😄
