### ISSUE TITLE
Amount

### ISSUE THREAD

**Issue by weiberta** [JirkaDellOro/EIA2-Inverted#133]
**Hi. Folgendes Problem:**
Ich habe den Code nach den Tutorials gecodet, jedoch habe ich bei der Rechnung irgendetwas verhauen oder falsch angegeben, so dass bei meiner inner.HTML dieses nervige Amount immer, jedes einzige mal, drinsteht. Ich habe immer wieder daran rumgebastelt, aber bekomme es einfach nicht raus. Erst war es eine 6 in der Konsole, jetzt ist es 5 in der inner.HTML. Kriese.

![Bildschirmfoto 2020-06-01 um 00 37 01](https://user-images.githubusercontent.com/48830856/83364277-6b638300-a3a0-11ea-96e2-7f6a0e7bcb62.png)
Es muss mit dem slider zusammenhängen, da nichts mehr von der Berechnung funktioniert, wenn ich etwas an ihm ändere (id="Amount" oder name="amount" umbenennen)
![Bildschirmfoto 2020-06-01 um 00 32 32](https://user-images.githubusercontent.com/48830856/83364278-6bfc1980-a3a0-11ea-9c29-a54e0f131e31.png)
Es könnte als an der Rechnung selbst liegen oder an der inner.HTML, ich kann aber keinen Zusammenhang knüpfen. 
![Bildschirmfoto 2020-06-01 um 00 39 09](https://user-images.githubusercontent.com/48830856/83364274-6999bf80-a3a0-11ea-8b35-b4edc1d03a6d.png)
_Gesamtsumme ignorieren_

Ich weiß nicht weiter. 
(ծ‸ ծ )

**Comment by JirkaDellOro** [comment]
Du hast vergessen die erforderlichen Links zu posten, so dass ich gleich reinschauen kann. Wenn ich mir den Code anschaue, denke ich aber, Du hast, wie viele andere, vergessen den Slider getrennt zu behandeln. Schau' nochmal in meiner Cocktailbar-Vorlage. Melde dich wieder, wenn das nicht hilft und poste die Links
