### ISSUE TITLE
Pfad wird nicht gefunden in Eingabeaufforderung

### ISSUE THREAD

**Issue by DominikWieck** [JirkaDellOro/EIA2-Inverted#134]
Finde in der Eingabeaufforderung nicht den Pfad 
Das geb ich ein : 

![image](https://user-images.githubusercontent.com/56441910/83395176-22401d00-a3fa-11ea-85fb-0e351df8fdd0.png)

und so ist meine Ordnerstruktur aufgebaut

![image](https://user-images.githubusercontent.com/56441910/83395229-35eb8380-a3fa-11ea-882b-1d4cfb0d6741.png)

komischerweise ist ein Ordner mit "Server" installiert worden obwohl ich keinen Haken gesetzt habe. 

![image](https://user-images.githubusercontent.com/56441910/83395329-62070480-a3fa-11ea-916e-77bf4d1eb19e.png)

Schonmal Dankeschön im Voraus!

**Comment by JirkaDellOro** [comment]
Ich denke, das rote Kreuz bedeutet, dass Du die Installation nicht abwählen kannst, weil dann die ganze Installation keinen Sinn ergeben würde.

Weiterhin zeigt dein Explorer-Screenshot, dass Mongo im Ordner "C:/Programme" installiert wurde. Der Terminalscreenshot macht dagegen den Eindruck, als würdest Du die Installation in "C:/Users/domin" erwarten.

**Comment by DominikWieck** [comment]
Wie änder ich "C:/Users/domin" in "C:/Programme"  im Terminal um?

Immer wenn ich im Terminal Enter drücke, erscheint "C:/Users/domin" :/

**Comment by Plagiatus** [comment]
der `cd` befehl steht für "change directory", damit kannst du das aktuelle Verzeichnis ändern.
in deinem Fall wahrscheinlich
`cd ../../Programme`, oder du gibst den absoluten Pfad an: `cd C:/Programme`

**Comment by JirkaDellOro** [comment]
Oder rechtsklickst, ggf mit gedrückter Shift-Taste, im Explorer auf den Ordner und wählst dann Eingabeaufforderung oder PowerShell.

**Comment by Plagiatus** [comment]
oder du schreibst in die Addresszeile im Explorer während du im richtigen Ordner bist "cmd" und drückst Enter.

**Comment by JirkaDellOro** [comment]
Öliger Krapfen! Wieder was gelernt... 👍
