### ISSUE TITLE
Error bei url.query

### ISSUE THREAD

**Issue by KohlerAl** [JirkaDellOro/EIA2-Inverted#135]
Hallo, 
ich bin grade dabei nachzuvollziehen, was in Lektion 7 gemacht wurde und bin jetzt auf folgendes Problem gestoßen:
Beim Aufruf von storeOrder gibt es einen Error, weil url.query nicht zu "Order" passt. Im Video ist dieser Fehler nicht aufgetaucht. 
![Screenshot (180)](https://user-images.githubusercontent.com/56314717/83404547-2294e400-a40b-11ea-8d90-446e815ff899.png)

Hat jemand eine Idee, wo da der Fehler liegt oder wie man ihn beheben kann? 
Danke schon mal!
LG Alida

**Comment by JirkaDellOro** [comment]
Bitte immer Links zum Code mit posten.

Wenn der Code dem Vorlesungscode entspricht, könnte es ggf. auch an einem Versionsunterschied unserer Installationen liegen. Was kommt bei dir raus wenn Du in der Konsole
`npm -v @types/node` 
eingibst? Ich habe 6.9.0

Die Lösung wird in der Fehlermeldung schon angedeutet. Order kann Werte vom Typ `string` oder `string[]` aufnehmen, `url.query` scheint aber in deiner Version vom Typ `string | string[] | undefined` sein. Du müsstes also den Wertetyp von Order um `undefined` erweitern. Ich bin gespannt ob das passt.

**Comment by KohlerAl** [comment]
Danke! Wenn ich undefined mit angebe, taucht zumindest da kein Error mehr auf :)
Der Code war exakt der aus der Vorlesung, aber ich habe Version 6.13.4  .
