### ISSUE TITLE
Datenbankordner wird nicht erstellt

### ISSUE THREAD

**Issue by k-poschmann** [JirkaDellOro/EIA2-Inverted#136]
Hallo,

ich habe das Problem, dass ich nachdem ich den Befehl: "MongoDB/bin/mongod --dbpath Database" eingegeben habe, folgende Meldung im Terminal kommt:
![Bildschirmfoto 2020-06-01 um 13 09 23](https://user-images.githubusercontent.com/56409026/83406287-9edcf680-a40e-11ea-8899-fa6861b29a03.png)

ich hoffe ihr könnt mir helfen.

Liebe Grüße ,
Kristin :)

**Comment by JirkaDellOro** [comment]
Hast Du auch das Verzeichnis Database vorher angelegt? Und ist es als Unterordner des Verzeichnisses zu finden, in dem gerade diese Konsole läuft?

Was dir Mongo aber gerade meldet ist, dass die Adresse bereits genutzt wird. Hast Du vielleicht bereits eine Mongo-Instanz am Laufen? Schließe sie. Wenn  Du kein Terminal findest, wo eine solche Instanz läuft und Du dich mit dem Task-Manager auskennst, kannst Du sie "abschießen". Ansonsten mal den Rechner neu starten.

**Comment by k-poschmann** [comment]
Ja den Ordner hatte ich zuvor schon angelegt gehabt. Aber jetzt hat es geklappt. Vielen Dank :D
