### ISSUE TITLE
Datenbank anlegen funktioniert nicht

### ISSUE THREAD

**Issue by FrankeSa** [JirkaDellOro/EIA2-Inverted#137]
Hallo,

ich kann leider irgendwie keine Datenbank anlegen, weil das mit dem Pfad nicht klappt.
![image](https://user-images.githubusercontent.com/56167839/83438267-6acef900-a441-11ea-95c0-a7e880d0cbd1.png)
![image](https://user-images.githubusercontent.com/56167839/83438296-78847e80-a441-11ea-8b9a-90145400851a.png)
was mach ich falsch?

**Comment by JirkaDellOro** [comment]
1. hast Du einmal probiert, was dir Powershell empfohlen hat einzugeben? 
2. wenn dein Terminal sich auf den bin-Ordner bezieht, wird darin auch nach deinem Datenbankordner gesucht, wenn Du das Kommando so eingibst wie auf dem Screenshot zu sehen. Entweder startest Du eine Ebene höher mit "bin/mongod" oder Du gibst den Pfad zur Datenbank so an "../Database_EIA"
3. lasse besser den MongoDB-Ordner unverändert und lege deine Datenbank parallel dazu an, statt darin.
