### ISSUE TITLE
Verwirrung auf mongodb :D

### ISSUE THREAD

**Issue by vschwan** [JirkaDellOro/EIA2-Inverted#138]
Hi!
Ich arbeite gerade Lektion 7 durch. Habe mich auf mongodb angemeldet und bin jetzt dabei ein cluster zu createn
![image](https://user-images.githubusercontent.com/56428408/83446755-88a35a80-a44f-11ea-92fb-1ed5fcb709bb.png)

Ich glaube die Anleitung ist an dieser Stelle in der Lektion nicht mehr ganz so aktuell. Beispielsweise gibt es keinen "Get Started"-Guide und ich finde die whitelist nicht. Für mich ist das ein bisschen verunsichernd, weil ich nicht weiß, ob ich alles richtig mache oder nicht. 
Könnte mir vorstellen, dass es anderen auch so geht und fände es hilfreich wenn das angeglichen würde. 
Hab ich denn, dem Screenshot nach, bisher alles richtig gemacht? 😅  

repository: https://github.com/vschwan/vschwan.github.io

**Comment by JirkaDellOro** [comment]
Vielen Dank! Da sich die Dinge ändern ist es wichtig, dass ihr solche Rückmeldung gebt und nachfragt. Wir schauen uns das an.
@AionixX

**Comment by vschwan** [comment]
Danke!
