### ISSUE TITLE
Eingabebefehl mongoDB

### ISSUE THREAD

**Issue by klinkewitzn** [JirkaDellOro/EIA2-Inverted#139]
Hallo, ich habe MongoDB installiert und den sich in der ZIP-Datei befindenden Ordner in mongoDB umbenannt. Außerdem habe ich den Ordner aus dem Downloads-Ordner in meinen EIA2 Repository Ordner verschoben.  Wenn ich den Eingabebefehl [MongoDB/bin/mongod --dbpath Database] im Terminal eingebe kommt diese Fehlermeldung:
![fehlermeldung1](https://user-images.githubusercontent.com/56318063/83458096-26a02080-a462-11ea-8f7e-1f355b9fc0f3.PNG)
Der Pfad ist aber richtig.

**Comment by JirkaDellOro** [comment]
Leider kann ich von hier aus nicht in deine Verzeichnisstruktur reinschauen um das zu prüfen, da machen wir nachher eine Bildschirmteilung. Was aber passiert wenn Du MongoDB/bin/mongod in Anführungszeichen schreibst. Ändert sich da etwas bei dir?

**Comment by klinkewitzn** [comment]
Das passiert:
![fehlermeldung2](https://user-images.githubusercontent.com/56318063/83502637-30f20700-a4c2-11ea-9b75-05de194e12a8.PNG)
