### ISSUE TITLE
Fehlermeldung: Cannot read property 'insert' of undefined + UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by vschwan** [JirkaDellOro/EIA2-Inverted#140]
Hello
Also ich habe inzwischen eine Datenbank und Collection auf mongodb angelegt, und im Servercode den URL zum Datenbankserver mit dem kopierten Connection-String ersetzt. 

Bis hierhin hat alles funktioniert. dann hab ich den Server neu gestartet. Dabei bekomme ich diese Fehlermeldung. Darunter ist die Fehlermeldung, die kommt, wenn ich ich eine weitere Bestellung absetze. 
![WhatsApp Image 2020-06-02 at 10 44 30](https://user-images.githubusercontent.com/56428408/83500851-9a244b00-a4bf-11ea-9877-a9620c859e5a.jpeg)

Dementsprechend kommt auch nichts in der online-Datenbank an.
Idee, was das Problem sein könnte? 

PS: Hab mich übrigens mit Alida kurzgeschlossen, die bekommt die gleiche Fehlermeldung

Repository: https://github.com/vschwan/vschwan.github.io

**Comment by JirkaDellOro** [comment]
Ist das noch aktuell?

**Comment by KohlerAl** [comment]
Ja, ich bin immer noch am rumprobieren, aber ich bekomme einfach keine Verbindung zu MongoDB aufgebaut :(

**Comment by vschwan** [comment]
ja

**Comment by JirkaDellOro** [comment]
Aus der Fehlermeldung, etwa in der Mitte des Blocks mit den ganzen "at", wird ersichtlich, das

`await mongoClient.connect();`

fehlschlägt. Habt ihr denn eine Datenbank "Haushaltshilfe" in der Mongo-Cloud angelegt?

**Comment by KohlerAl** [comment]
Bei mir heißt die Datenbank Household und darin ist die Collection Orders. 
So habe ich das dann auch im Skript eingegeben. 
![Screenshot (182)](https://user-images.githubusercontent.com/56314717/83558939-1183ca00-a514-11ea-93a4-d53d84082aa5.png)
![Screenshot (183)](https://user-images.githubusercontent.com/56314717/83558942-12b4f700-a514-11ea-92f1-d587178d76ce.png)

**Comment by JirkaDellOro** [comment]
- Sehr gut, dass Du englische Begriffe wählst. 
- Schicke bitte einen Screenshot der Fehlermeldung. 
- Wie kam der Eintrag in die Datenbank, von Hand?
- bringe bitte die Funktionsaufrufe von Zeile 39 und 40 nach oben vor die Funktionen, so dass man den Code von oben nach unten lesen kann.

**Comment by KohlerAl** [comment]
Den Eintrag habe ich von Hand geschrieben, weil ich wissen wollte ob wenigstens das geht oder ob vielleicht schon beim Erstellen der Datenbank was schief gelaufen ist... 

[agkeia-logs-1591125142558.txt](https://github.com/JirkaDellOro/EIA2-Inverted/files/4719178/agkeia-logs-1591125142558.txt)

**Comment by JirkaDellOro** [comment]
Mir fallen in deinem Log diese zwei Zeilen ins Auge:
`2020-06-02T19:12:18.990559+00:00 app[web.1]: (node:23) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.`

`2020-06-02T19:12:19.307610+00:00 app[web.1]: (node:23) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [alidaeia2-shard-00-00-qgqj8.mongodb.net:27017] on first connect [MongoNetworkError: connection 5 to alidaeia2-shard-00-00-qgqj8.mongodb.net:27017 closed`

In der zweiten Zeile erkennt man, dass dein Problem ein anderes ist als Valentinas, es scheitert schon beim Versuch sich überhaupt mit dem Datenbankserver zu verbinden.
Die erste könnte ein Hinweis auf eine Ursache sein, es wird empfohlen die Option "useUnifiedTopology" zu nutzen. Im Vorlesungscode wird das auch gemacht, in deinem Code ist es auskommentiert.

**Comment by KohlerAl** [comment]
Ich hab die Zeile wieder rein gemacht, jetzt sieht es wieder so aus wie im Code aus der Vorlesung, aber es funktioniert immer noch nicht :(
[agkeia-logs-1591127362771.txt](https://github.com/JirkaDellOro/EIA2-Inverted/files/4719347/agkeia-logs-1591127362771.txt)

**Comment by JirkaDellOro** [comment]
Erkennst Du aber, dass sich die Fehlermeldung geändert hat? Der Ort, an dem der Fehler auftritt, scheint aber der gleiche zu sein. Dass die Konsolenausgaben nach
`await mongoClient.connect();`
nie erscheinen deutet darauf hin, dass connect nie fertig wird. 

- Was passiert, wenn Du die Heroku-App startest und eine Weile wartest, bevor Du mit dem Client Daten sendest? Kommen die Ausgaben irgendwann?
- Wenn nicht, lege bitte nochmal eine Datenbank oder auch ein neues User-Account bei Mongo an. Das Problem scheint außerhalb unseres Einflussbereichs zu liegen.

**Comment by KohlerAl** [comment]
Dass die Fehlermeldung anders aussieht, habe ich bemerkt. Sie war auch deutlich kürzer als die Andere. Ich hab den Server jetzt grade nochmal gestartet und einfach nichts getan, aber auch nach 10 Minuten kamen keine Konsolen-Ausgaben. Als ich dann versucht habe, eine Bestellung zu versenden, kamen wieder Fehlermeldungen. 
[agkeia-logs-1591165483860.txt](https://github.com/JirkaDellOro/EIA2-Inverted/files/4721355/agkeia-logs-1591165483860.txt)

Ich probiere es jetzt nochmal mit einem neuen Account

**Comment by JirkaDellOro** [comment]
Aber durch das Warten haben wir noch eine andere Meldung bekommen, die meine Vermutung zu bestätigen scheint:
- 2020-06-03T06:12:28.532351+00:00 app[web.1]: (node:23) UnhandledPromiseRejectionWarning: MongoServerSelectionError: connection <monitor> to 18.157.126.246:27017 closed
2020-06-03T06:12:28.532368+00:00 app[web.1]:     at Timeout._onTimeout (/app/node_modules/mongodb/lib/core/sdam/topology.js:430:30)
2020-06-03T06:12:28.532368+00:00 app[web.1]:     at listOnTimeout (internal/timers.js:549:17)

Es gibt also einen Timeout, aus irgendwelchen Gründen kann die Verbindung zum Datenbankserver nicht hergestellt werden.

**Comment by KohlerAl** [comment]
Mit dem neuen Account scheint es aber auch nicht zu funktionieren. Auch da kommen wieder Fehlermeldungen. 
[agkeia-logs-1591165876007.txt](https://github.com/JirkaDellOro/EIA2-Inverted/files/4721378/agkeia-logs-1591165876007.txt)

Im neuen Account gibt es wieder die Datenbank Household und darin die Collection Orders. 

Ich habe mich beim registrieren an die Anleitung aus der Vorlesung gehalten, aber irgendeinen Fehler muss ich wohl gemacht haben, sonst würde es ja funktionieren

**Comment by KohlerAl** [comment]
Ich habe den Server die letzten 20 Minuten einfach in Ruhe gelassen, es kam wieder die Meldung mit dem Timeout
[agkeia-logs-1591167480736.txt](https://github.com/JirkaDellOro/EIA2-Inverted/files/4721477/agkeia-logs-1591167480736.txt)

**Comment by JirkaDellOro** [comment]
Dennis und ich versuchen den Fehler nachzubauen...

**Comment by JirkaDellOro** [comment]
Hattest Du hiermit zu tun?
https://docs.atlas.mongodb.com/tutorial/whitelist-connection-ip-address/

Ich kann mich gerade nicht erinnern, dass dies vor einem halben Jahr schon ein Thema war. Wenn es eine Rolle spielt, müsste man hier die Heroku-IP eintragen.

**Comment by KohlerAl** [comment]
Das könnte der Fehler sein. Ich habe da die IP eingetragen die mir von MongoDB vorgeschlagen wurde, also vermutlich die von meinem Computer. Aber jetzt wo du es sagst macht es natürlich Sinn, die IP von Heroku anzugeben. Wo finde ich die denn?

**Comment by KohlerAl** [comment]
![Screenshot (184)](https://user-images.githubusercontent.com/56314717/83608314-0022d800-a57d-11ea-8df1-109aa7b54453.png)

**Comment by JirkaDellOro** [comment]
Bei mir ist 0.0.0.0/0 eingetragen, möglicherweise heißt das: alles offen. Probier' mal bitte

**Comment by KohlerAl** [comment]
ES FUNKTIONIERT :)

**Comment by KohlerAl** [comment]
Danke! :)

**Comment by JirkaDellOro** [comment]
Ich danke dir für die geduldige Kooperation. Das war jetzt sehr wichtig für alle!

Bitte schließen wenn fertig

**Comment by KohlerAl** [comment]
Ich danke dir für deine Geduld :)

**Comment by vschwan** [comment]
Habs auch hinbekommen! Danke euch :)
