### ISSUE TITLE
Implementation scheitert.

### ISSUE THREAD

**Issue by luziagu** [JirkaDellOro/EIA2-Inverted#142]
Hallo zusammen, 

Ich weiss nicht wo genau mein Problem liegt. Mongo Shell sowie das installieren von MongoDb in Node hat funktioniert. Jetzt wollte ich mit der implementation weiter machen. Allerdings klappt das aufrufen von mongo nicht. 

<img width="527" alt="Bildschirmfoto 2020-06-02 um 20 45 28" src="https://user-images.githubusercontent.com/56430460/83557463-0039be00-a512-11ea-9c85-e73d9f887a3c.png">

Die Datei mongod lässt sich öffnen und zeigt auch an das sie läuft: 
<img width="1233" alt="Bildschirmfoto 2020-06-02 um 20 46 12" src="https://user-images.githubusercontent.com/56430460/83557519-19db0580-a512-11ea-8c09-6cc0d96a696f.png">

Ich glaube das es ein Fehler von meinem Mac ist. Da er ja auch sagt irgendwas muss geupdatet werden. Hab das auch versuch, allerdings scheint mein Passwort falsch zu sein was nicht der fall sein kann. 

<img width="1033" alt="Bildschirmfoto 2020-06-02 um 20 48 29" src="https://user-images.githubusercontent.com/56430460/83557728-6aeaf980-a512-11ea-99bd-48ee7f1cfb52.png">

Irgendwie bin ich verwirrt und weiss nicht weiter.

**Comment by JirkaDellOro** [comment]
In seinem Praxissemester hatte ich @MarkusDamm gezwungen mit einem Mac zu arbeiten. Vielleicht kommt ihm eine Idee?

Was mir aber gar nicht klar ist: wenn MongoShell und der Datenbankserver laufen... was genau läuft denn nicht? Das ist alles was wir brauchen...

**Comment by luziagu** [comment]
Weiß ich nicht. Das ist das Ergebnis wenn ich versuche die Shell nochmal zu starten. Im Video wird etwas anderes erwartet. 
<img width="577" alt="Bildschirmfoto 2020-06-02 um 21 08 05" src="https://user-images.githubusercontent.com/56430460/83559673-40e70680-a515-11ea-8d1d-cd9f08271560.png">

**Comment by JirkaDellOro** [comment]
Es macht den Eindruck, als versuchst Du gleichzeitig zwei Dinge zu tun (vorausgesetzt dieses Terminal funktioniert wie ein Windows-Terminal)
- mit cd willst Du das Verzeichnis wechseln
- mit mongo willst Du die Shell aufrufen

Probiere es mal nacheinander

**Comment by luziagu** [comment]
Hat funktioniert! Manchmal ist es doch einfacher als man denkt :D 

Danke Jirka

**Comment by luziagu** [comment]
<img width="1031" alt="Bildschirmfoto 2020-06-02 um 21 18 38" src="https://user-images.githubusercontent.com/56430460/83560491-a25ba500-a516-11ea-8be2-8ccd1ab76d33.png">
Jetzt wird mir das hier angezeigt. Es scheint also schon zu laufen wenn ich das richtig sehe?

**Comment by luziagu** [comment]
Jetzt hab ich es hinbekommen. War offensichtlicher als gedacht. :D Danke Jirka!

**Comment by JirkaDellOro** [comment]
Sehr schön. Wenn fertig, issue schließen.
