### ISSUE TITLE
Datanbank anlegen funktioniert nicht

### ISSUE THREAD

**Issue by luziagu** [JirkaDellOro/EIA2-Inverted#143]
Hallo zusammen. 

Ich habe versucht eine lokale Datenbank anzulegen. Wenn ich jetzt aber eine Bestellung verschicke ändert sich nichts in den Terminals. Es wird nicht angezeigt dass eine Collection created wird und somit auch keine Datenbank die hergestellt wird. Woran kann das liegen? 

Hier der Link zu meiner Server Datei: https://github.com/luziagu/EIA2/blob/master/Haushaltshilfe-Update/Server/Server.ts
<img width="896" alt="Bildschirmfoto 2020-06-03 um 09 33 32" src="https://user-images.githubusercontent.com/56430460/83608505-4d9f4500-a57d-11ea-80f4-97fa98d2582c.png">
<img width="954" alt="Bildschirmfoto 2020-06-03 um 09 33 50" src="https://user-images.githubusercontent.com/56430460/83608534-57c14380-a57d-11ea-9f92-00b12dd59b1a.png">
<img width="498" alt="Bildschirmfoto 2020-06-03 um 09 33 59" src="https://user-images.githubusercontent.com/56430460/83608549-5db72480-a57d-11ea-80f2-03ce08079a20.png">

**Comment by luziagu** [comment]
<img width="875" alt="Bildschirmfoto 2020-06-03 um 10 42 43" src="https://user-images.githubusercontent.com/56430460/83615552-ff8f3f00-a586-11ea-896f-aa1f3e925f21.png">
Das sind wieder die Fehlermeldungen die ich bekomme wenn ich ein die Bestellung absende, so wie letztes mal. Hat aber vor 5 min noch geklappt und ich habe ein Alert bekommen.

**Comment by luziagu** [comment]
<img width="875" alt="Bildschirmfoto 2020-06-03 um 10 42 43" src="https://user-images.githubusercontent.com/56430460/83615929-77f60000-a587-11ea-93ac-5742515c6b7d.png">
Das ist eine Fehlermeldung die ich bekomme wenn ich die Bestellung abschicken will, ähnlich wie bei der letzten Lektion. Hab jetzt wie beim letzten mal Fehler gesucht aber keine gefunden.

**Comment by luziagu** [comment]
Irgendwie ist das komisch, weil ich vor 10 Minuten noch ein Alert bekommen habe. Und seit dem nichts mehr geändert habe.

**Comment by luziagu** [comment]
Und auch die Verbindung zu Heroku herzustellen hatte ja funktioniert.

**Comment by luziagu** [comment]
<img width="1147" alt="Bildschirmfoto 2020-06-03 um 10 53 50" src="https://user-images.githubusercontent.com/56430460/83616778-87c21400-a588-11ea-9265-03665537933e.png">

**Comment by JirkaDellOro** [comment]
Hast Du auch deinen lokalen Server gestartet, damit der Client sich das JSON-File ziehen kann? (npx serve)

**Comment by JirkaDellOro** [comment]
Die Herokumeldung scheint daher zu kommen, dass Du noch die Adresse deiner lokalen Datenbank im Code hast. da steht 127.0.0.1:27017... das ist dein lokaler Horst.

**Comment by JirkaDellOro** [comment]
Die Fehler im Client kommen dann wohl daher, dass dein Server schon nicht mehr antwortet, weil der den Dienst quittiert hat, als er keine Verbindung zur Datenbank aufbauen konnte.

**Comment by luziagu** [comment]
Npx serve ist an. Irgendwie stehe ich grade auf dem Schlauch. Ich verstehe nicht ganz was ich für eine Adresse angeben soll? Ich habe es genauso gemacht wie in dem Video. Tut sich allerdings lokal eben gar nichts.

**Comment by luziagu** [comment]
Als Adresse habe ich jetzt localhost5001 angegeben, so wie im Code von der Cocktailbar. Aber auch so gibt die Konsole Fehlermeldungen aus.

**Comment by luziagu** [comment]
Ich habe jetzt als Adresse den localhost übernommen. Jetzt wird mir beim Abschicken folgendes angezeigt: "Dein gesamter Einkauf kostet: 6.90€Das hast du bestellt: <!DOCTYPE html><html lang="en"> <head> <meta charset="utf-8"> <meta name="viewport" content="width=device-width, initial-scale=1"> <title>Files within EIA2&#47;</title> <style>body { margin: 0; padding: 30px; background: #fff; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Roboto", "Oxygen", "Ubuntu", "Cantarell", "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif; -webkit-font-smoothing: antialiased;}main { max-width: 920px;}header { display: flex; justify-content: space-between; flex-wrap: wrap;}h1 { font-size: 18px; font-weight: 500; margin-top: 0; color: #000;}header h1 a { font-size: 18px; font-weight: 500; margin-top: 0; color: #000;}h1 i { font-style: normal;}ul { margin: 0 0 0 -2px; padding: 20px 0 0 0;}ul li { list-style: none; font-size: 14px; display: flex; justify-content: space-between;}a { text-decoration: none;}ul a { color: #000; padding: 10px 5px; margin: 0 -5px; white-space: nowrap; overflow: hidden; display: block; width: 100%; text-overflow: ellipsis;}header a { color: #0076FF; font-size: 11px; font-weight: 400; display: inline-block; line-height: 20px;}svg { height: 13px; vertical-align: text-bottom;}ul a::before { display: inline-block; vertical-align: middle; margin-right: 10px; width: 24px; text-align: center; line-height: 12px;}ul a.file::before { content: url("data:image/svg+xml;utf8,<svg width='15' height='19' fill='none' xmlns='http://www.w3.org/2000/svg'><path d='M10 8C8.34 8 7 6.66 7 5V1H3c-1.1 0-2 .9-2 2v13c0 1.1.9 2 2 2h9c1.1 0 2-.9 2-2V8h-4zM8 5c0 1.1.9 2 2 2h3.59L8 1.41V5zM3 0h5l7 7v9c0 1.66-1.34 3-3 3H3c-1.66 0-3-1.34-3-3V3c0-1.66 1.34-3 3-3z' fill='black'/></svg>");}ul a:hover { text-decoration: underline;}ul a.folder::before { content: url("data:image/..."

Was hat das zu bedeuten? Ich bin deshalb so verwirrt, weil alles heute morgen noch funktioniert hat bis auf das sich die lokale Datenbank nicht gebildet hat und auf einmal geht gar nichts mehr.

**Comment by luziagu** [comment]
<img width="1439" alt="Bildschirmfoto 2020-06-03 um 18 27 40" src="https://user-images.githubusercontent.com/56430460/83662549-ebb7fd00-a5c7-11ea-96ad-365ac1fbc65d.png">

Und das verbinden mit der Datenbank funktioniert ja auch. Nur bekomme ich die folgende Ausgabe nicht: 

<img width="751" alt="Bildschirmfoto 2020-06-03 um 18 28 22" src="https://user-images.githubusercontent.com/56430460/83662602-038f8100-a5c8-11ea-897b-c7bd84493466.png">

**Comment by luziagu** [comment]
Kurzes Update: Also ich konnte jetzt irgendwie doch die Datenbank herstellen. Allerdings funktioniert das mit den Einträgen noch nicht. Folgendes wird mir im Terminal angezeigt. Auch der Alert ist immer noch genauso komisch und ich weiß nicht woran das liegt. 

<img width="810" alt="Bildschirmfoto 2020-06-03 um 18 39 53" src="https://user-images.githubusercontent.com/56430460/83663946-9e3c8f80-a5c9-11ea-9ad8-5281f2ddf058.png">

**Comment by JirkaDellOro** [comment]
Ich glaube, Du hattest dich zwischenzeitlich etwas zwischen den Systemen verloren. Das ist auch verwirrend. Ich schlage vor, wir schauen morgen im Praktikum wieder danach. Einiges läuft ja schon ganz gut, der Rest sollte dann auch klappen.
