### ISSUE TITLE
Datensätze aus der Haushaltshilfe werden nicht erfasst

### ISSUE THREAD

**Issue by klinkewitzn** [JirkaDellOro/EIA2-Inverted#144]
Hallo, die Verbindung mit der Database wird im Server angezeigt. Jedoch werden die Datensätze aus der Haushaltshilfe nicht in der MongoShell ausgegeben. Die Datenbank verändert sich auch nicht. (Dieses Problem hatten wir bereits am Dienstag besprochen und da sonst trotzdem alles funktioniert hatte, haben wir es dabei belassen.)
![fehlermeldung2](https://user-images.githubusercontent.com/56318063/83689007-9ba06100-a5ee-11ea-92d2-2a4e5e12954a.PNG)

**Comment by JirkaDellOro** [comment]
Das schauen wir uns nachher im Praktikum an

**Comment by luziagu** [comment]
Ich hab auch das gleiche Problem. :(

**Comment by klinkewitzn** [comment]
Hallo Luzia,
bei mir hatte ich tatsächlich nur vergessen den Datenbank-Namen in meiner Server.ts Datei zu aktualisieren. Vielleicht ist das ja auch dein Problem?
![server-ts-datei](https://user-images.githubusercontent.com/56318063/83750868-3ab46f80-a666-11ea-8927-08efed44f7c3.PNG)
