### ISSUE TITLE
Ausbau der Datenbank

### ISSUE THREAD

**Issue by luziagu** [JirkaDellOro/EIA2-Inverted#146]
Hallo, 
bei mir geht es um den Ausbau der Datenbank, also den letzten Teil der Lektion. Ich bin dort nämlich ein bisschen verloren. Es geht um folgenden Abschnitt: 
<img width="581" alt="Bildschirmfoto 2020-06-06 um 11 10 40" src="https://user-images.githubusercontent.com/56430460/83940722-8f7ef400-a7e6-11ea-9659-c0e886bafa84.png">

Ich verstehe nicht ganz wozu ich diesen Teil implementieren soll. Alles scheint ja bei mir wie gewünscht zu funktionieren. Da ich eben nicht ganz weiß für was ich diese Funktion/en implementieren soll, bzw. was sie erreichen soll, finde ich auch keinen richtigen Ansatz die oben stehenden Anweisungen umzusetzen. 

Freue mich über eine kleine Hilfestellung. -Luzia

**Comment by JirkaDellOro** [comment]
Guter Einwand, der Kontext wird hilfreich sein. Ich habe noch zwei Sätze dazu gefügt, wird es damit verständlich?

- [x] Plane eine Funktion retrieveOrders, welche mit `orders.find()` alle Bestellungen ausliest und ein Array von `Orders` zurückliefert. Nutze dazu die asynchrone Funktion `toArray()` des Cursor-Objektes. Dieses Array soll in der Folge dem Barkeeper dargestellt werden, sodass er die Bestellungen abarbeiten kann.
- [x] Plane eine Erweiterung der Funktion `handleRequest`, so dass retrieveOrders aufgerufen und das Ergebnis als Zeichenkette in die Serverantwort eingefügt wird, wenn der Server mit dem Query-String `command=retrieve` aufgerufen wird. Eine Clientsoftware für den Barkeeper kann damit die Bestellungen abrufen.
- [x] Implementiere diese Erweiterungen und teste sie.

**Comment by luziagu** [comment]
Ja es wird damit verständlicher!
Ich habe jetzt mal ausprobiert damit herumzuspielen und zu schauen wie es funktioniert. Bin mir aber nicht ganz sicher ob ich das hinbekomme.

**Comment by JirkaDellOro** [comment]
> Ich habe jetzt mal ausprobiert damit herumzuspielen und zu schauen wie es funktioniert. Bin mir aber nicht ganz sicher ob ich das hinbekomme.

Damit herumspielen und schauen wie es funktioniert. Das ist genau das, was ich mir von dir erhoffe!!!

**Comment by luziagu** [comment]
Hallo nochmal Jirka, 
Ich bin grade dabei das alles zu implementieren. Jetzt bekomme ich folgende Fehlermeldung, die ich schon mithilfe des Debuggers versucht habe zu lösen. Allerdings weiß ich nicht wie ich das Problem lösen kann. 
<img width="1042" alt="Bildschirmfoto 2020-06-07 um 19 11 44" src="https://user-images.githubusercontent.com/56430460/83975179-bd515f00-a8f2-11ea-9d19-7e1bdc50ae7f.png">
<img width="1141" alt="Bildschirmfoto 2020-06-07 um 19 12 12" src="https://user-images.githubusercontent.com/56430460/83975190-ce01d500-a8f2-11ea-8cbf-3805079d844a.png">

In meiner App will mir folgendes ausgegeben: 
<img width="1200" alt="Bildschirmfoto 2020-06-07 um 19 12 47" src="https://user-images.githubusercontent.com/56430460/83975199-e2de6880-a8f2-11ea-9395-46d06406968c.png">

Link zu meiner App: https://luziagu.github.io/EIA2/Haushaltshilfe-Update/haushaltshilfe.html 
Meine Daten kommen auch bei MongoDB an. 

Danke-Luzia

**Comment by KohlerAl** [comment]
Du versuchst ein fetch an URL, deine Variable für die Url deines Servers heißt aber serverUrl

**Comment by luziagu** [comment]
Oh man, danke! Hab vergessen das ich das umbenannt hatte mit Jirka letztens :D
