### ISSUE TITLE
meldung mongod

### ISSUE THREAD

**Issue by buluthil** [JirkaDellOro/EIA2-Inverted#147]
Hallo ich arbeite gerade an der Aufgabe 7 und habe mongodb bereits problemlos installiert um mit der Aufgabe weiterzumachen wollte ich die mongod und mongo Terminal öffnen jedoch bekomme ich von meinem mac immer solche Meldungen das ich sie nicht öffnen kann oder nicht öffnen soll da mich das unsicher macht, wollte ich fragen wie ich da jetzt am besten weiter machen soll ? oder vielleicht hatte jemand das selbe Problem und kann mir weiterhelfen.

**Comment by buluthil** [comment]
die bilder noch 
<img width="1229" alt="Bildschirmfoto 2020-06-06 um 14 14 47" src="https://user-images.githubusercontent.com/43846406/83944182-d4fcea80-a801-11ea-8e7e-4587844e8742.png">
<img width="1005" alt="Bildschirmfoto 2020-06-06 um 14 25 46" src="https://user-images.githubusercontent.com/43846406/83944191-dc23f880-a801-11ea-85dc-25ccb365d8a8.png">

**Comment by JirkaDellOro** [comment]
Ich gehe davon aus, dass Du hier einen Vertrauensvorschuss geben kannst. Siehe Wikipedia:
> Es ist die am weitesten verbreitete NoSQL-Datenbank (Stand: Oktober 2019).

**Comment by buluthil** [comment]
Vielen Dank. 
habe das Problem gelöst in dem ich die Terminals einfach per Rechtsklick geöffnet habe ohne auf meinem mac weiteres Einzustellen.
