### ISSUE TITLE
Canvas getContext Fehlermeldung

### ISSUE THREAD

**Issue by luziagu** [JirkaDellOro/EIA2-Inverted#149]
Hallo Zusammen, bei der neuen Lektion bekomme ich eine Fehlermeldung. 
Allerdings kann ich mir diese nicht ganz erklären.
<img width="781" alt="Bildschirmfoto 2020-06-07 um 20 54 33" src="https://user-images.githubusercontent.com/56430460/83977514-453e6580-a901-11ea-848a-ffbd27d1736a.png">

**Comment by luziagu** [comment]
<img width="1271" alt="Bildschirmfoto 2020-06-07 um 20 56 46" src="https://user-images.githubusercontent.com/56430460/83977536-6bfc9c00-a901-11ea-8874-7eec4034aae3.png">

**Comment by AnnaLotz** [comment]
Das heißt, dass der canvas vermutlich nicht gefunden wurde. Schau nach, ob dieser richtig in der html steht und/oder versuche ihn über document.getElementById() zu holen.

**Comment by AnnaLotz** [comment]
Beziehungsweise nein, das Problem ist, dass der DOM noch nicht geladen wurde, daher existiert der canvas dort noch gar nicht! Setzt einen eventlister für load ein.

**Comment by luziagu** [comment]
Ah ja klar, danke dir!
