### ISSUE TITLE
Smartphone Optimierung

### ISSUE THREAD

**Issue by luziagu** [JirkaDellOro/EIA2-Inverted#150]
Hei! 

Ich bin mir grade etwas unsicher wegen der Pixel, also wie groß die Fläche sein muss. Bevor ich jetzt anfange alles aufzuzeichnen und dann nochmal alles neu machen muss, weil die Pixel nicht stimmen dachte ich, ich frage kurz mal nach. 
Ich hätte jetzt die Seitenverhältnisse 1280 X 720 genommen, mach das so Sinn? 

-Luzia

**Comment by JirkaDellOro** [comment]
Das hört sich vernünftig an. Wenn man weiter gehen will muss man sich Standardwerte für die Höhe der Browseradresszeile etc. anschauen. Letztlich entscheidest Du. Bitte schließen wenn fertig
