### ISSUE TITLE
Corona Virus Darstellung

### ISSUE THREAD

**Issue by celine333** [JirkaDellOro/EIA2-Inverted#151]
Hallo,

ich hätte da mal eine Frage zur Darstellung von dem Corona Virus. 
Würde es Sinn machen einen kleinen Kreis zu zeichnen (als Membran) und von dem aus dann immer jeweils 2 Linien weglaufen zu lassen, die dann wiederum mit einem Halbkreis geschlossen/ verbunden werden (für die einzelnen Proteine)? Evtl. mit moveTo() und lineTo()? Oder geht das viel einfacher?

Ich hoffe man kann sich etwas unter meiner Beschreibung vorstellen :D.

**Comment by JirkaDellOro** [comment]
Hübsch! 
Für eine erste Näherung könnte man auf die Stiele verzichten und einen Kranz von Kreisen "unter" den Viruskörper zeichnen. 
Wenn Du es gleich richtig machen möchtest, solltest Du unbedingt mit dem Befehl "rotate" arbeiten. Du bringst das Koordinatensystem zuerst in die Stelle auf dem Screen, wo das Zentrum des Virus sein soll und zeichnest den ersten Stiel mit Köpfchen. Dann rotierst Du das Koordinatensystem und zeichnest den gleichen Stiel wieder usw. Am Ende lässt Du den Viruskörper darüber zeichnen. So mein Vorschlag.

**Comment by JirkaDellOro** [comment]
Und noch ein wichtiger Tipp: markiere in deinen Detailskizzen immer, wo das Zentrum bzw. der Koordinatenursprung des Motivs liegen soll! Beim Virus wird das sicher dessen Mittelpunkt sein, bei deinem Antikörper wird die Wahl schon schwieriger.
