### ISSUE TITLE
Aktivitätsdiagramm 

### ISSUE THREAD

**Issue by luziagu** [JirkaDellOro/EIA2-Inverted#152]
Hallo Jirka, 
da Heute doch kein Praktikum stattgefunden hat jetzt auf diesem Wege :D. 

Ich stehe etwas auf dem Schlauch mit meinem Aktivitätsdiagramm. Der Hintergrund ist mir klar und da hab ich eine Idee wie ich das umsetzten kann. Aus irgendeinem Grund hänge ich aber bei den Zellen und dem Virus. Ich weiß nicht ob ich zu kompliziert denke und deswegen nicht weiter komme. 
Ich habe Ideen mit Schleifen und Variablen aber auf so einen richtigen Ansatz komme ich nicht. 
Ich denke mir würde es helfen zu wissen ob mein Scribble so sinn macht und was ich daran verbessern könnte. bzw. Ansätze, die mich weiter bringen. 

Hier mein Scibble + Aktivitätsdiagramm 
https://luziagu.github.io/EIA2/Corona-Canvas/Konzept/Scribble-konzept.pdf

-Luzia

**Comment by JirkaDellOro** [comment]
Dein Scribble ergibt für mich äußerst viel Sinn und dein Aktivitätsdiagramm auch. Die Idee mit dem Pattern als Background finde ich sehr interessant. Und die Idee mit den Schleifen ist auch genau die richtige. Ich denke, Du müsstest dich sehr gut z.B. an meiner Wolke orientieren können, wenn Du Gruppen von Humanzellen oder Viren darstellen willst. Die Wolke ist ja auch nur eine Gruppe von Wolkenpartikeln.

Zwei Dinge fallen mir aber im Aktivitätsdiagramm als fragwürdig auf
- Die Viren werden gezeichnet bevor die Humanzellen gezeichnet werden, und würde so hinter jenen verschwinden. Hast Du dir das so vorgestellt?
- mit "translate to sceen" kann ich nichts anfangen. Das Standard-Koordinatensystem hat seinen Ursprung in der linken oberen Ecke, damit solltest Du den Hintergrund gut zeichnen können.

**Comment by luziagu** [comment]
Okay, vielen Dank Jirka! Ich werde jetzt mal ein bisschen herum probieren :)

**Comment by luziagu** [comment]
Noch eine Frage: Wie bekomme ich die Form der Killerzellen hin, also dass ein Teil des Kreises rausgeschnitten wird, wie in einem Kuchen?

**Comment by JirkaDellOro** [comment]
Ah... deine Pakmen...
Es müsste so funktionieren können (Pseudocode):
- moveTo center
- draw arc
- close path
- stroke/fill

**Comment by luziagu** [comment]
Ja genau :D Super ich probiere es aus!
