### ISSUE TITLE
Gradient wird nicht angezeigt

### ISSUE THREAD

**Issue by schneine** [JirkaDellOro/EIA2-Inverted#153]
Hallo Jirka, 

ich bin am Anfang der Implementierung und mir wird dieser Fehler angezeigt, verstehe nicht sowieso, wollte es eig im Praktikum klären. 
<img width="669" alt="Bildschirmfoto 2020-06-11 um 12 19 31" src="https://user-images.githubusercontent.com/56204469/84374774-c6864880-abde-11ea-99d3-28504c8ca60d.png">

https://github.com/schneine/EIA2/tree/master/L08_Canvas

**Comment by JirkaDellOro** [comment]
Schickst Du mir bitte noch einen Link zur App?

**Comment by schneine** [comment]
file:///Users/nellys/Documents/EIA%202/schneine.github.io-EIA2/L08_Canvas/Corona.html

**Comment by schneine** [comment]
file:///Users/nellys/Documents/EIA%202/schneine.github.io-EIA2/L08_Canvas/Corona.html

**Comment by JirkaDellOro** [comment]
Ich brauche den http-Link zu Pages

**Comment by JirkaDellOro** [comment]
Ich habe ihn mir selbst zusammengebastelt.

Setze ich im Debugger einen Breakpoint an die Stelle, an der der Fehler auftritt, kann ich sehen, dass `middle` nicht definiert ist. Das liegt einfach daran, schätze ich, dass Zeile 10 so aussieht
`    let middle: 0.25; `
Du hast also keine Zuweisung (=) gemacht, sondern eine Typdeklaration...

**Comment by schneine** [comment]
Ohje das hab ich wohl komplett übersehen. Vielen Dank für den Hinweis.

**Comment by schneine** [comment]
Jetzt klappt es!
