### ISSUE TITLE
Fehlermeldung "getcontext"of null

### ISSUE THREAD

**Issue by luziagu** [JirkaDellOro/EIA2-Inverted#154]
Ich hatte diese Fehlermeldung letztens schonmal, aber jetzt bekomme ich sie nicht gelöst, das Script scheint zu laufen. 
Ich versuche grade den Hintergrund zu implementieren mithilfe von Patterns. 

https://luziagu.github.io/EIA2/Corona-Canvas/corona.html

**Comment by KohlerAl** [comment]
Dein Html wurde noch nicht geladen, wenn du die Variablen definierst...

**Comment by luziagu** [comment]
Hab den Fehler gelöst, aber jetzt bekomme ich einen neuen. 
<img width="700" alt="Bildschirmfoto 2020-06-11 um 14 55 39" src="https://user-images.githubusercontent.com/56430460/84387735-c5134b00-abf3-11ea-90cd-e93aa763e49d.png">

**Comment by luziagu** [comment]
Den Fehler habe ich behoben. Jetzt kommt aber eine neue Fehlermeldung, dass das width null ist. Das Pattern hat bei mir aber aus der Lektion beim Test funktioniert, jetzt funktioniert das gleiche nicht mehr. Muss ich width deklarieren und wenn ja warum auf einmal? 
<img width="700" alt="Bildschirmfoto 2020-06-11 um 14 55 39" src="https://user-images.githubusercontent.com/56430460/84388062-3ce17580-abf4-11ea-8d78-d648770659c4.png">

**Comment by KohlerAl** [comment]
Du deklarierst die Variable canvas zwei mal, ein mal in Zeile 9 und ein mal in Zeile 16. Die Canvas Variable in Zeile 16 ist aber nur in der Funktion handleLoad verfügbar. Die Variable in Zeile 9 ist null, weil das HTML zu dem Zeitpunkt, zu dem das Script gelesen wird, noch nicht geladen wurde.

**Comment by luziagu** [comment]
Ja habs grade gesehen, dass war aber irgendwie nicht das Problem. Habe jetzt das Problem jetzt so gelöst: crc2.fillRect(0, 0, crc2.canvas.width, crc2.canvas.height) und ein crc2 vor Canvas geschrieben.
