### ISSUE TITLE
Restore() und safe()

### ISSUE THREAD

**Issue by luziagu** [JirkaDellOro/EIA2-Inverted#156]
Ich habe noch mal eine Frage zu Restore und Safe. Ich habe die Zellen jetzt mithilfe einer Schleife gebildet und dann mit Restore und Safe gespeichert. 

Jetzt wollte ich das mit den Antikörpern machen. Habe die zuerst in einer Funktion erstellt und wollte jetzt mithilfe einer Schleife diese duplizieren. Vor der Schleife habe ich den erstellte Antikörper gespeichert mit safe(); Wenn die Schleife durchlaufen wird wird aber nichts dupliziert. 
Hat das etwas damit zutun, dass das safe noch die Zellen gespeichert hat? 

-Luzia 

Link zur Anwendung: https://luziagu.github.io/EIA2/Corona-Canvas/corona.html

**Comment by luziagu** [comment]
Hei, 
da ich immer nich nicht auf eine Idee gekommen bin wie ich das hier lösen könnte wollte ich noch einmal nachfragen ob es irgendwelche anderen Ansätze gibt. Danke schonmal im voraus :)

**Comment by JirkaDellOro** [comment]
Sorry, den Issue habe ich irgendwie übersehen. Ich schau rein...

**Comment by JirkaDellOro** [comment]
Dein Konzept kann ich leider nicht einsehen... :unamused: 

Aus dem Code glaube ich zu erkennen, dass Du `restore` und `save` überstrapazierst. Damit soll eigentlich nur der aktuelle Zeichenstil und das Koordinatensystem zwischengespeichert und wiederverwendet werden. Du bist damit aber ziemlich weit gekommen.

Besser, und für die folgenden Lektionen auch wichtig, ist folgende Vorgehensweise:
- entwickle zunächst Funktionen, die jeweils nur ein Motiv zeichnen, also ein Virus, eine Zelle etc.
- wenn es sinnvoll erscheint, kannst Du diese mit `crc2.save` beginnen und `crc2.restore` beenden, dann ist nach dem Aufruf der Funktion der Stil und das Koordinatensystem genau wie zuvor, auch wenn Du beides innerhalb der Funktion änderst. 
- entwickle dann erst Funktionen, die Gruppen dieser Motive darstellen. Darin hast Du deine Schleifen, die einfach die entsprechende Motivfunktion nutzen.

Kommt das verständlich rüber? Diese Grundstruktur findest Du auch in meiner Allee mit "drawTree" und `drawTrees`. Allerdings malt `drawTree` einen Baum immer auf (0|0) und nimmt keine Parameter an, die Positionierung und Skalierung der Bäume geschieht in der aufrufenden Schleife durch Manipulation des Koordinatensystems. Bei dir würde ich eher der Motivfunktion Parameter für die Position etc. übergeben.

**Comment by luziagu** [comment]
Hallo Jirka,

Ja das kommt alles verständlich rüber. Ich hatte das auch schon probiert mit der Art wie du es mit den Bäumen gemacht hast, aber auch das hat bei mir nicht richtig funktioniert. Ich werde es jetzt noch einmal versuchen.

**Comment by luziagu** [comment]
Ich hab das jetzt mit den zwei Funktionen bei den Antikörpern ausprobiert, allerdings funktioniert das bei mir nicht. Also hat ja auch schon vorher nicht funktioniert, dass mehrer Antikörper in der Schleife ausgegeben wurden.

**Comment by KohlerAl** [comment]
Wenn ich das richtig sehe, rufst du die Funktion drawAntibody zwar mehrfach auf, übergibst aber jedes mal dieselbe Position. Das bedeutet, dass alle Antikörper übereinander liegen.

**Comment by KohlerAl** [comment]
Update: Ich habe gerade den Code bei mir ausprobiert und einfach _position an drawAntibodies übergeben. 
![Screenshot (197)](https://user-images.githubusercontent.com/56314717/84564413-bb0f5a80-ad61-11ea-8c73-f329a49df096.png)

**Comment by luziagu** [comment]
Das heißt das verändert die Position der einzelnen Antikörper?

**Comment by luziagu** [comment]
Ich versteh dass nämlich noch nicht so ganz. Hab das jetzt auch mal mit den Killerzellen ausprobiert und auch da hat es dann nicht funktioniert. Ich meine aber halt auch das sie dort auch übereinander liegen. 

Und Danke für deine Hilfe Alida!!

**Comment by KohlerAl** [comment]
In der Funktion showAntibodies variierst du in den Zeilen 153 und 154  die Werte von x und y. Du übergibst die veränderten Werte dann aber nicht an drawAntibodies, sondern immer 250 und 600. Das heißt du hast dann sieben Antikörper an der gleichen Stelle. Wenn du stattdessen _position übergibst, übergibst du die veränderten Werte und die Antikörper haben unterschiedliche Positionen :)

**Comment by KohlerAl** [comment]
Sehr gerne :)

**Comment by luziagu** [comment]
Ja das macht total sinn! Aber warum passiert das bei den Killerzellen nicht? Die bekommen ja auch einen Wert übertragen. Ich hab das was ich ausprobiert habe nochmal gepusht.

**Comment by KohlerAl** [comment]
In den Zeilen 183 und 184 gibst du fixe Werte an, da müssten dann die Werte aus _position rein

**Comment by luziagu** [comment]
Ah vielen Dank!!! :)

**Comment by luziagu** [comment]
crc2.arc(100, 100, radiusKillerCell, 0.2 * Math.PI, 1.8 * Math.PI, false);
        crc2.lineTo(100, 100);

Meinst du die zwei Zeilen?

**Comment by KohlerAl** [comment]
Genau, die ersten zwei Werte von crc2.arc geben ja die Koordinaten vom Kreismittelpunkt an, das ist in deinem Fall für alle Zellen (100, 100)

**Comment by luziagu** [comment]
Danke dir Alida, wirklich!

**Comment by KohlerAl** [comment]
Gerne :) Funktioniert es denn jetzt?

**Comment by luziagu** [comment]
Ja funktioniert jetzt gut! Danke nochmal!!

**Comment by KohlerAl** [comment]
Das freut mich :)
