### ISSUE TITLE
Pfad rotieren

### ISSUE THREAD

**Issue by RueJohannes** [JirkaDellOro/EIA2-Inverted#157]
Hallo,
ich frage mich ob es möglich ist einen Pfad um einen bestimmten Radius rotieren zu lassen. Mein Virus ist kreisförmig und ich habe einen "Arm" gezeichnet der dann 12x in alle Richtungen vom Virus weggehen soll.
Ich hoffe mir kann jemand weiterhelfen.

**Comment by JirkaDellOro** [comment]
Du willst wahrscheinlich um einen Winkel rotieren. Nutze einfach die rotate-Methode um das Koordinatensystem zu drehen. Siehe: https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/rotate
