### ISSUE TITLE
Aufgabe 08 Object is possibly 'null'

### ISSUE THREAD

**Issue by smo-haenle** [JirkaDellOro/EIA2-Inverted#158]
Hallo, 
meine Anwendung geht soweit jedoch werden mir noch einige Fehlermeldungen ausgeworfen (immer wenn ich versuche auf den canvas (z.B. auf die Breite oder Höhe) zu zugreifen).

<img width="526" alt="Bildschirmfoto 2020-06-12 um 14 54 30" src="https://user-images.githubusercontent.com/56439337/84509194-a8464880-acc3-11ea-8f51-cdbc0791f594.png">

Repo:
https://github.com/smo-haenle/smo-haenle.github.io/tree/master/Eia2/Aufgabe%208

Pages:
file:///Users/SimonHanle/Desktop/studium/programmieren/Eia2/Aufgabe%208/Aufgabe8.html

**Comment by JirkaDellOro** [comment]
Typescript weist dich darauf hin, dass die Suche nach dem Canvas per querySelector auch erfolglos sein könnte und dann fillRect nicht funktionieren wird. Da gibt es verschiedene Ansätze:
- prüfe vor der Nutzung ob canvas definiert ist
- weise TypeScript darauf hin, dass Du sicher weißt, dass querySelector erfolgreich sein wird, indem Du `<HTMLCanvasElement` davor schreibst und somit das Ergebnis als gültiges Canvas-Element betrachtet wird
- nutze nicht `canvas` sondern `crc2.canvas`, der RenderingContext weiß nämlich, zu welchem Canvas er gehört.

Ich bevorzuge die letzte Variante

PS: vermeide unbedingt "Inner Functions", also Funktionen die innerhalb von anderen Funktionen definiert sind, wenn Du nicht ganz sicher weißt, warum Du sie unbedingt haben musst.. Lasse den Autoformatter laufen um sie leichter zu erkennen

**Comment by smo-haenle** [comment]
Hallo Jirka, danke für die schnelle Antwort.
Fehler sind weg, jedoch weiß ich nicht was du mit inner Functions in meinem Fall genau meinst.

**Comment by JirkaDellOro** [comment]
Wenn Du den Autoformatter nutzt, und dein Code sieht gerade so aus, als würdest Du es tun, kannst Du gut inner functions erkennen. Sie sind tiefer eingerückt. Beispielsweise erkennt man sofort, dass die Funktion drawBackground innerhalb von handleLoad definiert ist.
 
```typescript
function handleLoad(_event: Event): void {
        ...
        function drawBackground(): void {
```

Es gibt tatsächlich unter bestimmten Umständen Gründe, das so zu tun. Treffen solche bei dir zu?

**Comment by smo-haenle** [comment]
ahhh nein, du hast natürlich recht! 
Danke dir.

**Comment by smo-haenle** [comment]
close #158
