### ISSUE TITLE
Platzierung Partikel

### ISSUE THREAD

**Issue by DominikWieck** [JirkaDellOro/EIA2-Inverted#159]
Hello zusammen,

ich bekomme es irgendwie nicht auf die Reihe die Partikel im Bildschirm zu platzieren. Diese 
Kratzen wenn dann nur den Bereich an 

![image](https://user-images.githubusercontent.com/56441910/84513757-345b6e80-acca-11ea-94bc-b11aa66ea44f.png)

Link zu Aufgabe: https://github.com/DominikWieck/dominikwieck.github.io/tree/master/EIA2/Aufgabe08

Link zu Code:
https://github.com/DominikWieck/dominikwieck.github.io/blob/master/EIA2/Aufgabe08/coroni.ts

**Comment by JirkaDellOro** [comment]
Schenkst Du mir noch einen Link zur App?

**Comment by JirkaDellOro** [comment]
... und wo ist dein Konzept? Ich kann so nicht sehen, was Du vorhast und wie Du es zu tun gedenkst. ☹️

**Comment by DominikWieck** [comment]
Ich weiß es selber nicht genau wie :D Das Konzept stimmt mittlerweile auch nicht mehr 100% überein.
Aber probieren wirs einfach mal 👍 

Ich wollte erst die Corona-Viren mittels transform erstellen, habe dies aber verworfen und hab mich dazu entschieden die Viren sowohl als auch die Zellen als Partikel zu entwerfen. 

Link zur Anwendung: https://dominikwieck.github.io/EIA2//Aufgabe08/Coroni.html
Link zum Konzept:  https://dominikwieck.github.io/EIA2//Aufgabe08/Konzept.pdf

**Comment by JirkaDellOro** [comment]
Setze im Debugger einen Breakpoint auf Zeile 93 und lasse dein Programm mit F8 immer wieder an den Punkt laufen. Ich erkenne da, dass die vertikale Koordinate immer weit im negativen Bereich ist. Es scheint also, als würdest Du außerhalb des Canvas zeichnen...

Beachte unbedingt die Hinweise zur Aufgabenstellung wie
> Für jedes Motiv soll es eine Funktion geben, welche eine Position und gegebenenfalls weitere Parameter entgegen nimmt und das entsprechende Motiv an der richtigen Stelle unter Berücksichtigung der anderen Parameter zeichnet. Es kann auch Funktionen für Motivgruppen geben, die wiederum die **Funktionen der Einzelmotive** aufrufen.
