### ISSUE TITLE
rotate und translate

### ISSUE THREAD

**Issue by klinkewitzn** [JirkaDellOro/EIA2-Inverted#160]
Hallo, wenn ich für ein Element (meinen Virus) die Funktion rotate und translate anwenden möchte, wirkt sich dies gleichzeitig auch auf alle anderen Elemente aus. Wie kann ich da entgegen wirken, dass sich nicht auch der ganze Rest des Bildes verschiebt?

**Comment by KohlerAl** [comment]
Du kannst, bevor du dein Koordinatensystem drehst/ verschiebst, mit save() den aktuellen Zustand des Koordinatensystems speichern und dann wenn du den Virus gezeichnet hast, stellt du den ursprünglichen Zustand mit restore() wieder her.
