### ISSUE TITLE
Doppelte anfrage an Node.js Server

### ISSUE THREAD

**Issue by Plagiatus** [JirkaDellOro/EIA2-Inverted#161]
Ich schaue mir gerade das L06 Video Implementation 2 an (um mir Inhalte für GiS zu mopsen), und bei 11:30 sagst du @JirkaDellOro, dass du aus "irgendwelchen Gründen zwei Anfragen bekommst" und dass du "selbst nicht weißt woran das liegt".

Falls du das noch nicht heraus gefunden hast: Das liegt daran, dass der Browser versucht, das favicon als resource anzufragen, was als seperate Anfrage an der Server geschickt wird, siehe auch 6:30 im selben Video.

**Comment by JirkaDellOro** [comment]
Ah... super, danke! Ich habe das noch nicht weiter verfolgt.

**Comment by Plagiatus** [comment]
Hab gedacht ich sags dir schnell, das hat mich damals auch schon gewundert und hab mich da mal auf die Suche gemacht gehabt. :D
