### ISSUE TITLE
Corona-Viren 

### ISSUE THREAD

**Issue by luziagu** [JirkaDellOro/EIA2-Inverted#162]
Ich hab eine kleine Frage zu meinen Corona-Viren. Und zwar werden die egal wie ich sie positioniere immer oben links im Eck angezeigt. Sie verschieben sich also nicht. 
Woran liegt das? Mithilfe des Debuggers konnte ich auch nicht wirklich feststellen, warum diese in der Ecke verharren. 

Danke schonmal im voraus! 
-Luzia :) 

https://luziagu.github.io/EIA2/Corona-Canvas/corona.html

**Comment by MarkusDamm** [comment]
Dazu war auch mein Komment auf der Kursseite. Schau mal in der drawKillercell-Funktion, ob das save am Ende nötig ist oder ob das irgendwo anders hin sollte. Und wenn du ```crc2.save();``` benutzt, dann auch mit ```crc2.restore();```
Ist zumindest meine Vermutung :)

**Comment by AionixX** [comment]
Mir ist zudem noch aufgefallen das du deiner `drawCoronaCell` Funktion die Parameter `_position` und `_size` übergibst. Diese beiden Parameter werden in der Funktion aber nie benutzt.

Außerdem rufst du am Ende die Funktion `crc2.restore()` auf. Hast aber davor nicht `crc2.save()` aufgerufen.

**Comment by luziagu** [comment]
Okay, ich werde mal rumprobieren, danke!

**Comment by luziagu** [comment]
Also ich habe einfach beim Kreis den Parameter Position mit angegeben, dann wurden sie sichtbar. Aber irgendwie bekomme ich es jetzt nicht mehr hin das die Stäbchen sich an dem Kreis orientieren.

**Comment by JirkaDellOro** [comment]
Hast Du schon gepusht? Die roten Teile werden von der Pages-App immer noch links oben angezeigt...

**Comment by luziagu** [comment]
Hatte nicht gepusht, ist jetzt aber passiert! :D 
https://luziagu.github.io/EIA2/Corona-Canvas/corona.html

**Comment by JirkaDellOro** [comment]
Ich habe gleich Veranstaltung. Aber auf die Schnelle:

Für die Stengel rotierst Du das Koordinatensystem um die linke obere Ecke und zeichnest sie dann weit weg von diesem Zentrum. Einige sieht man so im Bild herumfliegen. Dann malst Du den Körper an `position`. Damit hast Du Körper und Stengel getrennt. 

Lösung verschiebe am Anfang der Funktion das Koordinatensystem an `position` und nimm den Parameter aus den Zeichenbefehlen heraus.

**Comment by luziagu** [comment]
Hallo Jirka, danke für deine schnelle Antwort. Ich habe das jetzt mal versucht, weiß aber nicht ob ich das richtig verstanden habe. Hat auf alle fälle nicht so richtig geklappt. 
Ich verstehe aber meinen Fehler den du beschrieben hast! 

https://luziagu.github.io/EIA2/Corona-Canvas/corona.html

<img width="611" alt="Bildschirmfoto 2020-06-17 um 11 43 19" src="https://user-images.githubusercontent.com/56430460/84882681-e78fe300-b08f-11ea-97f9-b98d15503c72.png">

**Comment by KohlerAl** [comment]
Du malst deine Stängel in die Mitte von deinem Koordinatensystem und machst dann den Kreis drüber. Das bedeutet, dass die Stängel unter dem Kreis liegen.

**Comment by JirkaDellOro** [comment]
Sie sind wohl einfach zu kurz!

**Comment by luziagu** [comment]
Stimmt! Danke
