### ISSUE TITLE
 Path

### ISSUE THREAD

**Issue by DominikWieck** [JirkaDellOro/EIA2-Inverted#163]
Heyho, ich habe grade etwas Probleme beim coden.

In der Implementation nutzt du für "AsteroidPaths" ein Array : 

![image](https://user-images.githubusercontent.com/56441910/84911874-10789e00-b0b9-11ea-8ff5-f78592fbdf20.png)

Da ich jetzt ja anders gecoded habe komme ich nicht mehr weiter an folgenden Punkt: 

![image](https://user-images.githubusercontent.com/56441910/84912282-8f6dd680-b0b9-11ea-976e-b870e3536fae.png)

Kann ich das so gleich coden oder brauch dafür ne andere Lösung? Oder bin ich komplett falsch? 

Anwendung: https://dominikwieck.github.io/EIA2//Aufgabe_09/Coroni.html

**Comment by JirkaDellOro** [comment]
Bitte nutze unbedingt die Auto-Formatierung, sonst ist dein Code sehr schwer zu lesen. Und poste bitte auch einen Link zum Source-Code.

Zu deinem Screenshot: 
- da Du kein Array nutzt um Pfade zu definieren, weiß ich nicht wie dein Code mit meiner Asteroids-Lösung zusammenhängen soll
- du nutzt in der dargestellten Zeile `particle` als wäre es eine Funktion. Wo ist diese definiert?
- wo ist überhaupt `particle` definiert und von welchem Typ ist es?

**Comment by DominikWieck** [comment]
Meinst du mit Source Code diesen hier ? 
https://github.com/DominikWieck/dominikwieck.github.io/tree/master/EIA2/Aufgabe_09 

Heiß und fettig nochmal Code mit Auto-Formatierung: 
https://dominikwieck.github.io/EIA2//Aufgabe_09_/Coroni.html

Ja, das weiß ich jetzt leider auch nicht :/ Deswegen tappe ich gerade etwas im Dunkeln... Ich steh auch auf dem Schlauch gerade und weiß jetzt nicht so recht wie ich weiter machen soll.

particle ist eine Variable, habe sie 2-mal definiert. Ist glaub auch nicht die sauberste Variante

Einmal Hier: 

![image](https://user-images.githubusercontent.com/56441910/84933047-8f7bcf80-b0d5-11ea-850e-ec55a33ede15.png)

und hier : 

![image](https://user-images.githubusercontent.com/56441910/84933115-ad493480-b0d5-11ea-9322-ca2bf22681a7.png)

Ich hab die particle auch nur genommen weil ich mich an deiner Lektion orientiert habe und dass das Einzige mir mögliche ist was ich dafür nehmen konnte. particle findest du in coroni.ts.

**Comment by JirkaDellOro** [comment]
- Ja, das habe ich mit Source-Code gemeint, dann muss ich mich nicht auf eine zeitraubende Suche begeben und betrachte am Ende den falschen Code. Bitte also immer unbedingt verlinken in den Issues
- Allerdings sehe ich ihn immer noch nicht ordentlich formatiert und die Zeile mit `export`  finde ich gar nicht...
- Hast Du schon ein Konzept (Klassendiagramm) gemacht und wo finde ich das?
- Du kannst particle durchaus mehrfach deklarieren, bei dir ist einer offensichtlich global im namespace, der andere local in einer Funktion. Es kommt darauf an was Du vorhast, das kann ich ohne Konzept leider nicht erahnen.
- beide sind offensichtlich vom Typ Path2D. So ergibt also `particle(this.type)` keinen Sinn, da `particle` keine Funktion ist. Deswegen sagt dir der Compiler auch `is not callable`
- einfach `crc2.stroke(particle)` wäre dagegen zumindest semantisch korrekt
