### ISSUE TITLE
Constructor Aufgabe09

### ISSUE THREAD

**Issue by smo-haenle** [JirkaDellOro/EIA2-Inverted#164]
Hallo Jirka, Hallo Andere,

ich bin gerade dabei ein Klassendiagramm für meinen Virus zu erstellen.
Der Virus sollte eine ...
... Zufällige Größe (size: number)
... Bestimmte Geschwindigkeit  (velocity: number)
... Und eine Position haben.( position: number)

Und er soll sich innerhalb einer Begrenzung bewegen können.

Da ich nun die beiden W- Fragen geklärt hab, kann ich zu meinem eigentlichen Issue kommen:
Bei den Asteroids hat man ja einen constructor "konstruiert" und ihm eine bestimmte Größe 
(_size: number) mitgegeben. Bei dem Virus ist es nun aber so, dass es keine bestimmte Größe gibt. Wenn ich nun nichts zum "mitgeben" habe, brauche ich dann trotzdem einen constructor?
Ich dachte eigentlich ich hätte das mit dem constructor verstanden aber anscheinend doch nicht. Schade eigentlich.

Hier noch meine letzte Aufgabe : 
https://github.com/smo-haenle/smo-haenle.github.io/tree/master/Eia2/Aufgabe%208

**Comment by JirkaDellOro** [comment]
Könnte dir dieser Auszug aus dem Absatz "Constructor" der Lektion helfen?

>Auch bei der Instanzierung von Objekten kommt ein Constructor zum Einsatz, den Du im Deutschen wiederum Konstruktor nennen kannst. Er ist eine besondere Methode, die automatisch aufgerufen wird, wenn die Anweisung new ausgeführt wird und kümmert sich darum, dass das Objekt ordentlich gebaut wird. Ein Standardkonstruktor ist in Javascript immer dabei und tritt nicht in Erscheinung. Du kannst aber für jede Klasse einen eigenen Konstruktor definieren.

Wenn Du nichts im Konstruktor zu erledigen hast, muss Du also keinen eigenen definieren.

**Comment by smo-haenle** [comment]
perfekt, danke!

**Comment by smo-haenle** [comment]
closed #164

**Comment by JirkaDellOro** [comment]
Schließt Du den Issue, bitte?
