### ISSUE TITLE
Fehlermeldung "refused to execute..."

### ISSUE THREAD

**Issue by luziagu** [JirkaDellOro/EIA2-Inverted#165]
Hallo zusammen, ich spiele grade mit meinem Code rum und er ist wahrscheinlich nicht mal ansatzweise lauffähig. Allerdings kommt beim aufrufen der HTML-Seite direkt folgende Fehlermeldung: 
<img width="928" alt="Bildschirmfoto 2020-06-18 um 18 45 33" src="https://user-images.githubusercontent.com/56430460/85048643-e5af4800-b193-11ea-87f6-aaf9ed125b9b.png">

Ich habe die noch nie gesehen und kann sie auch nicht zuordnen. Mein Code ist auch grade ziemlich durcheinander, weil ich glaube ich etwas verloren in der ganzen Animation bin, also nicht erschrecken :D 

Danke schonmal! 
-Luzia 

Link zur App: https://luziagu.github.io/EIA2/Corona-Animation/corona.html

**Comment by JirkaDellOro** [comment]
Die Endung `.ts` wird auch für ein Videoformat verwendet und die Fehlermeldung deutet darauf hin, dass dein System dem Browser mitteilt, dass ein Video der Dateityp sei.

Lass uns bei den `.js`-Dateien bleiben, weil der Browser ohnehin (noch) kein Typescript kann.

**Comment by luziagu** [comment]
Ups, so einfach kann es manchmal sein :D
