### ISSUE TITLE
Verstehe Klassen nicht so ganz

### ISSUE THREAD

**Issue by k-poschmann** [JirkaDellOro/EIA2-Inverted#167]
Hallo,

ich habe das Problem, dass ich nicht genau weiß wie man die Klassen benutzt. Welche Werte ich wo übergeben muss, damit was funktioniert. Ich weiß, was meine Methoden draw und move machen sollen, bin mir aber nicht sicher, wie ich sie in meiner Main.ts verankern soll...bzw. wie ich diese aufrufe. Ich hoffe das war irgendwie verständlich aber diesmal hab ich echt Probleme das Konzept der Klassen wirklich zu verstehen.

Ich danke schon mal im Voraus :)

Link zur App: https://k-poschmann.github.io/poschmannEia2/Aufgaben/Aufgabe_9/index.html
Link zum Repo: https://github.com/k-poschmann/poschmannEia2/tree/master/Aufgaben/Aufgabe_9

**Comment by JirkaDellOro** [comment]
Am Code kann ich Verständnisprobleme nicht gut erkennen. Hast Du ein Klassendiagramm gemacht? Falls nicht, erstelle bitte unbedingt eines! Es kann sogar sein, dass es dabei Klick schon macht. Und bei Bedarf, mache ich gerne morgen auch nochmal eine Online-Session.

**Comment by FrankeSa** [comment]
Ich bekomme auch nichts auf die Kette! Wenn es morgen eine Online-Session gäbe, wäre ich dabei :-) 

beim pushen auf github ist bei mir auch was schief gelaufen.

![image](https://user-images.githubusercontent.com/56167839/85171628-a9511a00-b26f-11ea-9427-82dc5b670539.png)
![image](https://user-images.githubusercontent.com/56167839/85171661-b79f3600-b26f-11ea-84b2-96fbd935957b.png)

**Comment by JirkaDellOro** [comment]
OK, ich werde von 12.00 bis 13.00 Uhr in dm16 sein. Spreizt das Wort.

**Comment by k-poschmann** [comment]
Ja ich habe bereits ein Klassendiagramm erstellt. Hier der Link dazu:
https://github.com/k-poschmann/poschmannEia2/blob/master/Aufgaben/Aufgabe_9/Corona_ClassDiagramm.pdf

Jedoch habe ich heute leider ein Termin um 12 und kann an der Online Session nicht teilnehmen...ist es möglich, dass jemand (an alle gefragt) das irgendwie mitschreibt oder aufnimmt?

**Comment by KohlerAl** [comment]
Ich geh für dich und schreib mit :)

**Comment by JirkaDellOro** [comment]
@k-poschmann Wann wäre es denn gut für dich?

**Comment by k-poschmann** [comment]
So ab 15/16 Uhr hätte ich Zeit

**Comment by JirkaDellOro** [comment]
Das ist bei mir schlecht und später geht's dann schon so nah an die Abgabe. Wenn allerdings nur Alida und ich da sind, ergibt es weniger Sinn, aber wir probieren es mal wie angedacht um 12

**Comment by KohlerAl** [comment]
Ich glaube Sarah Franke kommt auch... und auf WhatsApp wurde auch bescheid gegeben, vielleicht kommen noch mehr

**Comment by k-poschmann** [comment]
Ich habe meine Fragen schon Alida zukommen lassen :)

**Comment by KohlerAl** [comment]
Also Kristin, Nadine und ich (und Sarah war auch eine Stunde da) haben uns um 15.00 Uhr (bis gerade eben) nochmal in Alfa-View getroffen, haben Kristins Code korrigiert und meinen Code durchgesprochen, als Anhaltspunkt. Ich hoffe, dass damit Unklarheiten beseitigt wurden :)

**Comment by k-poschmann** [comment]
@JirkaDellOro wir sind nochmals meinen Code durchgegangen und es scheinen auch die Corona Zellen dazu sein, doch sie sind irgendwie...unsichtbar (?) und alle an derselben Position. Wir haben leider nicht herausgefunden wo genau der Fehler liegt

**Comment by KohlerAl** [comment]
Was mir zu deinem Code gerade noch auffällt: Du malst erst den Kreis und verschiebst dann das Koordinatensystem... Keine Ahnung warum ich das nicht gleich gesehen habe :(

**Comment by k-poschmann** [comment]
OH :O jetzt sind sie da aber alle immer noch an einer Position...also die liegen hintereinander sozusagen

**Comment by KohlerAl** [comment]
Die Zeilen 121 und 122 in Main.ts müssen in die for Schleife. So legst du Zufallszahlen ja nur einmal fest. Ich komme mir grade richtig blöd vor, dass ich das vorhin nicht gesehen habe :( Sorry

**Comment by JirkaDellOro** [comment]
@k-poschmann  haben sich deine Verständnisschwierigkeiten erledigt oder ist noch etwas bezüglich des Prinzips der Objektorientierung unklar?

**Comment by k-poschmann** [comment]
@KohlerAl jetzt sind sie da :D vielen Dank!
@JirkaDellOro da Alida das Prinzip an ihrem code erklärt hat, ist es mir viel verständlicher geworden :)
