### ISSUE TITLE
VSC push funktioniert nicht

### ISSUE THREAD

**Issue by FrankeSa** [JirkaDellOro/EIA2-Inverted#168]
Hallo Markus,

ich weiß nicht, ob ich dich auf diese Weise etwas schneller erreiche als per Mail. Wobei ich dir auch eine Mail geschrieben habe ;-)
Ich habe es irgendwie geschafft, dass es mir beim pushen was zerschossen hat! Können wir uns heute vlt. kurz in Alfaview treffen, um das zu fixen? Vielleicht zwischen 18 und 19 Uhr? Ich hab es schon selbst versucht aber es vermutlich nur schlimmer gemacht :(
![image](https://user-images.githubusercontent.com/56167839/85203417-013e5e00-b30e-11ea-9d96-9ca0b1b7e224.png)

**Comment by MarkusDamm** [comment]
Hallo Sarah,
hab beide deine Nachrichten bekommen, weshalb auch ich nicht weiß, ob ich hier oder per Mail schneller wäre 😄 
Joa, sieht erstmal nur so aus, als würde dich Git von falschen Handlungsweisen abhalten wollen. 18 Uhr in DM16 würde passen.
Aber hast du schon versucht zu pullen statt zu pushen? **(Leg vorher lieber noch eine Kopie des Ordners an)**

**Comment by FrankeSa** [comment]
super, vielen dank! Dann bin ich um 18 Uhr in DM 16. 

Ja, ich habe schon versucht zu pullen aber er sagt ich bin aktuell nicht auf einem branch...

**Comment by JirkaDellOro** [comment]
Sarah hatte Dateien per Drag&Drop auf Github gezogen, aber dann wohl vorherige Synchronisation lokal weiter gearbeitet. So stehen die Repos auf unterschiedlichem Stand. Entweder mergen, oder lokal löschen, neu klonen und die aktuellen Daten aus der lokalen Kopie holen.

**Comment by FrankeSa** [comment]
Danke, Markus für deine Hilfe! Jetzt klappt es :-)
