### ISSUE TITLE
Console Fehlermeldung 

### ISSUE THREAD

**Issue by FrankeSa** [JirkaDellOro/EIA2-Inverted#169]
Hallo zusammen,

ich habe etwas an meinem Code rumgeschraubt und unter anderem die Datei-Struktur übersichtlicher gemacht. Nun kommt mir auf der Konsole folgende Meldung: 
![image](https://user-images.githubusercontent.com/56167839/85315766-f1647c80-b4bb-11ea-9928-f2f3d5b38a15.png)

Den Corona_Path, den er da wohl noch sucht, habe ich längst schon gelöscht. Den gibt es nicht mehr. 

Ich bin die Pfade/Verlinkung in meinem Index nochmal durchgegangen...aber da müsste alles passen. Was habe ich übersehen?

Link: https://github.com/FrankeSa/EA2-Inverted/tree/master/L09_Classes/L09_Corona

**Comment by JirkaDellOro** [comment]
Deine HTML-Datei trägt zwei mal eine komplette HTML-Struktur...

Außerdem
- vermeide Leerzeichen in denen Pfaden
- korrekt heißt es Repository
