### ISSUE TITLE
plötzlich Terminal Fehlermeldung/en bei vorherigen Aufgaben

### ISSUE THREAD

**Issue by FrankeSa** [JirkaDellOro/EIA2-Inverted#170]
Hallo Jirka,

ich hatte ja ende der letzten Woche den Issue "VSC push funktioniert nicht"  den ich dank der Hilfe von Markus wieder schließen konnte. Nun kann ich wieder problemlos pushen. Was mir allerdings aufgefallen ist, ist dass mir nun im Terminal Probleme angezeigt werden von früheren Aufgaben (Database und Server). Das die auftauchen wundert mich, da alles ohne Probleme funktioniert hat und mir bis vor dem Vorfall mit dem Issue "VSC push funktioniert nicht"  keine Probleme angezeigt wurden. Hier ein Screenshot was er bemängelt. 
![image](https://user-images.githubusercontent.com/56167839/85317173-3ee1e900-b4be-11ea-9ab4-152a144ec2bc.png)

Ich weiß nicht womit das zusammenhängt, weil wie gesagt diese Bemängelung eigentlich gar kein Thema war.

**Comment by MarkusDamm** [comment]
Könnte sein, dass durch unsere Fehlerbehebung einige Installationen für diese Module nicht mehr richtig erkannt werden. Ich denke da vor allem an Node.js. In L06 sollten die Node-Module mit `npm install @types/node` eingerichtet werden. Das steht ja auch in der vierten Fehlermeldung, klingt also vielversprechend.
