### ISSUE TITLE
Type Error: ..is a constructor 

### ISSUE THREAD

**Issue by luziagu** [JirkaDellOro/EIA2-Inverted#172]
Hallo zusammen, 
folgender Fehler kommt mir sehr bekannt vor. Ich hab versucht diesen zu lösen, komme aber nicht weiter. Jetzt wollte ich gerne fragen, ob mir jemand weiterhelfen kann. Mir wird bis jetzt nämlich auch nur der Hintergrund. 

<img width="521" alt="Bildschirmfoto 2020-06-23 um 14 38 27" src="https://user-images.githubusercontent.com/56430460/85404440-368dba80-b55f-11ea-90eb-30171ff627f2.png">

Danke schonmal im Voraus! 

App: https://luziagu.github.io/EIA2/Corona-Animation/corona.html
Konzept: https://luziagu.github.io/EIA2/Corona-Animation/Konzept/Konzept-Corona-Animation.pdf

**Comment by AionixX** [comment]
Schau mal in deiner `corona.html` Datei. Du hast einfach nur ein "t" vergessen in der Zeile 14. Da steht statt `script` nur `scrip`.

**Comment by luziagu** [comment]
Hat geklappt, aber jetzt wird das nur ganz kurz angezeigt und dann ist alles wieder weg

**Comment by JirkaDellOro** [comment]
Wenn Du dir den Bildaufbau im Debugger schrittweise vornehmen lässt erkennst Du, dass schon beim ersten Bildaufbau nur eine oder zwei HumanZellen erscheinen, es müssten 15 sein, und danach nichts mehr gezeichnet wird.

Schau mal deren draw-Methode an. Du speicherst zweimal die Transformation, holst sie aber nur einmal zurück. So addiert sie sich auf...

**Comment by luziagu** [comment]
Hallo Jirka, ich verstehe irgendwie nicht ganz was du meinst. Ich habe mir die Transformation jetzt zweimal zurück geben lassen, aber auch dort ändert sich nichts. Und die Zellen, also deren Funktion, sind ja die selben wie in der Lektion 08. Ich verstehe nicht ganz warum die Animation nur kurz erscheint.

**Comment by JirkaDellOro** [comment]
Du willst doch mit save und restore die Transformation speichern und wiederherstellen. Jetzt scheinst Du im Code etwas verändert zu haben an besagter Stelle, aber so ergibt es noch weniger Sinn. Nun transformierst Du zuerst, speicherst dann die schon veränderte Transformation und restaurierst sie gleich wieder. Der save soll wahrscheinlich eher vor dem translate kommen, oder?

**Comment by luziagu** [comment]
Jetzt bin ich verwirrt. Safe habe ich jetzt vor der Transformation, aber so war es vorher ja auch? 
Liegt das jetzt nur daran, dass mir die Animation nur kurz angezeigt wird? 
Mit dem Debugger habe ich Beispielsweise die Partikel durchlaufen und die werden eine nach dem anderen erzeugt, aber warum verschwindet dann alles wieder?

**Comment by JirkaDellOro** [comment]
Sehr gut, dass Du den Debugger einsetzen kannst. Die HumanZellen hast Du offensichtlich repariert, die Killerzellen kriegst Du jetzt bestimmt auch hin...

**Comment by luziagu** [comment]
Ja das klappt. Aber mein Problem ist ja das die verschiedenen Zellen nur kurz gezeigt werden und dann wieder verschwinden, was bleibt ist dann mein Hintergrund, also "Pattern".  Ich verstehe nicht ganz woran das liegt. Oder liegt das an meinem Browser?

**Comment by JirkaDellOro** [comment]
Nein an deinem Browser liegt es nicht. Aber jetzt machst Du in der Killerzelle zweimal save und zweimal restore. Bring' bitte das zunächst in Ordnung

**Comment by luziagu** [comment]
Aber ich habe ja bei den Humsnzellen auch zweimal Safe und Restore? Hab es jetzt für die Killerzellen geändert. 
Aber woran liegt denn das Problem, dass es mir das gesamte Bild nur kurz angezeigt wird?

**Comment by JirkaDellOro** [comment]
Das weiß ich auch noch nicht genau, aber so lange ich Fehler finde kann ich annehmen, dass es an denen liegt. Deswegen ist es gut, wenn Du selbst gleich alles prüfst, wenn ich auf eine Fehlerquelle aufmerksam mache, sonst gibt das ein langes Ping-Pong-Spiel...

**Comment by JirkaDellOro** [comment]
Apropos: es ist auch ganz doof, dass Du deinen Zellen in draw eine Position mitgeben musst. Du hast sie doch extra so gebaut, dass sie ihre Position kennen und in der Aufgabenstellung ist auch explizit gefordert, dass sie die nutzen sollen. Es widerspricht sonst dem Grundprinzip der Kapselung.... und birgt auch wieder Fehlerquellen.

**Comment by luziagu** [comment]
Dann werde ich mich jetzt mal den Funktionen Draw zu wenden und versuchen was ich da noch hinbekomme. Danke dir Jirka!

**Comment by JirkaDellOro** [comment]
Und ich klone gerade dein Repo um der Sache weiter auf den Grund zu gehen.

**Comment by JirkaDellOro** [comment]
Dabei stelle ich als erstes fest, dass wieder ein Leerzeichen im Pfad ist zu Main.js und das dieses Skript als erstes geladen wird. Besser wäre als letztes.

**Comment by luziagu** [comment]
Wurde geändert!

**Comment by luziagu** [comment]
Habe jetzt auch nochmal Restore und Store + die _Position geändert. Am Bild selbst ändert sich aber nichts.

**Comment by JirkaDellOro** [comment]
Das hast Du gut versteckt... schau dir die add-Methode der Vector-Klasse an.

**Comment by luziagu** [comment]
Meinst du += statt nur = ? Oder ist es ein problem, dass der Name der Methode add gleich ist wie der Parameter _add? oder ganz was anderes? Habe serumprobiert, aber vom Bild her hat sich nichts geändert.

**Comment by luziagu** [comment]
Ne stop: compiler vergessen

**Comment by luziagu** [comment]
Ohje, danke Jirka!!!!
