### ISSUE TITLE
"Infizierung" der menschlichen Zelle funktioniert nicht

### ISSUE THREAD

**Issue by vschwan** [JirkaDellOro/EIA2-Inverted#173]
hi, 
Ich kämpfe noch damit es hinzubekommen, dass die Viren die menschlichen Zellen "infizieren". 
Meine Zellen machen eigentlich zumindest ansatzweise das was ich von ihnen will. wenn eine Zelle mit Corona in Kontakt kommt wird sie aus ihrem Array geholt und stattdessen eine neue Instanz erzeugt, zwar vom gleichen Typen, aber mit einer zweiten "drawnew" Methode, die die  neue Zelle einfach mit einer anderen Farbe zeichnet. Macht das Sinn, oder liegt hier vielleicht schon mein Denkfehler? 

Man sieht zwar, dass die Farbe der Zelle sich "verändert" wenn sie mit Corona in Berührung kommt, aber dann wechselt sie  direkt wieder zur ursprünglichen. Ich weiß leider nicht wo mein Fehler liegt...
Wäre dankbar um Hilfestellung  :)

Code 09: https://github.com/vschwan/vschwan.github.io/tree/master/EIA2/09/Virus_09
Konzept: https://github.com/vschwan/vschwan.github.io/blob/master/EIA2/09/Virus_09/Konzept/virus%20diagrams.pdf

**Comment by JirkaDellOro** [comment]
Poste bitte noch einen Link zur lauffähigen App

**Comment by vschwan** [comment]
Habe den Fehler gefunden! habe nur an einer stelle übersehen die Methode richtig aufzurufen 🤦

**Comment by JirkaDellOro** [comment]
Oh... wie machst Du es jetzt?

Jedenfalls wollte ich dir gerade schreiben, dass dein Ansatz nicht unsinnig, aber unnötig kompliziert ist. Da Du keine Klasse für infizierte Zellen hast, sondern lediglich eine zweite draw-Methode implementierst, ist es nicht erforderlich die Zellen aus dem Array zu löschen und stattdessen andere zu erschaffen. Du brauchst auch kein anderes Array für infizierte Zellen. 

Gib deinen Zellen einfach noch die Eigenschaft "infected", beispielsweise als boolschen Wert. Wenn eine Kollision mit dem Virus stattfindet, infizierst Du tatsächlich die Zelle, indem Du die Eigenschaft als true definierst. Die Zelle entscheidet dann in einer neuen draw-Methode, ob sie ihre drawHealthy- oder ihre drawInfected-Methode aufruft!

**Comment by vschwan** [comment]
ah, sry fürs schnelle Schließen des Issues 

ich habe hatte in der animate-Funktion die draw Methode anstatt der drawnew Methode aufgerufen, aber in der changeCell-Funktion die drawnew -Methode, daher das "flackern" der Farbe. warum ich die drawnew methode zweimal aufrufen wollte versteh ich jetzt gerade auch nicht mehr so ganz :D 

jep, dass ich kein zweites Array brauche leuchtet mir ein. Mein Gedanke dahinter war, dass die Instanzen dann sozusagen "aufgeräumt", - also dass die infizierten und die gesunden Zellen einfach getrennt in ihren arrays sind. Aber vermutlich macht es das komplizierter als es sein muss, stimmt. 
Alles klar...
Ich werde das gleich mal so probieren, danke! :)

**Comment by JirkaDellOro** [comment]
Zur Lösung der aktuellen Aufgabe soll ohnehin alles in einem Array verwaltet werden, dann müsstest Du sowieso "rückbauen"

**Comment by vschwan** [comment]
okok, dann bau ich mal zurück
