### ISSUE TITLE
Fehlermeldungen 

### ISSUE THREAD

**Issue by schuchte** [JirkaDellOro/EIA2-Inverted#174]
Hallo Jirka,

ich habe das Problem, dass mir ständig diese Fehlermeldungen angezeigt werden und ich weiß langsam nicht weiter.

![Screenshot_13](https://user-images.githubusercontent.com/56271810/85877127-f6d10800-b7d6-11ea-8b21-8f14ff79fd9e.png)

Kannst du mir helfen?

LG Tanja

**Link zum Repo:** https://github.com/schuchte/EIA2/tree/master/L10_Corona_Inheritance
**Link zur App:** https://schuchte.github.io/EIA2/L10_Corona_Inheritance/L09_Corona.html

**Comment by JirkaDellOro** [comment]
Lade deine Klassen in der Reihenfolge, in der sie benötigt werden. Zuerst Vector, dann Moveable und erst ganz zum Schluss das Hauptprogramm. Kann gut sein, dass es damit zusammenhängt, das ist zum Teil browserabhängig.

**Comment by schuchte** [comment]
super danke, hat funktioniert!!
