### ISSUE TITLE
Abschlussarbeit 

### ISSUE THREAD

**Issue by buluthil** [JirkaDellOro/EIA2-Inverted#175]
Hallo Jirka ,

was ist mit diesem Satz "Bei Programmstart wird eine in der Größe und der Hintergrunddarstellung einstellbare und ansonsten leere Zeichenfläche dargestellt." gemeint?

Das der Nutzer bei Programmstart auswählen kann, wie Groß die Zeichenfläche sein soll also der "Canvas" ? 

<img width="929" alt="Bildschirmfoto 2020-07-09 um 20 33 56" src="https://user-images.githubusercontent.com/43846406/87077518-88069c80-c223-11ea-967c-a68d9036c419.png">

**Comment by JirkaDellOro** [comment]
ja, so hatte ich mir das gedacht, und dass er Hintergründe auswählen kann.

**Comment by buluthil** [comment]
Was ist mit Hintergründe gemeint ? meinst du das er im Hintergrund die Hintergrundfarbe der Zeichenfläche ändern kann oder wie ist das gemeint?

**Comment by MarkusDamm** [comment]
Genau, sowohl die Größeneinstellung als auch die Auswahl der Hintergrundfarbe beziehen sich auf den Canvas - deine Zeichenfläche.

**Comment by JirkaDellOro** [comment]
Es können auch Hintergrundmuster oder ganze Motive sein, da darfst Du, wie auch beim Rest, kreativ sein!

**Comment by buluthil** [comment]
Alles klar Vielen dank :)

Ich habe das Anwendungsfalldiagramm schonmal versucht einigermaßen zu machen und habe mich hier an diese Struktur in L07 gehalten. Ist das soweit richtig, mittel, falsch?  was könnte ich noch hinzufügen ? oder passt das so ?

(Ps: ich sollte einbisschen besser zeichnen ja ich weiß aber ist erstmals nur eine Skizze :D)

<img width="1440" alt="Bildschirmfoto 2020-07-09 um 22 08 24" src="https://user-images.githubusercontent.com/43846406/87085787-bfc81100-c230-11ea-8204-ec3338f487c6.png">


![Scan](https://user-images.githubusercontent.com/43846406/87085606-737cd100-c230-11ea-8a66-2da51675dba0.jpeg)

**Comment by buluthil** [comment]
Alles klar vielen Dank :)

Ich habe das Anwendungsfalldiagramm schonmal gemacht und habe mich da an die L07 Struktur gehalten. 
Ist das schonmal so richtig, mittel, falsch ? was fehlt noch ? oder passt das so ? 

(Ps: und ich weiß ich sollte einbisschen besser zeichnen, damit es übersichtlicher wird aber ist erstmals nur die grobe Skizze :D)

<img width="1440" alt="Bildschirmfoto 2020-07-09 um 22 16 51" src="https://user-images.githubusercontent.com/43846406/87086453-e89cd600-c231-11ea-873b-4553c64d6f9b.png">

 
![Scan](https://user-images.githubusercontent.com/43846406/87086591-1aae3800-c232-11ea-8edb-64f890fc9ef9.jpeg)

**Comment by JirkaDellOro** [comment]
Für den Anfang gar nicht schlecht.  Dass man bei Programmstart gleich etwas vom Server bekommt leuchtet mir nicht ein, und das Bild laden auf Bild weiterverarbeiten verweist auch nicht. Kann man auf dem Server Bilder weiterverarbeiten? Grundsätzlich erscheinen die Begriffe "bekommen" und "erhalten" austauschbar, da musst Du etwas besseres finden.

Ich möchte Anna und Markus auch noch etwas übrig lassen....

**Comment by buluthil** [comment]
Ja bei Programmstart, macht es tatsächlich keinen sinn, dass man da was vom server bekommt, weil das Programm wird ja da nur gestartet stimmt. Aber bei dem Bild laden habe ich mir gedacht, dass der Nutzer bei Wiederöffnung des Programms das  gespeichert Bild ladet um dies weiter zu bearbeiten und deshalb diese Zeichnung mit Bild laden zum server und Datenbank :D
Aber er bearbeitet das ja nicht auf dem server sondern auf der Client Seite, deshalb die Aktivät Bilder weiterverabeiten falsch stimmts? was wäre da eine richtige Aktivität vielleicht statt Bild weiterverabeiten "aktuelles Bild" weil es ja aktualisiert wurde ?

**Comment by buluthil** [comment]
Ich habe jetzt das Anwendungsfalldiagramm  einbisschen geändert, ich hoffe das ist nicht falsch was ich da hingeschrieben habe, der Server und die Datenbank Arbeiten ja mit den Daten und nicht mit dem Bild an sich, deshalb steht da jetzt Daten anstatt Bild. 
Das mit den Daten finden und aktualisieren ist so gemeint, dass wen der Nutzer das Speichert und dann wieder das Bild ladet wird das ja überschrieben was er anfangs gespeichert hat oder was Anfangs da war. Also ich weiß nicht ob das jetzt falsch ist sowie ich mir das vorstelle. 
![Scan 1](https://user-images.githubusercontent.com/43846406/87160833-e2efd080-c2c3-11ea-8379-a8266fc8d86f.jpeg)


und noch eine andere Frage bezüglich der Aufgabe, wie ist das gemeint mit den animierten Bildern ? sind die Symbole schon animiert, bevor der Nutzer sie auf der Zeichenfläche platziert ? oder bewegen sie sich erst auf der Zeichenfläche nachdem man z.b auf das Symbol geklickt hat etc.

**Comment by MarkusDamm** [comment]
Soweit ich das sehe sind in deiner Skizze alle wichtigen Anwendungsfälle vorhanden. Da der User entscheiden kann, welches Bild geladen wird fehlt dafür noch ein Pfeil. Bis auf den dreibeinigen User wäre es dann meiner Meinung nach in Ordnung.

Bei den Animationen steht dir offen, ob Symbole schon vor oder erst nach dem Platzieren animiert sind. Ich fände es aber gut, wenn ich vor dem Platzieren schon erahnen kann, wie sich die Symbole dann bewegen.

**Comment by buluthil** [comment]
Alles klar :)
Vielen Dank für die Infos :D
