### ISSUE TITLE
GenerateContent?

### ISSUE THREAD

**Issue by k-poschmann** [JirkaDellOro/EIA2-Inverted#176]
Hallo,

ich habe eine Frage bezüglich meines Konzeptes:
https://github.com/k-poschmann/poschmannEia2/tree/master/Aufgaben/Abschlussaufgabe_Zauberbild

Ich habe mich bereits an einem Use Case Diagram (Ist dies so in Ordnung oder ist es unschlüssig?) und einem User Interface Scribble gesetzt. Nun zu meiner Frage:
Da ich die Größen der Canvas über Radiobuttons einstellen lassen möchte, ist mir die Frage gekommen, ob ich diese dann per TypeScript erstellen lassen soll oder ob es reicht, wenn sie einfach im HTML Dokument stehen?

Liebe Grüße,
Kristin

**Comment by JirkaDellOro** [comment]
Es reicht im HTML-Dokument, es sei denn, sie sollen selbst wieder konfigurierbar sein.

**Comment by MarkusDamm** [comment]
Dein UseCase-Diagram sieht erstmal gut aus. macht aber den Anschein, als wären fertige Bilder schon beim Starten der Anwendung im Hintergrund vorhanden, also Clientseitig. Die Bilder sollen aber von der Datenbank geladen werden. Außerdem scheinen die beiden Aktivitäten in der Datenbank vertauscht zu sein: wenn ein Bild gespeichert werden soll müssen Daten in die Datenbank eingefügt und nicht nur gefunden werden.

**Comment by k-poschmann** [comment]
Ok ich werde mir das nochmal anschauen. Vielen Dank für das Feedback :)
