### ISSUE TITLE
Zauberbild Animationsvorlagen

### ISSUE THREAD

**Issue by LukasBlea** [JirkaDellOro/EIA2-Inverted#177]
Hellooooo ich hätte mal eine Frageeeee.

Bei der Konzeption meines AD und meiner UI habe ich mich gefragt, wie genau das mit den Animationsvorlagen gemeint ist.

Kann ich z.B. dem User, Formen wie "Dreieck", "Viereck", "Kreis" usw zur Verfügung stellen und ihn selbst auswählen lassen, wie sich das Animieren lassen soll?

Da hatte ich mir vorgestellt Buttons einzubauen, mit denen man eine Rotation nach Links oder Rechts auswählen könnte. Wie schnell soll sich die Form bewegen (also das Speed der Rotation) und den Benutzer mit einem/mehreren Schieberegler versorgen, wo er das alles selbst auswählen kann. 

Hierbei wäre dem Nutzer dann natürlich keine direkte Animation gegeben, aber er kann es sich selbst auswählen wie es sich animieren soll (falls das Sinn ergibt). 

Danke schonmal im Vorhinein für die Antwort/en

Beste Grüße
Lukas Blea

**Comment by MarkusDamm** [comment]
So ähnlich hätte ich es auch gemacht. Ist auf jeden Fall so möglich 👍
