### ISSUE TITLE
UpdateKonzept/ UC/UI/Schwimmbahn

### ISSUE THREAD

**Issue by FrankeSa** [JirkaDellOro/EIA2-Inverted#178]
Hallo,

ich habe die o.g. Dokumente nach gestern nochmal angepasst. Passt das UC und die Schwimmbahn nun so?
https://github.com/FrankeSa/EIA2_Abschlussarbeit/tree/master/Abschulss_Konzept 

Und noch eine Frage: Wie finde ich auf gitHub nochmal den http-Pfad oder generell den Pfad, damit ich meine Dokumente z.B. auf der Kursseite hochladen kann?

**Comment by AnnaLotz** [comment]
Zur Schwimmbahn: "request" darf gerne noch etwas genauer definiert werden. Was wird angefragt und was wird zurück gesendet?

Gehe in deinem Repository oben auf Settings und scrolle runter bis "GitHub Pages". Da steht dann im grünen Kasten "Your site is published at...". Der Dateipfad zum gewünschten Dokument muss dann natürlich noch dran gehängt werden.

**Comment by FrankeSa** [comment]
Danke, Anna für deine Rückmeldung :)
Ich habe die Vorgänge nun etwas genauer benannt.  https://frankesa.github.io/EIA2_Abschlussarbeit/Abschulss_Konzept/Schwimmbahn_Zauberbild_Franke_Sarah.pdf 
Meine Idee dahinter ist, dass nach dem Starten, der Client schauen soll, ob Bildnamen und die Daten dahinter (gezeichnetes Bild) vorhanden sind. Diese Anfrage landet beim Server und der schaut in der Datenbank nach.  Wenn in der Datenbank etwas vorhanden ist, dann gibt es eine Rückmeldung mit dem Bildname und den Daten. Der Bildname wird dann dem Nutzer in einem Dropdown zur Verfügung gestellt. Klickt man auf den Bildname wird der Datensatz dahinter aufgerufen.  Wenn du/ihr mir hierzu ein kurzes Feedback geben könntet, ob die Idee und die Schwimmbahn nun so passen? :)

**Comment by AnnaLotz** [comment]
Sendet man als Nutzer eine allgemeine Anfrage, welche Bilder in der Datenbank zu finden sind oder sucht man mit Namen spezifisch nach bestimmten DB-Einträgen? Das ist mir aus deiner Beschreibung noch nicht ganz klar geworden. Letzeres hätte den Nachteil, dass man schlecht bis gar nicht in den vorhandenen Bildern stöbern kann, da man die Bezeichnung kennen muss, unter der das Bild gespeichert wurde.

**Comment by FrankeSa** [comment]
Also beim Start soll der Server bei der Datenbank anfragen, ob Datensätze vorhanden sind. Ich habe das Schaubild nun nochmal angepasst.  https://frankesa.github.io/EIA2_Abschlussarbeit/Abschulss_Konzept/Schwimmbanhn_Zauberbild_2.0.pdf
Nachdem ich mich nochmal in L07 eingelesen habe, denke ich es wäre geschickt, wenn der Nutzer, indem er "speichern" klickt, eine collection mit seinem gewählten Namen anlegt. Die Datenbank kann dann bei Start die vorhandenen Collections ausgeben und der Client zeigt diese dann dem Nutzer an.   Geht das so? Bzw. ist das verständlich wie ich es meine?

**Comment by FrankeSa** [comment]
PS. In meiner Überlegung sollen dann die Collections durch ein Dropdown-Feld ausgewählt werden.

**Comment by FrankeSa** [comment]
Es wird eine allgemeine Anfrage gesendet.

**Comment by JirkaDellOro** [comment]
Es könnte hilfreich sein, wenn Du ein Skizze von deinem geplanten Datenbankinhalt machst und uns zeigst. Ich verstehe es jetzt so, dass jedes Bild eine eigene Collection erhält. Das wäre machbar, aber für mich nicht intuitiv. Wie sehen die Dokumente in der Collection aus? Oder liegt in jeder Collection nur ein einziges Dokument?
@AnnaLotz wie hast du das verstanden?

**Comment by FrankeSa** [comment]
Als erste Idee dachte ich, dass jede Collection ein Doc hat, welches das abgespeicherte Bild des Nutzers hat. Anbei die Skizze, wie ich es mir gedacht hatte:  https://frankesa.github.io/EIA2_Abschlussarbeit/Abschulss_Konzept/Ablauf_Daten_speichern_in_DB.pdf

Wenn der Nutzer sein Bild benennt, dann ist das quasi die Collection und darin das Canvas Bild.

**Comment by MarkusDamm** [comment]
Der Ansatz ist schon mal gut. So würdest du aber für einen Eintrag eine ganze Collection anlegen. Wie Jirka schon gesagt hat scheint das nicht intuitiv.
Aus deinem Konzept geht für mich nicht ganz hervor, was du genau abspeichern willst. Den Namen ja auf jeden Fall. Dann noch ein Doc, das den Canvas beschreibt. Mit welchen Sachen kann denn der Canvasinhalt beschrieben werden?  
Wenn du das weißt, dann kann beides für einen Eintrag in einer Collection für alle Bilder gespeichert werden. Die einzelnen Einträge können immerhin auch verschiedene Eigenschaften haben.

**Comment by JirkaDellOro** [comment]
... und der Name des Bildes könnte einfach ein Wert im Doc sein.

**Comment by FrankeSa** [comment]
Ich weiß nicht genau was du mit "Sachen" meinst. Ich habe noch keine genaue Ahnung was genau ich abspeichern muss, damit alle Eigenschaften des Canvas (Größe, Farbe, Symbole) gespeichert werden. Ich dachte, dass man das vlt. alles in einer Variablen zusammen führen könnte. Oder vlt. auch nur jede Eigenschaft für sich in eine Variable. Das erstmal als grobe Überlegung aber wie genau das im Detail aussehen könnte... kann ich mir nicht genau vorstellen. Da hänge ich...  Am intuitivsten wäre ja, wenn der Nutzer auf den Namen des Bildes klickt, und dadurch alle zusätzlichen Infos abgerufen und angezeigt werden.

**Comment by JirkaDellOro** [comment]
Vielleicht führt dich folgende Frage weiter: welche Informationen brauchst Du, um ein Bild rekonstruieren zu können?

**Comment by FrankeSa** [comment]
Also in der Datenbank muss ich erstmal wissen wie das Bild heißt. (Name)
-Dann wo es abgespeichert ist (in welcher collection?) und dann zum rekonstruieren..

-Die Canvas Größe
-Die Hintergrundfarbe 
- Die platzierten Symbole und ihre Animationsmuster auf dem Canvas

zum Schluss vllt. noch, wo es wieder hingezeichnet werden soll.

oder denke ich da zu bildlich?

**Comment by AnnaLotz** [comment]
> -Die Canvas Größe
-Die Hintergrundfarbe
-Die platzierten Symbole und ihre Animationsmuster auf dem Canvas
zum Schluss vllt. noch, wo es wieder hingezeichnet werden soll

Genau das sind die wichtigen Dinge, über die du dir Gedanken machen solltest. Wie kann ein Bild gezeichnet werden, damit man diese Werte noch nachvollziehen kann? Irgendwie muss ja gespeichert sein, was wo sitzt... Überlege, wie die gezeichneten Elemente gezeichnet und gespeichert werden können.
Wenn du das ausgetüftelt hast, weißt du auch, welche Informationen die Datenbank braucht.

**Comment by FrankeSa** [comment]
Hey :) Danke für das Feedback.  Ich habe nun etwas getüftel... :) Ich habe mir mal das HTML5 Canvas Cheat Sheet angeschaut und dann bin ich auf folgende Überlegung gekommen. Man braucht das CanvasElement mit dem Attributen width und heigth und den 2D Context mit den Methoden Save und Restore. Das alles zusammen speichern wir ja immer in der Variable zb. crc2 ab.  let **crc2**: CanvasRenderingContext2D = canvas.getContext("2d");    

diese Variable und der name des Bildes müssten ja dann für die Datenbank reichen, oder? Ich hoffe ich drehe mich jetzt nicht um den heißen Brei XD

**Comment by JirkaDellOro** [comment]
Oh... Achtung. Save and Restore speichern nur die aktuellen Mal-Einstellungen, nichts vom Bild. Ein CanvasRenderingContext2D-Objekt stellt dir Methoden zum Malen zur Verfügung, dieses Objekt zu speichern ergibt keinen Sinn. Das wäre, wie wenn Du deinen Malkasten einpackst und das gerade gemalte Bild in den Müll wirfst in der Hoffnung, dass das Bild wieder erscheint, wenn Du den Malkasten später aus der Tasche holst.

**Comment by FrankeSa** [comment]
ok, dann hab ich da echt was falsch verstanden. danke.

**Comment by JirkaDellOro** [comment]
Eigentlich warst Du mit https://github.com/JirkaDellOro/EIA2-Inverted/issues/178#issuecomment-662574618 auf einem guten Weg. Es gibt keine Abkürzung...
