### ISSUE TITLE
Uncaught Type Error format1 is null 

### ISSUE THREAD

**Issue by beliema** [JirkaDellOro/EIA2-Inverted#179]
Hey, 
nach dem HTML Teil, in dem ich meine Canvas-Elemente folgendermaßen angelegt habe; 
<img width="562" alt="Bildschirmfoto 2020-07-17 um 12 16 01" src="https://user-images.githubusercontent.com/48830827/87776386-fbae3800-c827-11ea-9501-77b04fb26b06.png">
und Einbindung in die TS Funktion GenerateContent 
<img width="809" alt="Bildschirmfoto 2020-07-17 um 12 18 20" src="https://user-images.githubusercontent.com/48830827/87776490-226c6e80-c828-11ea-9781-cf2c0e2e6461.png">
<img width="809" alt="Bildschirmfoto 2020-07-17 um 12 18 07" src="https://user-images.githubusercontent.com/48830827/87776493-24363200-c828-11ea-9c2b-d4b1852ca751.png">

habe ich versucht durch die Funktion GenerateCanvasSize() je nachdem welcher Button angeklickt wird 
<img width="314" alt="Bildschirmfoto 2020-07-17 um 12 23 09" src="https://user-images.githubusercontent.com/48830827/87776572-4a5bd200-c828-11ea-869e-9178447be3ba.png">

die entsprechende Größe generieren zu lassen: 

<img width="655" alt="Bildschirmfoto 2020-07-17 um 12 16 23" src="https://user-images.githubusercontent.com/48830827/87776612-56479400-c828-11ea-8fe5-c401e7f610e5.png">

Jedoch klappt das nicht und mir wird in der Konsole folgender Fehler angezeigt: 

<img width="1382" alt="Bildschirmfoto 2020-07-17 um 12 17 23" src="https://user-images.githubusercontent.com/48830827/87776660-66f80a00-c828-11ea-8a62-871bc2c20f8b.png">

Habe auch schon versucht das Canvas im HTML als Fieldelement und Canvas Element stehen zu lassen, allerdings hat das auch nicht funktioniert. 
Was kann ich tun dass es klappt? Beziehungsweise wo liegt mein Fehler? Habe format1 ja eigentlich in handleLoad definiert... 

LG Alina

**Comment by JirkaDellOro** [comment]
Unbedingt Links zur App und zum Code posten!

**Comment by beliema** [comment]
hab den code noch nicht auf Github hochgeladen, wollte erst noch ein neues Repository erstellen. Ich mach es kurz

**Comment by beliema** [comment]
Habe es jetzt auf der EIA2 Kursseite im Steckbrief verlinkt 
(https://beliema.github.io/Semester2/EIA2Abschluss/zauberbild.html) 

Ebenso auch das Konzept, passt das auch so?

**Comment by KohlerAl** [comment]
Auch wenn ich die Fehlermeldungen die in deinem Screenshot sind nicht sehe, habe ich einen Verdacht woran es liegen könnte. Und zwar verwendest du in den Zeilen 30 bis 32 getElementbyId mit einem # vor der ID. Das ist eigentlich unnötig, weil du mit getElementById schon sagst, dass es sich um eine ID handelt, anders als bei querySelector, wo man ja zwischen Tag, Klasse und ID unterscheiden muss.

**Comment by beliema** [comment]
okay, habe den # vor der ID weggenommen; 
let format1: HTMLInputElement = <HTMLInputElement>document.getElementById("canvas1");

die Fehlermeldung ist nun weg, allerdings generiert sich keine Canvas-Fläche nach Klicken des Buttons 

zweiter Versuch war dann mit  let format1: HTMLInputElement = <HTMLInputElement>document.querySelector("#canvas1"); 
hier kommt bei mir nun auch keine Fehlermeldung mehr, allerdings generiert sich auch keine Fläche

Ist es eventuell irgendwie falsch verlinkt?

**Comment by KohlerAl** [comment]
Die Variablen format1, format2 und format3 sind ja deine Canvas. Du überprüfst in deiner Funktion generateCanvasSize, ob die jeweilige Canvas "checked" ist. Ich kenne leider dein Konzept nicht, aber ich vermute, du willst hier eher schauen, welcher Radiobutton angeklickt wurde.

**Comment by KohlerAl** [comment]
Update: Hab grade gesehen, dass du das Konzept auch hochgeladen hast und da suchst du nach Checkboxen :) Also denke ich du bist da ein bisschen mit den IDs von den  Inputs (Format1, Format2 und Format3) und den Variablennamen (format1, format2 und format3) durcheinander gekommen

**Comment by beliema** [comment]
Okay, ich Versuchs mal, danke :)

**Comment by beliema** [comment]
Habe meine Variablen und die Inputs neu definiert, nun wird mir auch folgendes in der Konsole angezeigt: 
<img width="1387" alt="Bildschirmfoto 2020-07-17 um 17 00 17" src="https://user-images.githubusercontent.com/48830827/87800847-35df0000-c84f-11ea-87fa-d92f19f0606c.png">
Noch immer wird kein Canvas generiert. habe dann die Variablen Canvas1/2/3 als HTMLCanvasElement bezeichnet, doch jetzt wird mir als Fehlermeldung gesagt, dass der Befehl "disabled" gar nicht im HTMLCanvasElement existiert. 
<img width="1387" alt="Bildschirmfoto 2020-07-17 um 17 04 02" src="https://user-images.githubusercontent.com/48830827/87801110-86eef400-c84f-11ea-9f4f-9b86c0d03c73.png">

**Comment by KohlerAl** [comment]
Dann ist disabled nicht der richtig Weg. Du könntest stattdessen mit display:none arbeiten. Dann existiert das Element zwar, wird aber nicht angezeigt und nimmt auch nicht den Platz ein, den es benötigen würde. Visibility:hidden geht auch, dann nimmt das Element weiter den Platz ein, den es braucht, wird aber nicht angezeigt

**Comment by beliema** [comment]
hat geklappt! Vielen Dank :)

**Comment by JirkaDellOro** [comment]
Nicht vergessen den Issue zu schließen, wenn er durch ist.

**Comment by beliema** [comment]
Hab ihn noch nicht geschlossen, weil ich gerne noch Feedback zu meinem Konzept hätte 😁

**Comment by JirkaDellOro** [comment]
Dann mach daraus bitte einen eigenen Issue., das ist völlig okay Es ist problematisch, wenn man mehrere Themen in einem behandelt. Und verlinke dein Konzept direkt damit.

Kurz darüber geschaut kann ich dir schon zurückmelden, dass dein Konzept klasse aussieht. Welche Software nutzt Du dafür? Die Navigation die Teile der Konzeption ist interessant. Für detaillierte Kritik möchte ich zunächst verweisen an @MarkusDamm / @AnnaLotz

**Comment by beliema** [comment]
Draw.IO dafür benutzt. Okay super, dann wende ich mich an Anna & Markus :)

**Comment by JirkaDellOro** [comment]
Ich gehe davon aus, dass sie deine Issues finden werden.
