### ISSUE TITLE
Canvas auswählen

### ISSUE THREAD

**Issue by luziagu** [JirkaDellOro/EIA2-Inverted#180]
Hallo zusammen, 
ich versuche gerade zu implementieren, dass es möglich ist mithilfe von Radiobuttons den Canvas auszuwählen. Bei mir erscheint jetzt folgende Meldung: 
<img width="837" alt="Bildschirmfoto 2020-07-19 um 09 58 36" src="https://user-images.githubusercontent.com/56430460/87870475-b82f0780-c9a8-11ea-9ed8-5acfa20f9ab6.png">
Ist der Ansatz überhaupt so Sinn? 

Gruß, Luzia 
https://luziagu.github.io/Abschlussarbeit_SOSE2020/zauberbild.html

**Comment by MarkusDamm** [comment]
Hallo Luzia, der Ansatz ist sinnvoll. 
![Screenshot (44)](https://user-images.githubusercontent.com/44026453/87870737-2aa0e700-c9ab-11ea-9609-2819bbf79824.png)
Bevor du aber versuchst deinen Variablen InputElemente zuzuweisen sollten die jeweiligen Elemente zuerst geladen werden. Dafür hast du ja bereits eine handleLoad-Funktion angelegt.

**Comment by luziagu** [comment]
Ich hab die Funktion + Variablen jetzt in die HandleLoad Funktion gepackt. Gibt es noch eine andere Möglichkeit?

**Comment by KohlerAl** [comment]
Du kannst die Variablen schon global definieren, nur die Wertzuweisung kannst du erst machen, wenn die Elemente geladen wurden, zum Beispiel in HandleLoad :)
Also zum Beispiel so: 
![Screenshot (266)](https://user-images.githubusercontent.com/56314717/87872171-9ccaf900-c9b6-11ea-8e2f-e80bfcc6c7ab.png)

**Comment by luziagu** [comment]
Woher sehe ich jetzt ob auch wirklich ein Canvas gezeichnet wird?

**Comment by luziagu** [comment]
Ja klar, danke!

**Comment by luziagu** [comment]
Wie erkenne ich denn jetzt am besten ob der Canvas auch wirklich die Größe annimmt bevor ich ihn zeichne und der Hintergrund auf der Fläche die Farbe annimmt.

**Comment by JirkaDellOro** [comment]
- nutze deine DevTools im Browser (F12), dort im Menu das Icon mit dem Mauscursor und bewege die Maus dahin, wo Du den Canvas vermutest
- oder fülle den Canvas über seine ganze Fläche mit einer Farbe
- oder gibt dem Div, indem der Canvas liegt eine Hintergrundfarbe, dann hebt sich der Canvas weiß dagegen ab.

Wenn Du immer fleißig committest und pushst können auch wir den aktuellen Stand einsehen und dir besser helfen

**Comment by luziagu** [comment]
Gepusht habe ich, also die neueste Version müsste oben sein :) Mir ist gerade aufgefallen, dass nach der Bedingung der Befehl gar nicht ausgeführt wird. Warum? hat das damit was zu tun, dass ich kein Break habe?

**Comment by luziagu** [comment]
Ich weiß auch irgendwie nicht ganz wie ich das mit if else umsetzten könnte.

**Comment by JirkaDellOro** [comment]
Welcher Befehl soll nach Beendigung ausgeführt werden? Nach Beendigung können es ja nur noch Handler-Funktionen sein, die von Listeners aufgerufen werden. Hast Du das entsprechend eingerichtet?

**Comment by luziagu** [comment]
Hab es jetzt hinbekommen. Hat auch alles funktioniert aber jetzt wird die Funktion chooseCanvas nicht mehr ausgeführt. Ich hab auch schon mithilfe des Debuggers versucht den Fehler zu finden. Finde ihn aber nicht und kann mir auch nicht erklären. Die Dateien sind verknüpft. 

Danke schonmal für die Hilfe!

**Comment by luziagu** [comment]
<img width="281" alt="Bildschirmfoto 2020-07-19 um 21 38 12" src="https://user-images.githubusercontent.com/56430460/87883518-32db3f80-ca08-11ea-82b1-0cda98af2d80.png">

Ich meine das ausersehen gedrückt zu haben, wenn das einen unterschied macht.

**Comment by JirkaDellOro** [comment]
Zeile 32f:
```typescript
        if (!canvas)
            return; 
```
Da er keinen Canvas findet, wird hier deinem Wunsch gemäß die Funktion beendet und die Listener werden nicht installiert.

Noch ein Hinweis: es wäre deutlich eleganter und sicherer, wenn Du nicht die Klicks auf den Radiobuttons abfängst, sondern den `change` in der Radiobuttongroup, so wie wir es in der Lektion geübt haben. Dafür hat man ja die Radiobuttons....

**Comment by luziagu** [comment]
Danke! Den Canvas hab ich rausgenommen, warum auch immer :D Und das mit dem Change werde ich umsetzte. Danke! :)
