### ISSUE TITLE
Mehrere Camvase 

### ISSUE THREAD

**Issue by luziagu** [JirkaDellOro/EIA2-Inverted#181]
Hei, 

ich bin jetzt gerade damit beschäftigt vier Cannes aufzusetzen, damit da jeweils die Symbole angelegt werden können. 
Dies klappt aber nicht ganz so wie ich mir das gedacht habe, weil ich jetzt nicht mehr das Format ändert. Die Symbole lassen sich auch nicht in den Canvas Zeichen. Ich habe jedem Canvas einen Div zugewiesen. 

Mein letzter Stand ist diese Fehlermeldung. 
Ist das eine richtige Umsetzung der verschieden Canvas oder gibt es noch einen anderen weg dies zu lösen, auch ohne, dass die einzelnen Canvase sich gegenseitig beeinträchtigen. 

<img width="827" alt="Bildschirmfoto 2020-07-20 um 17 06 02" src="https://user-images.githubusercontent.com/56430460/87953414-4d1a2980-caab-11ea-97be-6e879725549d.png">

https://luziagu.github.io/Abschlussarbeit_SOSE2020/zauberbild.html

Ich habe noch eine kurze andere Frage: Wie ist es am Sinnvollsten den Hintergrund auszuwählen und dem Canvas zuzuweisen. die jeweilige klasse ändern oder kann ich direkt auf das "fill" zugreifen und dort Sen string ändern? 

Vielen Dank schonmal für die Hilfe!

**Comment by luziagu** [comment]
Einen Fehler hab ich jetzt gefunden. Der Canvas auf dem später gezeichnet werden soll, der hatte noch keine ID. Das Problem von oben wurde dadurch immer noch nicht behoben.

**Comment by luziagu** [comment]
Hab es gelöst :)

**Comment by JirkaDellOro** [comment]
let mainCanvas: HTMLCanvasElement = <HTMLCanvasElement> document.getElementById("#mainCanvasDraw");

Das war wohl wieder das #

**Comment by JirkaDellOro** [comment]
Ich empfehle auch dringend 
`querySelector("canvas#mainCanvasDraw");`

Die Methode sucht dann nicht nur nach irgendeinem Element mit der id mainCanvasDraw, sondern nach einem HTMLCanvasElement mit dieser id. Und TypeScript erkennt das auch, weshalb Du dir die Type-Assertion `<HTMLCanvasElement>` sparen kannst.
