### ISSUE TITLE
Variable mit propmt is possibly null

### ISSUE THREAD

**Issue by LukasBlea** [JirkaDellOro/EIA2-Inverted#182]
Helloooooo eine kurze Frage!

![prompt](https://user-images.githubusercontent.com/44029295/88036251-961dbc80-cb43-11ea-978a-34b6499f6224.PNG)

Hat jemand einen Lösungsansatz um zu umgehen, dass meine variable "user" possibly null ist? 
Auf w3schools steht das hier:

![w3schools](https://user-images.githubusercontent.com/44029295/88036390-c6fdf180-cb43-11ea-880a-ec12d7fb6882.PNG)

Es leuchtet also schon ein, aber ich finde keinen effektiveren Weg um den User nach einem Nutzernamen zu fragen und finde es ganz schön, dass man dadurch "gezwungen" wird, direkt seinen Namen einzustellen.

Ich sehe keine funktionsweise der Methode "prompt", die es verhindert, dass der Nutzer auch einfach nichts eingeben kann und somit ist die Fehlermeldung logischerweise gerechtfertigt. 

Danke für die Hilfe schonmal im vorraus! Bin gespannt auf Lösungsansätze.

Beste Grüße
Lukas Blea

**Comment by JirkaDellOro** [comment]
Es ist gut, dass dich TypeScript gleich darauf hinweist, dass hier Gefahr im Verzug ist. Und dass Du es zu schätzen weißt. 

Was soll den passieren, wenn der User abbricht oder einen leeren String eingibt?

**Comment by LukasBlea** [comment]
Am besten soll direkt noch eine Abfrage gestartet werden, wodurch dem Nutzer verhindert wird, dass er KEINEN Nutzernamen angeben kann.  

Also in meinem fall 
while (user == null) 

Allerdings sagt mir VSC, dass das Problem dann immer noch besteht.
Vielleicht die Seite einfach nochmal neu Laden lassen? Ich bin mir nicht sicher.

**Comment by LukasBlea** [comment]
Ahhhhh oder man kann einfach einen Default angeben, dass die Variable "user" einfach eine string wie z.B. "User" ausspuckt. Somit ist gewährleistet, dass die string nie = null sein kann! 

Das mir das nicht früher eingefallen ist :D

**Comment by JirkaDellOro** [comment]
Ich denke, deine erste Idee ist zielführender, Du willst ja, dass er etwas eingibt. Was passiert, wenn Du die Weiterverarbeitung erst nach deiner do-while-schleife vornimmst? TypeScript könnte dann feststellen, dass der String nicht null sein kann.

**Comment by JirkaDellOro** [comment]
Kommentarlos geschlossen? Welche Lösung hast Du denn gefunden?
