### ISSUE TITLE
Symbol auf zweiten Canvas zeichnen

### ISSUE THREAD

**Issue by luziagu** [JirkaDellOro/EIA2-Inverted#183]
Hallo, 

Meine Idee ist es ein Symbol das geklickt wurde in den MainCanvas zeichnen zu lassen. Bis jetzt lässt es sich nur in den den zuvor gezeichneten Canvas zeichnen. Meine Idee war es mithilfe eines Boolean zu fragen ob das Target abgerufen wurde, um dann den CanvasRenderingContext in den MainCanvas zu ändern. Ich hab das versucht umzusetzen, aber alles ist ziemlich verschachtelt. Jetzt wollte ich fragen ob es noch eine weiter Möglichkeit gibt. Vielleicht mit einem Array? Aber eigentlich wäre das einfachste ja in der Draw Methode einfach den Context zu ändern mithilfe einer Bedingung? 

Ein anderes Problem ist, dass die App bei Github nicht läuft. Der vorlegende Link führt zur App aber das was bei mir lokal funktioniert funktioniert über Pages nicht. 
https://luziagu.github.io/Abschlussarbeit_SOSE2020/zauberbild.html
https://github.com/luziagu/Abschlussarbeit_SOSE2020/blob/master/zauberbild.html

Gruß, Luzia

**Comment by luziagu** [comment]
Das andere Problem hat sich erledigt.

**Comment by schneine** [comment]
Vllt über eine Parameterübergabe in der Methode draw(), sodass man entscheiden kann auf welchem Canvas die Methode ausgeführt wird?

**Comment by KohlerAl** [comment]
Ja, sowas in die Richtung würde ich sagen... dass man halt eine Variable übergibt und je nach dem welchen Wert die Variable hat, wird dem RenderingConext ein anderer Wert zugewiesen

**Comment by JirkaDellOro** [comment]
Ich würde gleich den Context als Parameter mitgeben und einfach darauf malen.

**Comment by luziagu** [comment]
Danke euch allen! Hat funktioniert :)
