### ISSUE TITLE
Bildgröße/ Hintergrund

### ISSUE THREAD

**Issue by schneine** [JirkaDellOro/EIA2-Inverted#184]
Hallo zusammen, 

ich finde meinen Fehler nicht, warum es mir die Größe und den Hintergrund nicht verändert...

https://github.com/schneine/EIA2/tree/master/Zauberbild

https://schneine.github.io/EIA2/Zauberbild/Client/zauberbild.html

**Comment by MarkusDamm** [comment]
Hallo Nelly,

das Problem liegt darin, auf welche Werte du zugreifst. Beide Funktionen, also `choosePictureSize` und `chooseBackground` greifen auf die ID des Eventtargets zu. Das Eventtarget ist in dem Fall das select-Element. Deshalb bekommst du als ID immer background oder size, statt die eigentlichen **Werte**.

**Comment by schneine** [comment]
Hallo Markus, 

vielen Dank für deine Hilfe, dass verändern der Bildgröße funktioniert nun, nur der Hintergrund bleibt weiß.. ich werd es mal mit dem Debugger versuchen.
