### ISSUE TITLE
Animation wird nicht gezeichnet

### ISSUE THREAD

**Issue by JanaKraemer** [JirkaDellOro/EIA2-Inverted#185]
Hallo zusammen,

ich versuche gerade mein Objekt zu animieren und laut meiner Console wird es auch neu gezeichnet (ich lasse mir die x und y Werte ausgeben), allerdings bewegt sich der Kreis (linie.ts) nicht. Er wird gezeichnet, und die move wird auch aufgerufen. Ich habe bereits vieles ausprobiert, aber komme einfach nicht weiter, ich hoffe ihr könnt mir weiterhelfen:

https://github.com/JanaKraemer/JanaKraemer/tree/master/Abschlussaufgabe2/Abschlussaufgabe2

**Comment by MarkusDamm** [comment]
Hallo Jana,

in deiner draw-Methode steht `circle.arc(525, 200, 25, 0, 360);`. Dadurch wird ein Kreis mit dem Zentrum bei x=525 und y=200; und das bei jedem Aufruf von draw genau an der selben Stelle.

**Comment by JanaKraemer** [comment]
Vielen Dank, jetzt funktioniert es :)
