### ISSUE TITLE
[...] is not a constructor

### ISSUE THREAD

**Issue by LukasBlea** [JirkaDellOro/EIA2-Inverted#186]
Hellloooooo ein weiteres mal!

Diesmal stoße ich auf ein Problem, dass ich hoffentlich irgendwie beschreiben kann.

In meiner "tools.ts" Datei, besitze ich eine Funktion namens "drawCircle2", welche die "_event.offsetX" & "_event.offsetY" Koordinaten der Maus an den Constructor meiner "circle.ts" weiterleitet. 

![drawCircle2](https://user-images.githubusercontent.com/44029295/88263327-26860980-ccca-11ea-89cc-06c88bb089f6.PNG)

Hierbei greift der Constructor dann auf die Klasse "Vector" zu und übergibt diese die Position meiner Maus, da ich will, dass der Kreis genau dort gezeichnet wird, wo der User es platzieren möchte. Dies hat vorher schon funktioniert, allerdings nachdem ich mein Klassensystem besser aufgebaut habe, wird dieser nicht mehr gezeichnet (da die Fehlermeldung auftaucht).

Hier meine class "Circle":
![classCircle](https://user-images.githubusercontent.com/44029295/88263637-a7450580-ccca-11ea-934f-38f0393651a7.PNG)

Hier meine class "Vector":
![classVector](https://user-images.githubusercontent.com/44029295/88263731-c774c480-ccca-11ea-9691-8538e5ce4756.PNG)

Mein Kopf ist etwas durcheinander vom ganzen Programmieren, also vielleicht hat einer von euch einen Lösungsansatz, der mir bei meinem Problem weiterhilft. Ich nehme stark an, dass es irgendwas mit "set" aus meiner class "Vector" zu tun hat und habe mir schon etwas dazu durchgelesen. 

Brauche ich auch ein "set" bei meiner Circle class?

Ich komme irgendwie nicht auf die Lösung uff

Hier nochmal ein Link zu meinem Repo: https://github.com/LukasBlea/Endabgabe
Hier ein Link zur Anwendung: https://lukasblea.github.io/Endabgabe/Endabgabe.html

PS: In 1-2 Versionen vor meinem letzten Push, müsste die Kreisfunktion noch funktionieren. Sollte alles gut dokumentiert sein für diejenigen, die auf Fehlersuche gehen möchten.

Ich danke euch schonmal für eure Hilfe.

Beste Grüße
Lukas Blea

**Comment by KohlerAl** [comment]
Hi, in deinem HTML fehlt die Verlinkung zu circle.js

**Comment by LukasBlea** [comment]
sfeajipijNFNKJIN ich hab jetzt also 3 Stunden meines Lebens verschwendet :DD
Mir wäre das niemals im Leben aufgefallen, vielen dank!!

**Comment by KohlerAl** [comment]
Gerne :)
