### ISSUE TITLE
Probleme mit Übergabeparametern?

### ISSUE THREAD

**Issue by Koefe** [JirkaDellOro/EIA2-Inverted#187]
Hey hey,

ich versuche gerade die Elemente in meiner Canvas mithilfe von Übergabeparametern zu neu zu platzieren (also schon existierende Formen neu platzieren).
Der Gedanke ist, dass sobald ein Kreis mit mausedown selektiert ist und der Button "drag" gedrückt wurde, der Kreis an eine gewählte x/y Position des Users im Canvas neu gezeichnet wird.
Mein Problem ist aber, dass ich client x und y durch ein mausedown Event weitergeben möchte, dieser aber am Ende undefined ist.
Ich hab auf ziemlich kompliziertem Weg versucht die funktion  "getNewPosition" so zu bauen, dass auf einen klick des Users gewartet wird aber das ganze funktioniert nicht wie gedacht. Die x/y werte bleiben undefiniert.
Gibt es einen besseren Weg, nachdem der drag Button gedrückt wurde, auf einen klick des Users zu warten?
Und warum bleiben meine x/y Werte undefiniert?

Ich hoffe ich konnte mein Problem einigermaßen erklären haha.

https://github.com/Koefe/EIA2/tree/master/Abschlussaufgabe_EIA2_2020

Grüßle, Felix

**Comment by JirkaDellOro** [comment]
Bitte poste Links
1. zu deinem Konzept
2. zur App

**Comment by Koefe** [comment]
mein Konzept zu der drag Funktion:
https://github.com/Koefe/EIA2/tree/master/Abschlussaufgabe_EIA2_2020/Konzept
zur App:
https://koefe.github.io/EIA2/Abschlussaufgabe_EIA2_2020/index.html

**Comment by JirkaDellOro** [comment]
Im Konzept fehlen UseCase- und Klassendiagramm. Bitte außerdem ein Konzept unbedingt als ein PDF mit allen relevanten Seiten präsentieren.
