### ISSUE TITLE
Delete symbol 

### ISSUE THREAD

**Issue by schneine** [JirkaDellOro/EIA2-Inverted#188]
Hallo zusammen, 

ich mache mir gerade Gedanken zu dem Löschen von ausgewählten Symbolen. 
Ich hatte überlegt, dass ich auf dem mainCanvas ein KeyboardEvent setze und daraufhin das Symbol wo die Maus sich vom Nutzer befindet, sich durch die Löschtaste aus dem Array löscht, da ich vermute, dass man kein Keyboard Event auf ein einzelnes Symbol setzen kann. 
Dh ich müsste die Position des Symbols(Array durchlaufen) und der Maus abgleichen und wenn diese übereinstimmen, dass Symbol aus dem Array löschen oder? Jedoch würde es ja dann nur bei exakt der Mitte des  Symbols übereinstimmen, sprich ich müsste eine hitArea für jedes Symbol erstellen, um es dem Nutzer zu vereinfachen...
Gibt es einen einfacheren Ansatz oder ist das der logischste?

Grüße, Nelly

**Comment by JirkaDellOro** [comment]
Nein, der Ansatz ist gut und passt. Du könntest auch das Symbol nehmen, dass dem Mauscursor mit seinem Mittelpunkt am nächsten ist, dann wird aber vielleicht auch eines gelöscht, dass recht weit entfernt ist, wenn nur die anderen noch weiter entfernt sind. Optimal, aber für die Aufgabe übertrieben, wäre es beides zu tun, also von denen, die getroffen sind, das zu nehmen, dass dem Cursor am nächsten ist.

**Comment by schneine** [comment]
Okay, danke!
Daran hatte ich auch gedacht, aber ich denke mit der Umsetzung dieses Ansatzes bin ich schon genug beschäftigt :D

**Comment by JirkaDellOro** [comment]
Einen Laufzeit-Fehler kann ich nicht erkennen. Meinst Du den logischen Fehler, dass die Objekte nicht getroffen werden? Ich schätze, es liegt daran, dass Du die `client`-Koordinaten verwendest, die sich auf das Browserfenster und nicht auf den Canvas beziehen. Schau mal bei MDN unter MouseEvent, da gibt es einen ganzen Sack voll Koordinaten, das experimentelle 'offset` vielleicht für dich am besten.

Oder Du schaust nochmal in den eiaSteroids, da hatte ich eine Umrechnung implementiert:
```typescript
  /**
   * Map a position on the client (event.clientX / Y) to a position on the canvas
   */
  function mapClientToCanvas(_x: number, _y: number): Vector {
    return new Vector(_x - crc2.canvas.offsetLeft, _y - crc2.canvas.offsetTop);
  }
```

**Comment by schneine** [comment]
Hallo Jirka, 
danke für deine Hilfe und Hinweise. Zusammen mit der lieben Alida hab ich es geschafft, dass sie sich löschen!
Schönes Wochenende!

**Comment by JirkaDellOro** [comment]
Magst Du den Issue schließen, bitte?
