### ISSUE TITLE
Argument of type 'Herz' is not assignable to parameter of type 'Symbol'.

### ISSUE THREAD

**Issue by beliema** [JirkaDellOro/EIA2-Inverted#189]
Hallo, 
Ich bin gerade dabei meine Klassen auf den Canvas zeichnen zu lassen. Meine Idee war, dass wenn man im Feld Symbol das jeweilige Symbol anklickt (checkbox) und anschließend auf das Canvas drückt, dass dieses dann an dieser Stelle generiert wird und die Animation startet. 
Dazu hatte ich die Funktion so gedacht 
<img width="797" alt="Bildschirmfoto 2020-07-24 um 10 20 28" src="https://user-images.githubusercontent.com/48830827/88373004-52bb8c00-cd97-11ea-9bd9-bd48c929d3ca.png">
jedoch tut es nicht. Bei dem rot untermalten Worten wird folgende Fehlermeldung angezeigt: Argument of type 'Herz' is not assignable to parameter of type 'Symbol'.
  Property '[Symbol.toStringTag]' is missing in type 'Herz' but required in type 'Symbol'.ts(2345)

mir ist nicht ganz klar, was ich tun muss, um dies zu beheben. Ist der Ansatz zur Lösung überhaupt richtig/gut? 

Liebe Grüße, Alina

**Comment by beliema** [comment]
Code ist auf der Kursseite hochgeladen/verlinkt

**Comment by JirkaDellOro** [comment]
Bitte hilfreiche Links immer gleich mitposten, sonst müssen wir zusätzlich Detektivarbeit leisten.

**Comment by JirkaDellOro** [comment]
Mehrere Punkte fallen mir auf:
- du nutzt im Code deutsche Bezeichnungen, bleibe ganz bei Englisch
- `symbol` scheint ein Array vom Typ `Symbol` zu referenzieren, allerdings hast Du keine Klasse `Symbol` definiert
- solltest Du auch nicht tun, den `Symbol` ist ein reserviertes Wort, das solltest Du nicht benutzen
- wenn Du die Symbole in einem Array halten willst, was gut ist und was Du tun solltest, sollten sie alle Instanzen von Subklassen einer gemeinsamen Superklasse sein. Im Konzept hast Du das bereits anders geplant.
- im Code oben bist Du gerade dabei, ganz viel und umfangreiche Code-Vervielfachung zu bauen, dass solltest Du unbedingt vermeiden
- nutze statt getElementById für alle Radio-Buttons doch einfach den Change-Event für die ganze Gruppe.

**Comment by beliema** [comment]
okay, durch erstellen einer Shape Klasse hat es geklappt, dass sich etwas generieren lässt, allerdings wird mir der Canvas dann so angezeigt: 
<img width="1088" alt="Bildschirmfoto 2020-07-24 um 19 12 05" src="https://user-images.githubusercontent.com/48830827/88419303-42ca9900-cde5-11ea-9759-99e87c67f25f.png">
Ich will aber, dass sich erst auf Mausklick im Canvas das zuvor ausgewählte Symbol generiert und dass der Canvas sich über die gesamte ausgewählte Fläche erstreckt und nicht nur über das kleine lila Quadrat.
Gibt es einen Ansazt es so zu beheben?

**Comment by JirkaDellOro** [comment]
Bitte poste die erforderlichen Links, sonst muss ich wieder suchen...

**Comment by beliema** [comment]
Repository: https://github.com/beliema/beliema.github.io/tree/master/Semester2/EIA2Abschluss
Link: https://beliema.github.io/Semester2/EIA2Abschluss/zauberbild.html

**Comment by JirkaDellOro** [comment]
Du musst unbedingt deinen Code etwas aufräumen. Beginne mit Autoformat (Alt+Shift+F) um zu sehen wo deine Klammern landen. Du hast scheinbar versehentlich verschachtelte Schleifen drin. Schaue auch, ob Du die Codedopplungen eliminieren und das ganze etwas geschickter aufziehen kannst, der Code könnte geschätzt auf 30% zusammenschrumpfen. Derzeit können sich Fehler sehr leicht verstecken.

**Comment by beliema** [comment]
Ich habe jetzt versucht Codedopplungen zu vermeiden und allgemein das Ganze etwas abzukürzen, allerdings kommen dann weitere Fehlermeldungen wie canvas is null, oder not defined. Klammern hab ich auch keine vergessen, habe ich noch einmal nachgeprüft. Bin grade ziemlich ratlos, was ich noch versuchen kann, damit es sich richtig generiert

**Comment by JirkaDellOro** [comment]
Ich bin bis Donnerstag auf einem Lehrgang und nur sporadisch zu erreichen. Daher Aufruf an @AnnaLotz und @MarkusDamm
