### ISSUE TITLE
Problem mit Heroku App

### ISSUE THREAD

**Issue by reginafaller** [JirkaDellOro/EIA2-Inverted#190]
Ich bekomme bei meiner Heroku App trotz erfolgreichem deploy einen Application error. Die package.json Datei und die Server.ts liegen jeweils auf oberster Ebene in meinem Repository.
https://github.com/reginafaller/EIA2

Hier mal der Error und Screenshots von dem log:
<img width="709" alt="Screenshot 2020-07-24 at 16 37 45" src="https://user-images.githubusercontent.com/44026417/88403668-202c8600-cdcd-11ea-9efe-4fe3a7602039.png">
<img width="1296" alt="Screenshot 2020-07-24 at 16 36 49" src="https://user-images.githubusercontent.com/44026417/88403714-2ae71b00-cdcd-11ea-8df1-f32fe8de51f8.png">
<img width="1311" alt="Screenshot 2020-07-24 at 16 37 02" src="https://user-images.githubusercontent.com/44026417/88403726-2e7aa200-cdcd-11ea-8403-9f8b8fb8fb5d.png">
<img width="1280" alt="Screenshot 2020-07-24 at 16 37 10" src="https://user-images.githubusercontent.com/44026417/88403730-2fabcf00-cdcd-11ea-868a-e7ad46d9bfc8.png">

**Comment by JirkaDellOro** [comment]
Was Du darstellst ist der Build-Log. Scheinbar also kann sich Heroku aus deinem Projekt zusammenbasteln. Aber Du suchst ja nicht nach Compilerfehlern sondern nach Laufzeitfehlern. Was zeigt denn das App-Log?

**Comment by reginafaller** [comment]
<img width="1230" alt="Screenshot 2020-07-24 at 17 19 20" src="https://user-images.githubusercontent.com/44026417/88407088-e0b46880-cdd1-11ea-9016-9e2a32459221.png">

**Comment by JirkaDellOro** [comment]
Da gibt es irgendwo einen Button, mit dem man mehr sehen kann, glaube ich

**Comment by JirkaDellOro** [comment]
Ich bin gerade in dm16, wollen wir eine kurze Fernwartung machen?

**Comment by reginafaller** [comment]
das wäre perfekt, finde keinen Button. Bin sofort da

**Comment by yeniayeb** [comment]
ich habe das selbe problem, wie wurde das gelöst?

**Comment by reginafaller** [comment]
ich glaube mein Problem war, dass ich den falschen Pfad in meiner package.json angegeben habe. Bin mir leider auch nichtmehr 100% sicher

**Comment by JirkaDellOro** [comment]
War das der richtige Tipp? Dann bitte Issue schließen, ansonsten gerne auf Discord kommen

**Comment by yeniayeb** [comment]
habe gefunden woran es lag. Habe den falschen Pfad gehabt , deshalb lief es nicht. Danke  für die Rückmeldung :)

**Comment by JirkaDellOro** [comment]
Also schließen?

**Comment by yeniayeb** [comment]
ja :)

**Comment by JirkaDellOro** [comment]
Oh Mann, jetzt sehe ich erst, dass der gar nicht offen war! Toll, dass Du in den geschlossenen Issues nach einer Lösung gesucht hast, damit hatte ich einfach nicht gerechnet...
