### ISSUE TITLE
Löschen Canvas & Löschen einzelner Symbole 

### ISSUE THREAD

**Issue by luziagu** [JirkaDellOro/EIA2-Inverted#191]
Hallo zusammen, 

ich habe gestern meine Funktion implementiert, die die einzelnen Symbole löschen soll (deleteSymbol). Mir hat es dann aus einem Grund, den ich noch nicht herausgefunden habe, sowohl das löschen des kompletten MainCanvas, als auch den leeren Canvas, der am Anfang zusehen ist zerhauen. Zusehen waren dann alle Symbole einmal auf dem MainCanvas. Ich habe jetzt in der Funktion createForms das pushen in das Array Forms ausgeklammert, sodass der Maincanvas am Anfang leer ist. Das scheint aber irgendwas anderes verändert zu haben, da die Symbole sich jetzt ganz langsam bewegen ohne, dass ich eine Funktion habe in der die Symbole animiert werden. Das löschen der einzelnen Symbole klappt jetzt auch nicht mehr. Ich bin jetzt ein bisschen hilflos woran das liegen könnte. Ganz am Anfang dachte ich, dass es an der Reihenfolge liegt wie die Funktionen in der HandleLoad Funktion aufgerufen werden. Aber auch durch das ändern der Reihenfolge war es mir nicht möglich einen leeren Canvas am Anfang herzustellen. 

Hat jemand eine Idee woran das liegen könnte? Danke schonmal im voraus! 

https://luziagu.github.io/Abschlussarbeit_SOSE2020/zauberbild.html

https://github.com/luziagu/Abschlussarbeit_SOSE2020/blob/master/zauberbild.html

**Comment by KohlerAl** [comment]
Also den Fehler mit dem Hintergrund finde ich nicht, bei mir wird einfach eine leere Fläche angezeigt, das ist ja das was passieren soll, oder? 
Und wegen dem löschen: Es funktioniert, aber nur wenn man zufällig einen Punkt in der Nähe der Position der Figur erwischt. Das liegt daran, dass dein Radius mit 5 einfach viel kleiner ist als die Figur.

**Comment by KohlerAl** [comment]
Und wegen dem Animieren: Ich habe eine Funktion gefunden, in Zeile 290. Die wird alle 100ms aufgerufen (in Zeile 71)

**Comment by KohlerAl** [comment]
Bei der Funktion clearCanvas zeichnest du zwar ein neues Rechteck, da du aber dein Array nicht leerst, werden die Symbole einfach wieder drauf gezeichnet.

**Comment by luziagu** [comment]
> Also den Fehler mit dem Hintergrund finde ich nicht, bei mir wird einfach eine leere Fläche angezeigt, das ist ja das was passieren soll, oder?
> Und wegen dem löschen: Es funktioniert, aber nur wenn man zufällig einen Punkt in der Nähe der Position der Figur erwischt. Das liegt daran, dass dein Radius mit 5 einfach viel kleiner ist als die Figur.

Aber das mit dem Hintergrund ist nur der Fall weil ich die Symbole nicht mehr in das Array Pushe. Das mit dem Radius habe ich nicht bedacht, danke! 

Die Funktion mit dem ClearCanvas hatte aber davor so funktioniert, ohne dass ich das Array noch leeren musste.

**Comment by luziagu** [comment]
Also trotz erhöhen des Radius, wird bei mir nur der Stern gelöscht. Und die Symbole tauchen jetzt auch wieder am Anfang auf.

**Comment by KohlerAl** [comment]
Das mit dem clearCanvas hat wahrscheinlich so funktioniert, weil die Symbole noch nicht animiert waren. Da hast du dann einfach ein Rechteck drüber gemalt und fertig. Weil die Symbole jetzt aber animiert werden, werden sie alle 100ms neu gezeichnet. Damit das nicht mehr passiert, musst du das Array leeren.

**Comment by KohlerAl** [comment]
In der Funktion createForms pushst die kleinen Symbole, die links auf die kleinen Canvas gezeichnet werden, auch in das Array. Da jetzt alles animiert wird, werden die kleinen Symbole auch gezeichnet. Da die Animation aber auch dem mainCanvas passiert, tauchen auf einmal die kleinen Symbole auf dem mainCanvas auf.

**Comment by KohlerAl** [comment]
Und der Radius ist bei allen Figuren immer noch 5, du hast es zwar in der Superklasse geändert, überschreibst den Wert aber in allen Subklassen wieder mit 5.

**Comment by luziagu** [comment]
Vielen Dank Alida!! Hat funktioniert. Bis auf den Kreis und das Dreieck lassen sich jetzt alle löschen.

**Comment by KohlerAl** [comment]
Wenn du nochmal in die Klassen Circle und Triangle schaust siehst du, dass du die Figuren nicht an die Position zeichnest, sondern ein Stückt daneben. Du gehst aber in der Funktion zum löschen davon aus, dass die Position ungefähr in der Mitte der Figur liegt. Kreis und Dreieck lassen sich auch löschen, wenn man mal ein bisschen neben die Figuren klickt.
