### ISSUE TITLE
Funktion löschen und Daten abrufen

### ISSUE THREAD

**Issue by FrankeSa** [JirkaDellOro/EIA2-Inverted#192]
Hallo zusammen,

ich habe hier zwei Funktionen bei denen ich mir nicht sicher bin, ob die so funktionieren bzw. man sie überhaupt versteht.
Bei handleLoad habe ich mich ein bisschen an der Lektion Client orientiert. Die Daten zum Canvas sollen bei der DB abgerufen werden und dann zur Verfügung sein, damit die Funktion displayPictureData die Daten holen kann und entsprechend in das Dropdown pushen kann.  https://frankesa.github.io/EIA2_Abschlussarbeit/Abschulss_Konzept/handleLoad und DeletCanvas Funktion.pdf

Bei der Lösch-Funktion ist es so, dass ich mit gedacht habe, egal welche Farbe ausgewählt war, soll der Canvas weiß übermalt werden. Alle Objekte die sich darauf befinden, sollen gelöscht werden. Wie das aber im einzelnen aussieht, weiß ich noch nicht, da wäre ich für einen Ansatz dankbar.

**Comment by FrankeSa** [comment]
https://frankesa.github.io/EIA2_Abschlussarbeit/Abschulss_Konzept/handleLoad und DeletCanvas Funktion.pdf

**Comment by FrankeSa** [comment]
[handleLoad und DeletCanvas Funktion.pdf](https://github.com/JirkaDellOro/EIA2-Inverted/files/4975441/handleLoad.und.DeletCanvas.Funktion.pdf)

**Comment by JirkaDellOro** [comment]
Ich bin bis Donnerstag unterwegs, daher in aller Kürze:

Da die Symbole animiert werden, müssen sie immer wieder gezeichnet werden. Es muss also entsprechende Informationen darüber vorliegen. Wenn Du diese Informationen entfernst, solltest Du also wieder eine leeres Bild erhalten.

**Comment by MarkusDamm** [comment]
Wie schon gesagt würden die Objekte einmalig gemalt werden. Da du in deinem [Interface](https://frankesa.github.io/EIA2_Abschlussarbeit/Abschulss_Konzept/User_Interface_Zauberbild_Franke_Sarah.pdf) mehrere Canvaseses verwendets wird im AD nicht klar, auf welchem Canvas bei handelLoad gezeichnet, und welcher bei deleteCanvas gelöscht werden soll.   

Die letzte Aktion, also `splice Objects from Canvas` ist schon mal gut, wenn Objects die Objekte vom großen Canvas beinhaltet. Nur brauchst du in delteCanvas die Farben nicht abzufragen, wenn immer das gleiche ausgeführt werden soll.

**Comment by FrankeSa** [comment]
Wenn ich alle Objekte, die sich auf dem Main canvas befinden, entferne und ein neuer Canvas erzeuge, der dann die Maße und die ID meines "Start-Canvas" hat. Klingt das machbar?

**Comment by JirkaDellOro** [comment]
Eigentlich ist doch dein Problem nur der gewählte Hintergrund, oder? Den wählt der Nutzer doch ohnehin wie er will. Verstehe ich dich richtig?

**Comment by FrankeSa** [comment]
Genau, der Nutzer kann den Hintergrund wählen. Aber wenn sich schon Objekte auf dem Canvashintergrund befinden und der Nutzer das Bild löschen will, dann muss ja der Hintergrund zurück auf Ursprung gesetzt werden und die Objekte vom Canvas runter, damit alles wieder so aussieht wie vorher...

**Comment by JirkaDellOro** [comment]
Dann ist deine Lösung zielführend, denke ich. Du musst allerdings nicht unbedingt einen neuen Canvas erzeugen, es würde genügen den existierenden weiß zu füllen

**Comment by FrankeSa** [comment]
Okay :) Danke!
