### ISSUE TITLE
Symbole werden nach platzieren kleiner?

### ISSUE THREAD

**Issue by k-poschmann** [JirkaDellOro/EIA2-Inverted#193]
Hallo :)
Nachdem ich es endlich geschafft habe die Symbole mit einem Mausklick auf die Canvas zu platzieren, stellt sich mir eine neue Herausforderung. Nach jedem neuen platzieren eines Symbols, werden diese kleiner und platzieren sich nicht an die Position wo der Nutzer hinklickt...

meine Seite: https://k-poschmann.github.io/poschmannEia2/Aufgaben/Abschlussaufgabe_Zauberbild/index.html
zum Repo: https://github.com/k-poschmann/poschmannEia2/tree/master/Aufgaben/Abschlussaufgabe_Zauberbild
mein Konzept: https://github.com/k-poschmann/poschmannEia2/blob/master/Aufgaben/Abschlussaufgabe_Zauberbild/Konzept/Konzept.pdf

Ich danke schon mal im voraus :)
Kristin

**Comment by KohlerAl** [comment]
Du skalierst und verschiebst in allen Subklassen dein Koordinatensystem beim zeichnen, verwendest aber nach dem Zeichnen kein restore, um das Koordinatensystem wieder in seinen ursprünglichen Zustand zu versetzen.

**Comment by k-poschmann** [comment]
Ah ... ja das hat beides mit einmal gelöst :D Danke :)
