### ISSUE TITLE
Deutsch oder Englisch oder geht beides?

### ISSUE THREAD

**Issue by Jonas915** [JirkaDellOro/EIA2-Inverted#194]
Guten Morgen,

Ich habe bisher immer auf deutsch geschrieben (Konzept und Teile des Codes). 
Das Booklet ist allerdings komplett auf englisch, wie mir aufgefallen ist..
@JirkaDellOro @AnnaLotz soll ich die Sachen besser nochmal auf englisch aufschreiben oder gebt ihr euch auch mit germanischer Sprache zufrieden?

Danke & einen schönen Sonntag
ſouɐs :)

**Comment by MarkusDamm** [comment]
Wie Jirka schon in einem anderen Issue geschrieben hat:  

Mehrere Punkte fallen mir auf:
- du nutzt im Code deutsche Bezeichnungen, bleibe ganz bei Englisch
_Originally posted by @JirkaDellOro in https://github.com/JirkaDellOro/EIA2-Inverted/issues/189#issuecomment-663542715_

Im Konzept ist es weniger schlimm, wenn du auf deutsch schreibst. Nur sollte dabei bei Variablen, Klassen und ähnliches, was du selbst benennst, im Code die selbe Bezeichnung genutzt werden, wie im Konzept; für die sollte englisch genutzt werden

**Comment by Jonas915** [comment]
Alles klar, danke!
