### ISSUE TITLE
Drag & Drop

### ISSUE THREAD

**Issue by luziagu** [JirkaDellOro/EIA2-Inverted#195]
Hei, 

Ich würde gerne ein Drag & Drop auf die Symbole implementieren um die Position zu verändern und wollte einmal nachfragen, was es für Möglichkeiten gibt. Ich habe gedacht ich könnte mit Eventlistener arbeiten, die dann bei Mousedown das Symbol an den Cursor hängen und bei Mouseup an der Position loslassen. Das Symbol bekommt also die gleiche Position wie der Cursor. Man könnte dem Symbol auch eine Eigenschaft mitgeben und solange die True ist haben Cursor und Symbol die gleiche Position. Gibt es noch andere Möglichkeiten? Was macht von der Umsetzung her am meisten Sinn? 

Gruß, Luzia

**Comment by JirkaDellOro** [comment]
Beide Ansätze sind sinnvoll. Ich habe aber die besten Erfahrungen gemacht, wenn ich ein Extra-Objekt verwende, dass im Code auch eine Sonderbehandlung erfährt, also nicht mit den anderen im Array liegt, sondern durch eine eigene Variable z.B. mit Namen `objDragDrop` referenziert wird. Das wird dann auch immer als letztes, also im Vordergrund gezeichnet und folgt immer der Mausposition. Dann kannst Du mit dieser Variable referenzieren was Du willst, also entweder ein Objekt im Array oder ein neues etc.

**Comment by luziagu** [comment]
Hallo Jirka, 
Alida und ich basteln grade ein bisschen an der Drag & Drop Funktion rum und wollten fragen wie wir das Symbol an den Cursor hängen kann ohne ein MouseEvent, da ja das Mousedown event durch die Funktion nicht konstant getriggerd wird. Ist das immer so oder gibt es eine andere Möglichkeit? 

Gruß, Luzia und Alida 


https://luziagu.github.io/Abschlussarbeit_SOSE2020/zauberbild.html

https://github.com/luziagu/Abschlussarbeit_SOSE2020/blob/master/zauberbild.html

**Comment by JirkaDellOro** [comment]
Schaut euch den Event "mousemove" an. Damit könnt ihr das Droplet, also das Objekt, das als Indikator für's Draggen dargestellt wird, ständig mit der Maus mitführen. Das geht natürlich auch einfach in eurer Animation-Funktion. Mit dem "mousdown"-Event oder anderen, je nachdem was ihr wollt, definiert ihr die dropLet-Variable mit einer Referenz auf ein zu bewegendes Objekt. oder mit null, wenn keines gerade gedragt wird. In letzterem Fall darf es dann in der Animations-Funktion, bzw. im MouseMove-Handler, nicht gezeichnet werden.

**Comment by luziagu** [comment]
Hallo Jirka, 

also es Funktionier so lala, manchmal tut es das was es soll und manchmal gar nicht. Auch kommen sich das löschen und Drag&Drop oft in die quere.

**Comment by JirkaDellOro** [comment]
Hattet ihr die Funktionalität einmal durchkonzipiert? Seid ihr beim Coden vom Konzept abgewichen? Habt ihr für eine neue Herangehensweise auch ein entsprechendes Konzept gemacht? In eurem aktuellen Lernstatus ist es so, dass man bei der Produktion viel Neues lernt, das ist super. Allerdings muss man dies in die Konzeption zurück reflektieren, sonst verrennt man sich mit den neuen Möglichkeiten.

Wenn ich nun schauen soll, was in eurem Code schief läuft, muss ich zunächst gut erkennen können, wie ihr ihn denn geplant habt und ob der Plan Sinn ergibt. Sonst haben wir keine Grundlage für den Austausch.

**Comment by luziagu** [comment]
[Konzept_DragDrop.pdf](https://github.com/JirkaDellOro/EIA2-Inverted/files/4987427/Konzept_DragDrop.pdf)

**Comment by luziagu** [comment]
Danke Jirka!

**Comment by luziagu** [comment]
Hier nochmal mit der Funktion Animate: 
[Konzept_DragDrop.pdf](https://github.com/JirkaDellOro/EIA2-Inverted/files/4987593/Konzept_DragDrop.pdf)

**Comment by JirkaDellOro** [comment]
Ok, genau genommen muss man das Konzept so interpretieren, dass ihr auf Mausklick das Array von Symbolen durchgeht und nacheinander dem objectDragDrop eine Referenz zuweist. Wenn ihr durch seid, löscht ihr ihr ein Symbol, dass nicht existiert vom Array. Wahrscheinlich soll eigentlich da irgendwo die Abfrage rein, ob das Symbol in der Nähe es Mauscursors ist, woraufhin es dem objectDragDrop zugewiesen und aus dem Array gelöscht wird. Außerdem setzt ihr auf jeden Fal dragDrop auf true, auch wenn kein Symbol in der Nähe ist. Das muss schief gehen.

In animate sollte auch die Abfrage nach dragDrop rein, sonst geht der draw des objectDragDrop daneben.

Weitere Details
- mooveSymbol ist kein guter Name für die Funktion
- nach draw object DragDrop fehlt der Endknoten

Schaut mal, ob ihr mit diesen Tipps schon Fehler findet, ansonsten melden und ich schau in den Code

**Comment by schneine** [comment]
Hallo Jirka, wir hatten das Konzept falsch....

![WhatsApp Image 2020-07-28 at 16 54 01](https://user-images.githubusercontent.com/56204469/88682530-0ce22900-d0f3-11ea-982c-8cceecb0949f.jpeg)

**Comment by JirkaDellOro** [comment]
Ok, das passt besser. Habt ihr schon Fehler oder Verbesserungsmöglichkeiten mit Hilfe der Konzeptaktualisierung gefunden?

**Comment by schneine** [comment]
ja wir haben den Code so wie im Konzept beschreiben. Es läuft aber nicht so wie gewünscht. Symbole können nicht mehr gelöscht werden, nachdem sie bewegt wurden und die Symbole werden schneller, wenn man drauf klickt. Manche Symbole duplizieren sich auch. 
Wir wissen nicht mehr weiter...

**Comment by JirkaDellOro** [comment]
Morgen Live-Review? Ich könnte um 9.00 Uhr in dm16 sein.

**Comment by schneine** [comment]
Ja Luzia und ich sind dabei. Danke!
