### ISSUE TITLE
Verzerrung der Symbole auf Zeichenfläche & generierung neuer Canvas auf altem bei mehreren angeklickten Symbolen

### ISSUE THREAD

**Issue by beliema** [JirkaDellOro/EIA2-Inverted#197]
Hi, 
Nachdem ich es hinbekommen habe meine Symbole nach Klicken des jeweiligen Radio-Buttons in das Canvas generieren zu lassen, sind mir 2 Sachen aufgefallen. 
Zum einen, wenn ich Format 1 & 2 wähle, werden mir die Elemente verzerrt in den Canvas gezeichnet. 
<img width="1088" alt="Bildschirmfoto 2020-07-26 um 21 30 19" src="https://user-images.githubusercontent.com/48830827/88487637-43029a00-cf87-11ea-977d-bd95e451060a.png">

wie kann ich es machen, dass meine Objekte in allen ausgewählten Formaten unverzerrt dargestellt werden? 

Die zweite Sache ist, dass wenn ich beispielsweise ein Canvas generieren lasse, etwas darauf zeichne und danach zb eine andere Hintergrundfarbe wählen will, dass sich eine zweite, kleinere Fläche auf die bereits bestehende generiert: 
<img width="1088" alt="Bildschirmfoto 2020-07-26 um 21 32 22" src="https://user-images.githubusercontent.com/48830827/88487678-878e3580-cf87-11ea-996f-cbc462d2a348.png">

Es werden mir auch keine Fehler in der Konsole angezeigt. Wäre für Hilfe sehr dankbar @AnnaLotz @MarkusDamm 

Repository: https://github.com/beliema/beliema.github.io/tree/master/Semester2/EIA2Abschluss
Link: https://beliema.github.io/Semester2/EIA2Abschluss/zauberbild.html

**Comment by MarkusDamm** [comment]
Für das zweite Problem fehlt in den draw-Methoden wohl nur das restore.

Beim ersten bin ich mir nicht ganz sicher. Ich denke es könnte etwas damit zu tun haben, dass beim Laden der CanvasRenderingContext von der Standardgröße des Canvas genommen wird, also 500*300. Bei der Größenänderung hilf es dann vielleicht, crc2 wieder einen Wert zuzuweisen, nachdem die Canvasgröße angepasst wurde.

**Comment by beliema** [comment]
okay, hat beides geklappt, super danke!
