### ISSUE TITLE
"click" oder "keydown" listener? 🤔

### ISSUE THREAD

**Issue by Jonas915** [JirkaDellOro/EIA2-Inverted#199]
Hallo,
ich habe nur eine kleine (triviale) Frage: Wenn ich einen Wert (z.B. Scale-Faktor) in ein Textfeld eingebe und es mit der Entertaste erst ausgelöst wird, ist es dann ein "keydown" Event oder ein "click" Event, da das Feld ja zunächst durch einen Klick aktiviert werden muss?

LG :)

**Comment by JirkaDellOro** [comment]
Am Besten ein "change"

**Comment by Jonas915** [comment]
Ja stimmt, hast Recht, das passt besser 👍 
Danke!
