### ISSUE TITLE
Heroku: Repository zugriff erlauben

### ISSUE THREAD

**Issue by luziagu** [JirkaDellOro/EIA2-Inverted#200]
Hei, ich versuche grade mein neues Repository  mit Heroku zu verbinden. Hier lädt es aber ewig und jetzt hab ich gedacht vielleicht muss ich hier auch erst von Github aus den Zugriff erlauben. Ich finde aber nicht heraus wie und auch bei EIA-Invertet steht, dass man sich an einen Praktikanten wenden soll. Deswegen jetzt hier: Wie kann ich den Zugriff erlauben? 
<img width="857" alt="Bildschirmfoto 2020-07-28 um 11 28 19" src="https://user-images.githubusercontent.com/56430460/88646468-71868f00-d0c5-11ea-9fed-ab6c6fc13659.png">

**Comment by JirkaDellOro** [comment]
Wenn ich mich richtig erinnere, setzt Heroku eine Anfrage ab, die Du auf Github findest und bestätigst. Ich binde auch den Praktikanten ein: @AionixX

**Comment by luziagu** [comment]
Komisch, eine Anfrage hab ich auf GitHub nicht bekommen. Es scheint immer noch zu laden..aber dann warte ich mal was @AionixX sagt.

**Comment by luziagu** [comment]
Es hat jetzt verbunden. Ich erhalte aber keine Response. 
<img width="1204" alt="Bildschirmfoto 2020-07-28 um 12 13 53" src="https://user-images.githubusercontent.com/56430460/88653104-ed83d580-d0cb-11ea-9555-68b3b8a45b1b.png">
