### ISSUE TITLE
Animation Canvas 

### ISSUE THREAD

**Issue by beliema** [JirkaDellOro/EIA2-Inverted#201]
Hi hi, hier bin ich wieder :) 

Ich habe jetzt versucht mit Orientierung an L09_Classes meine Elemente beweglich zu machen durch 1. setIntervall 
<img width="706" alt="Bildschirmfoto 2020-07-28 um 11 59 53" src="https://user-images.githubusercontent.com/48830827/88651349-dc39c980-d0c9-11ea-9c8d-e15c288085db.png">
und die zugehörige Funktion Update: 
<img width="648" alt="Bildschirmfoto 2020-07-28 um 12 02 00" src="https://user-images.githubusercontent.com/48830827/88651624-291da000-d0ca-11ea-8501-0bd7d64dd56e.png">

Wenn ich in die Konsole gucke, läuft Update quasi unendlich lange weiter mit der Fehlermeldung 
<img width="1440" alt="Bildschirmfoto 2020-07-28 um 11 58 19" src="https://user-images.githubusercontent.com/48830827/88651716-42265100-d0ca-11ea-9e5d-7490470f8237.png">

Wie kann ich diesen Fehler beheben? 

LG 

Repository: https://github.com/beliema/beliema.github.io/tree/master/Semester2/EIA2Abschluss
Link: https://beliema.github.io/Semester2/EIA2Abschluss/zauberbild.html

**Comment by KohlerAl** [comment]
Hi, der Fehler kommt, weil backgroundImage undefined ist. Der Variablen wird nämlich nie ein Wert zugewiesen.

**Comment by beliema** [comment]
ich habe ja oben let backgroundImage = ImageData 
das heißt ich muss ImageData noch einen Wert zuweisen?

**Comment by AionixX** [comment]
Hi, du hast oben stehen `let backgroundImage: ImageData`. Das bedeutet nur das du eine Variable namens `backgroundImage` erstellt hast welche vom Typ `ImageData` ist. Du musst nach dem du das Hintergrundbild das erste mal generiert hast, dieser Variablen auch dein Hintergrundbild zuweisen, dann sollte es funktionieren.

**Comment by KohlerAl** [comment]
Bevor du putImageData verwenden kannst musst du getImageData verwenden, um der Variablen einen Wert zu geben. Du kannst der Variablen aber erst einen Wert geben, wenn der Hintergrund gezeichnet ist, weil du mit der Variablen ja den Hintergrund speicherst

**Comment by beliema** [comment]
habe jetzt wie erklärt nach der Funktion backgroundcolor/nach 1.Generierung des Hintergrundbildes das Hintergrundbild. zugewiesen 
<img width="833" alt="Bildschirmfoto 2020-07-28 um 13 43 26" src="https://user-images.githubusercontent.com/48830827/88661149-56714a80-d0d8-11ea-88fe-fc5b53c24d20.png"> 
aber der Fehler bleibt und wird weiter in der Konsole angezeigt

**Comment by beliema** [comment]
meintet ihr das? oder war das auf was anderes bezogen?

**Comment by AionixX** [comment]
Ja das ist richtig, dein Problem jetzt ist aber das `backgroundImage = crc2.getImageData(0, 0, canvas.width, canvas.height);` nur aufgerufen wird wenn du dein Hintergrund änderst, da du das in deiner `change` Methode aufrufst. Du musst noch beim Start dafür sorgen dass `backgroundImage` nicht `undefined` ist.

**Comment by beliema** [comment]
ich dachte ich kann der Variablen erst einen Wert geben, wenn ich meinen Hintergrund gezeichnet habe? 
Meinst du mit Start der Start vom Programm allg oder von der Funktion drawbackground?

**Comment by AionixX** [comment]
Ja du kannst ihr erst einen Wert geben wenn du den Hintergrund das erste mal zeichnest. Aber du startest beim laden der Seite ein Intervall welches alle 100 Millisekunden aufgerufen wird. In dieser Update Funktion versucht er auf dein `backgroundImage` zuzugreifen welches aber erst existiert wenn du das erste mal deinen Hintergrund änderst.

Jetzt hast du 2 Möglichkeiten:

1. Du erstellst beim laden deiner Seite einfach irgendein Hintergrund damit die Variable nicht `undefined` ist oder
2. Du frägst ab ob in deiner `update`-Methode `backgroundImage` einen Wert besitzt und führst den entsprechenden Code auch nur dann aus

**Comment by beliema** [comment]
Ich habe jetzt einen Background am Anfang erstellen lassen und daraufhin ist auch die Fehlermeldung in der Konsole weggegangen, allerdings bewegt sich immer noch nichts in meinem Canvas. Was kann ich noch probieren?

**Comment by JirkaDellOro** [comment]
Machst Du hier weiter @AionixX ?

**Comment by AionixX** [comment]
Hi, Ich habe mir gerade mal deinen Code angeschaut. In deiner `move` Funktion holst du dir eine Kopie deiner `velocity` , damit willst du dann deinen neuen `offset` berechnen.  Das Problemen daran ist aber das du deine `velocity` niemals veränderst und sie somit immer `x = 0 & y = 0` ist. Und irgendwas mal 0 ist immer 0. Wenn du dir zu Testzwecken eine Kopie der `position` holst und damit den neuen offset berechnest siehst du das sich sie Symbole bewegen.

**Comment by beliema** [comment]
also verstehe ich richtig, dass ich in meiner Shape-Klasse in der Move-Funktion folgendes schreiben soll: 

   public move(_timeslice: number): void {
            
            let offset: Vector = new Vector(200, 70); //meintest du hier die position eintragen? 
            offset.scale(_timeslice);
            this.position.add(offset);

            if (this.position.x < 0)
            this.position.x += (crc2.canvas.width);
            if (this.position.y < 0)
                this.position.y += crc2.canvas.height;
            if (this.position.x > (crc2.canvas.width))
                this.position.x -= (crc2.canvas.width);
            if (this.position.y > crc2.canvas.height)
                this.position.y -= crc2.canvas.height;
        }

oder welche move Funktion meinst du?

**Comment by AionixX** [comment]
Der Code den du jetzt gepostet hast ist in Ordnung, jedoch hast du in all deinen Unterklassen eine eigene `move` Funktion. Diese Funktionen überschreiben die Funktion in `Shape`. Wenn du das was du hier geschrieben hast in deine Unterklassen packst sollte es auch funktionieren.

**Comment by beliema** [comment]
Okay, habe das in meine Subklassen gepackt, aber es bewegt sich immer noch nichts 😅

**Comment by beliema** [comment]
habe es mittlerweile auch in ein neues Repository angelegt: https://github.com/beliema/EIA2Abschlussaufgabe

**Comment by JirkaDellOro** [comment]
Bitte publiziere das auch auf Pages und schicke immer einen Link auf die Client-App mit.

**Comment by beliema** [comment]
Link zur App: https://beliema.github.io/EIA2Abschlussaufgabe/Client/zauberbild.html
Pages: https://beliema.github.io/EIA2Abschlussaufgabe/

**Comment by AionixX** [comment]
Also bei mir geht es wenn ich die watch anmache. Ist es bei dir an?

**Comment by beliema** [comment]
Okay, hat geklappt! Vielen Dank! :)
