### ISSUE TITLE
Ladereihenfolge 

### ISSUE THREAD

**Issue by elenajenny** [JirkaDellOro/EIA2-Inverted#202]
Hallo!
Ich habe ein Problem mit meiner handleLoad Funktion. Der Eventlistener von Color zeigt das Problem "cannot read property addEventListener of null" an. Ich habe etwas recherchiert dazu und es scheint etwas mit der Ladereihenfolge nicht zu stimmen ich finde aber nicht den Fehler. Außerdem zeigt es mir den gleichen Fehler an wenn ich direkt document.querySelector... erstelle und nicht davor noch extra eine Variable deklariere. 
Was mache ich falsch?
https://github.com/elenajenny/EIA2/tree/master/Abschlussarbeit/Code

Danke schonmal im Vorraus

**Comment by AnnaLotz** [comment]
Versuche mal, in deiner html erst die Klassen und dann die Main zu verlinken.

**Comment by AnnaLotz** [comment]
Ansonsten würde ich noch versuchen, dass HTML-Element genauer zu beschreiben, also als HTMLButtonElement.

**Comment by elenajenny** [comment]
Habe das beides ausprobiert. 
Ich verstehe gerade gar nichts mehr, bei mir wird alles rot angezeigt und ich weiß wirklich nicht woran das liegt. Daher dass etwas an den Funktionsaufrufen ist, wird auch keine Funktion aufgerufen... Ich weiß grade echt nicht wie ich dann weitermachen soll.

**Comment by AnnaLotz** [comment]
Poste bitte mal den Link zur ausführbaren Pages-Seite, dann kann ich mir die errors direkt selber anschauen!

**Comment by elenajenny** [comment]
https://elenajenny.github.io/EIA2/Abschlussarbeit/Code/index.html

**Comment by JirkaDellOro** [comment]
Der Fehler wird bei mir in einer auskommentierten Zeile geworfen. Das deutet darauf hin, dass Du gar nicht kompiliert hast... ?

**Comment by elenajenny** [comment]
Hm okay komisch ich habe den eigentlich immer an. Habe jetzt nochmal aktualisiert und nochmal gepusht aber das Problem besteht noch also ich kann in handleLoad die einzelnen Elemente mit document.querySelector selektieren, was ich bereits öfter schon so gemacht haube aber es wird immer der Fehler object is possibly null angezeigt und ich nicht weiß warum der Fehler jetzt auf einmal auftaucht...

**Comment by elenajenny** [comment]
Ich habs gelöst bekommen

**Comment by JirkaDellOro** [comment]
Was war das Problem, was die Lösung?

**Comment by elenajenny** [comment]
Das Problem ist, dass ich immer eine Variable deklarieren muss und dann erst dort den EventListener draufsetzen kann. Ich habe zuerst die Ladereihenfolge geändert, damit sind ein paar Fehler verschwunden aber das mit den Variablen in handleLoad hat sich nicht verändert.

**Comment by JirkaDellOro** [comment]
Ich habe gerade getestet und es wurde zumindest auf der Konsole kein Fehler angezeigt. Mach' gerne einen neuen Issue auf, wenn Du das Problem besser umreißen kannst.
