### ISSUE TITLE
Server Fehler (?)

### ISSUE THREAD

**Issue by k-poschmann** [JirkaDellOro/EIA2-Inverted#203]
Hallo :)
Ich habe mich heute daran gesetzt mich mit dem Server und der Datenbank zu verbinden. Laut Heroku besteht die Verbindung auch, allerdings wird mir dieser Fehler angezeigt :

![Bildschirmfoto 2020-07-28 um 14 25 30](https://user-images.githubusercontent.com/56409026/88667283-75280f00-d0e1-11ea-8bfd-cd61ef677127.png)

Bin etwas ratlos was es sein könnte, weil auf der Zeile in meiner TS Datei nichts mit export steht 

Danke schon mal voraus :)
Kristin

https://github.com/k-poschmann/poschmannEia2/tree/master/Aufgaben/Abschlussaufgabe_Zauberbild/Server

**Comment by MarkusDamm** [comment]
Hallo Kristin,
um da besser drauf antworten zu können bräuchte ich noch paar Infos. Wie stellst du eine Verbindung vom Client zum Server her? Auf welcher Seite wird dir der Fehler angezeigt? Und hast du auf Heroku schon den Server eingerichtet?

**Comment by k-poschmann** [comment]
da liegt wahrscheinlich der Fehler...ich bin gerade die Lektionen nochmal durchgegangen und die url zum heroku server fehlt. Der Fehler wird mir im Browser angezeigt (wenn du das meinst?) In der Server.ts wird mir nämlich kein Fehler angezeigt diesbezüglich.

**Comment by MarkusDamm** [comment]
Genau, der Fehler wird dir ausgegeben, weil du das Server-Script in der index.html angegeben hast. Damit würdest du sozusagen versuchen, dein Browserfenster als Client und Server zu benutzen – geht natürlich nach hinten los.

Das Server-Script sollte nur von Heroku ausgeführt werden, und dafür sorgst du schon in der package.json. Dass Anfragen an den Server gesendet werden, sollte aber dein Client-Script übernehmen.

**Comment by k-poschmann** [comment]
Ahhh alles klar! Vielen Dank :D
