### ISSUE TITLE
Aufgabenstellung

### ISSUE THREAD

**Issue by maxbuchwald** [JirkaDellOro/EIA2-Inverted#204]
Hallo zusammen, 

verstehe ich die Aufgabenstellung richtig, dass einer dieser drei Punkte erfüllt werden soll? Also reicht es zum Beispiel aus wenn meine Symbole nachträglich gelöscht werden können? 

"Bereits platzierte Symbole können nachträglich verändert, verschoben oder gelöscht werden."

Grüße 
Max

**Comment by LukasBlea** [comment]
Alle der genannten Funktionen sollen durch den Nutzer getätigt werden können! 
Also in der Besprechung über die Endabgabe wurde nicht spezifisch danach gefragt, aber ich bin mir zu 99% sicher, dass das so gemeint ist. Er soll also Symbole nachträglich verändern, verschieben und löschen können.

Beste Grüße
Lukas Blea

**Comment by JirkaDellOro** [comment]
Lukas hat Recht. Und Max hat auf eine sprachliche Unzulänglichkeit hingewiesen, die ich jetzt korrigiert habe.
