### ISSUE TITLE
Fehlermeldung zu Server Datei

### ISSUE THREAD

**Issue by maxbuchwald** [JirkaDellOro/EIA2-Inverted#205]
Hallo zusammen,

Bekomme folgenden Fehler in der Konsole. Eine Mongodb Datenbank habe ich bereits angelegt und so wie ich es verstehe sollte auch eine Verbindung dazu bestehen. 

![image](https://user-images.githubusercontent.com/32566080/88798641-7cb0ec00-d1a5-11ea-9315-e7cd2482e6e2.png)

Aus dem Fehler kann ich lesen, dass ich die Daten für die Partikel (name, position, size)  in ein Interface, mit einem Key und Value übertragen muss. Bin ich da auf dem richtigen Weg? 

Außerdem möchte ich die Größe von dem Canvas von dem Nutzer in der Datenbank speichern lassen. Sollten diese Daten in dem gleichen Interface gespeichert werden? 

https://github.com/maxbuchwald/EIA2/tree/master/Endabgabe

Danke & Grüße 
Max

**Comment by JirkaDellOro** [comment]
Ich denke, der Verdacht mit dem Interface geht in die richtige Richtung. URLSearchParams braucht bestimmte Typen von Parametern, ein einfaches Array ist nicht dabei. Siehe: https://developer.mozilla.org/de/docs/Web/API/URLSearchParams/URLSearchParams
Mit FormData ist es einfach, aber Du kannst den Query-String natürlich auch selbst zusammenbasteln. Du bist nicht auf URLSearchParams angewiesen.

Die Größe dann mit dem Bild zu speichern erscheint sinnvoll.

Grundsätzlich:
- erstelle für jedes Problem einen eigenen Issue, sonst wird eine Diskussion unübersichtlich
- poste immer einen Link auf die App
