### ISSUE TITLE
failed to fetch

### ISSUE THREAD

**Issue by FrankeSa** [JirkaDellOro/EIA2-Inverted#207]
Hallo,

ich habe gerade den Server implementiert und habe auch schon den HerokuPfad in das Skript eingebunden. Und zeitweise hat es funktioniert, dass mir im Alert meine ausgewählten Daten angezeigt wurden. Jetzt...nach Neustart von VSC und der Index-Seite... wird mir in der Console folgendes ausgegeben. 
![image](https://user-images.githubusercontent.com/56167839/88821855-70d42280-d1c3-11ea-8cb8-11415e0aa4fb.png)
Auch die App in Heroku lässt sich nicht öffnen. Ich bekomme folgende Meldung:
![image](https://user-images.githubusercontent.com/56167839/88821942-88aba680-d1c3-11ea-9af9-1a7b6d404ce0.png)

Woran liegt das? 
Link zum Repo: https://github.com/FrankeSa/EIA2_Abschlussarbeit
Die Zauberbild-Datei liegt im Ordner Main.

**Comment by JirkaDellOro** [comment]
Hast Du einmal die Logs gecheckt? Ist der Build in die Hose gegangen?

**Comment by FrankeSa** [comment]
Der Build funktionierte. Es hat mir angezeigt. -> Build succeded! 
Ich starte meinen lokalen Server, dann drücke ich in Heroku auf Deploy Branch und dann kommt im log das
![image](https://user-images.githubusercontent.com/56167839/88844342-cb30ab80-d1e2-11ea-86c2-5dc8753b5650.png)
![image](https://user-images.githubusercontent.com/56167839/88844448-f74c2c80-d1e2-11ea-9b5e-de1cc32b9fd1.png)
![image](https://user-images.githubusercontent.com/56167839/88844474-00d59480-d1e3-11ea-9c14-690897c0a5f1.png)
Und wenn ich dann in meiner Anwendung auf Bild speichern drücke, kommt eben die Consolen Meldung...

**Comment by JirkaDellOro** [comment]
Du scheinst noch den port 5001 ansprechen zu wollen. Heroku aber besteht darauf, dir einen Port mitzuteilen durch `process.env`

**Comment by FrankeSa** [comment]
Hmm..ok. Heißt das, ich soll die Zeile mit port = 5001 auskommentieren? Wenn ich das mache, dann findet er aber keinen port mehr
   if (port == undefined)
        //port = 5001; -> auskommentieren?

Oder welche Code-Zeile muss ich rausschmeißen? Was mich auch stutzig macht ist, dass er mir in der Console was mit CORS policy ausgibt. Dieser Mechanismus hast du in den Videos erklärt und ich hab ihn dann auch so ausgeschaltet!? Kann es vtl. damit zusammen hängen?

**Comment by JirkaDellOro** [comment]
Schau nochmal in meinen Code. Da wird gewählt zwischen den Ports.

**Comment by FrankeSa** [comment]
Ich hab schon den Code verglichen. Hab aber nicht die Stelle gefunden wo du meinst... vielleicht sehe ich den Wald voller Bäume nicht. Aber es ist nicht die Zeile wo man fragt if == undefined usw.? 

Welche stelle meinst du?

**Comment by FrankeSa** [comment]
Also ich habe gerade nochmal verschieden Varianten getestet. Zuerst habe ich nochmal deinen Code mit meinem Verglichen. Dann habe ich die Abfrage nach den Ports auskommentiert, aber dann wird mir der port in startServer rot unterstrichen.
![image](https://user-images.githubusercontent.com/56167839/89010130-480c7400-d30e-11ea-98fa-5b2a421dea9d.png)
Ich habe die Consolenausgabe mit "SErver starting on Port..." auskommentiert. was mich aber wundert ist, dass es mir in Heroku im View Logs dieser Befehl trotzdem angezeigt wird. Obwohl ich die aktuelle Version meiner Datei ohne die Ausgabe in mein Repo gepusht habe. Folgende Fragen:

- Warum zeigt es mir immer noch die Consolenausgabe an?
- Wird da was nicht aktualisiert? 
- Heroku ist ja jetzt unser externer Server d.h. ich muss meinen Server lokal nicht auch laufen lassen, oder?
![image](https://user-images.githubusercontent.com/56167839/89010817-9bcb8d00-d30f-11ea-87e6-27554e5f51aa.png)
![image](https://user-images.githubusercontent.com/56167839/89010858-adad3000-d30f-11ea-80a7-0daa53f9160d.png)

- Hab ich irgend einen Schritt übersehen...?

**Comment by JirkaDellOro** [comment]
Den Fallback auf 5001 solltest Du ruhig drin lassen, dann kann port wenigstens nie `undefined` sein und TypeScript wird dich nicht anmeckern.

Hast Du die Zeilen wirklich genau und gewissenhaft verglichen? Versuch's nochmal...

**Comment by FrankeSa** [comment]
Luzia hat mir einen hilfreichen Hinweis gegeben. Ich hatte eine CodeZeile in der falschen Reihenfolge. Ich habe den Code noch paar Mal angeschaut aber nichts abweichendes sonst noch gefunden. Leider klappt es immer noch nicht.  Ich habe die Fehlermeldungen mal aufgeklappt. Vlt. hilft das?
![image](https://user-images.githubusercontent.com/56167839/89066860-791c9100-d36e-11ea-9653-9d42289219bf.png)

**Comment by JirkaDellOro** [comment]
Dann löse ich auf:
`process.env.Port`
vs
`process.env.PORT`

**Comment by JirkaDellOro** [comment]
Hat es sich erledigt? -> close

**Comment by FrankeSa** [comment]
Ja! Das hatte ich die ganze Zeit übersehen! Furchtbar...

Danke für die Auflösung, jetzt funktioniert es :)
