### ISSUE TITLE
Import des HTMLs aus externer Typescript Datei funktioniert nicht 

### ISSUE THREAD

**Issue by ivenios** [JirkaDellOro/EIA2-Inverted#208]
Ich bin gerade dabei meine Endabgabe komplett dynamisch aufbauen zu lassen, doch scheitert es gerade irgendwie an den einfachsten Sachen. 
Ich habe ein Assoziatives Array in einer externen HTMLData Datei liegen. Dieses soll dann von der Client.ts importiert werden und in die Index geschrieben werden. Doch wirft die Konsole dann diesen Fehler aus: 
_"ReferenceError: Can't find variable: exports
_Globaler Code — client.js:2_
_Globaler Code — HTMLData.ts:9"__  ->Wieso Verwendet der browser hier aufeinmal die ts Datei? 

In Beiden Dateien wird der Error von dieser Zeile ausgelöst:` Object.defineProperty(exports, "__esModule", { value: true }); ` die nach dem Compiling auftaucht. 

Ich habe es auch noch mit einer normalen "helpMe" Funktion versucht, da ich erst dachte, das A.Arrays nicht exportiert werden können, geht aber auch nicht. 

Woran könnte dies liegen?
Vielen Dank schon einmal für eure Hilfe. 

Hier die Links: 
Test index.html: [Click here](https://ivenios.github.io/EIA2/01_Endabgabe_v2/index.html)
repo: [Click here](https://github.com/ivenios/EIA2/tree/master/01_Endabgabe_v2) 
client ts: [Click here](https://github.com/ivenios/EIA2/blob/master/01_Endabgabe_v2/2_Programm/JS/client.ts)
HTMLData.ts:[click here](https://github.com/ivenios/EIA2/blob/master/01_Endabgabe_v2/2_Programm/JS/HTMLData.ts)

**Comment by ivenios** [comment]
Ich könnte das a.Array natürlich auch in der client.ts speichern, fand das aber nicht so schön. Wenn da so viel Text am Anfang klebt.

**Comment by AionixX** [comment]
Das `export` Statement funktioniert nur wenn beide Dateien im gleichen namespace liegen. Wenn du also einfach deinen Code in einen namespace packst sollte es funktionieren.

**Comment by ivenios** [comment]
Ah oke, danke. Den hatte ich zum Testen wieder rausgenommen, vielleicht hatte ich mich da vertippt. Ich probiere es gleich.

**Comment by ivenios** [comment]
So jetzt. 
Wenn ich beide in den gleichen namespace packe wirft der Linter mir bei dem Import `import { htmlData } from "./HTMLData";` den Error "Import declarations in a namespace cannot reference a module." aus.

Oder habe ich gerade die Falsche import Funktion genommen.

**Comment by AionixX** [comment]
Wenn sie im gleichen namespace sind brauchst du die `import` Funktion gar nicht mehr. Solange du deinen code, auf den du von überall zugreifen möchtest, mit `export` deklarierst reicht das.

**Comment by ivenios** [comment]
oooh well. Dankeschön ^^
