### ISSUE TITLE
 Drag & Drop Symbole duplizieren sich 

### ISSUE THREAD

**Issue by luziagu** [JirkaDellOro/EIA2-Inverted#209]
Hallöchen, 

nochmal kurz wegen dem Drag & Drop. Mir ist grade aufgefallen, dass sich meine Symbole nur in einem kleinen Teil des Canvas verschieben lassen. Außerhalb dieses Bereiches publizieren sie sich. Ich hab jetzt ein bisschen versucht herauszufinden woran das liegt und dachte erst das es vielleicht sein kann, dass der Canvas sich gar nicht vergrößert oder die Höhe und Breite sich in der Funktion dragSymbol nicht an die Canvas Größe anpassen. Das erste konnte ich ausschließen, aber bei dem zweiten bin ich mir noch etwas unsicher. 
Woran könnte es noch liegen und wie kann ich das Problem lösen? 

Gruß, Luzia :) 

https://luziagu.github.io/Abschlussarbeit_SOSE2020/zauberbild.html
Das Bild verdeutlicht vielleicht  noch einmal besser das Problem. Oben Rechts der Bereich in dem es wunderbar klappt. Unten wird allerdings dupliziert. 

<img width="674" alt="Bildschirmfoto 2020-07-30 um 14 25 09" src="https://user-images.githubusercontent.com/56430460/88922484-7a679400-d270-11ea-92d3-0abe00533683.png">

**Comment by JirkaDellOro** [comment]
Ich schätze, dass Du dir am Anfang einmal den Hintergrund zum Übermalen holst, und den dann nicht mehr neu anlegst, wenn Du die Canvasgröße änderst. Dann malst Du immer einen zu kleinen Hintergrund auf ein zu großes Bild.

**Comment by luziagu** [comment]
Ah ja genau, jetzt funktioniert es. Danke!!
