### ISSUE TITLE
 L01_V1_Tracetables_041019.mp4 Problem

### ISSUE THREAD

**Issue by TobMer** [JirkaDellOro/EIA2-Inverted#21]
Hey,

ich habe ein Problem mit dem oben genannten Lehrvideo (die anderen auch).
Und zwar öffnet sich das Fenster zum Video aber es zeigt nur diesen Ladebalken aber es lädt das Video nicht. Ich habe auch schon die Internetverbindung getestet aber es will einfach nicht laden. Schade, da ich gern den Inhalt anschauen wollte.

Ich hab ein Windows Rechner (recht neu) ,falls das hilft.
Vielen Dank.

**Comment by JirkaDellOro** [comment]
Ho,

ich kann leider das Problem nicht nachvollziehen, es scheint alles korrekt zu funktionieren. Wie schaust Du dir den die Lektionen an? Vier Wege drängen sich auf:

1. auf Github-Pages: bevorzugt wenn online
1. im Github-Repository: auch ok wenn online, aber nicht ganz so hübsch
1. lokal den Klon mit einem Markdown-Viewer: sehr gut wenn offline
1. lokal den Klon in VSCode: ok unter Nutzung des Previews (Ctrl+K, V) wenn offline

Da die Videos aber derzeit sich in eine GoogleDrive befinden, ist ohnehin eine Online-Verbindung erforderlich. Ich empfehle Zugang 1.

**Comment by Plagiatus** [comment]
Heyho,

Das kenne ich. Die Videos werden auf GDrive nur abgespielt, wenn man Drittanbieter-cookies (bzw google cookies allgemein) nicht blockiert. Es liegt also eventuell an deinen Browsereinstellungen.

Außerdem hat GDrive ein Ratelimit, wo es nach X Downloads erstmal für 24h den Download verweigert bis wieder Kontingente verfügbar sind. Das könnte auch sein dass das passiert ist.

(Bei mir läuft das Video im Moment)

**Comment by TobMer** [comment]
Danke hat dann funktioniert als ich die Cookies Funktion auf erlauben gestellt habe.
Jetzt laufen die Videos super.

**Comment by JirkaDellOro** [comment]
Schließen wenn fertig!
