### ISSUE TITLE
Zeitpunkt der Abgabe des Konzepts/Code's

### ISSUE THREAD

**Issue by LukasBlea** [JirkaDellOro/EIA2-Inverted#210]
Guten Morgen an alle,

hier eine schnelle Frage: Bis wann müssen wir alles nochmal hochgeladen haben? Ich weiß nicht ob das die richtige Stelle ist um nachzufragen und bitte um Entschuldigung, falls dieser Issue als unnötig erscheint. Ich möchte mir nur 100% bewusst und sicher sein, wann die offizielle Deadline ist.

Beste Grüße
Lukas Blea

**Comment by JirkaDellOro** [comment]
Das ist der falsche Ort, der richtige ist das Veranstaltungsforum im Intranet, da steht auch alles.
