### ISSUE TITLE
Übermittlung der Daten meiner Objekte an ein (Assoziatives) Array

### ISSUE THREAD

**Issue by LukasBlea** [JirkaDellOro/EIA2-Inverted#211]
Guten morgen an alle,

ich stoße momentan auf ein Problem bei dem ich mir nicht ganz sicher bin, wie ich es lösen soll. 

Wenn der Benutzer auf "Save Canvas" drückt, bzw wenn die Daten der Objekte, welche sich wie & wo auf dem Canvas befinden, an die Datenbank weitergeleitet werden sollen: Wie schaffe ich das am besten?

Ich habe mir überlegt, dass ich die Arrays meiner Objekte (momentan noch: Circle, Triangle, Heart) durchiteriere (mit einer klassischen "for"-loop) und jeweils die positionen, verlocity und größe meiner Objekte, in einem neuen Array abspeichere. 

Jetzt meine meine eigentliche Frage: Assoziative Arrays. 
Ich nehme an, dass dies der richtige Ansatz ist. Jetzt weiß ich allerdings nicht, wie ich dieses Array gestalten soll, dass es die Daten problemlos übernimmt, bzw. wie kann ich diese Objekteigenschaften an das Array weiterleiten? 

Dazu finde ich überraschend wenig im Internet und ich komme mir irgendwie blöd vor, weil ich das früher noch alles gut wusste aber mittlerweile ist dieses Thema sehr verschwommen bei mir. Ich habe auch schon bei den Lektionen im EIA2-Inverted Classroom nachgeschaut aber finde da keine schlüssige Erklärung die mir die Übertragung auf mein eigenes Projekt ermöglicht.

Ich habe diese gesamte - und vorherige Woche schon sehr viel Programmiert und bin immer auf eine Lösung gekommen, allerdings mache ich jetzt schon zwei Tagen an der Prolematik herum und dachte mir "Jetzt reichts, ich poste einen Issue".

Vielen Dank schonmal im vorraus für die möglichen Lösungsansätze und Tipps!

EDIT: Hier die Page zu meiner bisherigen Anwendung: https://lukasblea.github.io/Endabgabe/Endabgabe.html
EDIT 2: Und hier zu meiner Repo: https://github.com/LukasBlea/Endabgabe

Beste Grüße
Lukas Blea

**Comment by LukasBlea** [comment]
Update:

Ich pushe nun alle meine Objekte auf dem Canvas in ein einzelnes Array, welches alle Werte von all meinen Objekten kennt. 

Jetzt liegt es wirklich nur noch daran, diese Informationen dem Server weiterzuleiten. Ich lasse den Issue noch offen, falls es Kommentierbedarf gibt. Ansonsten wurde das Problem beseitigt und somit auch meine Frage beantwortet.

**Comment by JirkaDellOro** [comment]
Ich schaue mir das gern einmal an, kann es aber im aktuellen Code nicht finden....

**Comment by LukasBlea** [comment]
Entschuldigen Sie Herr DellOro, mir wurde nicht angezeigt, dass auf diesem Issue eine Antwort gepostet wurde!
Gerne erkläre ich ihnen mein Problem nochmal in meiner Vorstellung der Anwendung und wie ich es gelöst habe.

Beste Grüße
Lukas Blea

**Comment by JirkaDellOro** [comment]
Wenn Du keinen Bedarf hast ist das für mich vorteilhaft.
