### ISSUE TITLE
Symbole werden nicht richtig dargestellt

### ISSUE THREAD

**Issue by klinkewitzn** [JirkaDellOro/EIA2-Inverted#212]
Hallo, meine Symbole werden größer, verzerrt und alle an der selben Stelle dargestellt.
(Zum Zeichnen: Erst Klick auf Symbol, dann Klick auf Haupt-Canvas)

pages: https://klinkewitzn.github.io/EIA2/Abschlussaufgabe/Zauberbild/zauberbild.html
github Link: https://github.com/klinkewitzn/EIA2/tree/master/Abschlussaufgabe/Zauberbild

**Comment by LukasBlea** [comment]
Das mit den Symbolen an der selben Stelle liegt daran, dass du die Position im Code fest codest.

![positionXundY](https://user-images.githubusercontent.com/44029295/89023744-5cf40200-d324-11ea-93cd-0d5aa1c7ed75.PNG)

Hier wäre es sinnvoll, wenn du der Funktion "createSymbols" ein Mouse Event mitgibst und die Varbiable "_event" den Parameter "offsetX" und "offsetY" mitgibst. Diese solltest du dann deiner Variale "positionX" und "positionY" mitgeben, so das bei der Erstellung deines Objektes durch die Klasse "Vektor" nicht z.B. 0 und -10 steht, sondern die eigentliche Position deiner Maus auf dem Canvas.

Also:
1. createSymbols(_event: MouseEvent): void
2. let positionX: number = _event.offsetX & let positionY: number = event_offsetY

PS: Du musst keine variable festlegen, welche die Werte deiner Maus erhalten. Du kannst auch einfach schreiben:

"let position: Vector = new Vector(_event.offsetX, _event.offsetY);"

Hoffe ich konnte dir ein Stückweit helfen!

**Comment by KohlerAl** [comment]
Du musst aber auch bedenken, dass die Mausposition auf window bezogen ist. Du musst also den Abstand von Canvas zu window noch rausrechnen, sonst macht es wahrscheinlich komische Sachen :)

**Comment by klinkewitzn** [comment]
Vielen Dank für deine Antwort Lukas! (und Alida :D )
Die Funktion createSymbols wird ja auch genutzt um die Symbole in die jeweiligen Symbole-Canvas zu zeichnen. Wenn ich  es so ändere wie du geschrieben hast, sieht man die Symbole leider nicht mehr.
Ich habe es trd. ausprobiert mit dem Herz und es wird immer noch immer an die selbe Stelle gezeichnet. 
![symbole-lukas-antwort](https://user-images.githubusercontent.com/56318063/89027188-5c5e6a00-d32a-11ea-98db-4e9d6a9f56e6.PNG)

**Comment by JirkaDellOro** [comment]
Eine ganz grundsätzliche Zwischenfrage: warum eine Schleife um genau 1 Element zu erzeugen??

**Comment by KohlerAl** [comment]
Es funktioniert wahrscheinlich nicht, weil die Mausposition viel zu groß ist. Und den Symbolen für die kleinen Canvas würde ich weiterhin eine Position mitgeben, die soll man ja nicht bewegen können. 
Was mich grade noch verwirrt sind die Variablen positionX und positionY, wofür brauchst du die wenn du den Vektor dann mit den Werten erstellst, die du auch den Variablen zugewiesen hast?

**Comment by klinkewitzn** [comment]
Ich habe die Schleifen jetzt herausgenommen. Hatte da einen Denkfehler.
![symbole-lukas-antwort2c](https://user-images.githubusercontent.com/56318063/89036932-ed8b0c00-d33d-11ea-930a-fdee718eee2f.PNG)
Die Mausposition sollte ja eigentlich für den Canvas  _event.offsetX & _event.offsetY sein....das müsste ja stimmen. Ich habe gerade mal zum Spaß irgendwelche anderen Werte eingegeben und die Elemente werden trd. immer genau an der gleichen Stelle im Zeichen/Haupt-Canvas positioniert.

**Comment by klinkewitzn** [comment]
Ich habe mir die _events in der Konsole ausgeben lassen und da sieht man auf jeden Fall, dass die Mausposition im Canvas erkannt wird. Sie scheint nur ca. 200px in x und y Richtung verschoben zu sein :/ 
![symbole-lukas-antwort2d](https://user-images.githubusercontent.com/56318063/89038611-f92c0200-d340-11ea-927e-06c3ad0ed9ae.PNG)
...

**Comment by KohlerAl** [comment]
Das ist das was ich oben geschrieben habe. Die Mausposition wird im ganzen Window gemessen und dein Canvas ist halt nicht ganz oben links. Um den Abstand zwischen window und canvas rauszurechnen, kannst zu zum Beispiel getBoundingClientRect verwenden. 
https://developer.mozilla.org/de/docs/Web/API/Element/getBoundingClientRect

**Comment by JirkaDellOro** [comment]
Du kannst wahrscheinlich auch mit offsetX und offsetY arbeiten, so hatten wir es bereits beim Blackmailer Companion: https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/offsetX

Achtung: experimental technology

**Comment by klinkewitzn** [comment]
Also in der Funktion mit der ich die Symbole auf den Canvas zeichnen lasse (function drawSymbolsOnMainCanvas) arbeite ich bereits mit offsetX und offsetY. Leider funktioniert es anscheinend nicht.

**Comment by JirkaDellOro** [comment]
Könnte browserabhängig sein, mit Alidas Lösung bist Du auf der sicheren Seite.

**Comment by klinkewitzn** [comment]
Also ich habe alles ausprobiert (auch die Methode getBoundingClientRect().left und .top) , aber egal was ich als Positionswert hinschreibe, es ändert sich nichts. Hier auch ein Beispiel mit völlig absurden Werten:
![symbole-lukas-antwort2g](https://user-images.githubusercontent.com/56318063/89047254-78740280-d34e-11ea-9673-a1490f33011e.PNG)
immer noch genau die gleiche position:
![symbole-lukas-antwort2h](https://user-images.githubusercontent.com/56318063/89047315-888be200-d34e-11ea-869c-142fa3cfd787.PNG)

**Comment by KohlerAl** [comment]
Ich bin gerade nochmal mit dem Debugger durch gegangen und in den draw-Methoden deiner Subklassen verschiebst du das Koordinatensystem um feste Werte, nicht um die position der Figur und zeichnest die Figur dann dort hin.

**Comment by JirkaDellOro** [comment]
Also nun habe ich doch mal ein paar Sekunden in deinen Code geschaut und den Eindruck erlangt, dass Du die Position des Sterns beim Zeichnen gar nicht berücksichtigst. Das wäre eine gute Erklärung für das beobachtete Phänomen.

**Comment by klinkewitzn** [comment]
Es klappt es jetzt alles, danke!! :) Ich habe in den Subklassen jetzt nur "translate(this.position.x, this.position.y);" verwendet und wenn ich den canvas für die einzelnen Symbole verschieben wollte habe ich das direkt in der Funktion im Main-Programm gemacht.
