### ISSUE TITLE
Animation der platzierten Symbole funktioniert nicht

### ISSUE THREAD

**Issue by klinkewitzn** [JirkaDellOro/EIA2-Inverted#214]
pages: https://klinkewitzn.github.io/EIA2/Abschlussaufgabe/Zauberbild/zauberbild.html
github Link: https://github.com/klinkewitzn/EIA2/tree/master/Abschlussaufgabe/Zauberbild

Hallo, ich versuche gerade die platzierten Symbole zu bewegen/animieren. Leider klappt es nicht. Der Funktionsaufruf der update-Funktion liegt am Ende von handleLoad. Die platzierten 
Symbole werden auf jeden Fall auch in das symbols-Array hereingepusht.
![update-funktion-issue](https://user-images.githubusercontent.com/56318063/89099946-57192200-d3f3-11ea-838e-74e184b7ea6e.PNG)
![update-funktion-issueb](https://user-images.githubusercontent.com/56318063/89099953-6a2bf200-d3f3-11ea-95ce-19e6e06f64db.PNG)
![update-funktion-issuec](https://user-images.githubusercontent.com/56318063/89099960-7021d300-d3f3-11ea-906d-ef7c39998296.PNG)
![update-funktion-issued](https://user-images.githubusercontent.com/56318063/89099961-731cc380-d3f3-11ea-99eb-68eae5aa074f.PNG)

**Comment by JirkaDellOro** [comment]
Du rufst in `update` die Methode `draw` gar nicht auf! In deinem Screenshot oben fehlt sie ganz und in deinem aktuellen Code wird ist nur der Verweis auf die Funktion zu sehen. Ein Aufruf benötigt immer die Parameterklammern...

**Comment by klinkewitzn** [comment]
Ja, es waren die Parameterklammern, die gefehlt haben. Jetzt funktioniert es. Danke Jirka!
