### ISSUE TITLE
crc2.Rotate( ) 

### ISSUE THREAD

**Issue by smo-haenle** [JirkaDellOro/EIA2-Inverted#215]
Guten Abend,

ich habe Probleme dabei meine Formen rotieren zu lassen. 
Der Plan war es einen Galaxysimulator zu bauen. Dafür sollten die Planeten um den Mittelpunkt des Canvas kreisen (am besten langsamer als jetzt). 
Die Planeten rotieren zwar um den Mittelpunkt, jedoch werden diese immer schneller um so mehr Objekte man setzt und diese Objekte werden dann von den Planeten mitgerissen (auch wenn sie davor gesetzt wurden). Ich vermute mal dass es an safe()/ restore() liegt.
Ein weiteres Problem ist, dass ich einen Hexgenerator gebaut habe um so die Planeten zufällig zu färben, leider färben diese sich nach jeder Update funktion um. 

Am besten einfach mal selbst testen 😄 
Repo : https://github.com/smo-haenle/Galaxysimulator/tree/master/Endabgabe
Pages : https://smo-haenle.github.io/Galaxysimulator/Endabgabe/Index.html

Ich denke, wenn ich die Planeten hinbekomme, sollten die Sterne das geringste Problem darstellen. 
Schon mal vielen Dank für die Hilfe 👍

**Comment by smo-haenle** [comment]
Ich seh gerade dass Pages noch nicht aktuell ist.

**Comment by JirkaDellOro** [comment]
Wo finden wir dein Konzept? Ohne ergibt es keinen Sinn nach Fehlern zu suchen...

**Comment by smo-haenle** [comment]
Guten Morgen, 

Konzept ist zu Teilen hier: https://github.com/smo-haenle/Galaxysimulator/blob/master/Konzept%20V2.pdf

Hab gestern noch einiges umgeworfen und konnte noch nicht alle Konzepte abändern.

**Comment by JirkaDellOro** [comment]
Dann mach' das erst fertig. Die Konzeption erfolgt immer vor der Produktion, sonst ergibt alles keinen Sinn.

**Comment by smo-haenle** [comment]
closed #215
