### ISSUE TITLE
Symbole werden kopiert, statt verschoben

### ISSUE THREAD

**Issue by klinkewitzn** [JirkaDellOro/EIA2-Inverted#216]
pages: https://klinkewitzn.github.io/EIA2/Abschlussaufgabe/Zauberbild/zauberbild.html
github Link: https://github.com/klinkewitzn/EIA2/tree/master/Abschlussaufgabe/Zauberbild

Hallo noch einmal, ...ich versuche mich seit einer Weile an dem drag&drop.
Das Symbol wird bei mouseup an eine bestimmte Stelle kopiert, das Original bleibt aber...
Auch diese Fehlermeldung erscheint:
![dragdrop1PNG](https://user-images.githubusercontent.com/56318063/89105346-8db96180-d420-11ea-96c7-4c28d3685d84.PNG)

![fehler-meldng2743b](https://user-images.githubusercontent.com/56318063/89105461-9d857580-d421-11ea-9dd2-ab76b5d37390.PNG)

**Comment by JirkaDellOro** [comment]
Woran erkennst Du, dass tatsächlich Drag&Drop geschieht und nicht einfach nur ein weiteres Symbol abgesetzt wird?

**Comment by klinkewitzn** [comment]
Du hast recht, es hatte nichts mit der drag und drop Funktion zu tun. Ich hatte beim herumprobieren einen neuen Fehler eingebaut... Ich habe diesen jetzt berichtigt. Das drag und drop funktioniert leider trotzdem nicht, beziehungsweise habe ich immer noch die selbe Fehlermeldung.

**Comment by JirkaDellOro** [comment]
Ich nehme an, Du meinst immer noch diese hier: 
`main.ts:323 Uncaught TypeError: Cannot read property 'x' of undefined at HTMLCanvasElement.mouseDown (main.ts:323)`
Demnach wird versucht die Eigenschaft x auszulesen, allerdings von etwas Nicht-Definiertem.

Zeile 323 sieht bei dir so aus:
```typescript
   if (symbol.position.x - symbol.radius.x < offsetX &&
```
Also ist wohl entweder position oder radius nicht definiert. Überprüfe dies, Du kannst ja gleich mit dem Debugger reinschauen. Bei der Gelegenheit wundert mich, das `radius` ein zweidimensionaler Vektor sein soll. Das ist ziemlich unintuitiv. Du testest doch gegen eine Hit-Box, nicht gegen einen Kreis. Es wäre übrigens einfacher gegen einen Kreis zu testen, also nur die Nähe zu berechnen. (siehe eiaSteroids)

**Comment by klinkewitzn** [comment]
Also ich habe radius jetzt einfach durch eine feste Zahl ausgetauscht und Vektor als number definiert. Die Fehlermeldung ist weg, trotzdem funktioniert es leider nicht und ich habe keine Idee warum...
![dragdropneu](https://user-images.githubusercontent.com/56318063/89175403-fff88600-d587-11ea-8f77-0d65b5fddaa4.PNG)

**Comment by JirkaDellOro** [comment]
Die aktuelle Version scheint nicht durchkompiliert worden zu sein.
