### ISSUE TITLE
Datenbank local anlegen oder über Heroku?

### ISSUE THREAD

**Issue by beliema** [JirkaDellOro/EIA2-Inverted#217]
Hallo, ich bin gerade dabei meine Datenbank aufzusetzen/bzw zu installieren. Jetzt frage ich mich, on es reicht die Datenbank lokal auf dem Computer zu installieren wie in Lektion 7, oder soll man die Datenbank über einen Online-Provider laufen lassen(Heroku) sodass man auch extern darauf zugreifen kann? 

Liebe Grüße

**Comment by JirkaDellOro** [comment]
Letztlich auf Heroku. Es ist aber natürlich dringend zu empfehlen, alles erst einmal lokal fertig zu machen und erst ganz zum Schluss auf Heroku umzuziehen.

**Comment by beliema** [comment]
Okay alles klar, danke!
