### ISSUE TITLE
Animation von einem Haus

### ISSUE THREAD

**Issue by geibelan** [JirkaDellOro/EIA2-Inverted#218]
Hi,

ich habe unter meinen Symbolen unter anderem ein Haus, dass sich ja eigentlich nicht wirklich bewegt. Soll ich das trotzdem animieren?

MfG,
Anastasia

**Comment by JirkaDellOro** [comment]
Das ist eigentlich dir überlassen. Es kommt ja auch darauf an, ob die Animationen an die Symbole gebunden oder austauschbar sind. Wenn austauschbar, sollte das Haus wie alles andere animiert werden, wenn gebunden könnten vielleicht die Lichter an und ausgehen oder so etwas...
