### ISSUE TITLE
EIA2-Inverted/L01_Recap&Foundation/Material/Hochsprung.webm

### ISSUE THREAD

**Issue by weiberta** [JirkaDellOro/EIA2-Inverted#22]
Beim Öffnen der Datei in VSC, wird kein Video angezeigt. 
Stattdessen kommt ein unverständlicher Code bzw. ein Fehler.

1) <img width="970" alt="1" src="https://user-images.githubusercontent.com/48830856/66557986-1514ac00-eb53-11e9-8296-ddc324d08b6c.png">

2) <img width="793" alt="2" src="https://user-images.githubusercontent.com/48830856/66557987-1514ac00-eb53-11e9-86be-980b1e7dbffa.png">

**Comment by MarkusDamm** [comment]
Versuchst du das Video über Visual Studio Code auszugeben? Wenn du es heruntergeladen hast, dann benutze lieber einen Videoplayer wie VLC um es abzuspielen

**Comment by Plagiatus** [comment]
das ist eine Videodatei. VSC ist ein Code Editor. etwas ähnliches passiert, wenn du versuchst, irgendwas zu öffnen das nicht als reine text datei codiert ist (pdf, mp3, mp4, wav, etc).

Darum sagt dir VSC ja auch extra, dass es die Datei nicht öffnen kann. Dafür wurde es nicht gemacht.

**Comment by weiberta** [comment]
Ich habe es direkt im Ordner geöffnet, dort ging es. Dank!

LG awb.

 

Gesendet: Donnerstag, 10. Oktober 2019 um 12:42 Uhr
Von: "Markus Damm" <notifications@github.com>
An: JirkaDellOro/EIA2-Inverted <EIA2-Inverted@noreply.github.com>
Cc: weiberta <weibert-ang@web.de>, Author <author@noreply.github.com>
Betreff: Re: [JirkaDellOro/EIA2-Inverted] EIA2-Inverted/L01_Recap&Foundation/Material/Hochsprung.webm (#22)


Versuchst du das Video über Visual Studio Code auszugeben? Wenn du es heruntergeladen hast, dann benutze lieber einen Videoplayer wie VLC um es abzuspielen

**Comment by weiberta** [comment]
Danke für die Information, das ist nützlich.

Es hat mich wohl nur verwundert, da sich Bilder in VSC anzeigen lassen.

 

Lg, awb.



Gesendet: Donnerstag, 10. Oktober 2019 um 15:20 Uhr
Von: "Lukas Scheuerle" <notifications@github.com>
An: JirkaDellOro/EIA2-Inverted <EIA2-Inverted@noreply.github.com>
Cc: weiberta <weibert-ang@web.de>, Author <author@noreply.github.com>
Betreff: Re: [JirkaDellOro/EIA2-Inverted] EIA2-Inverted/L01_Recap&Foundation/Material/Hochsprung.webm (#22)


das ist eine Videodatei. VSC ist ein Code Editor. etwas ähnliches passiert, wenn du versuchst, irgendwas zu öffnen das nicht als reine text datei codiert ist (pdf, mp3, mp4, wav, etc).

Darum sagt dir VSC ja auch extra, dass es die Datei nicht öffnen kann. Dafür wurde es nicht gemacht.

**Comment by Plagiatus** [comment]
Ja das stimmt. Bilder sind da eine Ausnahme.

**Comment by JirkaDellOro** [comment]
Wenn geklärt, bitte schließen. Das sollte der Initiator des Posts machen
