### ISSUE TITLE
Move-Animation wird bei Wiederherstellung des Canvas nicht richtig ausgeführt

### ISSUE THREAD

**Issue by Koefe** [JirkaDellOro/EIA2-Inverted#220]
Hey alle zusammen,

also ich hab ein paar Probleme mit meinem Code bei dem ich nicht wirklich weiß wie ich weitermachen soll.

Momentan ist es so, das ich meine Canvas nach einem Button klick aus der Datenbank wieder herstellen kann. Allerdings wird nicht alles richtig hergestellt. Wenn man seine Canvas absichert und man hat z.B. einen Kreis der die Farbe verändert und ein Rechteck das sich bewegt, so wird nach abspeichern und reloading die Objekte erstmals richtig platziert, allerdings bewegen sie sich alle. Ich hab auch schon geschaut an was das liegen könnte. Grundsätzlich scheint es so, als würde mein Code immer denken, dass sich alle Objekte bewegen, obwohl es nur einige tun. (Sieht man wenn man in der Datenbank schaut ob move gleich "true" ist) Wie kann ich das umschreiben das nicht jedes Objekt den string "true" bekommt. Ansonsten kann ich ja nicht differenzieren was sich bewegt und was nicht.
Hab das in einer for Schleife, bzw in einer if Abfrage in einer for schleife drin, in der gefragt wird ob eben das zu rekonstruierende Objekt den string == "true" hat.

Mein zweites Problem ist, dass bei mir das platzieren und gestalten der Objekte zwar funktioniert, allerdings nicht in einem bestimmten Fall:
Wenn man zuvor Objekte gedragged und dann irgendwie anders verändert (Farbregenbogen, moving...) und dann versucht nochmal ein Objekt zu draggen, dann wird es einfach gelöscht. Und ich weiß wirklich nicht warum. Es scheint so als würde es nicht wirklich aus dem array gelöscht, sondern vielmehr einfach nicht mehr dargestellt.

Okay, ich hoffe ich konnte meine Probleme gut beschreiben.
Hier die Links:

App:
https://koefe.github.io/EIA2/Abschlussaufgabe2020/index.html
- > hier wichtig, drückt den einzelnen Radioutton mit dem Label "edit particular shapes". 
Ansonsten lassen sich die Formen nicht anwählen.

Konzept: 
https://github.com/Koefe/EIA2/blob/master/Abschlussaufgabe2020/Konzept/EIA_Konzept.pdf

Repository:
https://github.com/Koefe/EIA2/tree/master/Abschlussaufgabe2020

Jetzt schon vielen Dank für Eure Hilfe!

**Comment by AnnaLotz** [comment]
Das erste Problem scheinst du ja schon gelöst zu haben, das gespeicherte Bild "5circles_2moving" zeigt ja bewegte und unbewegte Objekte.

Das zweite Problem hat seinen Ursprung vermutlich im event selbst. Wenn die Funktion `select `aufgerufen wird, sollte ja eigentlich das Mousevent als `_e `mit gegeben werden. In deiner genannten Situation ist `_e `aber undefined. Woran das liegt habe ich leider noch nicht rausfinden können :/ Was dann passiert, ist das der Kreis an die Stelle vom click gesetzt werden soll. Wenn aber die Position vom Click nicht definiert ist, bekommt der Kreis auch diese undefinierte Stelle, sprich er ist nicht mehr zu sehen. Wenn du die Abfrage `if (_e == undefined) {...}` um den gesamten Code-Block in der Funktion setzt, dann sollte der Kreis wenigstens nicht mehr direkt verschwinden.
