### ISSUE TITLE
draw wird ausgeführt, aber nix ist auf dem Canvas zu sehen

### ISSUE THREAD

**Issue by Cari1512** [JirkaDellOro/EIA2-Inverted#221]
Hallo,

Endaufgabe: https://github.com/Cari1512/EIA2/tree/master/Endabgabe

ich versuche Objekte auf meinem Canvas zu Zeichnen. Ich bin mit dem Debugger durch meinen Code gegangen und die draw() Funktion wird auch mit den richtigen x und y Werten durchgeführt. Plan ist, dass nachdem man in einem Modus ist (bisher nur bei einer Linie), beim ersten klicken auf dem Campus ein Punkt entsteht und beim 2. Klicken ein Punkt und eine Linie zwischen den beiden Punkten. 
![Screenshot (255)](https://user-images.githubusercontent.com/56436935/89125637-32e73f00-d4e0-11ea-9229-8417761673d1.png)

**Comment by JirkaDellOro** [comment]
Poste bitte einen Link zur App

**Comment by Cari1512** [comment]
https://cari1512.github.io/EIA2/Endabgabe/endabgabe.html

**Comment by JirkaDellOro** [comment]
Wo finden wir denn dein Konzept?

**Comment by Cari1512** [comment]
Oh sorry, ich hatte mein Konzept bei mir lokal gespeichert.Habe es jetzt als pdf auf github hochgeladen. Die Classes ADs habe ich bisher noch auf Blattpapier welche ich also noch in drawio zeichnen muss. Genauso die ganzen Server/Database ADs. 

https://github.com/Cari1512/EIA2/blob/master/Endabgabe/Konzept_version1.pdf

**Comment by JirkaDellOro** [comment]
Das Konzept sieht sehr gut aus. Daraus kann ich entnehmen, dass Du immer zwei Punkte als Nutzereingabe anforderst und damit bestimmst, wie genau die zu zeichnende Instanz des gewählten Objekttyps aussehen soll. Korrekt? Das Schema geht also konsequent durch?

**Comment by Cari1512** [comment]
Genau!

**Comment by JirkaDellOro** [comment]
- wo erhält dein Canvas die Senf-Farbe?
- wo wird die Zeichenfarbe und Liniendicke definiert?
- hast Du Canvas-Transformationen in deinem Code, wo?

**Comment by Cari1512** [comment]
Bisher noch in css, Zeichenfarbe und Liniedicke in den Classes, keine Canvas-Transformationsind vorhanden

**Comment by JirkaDellOro** [comment]
Wo genau Zeichenfarbe und Liniendicke? Ich konnte nämlich beim schnellen Durchschauen auch keinen Fehler finden, daher möchte ich zunächst ausschließen, dass vielleicht alles gezeichnet wird aber an die falsche Stelle oder transparent...

**Comment by Cari1512** [comment]
![grafik](https://user-images.githubusercontent.com/56436935/89216528-d876dd00-d5ca-11ea-9bec-13bb74c2cd8e.png)

**Comment by JirkaDellOro** [comment]
Die kommen da allerdings nach den Strokes.

**Comment by Cari1512** [comment]
Ich habe das mal vor den strokes geschoben, aber leider funktiert das nicht.

**Comment by JirkaDellOro** [comment]
Versuche mal einfach auf Mausklick irgendwas auf deinen Canvas zu malen, ohne große weiterführende Struktur. Vielleicht findest Du dann deinen Fehler. Ich kann ihn auf die Schnelle nicht sehen und müsste ansonsten heute Abend noch eine Online-Session mit dir machen.

**Comment by JirkaDellOro** [comment]
So viel habe ich aber eben noch erkannt: es ist ein Positionsproblem. Mach' mal das Fenster ganz klein und zeichne dann in die linke obere Ecke deines Canvas....

Die Mauskoordinaten sind auf die Fensterecke bezogen, Du musst sie noch auf Canvaskoordinaten umrechnen. Siehe dazu den Blackmailer Companion oder eiaSteroids
