### ISSUE TITLE
glowing und rotating Eigenschaften

### ISSUE THREAD

**Issue by FrankeSa** [JirkaDellOro/EIA2-Inverted#222]
Hallo zusammen,

ich habe ein Symbol das leuchten soll. Also quasi einen Feldgradienten um sich rum haben, der in gewissen Abständen die Helligkeit ändert. 

Ein Symbol soll sich drehen. 

Da das ja eigentlich Eigenschaften sind, hätte ich sie jetzt in das Klassendiagramm der Objekte mit aufgenommen. Ist das richtig?

**Comment by LukasBlea** [comment]
Ich sehe darin kein Problem!

Ich würde dann durch einen boolean entscheiden lassen (bzw bei der Weiterverarbeitung in der Datenbank) ob die Effekte gerade aktiv sind oder deaktiviert.

**Comment by JirkaDellOro** [comment]
Nun, Eigenschaften von was? Es kommt auch auf dein Gesamtkonzept an. Ich kann mir hier auch Eigenschaften der Animation vorstellen, nicht der Objekte. Denn das eine ist die Rotation des Koordinatensystems, das andere die Änderung der Zeicheneigenschaften. Das müssten nicht zwingend Objekteigenschaften sein. Wenn Du Animation und Objekt beliebig kombinieren willst, könnte man über eine solche Aufteilung nachdenken. Ansonsten kannst Du die Eigenschaften natürlich auch der Superklasse deiner Objekte spendieren...
