### ISSUE TITLE
failed to fetch 

### ISSUE THREAD

**Issue by beliema** [JirkaDellOro/EIA2-Inverted#223]
Hi, 
Ich bin etwas ratlos. Bei der Implementierung von MongoDB werden mir folgende Fehler in der Konsole angezeigt: 
<img width="1440" alt="Bildschirmfoto 2020-08-02 um 19 41 20" src="https://user-images.githubusercontent.com/48830827/89128767-443c4580-d4f8-11ea-818d-df7688b972f4.png"> 

Ich verstehe jedoch nicht ganz wieso, weil ich im Code in der Server.ts Datei bereits 
   _response.setHeader("content-type", "text/html; charset=utf-8");
        _response.setHeader("Access-Control-Allow-Origin", "*");
angegeben habe. 
ebenso funktioniert mein Heroku-Server auf einmal nicht mehr, obwohl er dies vor Implementierung von Mongo problemlos getan hat. 

<img width="1440" alt="Bildschirmfoto 2020-08-02 um 19 45 06" src="https://user-images.githubusercontent.com/48830827/89128828-af861780-d4f8-11ea-88b3-de10429d9153.png">

Wie kann ich das Problem lösen? 
Link zur App: https://beliema.github.io/EIA2Abschlussaufgabe/Client/zauberbild.html
Pages: https://beliema.github.io/EIA2Abschlussaufgabe/

Liebe Grüße

**Comment by JirkaDellOro** [comment]
Klar ist, dass deine Heroku-App nicht läuft, daher kann sie auch nicht antworten und Du erhältst den Fehler im Client. Starte die Herkoku-App neu und klick beim App-Log unten auf "Save" um das ganze Log zu erhalten und poste dieses hier.

**Comment by JirkaDellOro** [comment]
Poste bitte auch einen Link zu deinem Code und zum Konzept

**Comment by beliema** [comment]
[zauberbildabschluss-logs-1596440966001.txt](https://github.com/JirkaDellOro/EIA2-Inverted/files/5014574/zauberbildabschluss-logs-1596440966001.txt)

Link zum Konzept: 
[EIA2Abschluss.pdf](https://github.com/JirkaDellOro/EIA2-Inverted/files/5014599/EIA2Abschluss.pdf)

Link zum Code: https://beliema.github.io/EIA2Abschlussaufgabe/Client/zauberbild.html

**Comment by JirkaDellOro** [comment]
Das ist wieder ein Link zur App, nicht zum Code.

Im Log steht drin, dass dein Pfad zur Server.js falsch zu sein scheint.

**Comment by beliema** [comment]
Oh, sorry https://github.com/beliema/EIA2Abschlussaufgabe

**Comment by beliema** [comment]
habe in meiner package.JSON meinen Pfad von der obersten Ebene meines Repositorys angegeben: 
"scripts": {
    "start": "node EIA2Abschluss/Server/Server.js"
  }, 

Mir wird aber noch immer angezeigt, dass er nicht tut.

**Comment by beliema** [comment]
okay, nach etwas mehr Herumprobieren wurde der alte Fehler wohl behoben, allerdings wird mir jetzt folgendes in der Konsole als Error angezeigt: 
<img width="1440" alt="Bildschirmfoto 2020-08-03 um 13 57 36" src="https://user-images.githubusercontent.com/48830827/89180123-659d4000-d591-11ea-9564-b60e90c107e5.png">

**Comment by JirkaDellOro** [comment]
Ich finde, wie wohl auch Heroku, in dem Repository auf der obersten Ebene keinen Ordner namens "EIA2Abschluss"
