### ISSUE TITLE
Uncaught TypeError: Cannot read property 'setAttribute' of null at objectSelect

### ISSUE THREAD

**Issue by t0mmy93** [JirkaDellOro/EIA2-Inverted#224]
Hallo Zusammen, 

sobald ich mit dem Cursor auf das Gelbe untere Viereck klicke bekomme ich einen Consolen Error "Main.ts:187 Uncaught TypeError: Cannot read property 'setAttribute' of null at objectSelect", dies geschieht bei der vom Eventlistener ausgeführten Funktion objectSelect() in der Zeile 187. Dort versuche ich das Value des "<input>type range" zu ändern oder auszulesen. Ich habe schon sehr viele Zugriffsmöglichkeiten ausprobiert, doch bekomme immer diesen Fehler, jedoch nur in der Browser Console und nicht in vs-code.
Ist die Syntax falsch? Oder gibt es eine andere Möglichkeit.

Konzept (möglicherweise geht der Link nicht --> Option 2 nutzen): https://t0mmy93.github.io/Abgabe_2020_die_Echte/EIA2_Abgabe/Konzept/TestKonzept.pdf

Konzept2: https://github.com/t0mmy93/Abgabe_2020_die_Echte/blob/master/EIA2_Abgabe/Konzept/TestKonzept.pdf

Index.html: https://t0mmy93.github.io/Abgabe_2020_die_Echte/EIA2_Abgabe/Code/index.html

pls need help :D

**Comment by JirkaDellOro** [comment]
Klassiker!

Du definierst lauter Variablen mit Referenzen auf HTML-Elemente die es noch gar nicht gibt zur der Zeit, da die HTML-Seite noch gar nicht fertig geladen und das DOM noch nicht aufgebaut ist. Darunter auch sliderXSpeed

**Comment by t0mmy93** [comment]
Vielen Dank hat geklappt :)
