### ISSUE TITLE
Query String kommt nicht ganz bei Heroku an 

### ISSUE THREAD

**Issue by ivenios** [JirkaDellOro/EIA2-Inverted#225]
Hallo zusammen, 
sitze daran jetzt leider schon etwas länger. Da ich mit Trail end Error hier nicht mehr weiter komme. 
Ich möchte meine platzierten Objekte aus meinem Objekte Array per Query string an die DB schicken. Problem ist zur Zeit, dass der Teil mit den Objekten immer abgeschnitten wird. 

Beispiel: 
Vollständiger query: `command=safePicture&username=Admin&pictureName=test save 2&placeableObjects=[{"x":256,"y":143,"color":"#000000","scale":2},{"x":652,"y":139,"color":"`_#000000","scale":2},{"x":814,"y":225,"color":"#000000","scale":2},{"x":857,"y":357,"color":"#000000","scale":2}]_

Bei Heroku kommt an ` command=safePicture&username=Admin&pictureName=test save 2&placeableObjects=[{%22x%22:68,%22y%22:66,%22color%22:%22%23000000%22,%22scale%22:2},{%22x%22:417,%22y%22:139,%22color%22:%22`

Ich lasse mittlerweile den jsonString manuell durchlaufen um die " und # zu entfernen. 
Da die encodeURI oder endcodeURIComponent irgendwie auch nur die hälfte ausgetauscht haben: 
```

for (let i: number = 0; i < jSONString.length; i++) {
        // Hashtag aus query string entfernen
        jSONString = jSONString.replace(hash, "%23");
        jSONString = jSONString.replace(quotes, "%22"); }
```

Das Zeichenlimit von Heroku ist doch eigentlich 2048 dachte ich :/. Ansonsten stehe ich etwas auf dem schlauch wie ich die platzierten Objekte abspeichern soll. 

Vielen Dank schon einmal im Voraus für eure Hilfe. 

Repo: https://github.com/ivenios/EIA2/tree/master/01_Endabgabe_v2
Laufende Endabgabe: https://ivenios.github.io/EIA2/01_Endabgabe_v2/index.html?

**Comment by AionixX** [comment]
Hi,
es ist relativ schwer den Code zu debuggen da ich kein Zugriff auf die Heroku Konsole habe. Außerdem konnte ich kein Konzept finden, jedoch sind mir ein paar Dinge aufgefallen:
1. Es sind nur bestimmte Sonderzeichen in einer URL erlaubt. `[`, `]`, `{`, `}` gehören **nicht** dazu! Aber mich wundert das er trotzdem die ersten paar Sonderzeichen verschickt.
2. Das `:` Zeichen ist ein Reserviertes Zeichen und sollte auch nicht benutzt werden.
3. Ich würde dir empfehlen die Daten in einer JSON Datei mit der `POST` - Methode und nicht mit `GET` zu verschicken. Zumal die maximale Länge der URL schon bei ca 30 Objekten überschritten wird.

**Comment by JirkaDellOro** [comment]
POST wäre schon geschickt, allerdings brauchen wir dann mehr Aufwand auf der Serverseite. Die Aufgabenstellung ist auf GET ausgelegt.

Im Query-String sind auch mehr Zeichen erlaubt, er ist nur ein Anhängsel, das beliebig von der Serversoftware interpretiert werden kann. Was allerdings Heroku weiter berücksichtigt ist `#` für den Hash. Siehe https://jirkadelloro.github.io/EIA2-Inverted/L05_Client/Material/URL.png

An einem `#` wird also die Interpretation des Query-Strings abgebrochen und der Rest als Hash interpretiert. Ich empfehle
- Alle Leerzeichen raus
- Alle Anführungszeichen raus
- Alle Doppelkreuze raus

Ich habe dies einmal mit meinem Testcode gemacht und noch mehr Dummy-Symbole nach deinem Muster eingefügt. Das ist meine Ausgabe:
https://eia2-w18-node.herokuapp.com/?command=safePicture&username=Admin&pictureName=testsave2&placeableObjects=[{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:256,y:143,color:000000,scale:2},{x:652,y:139,color:000000,scale:2},{x:814,y:225,color:000000,scale:2},{x:857,y:357,color:000000,scale:2}]

**Comment by JirkaDellOro** [comment]
PS: wo finden wir dein Konzept? https://github.com/ivenios/EIA2/blob/master/01_Endabgabe_v2/1_Konzept/Ivens%20Thoughts.txt scheint unvollständig und ist unübersichtlich.

**Comment by ivenios** [comment]
Ja an POST habe ich mich noch nicht ran getraut, dann wenn der Rest der Abgabe flüssig funktioniert vielleicht. 

Die Konzepte liegen bei mir hier noch analog :) Reicht es hier, wenn man den groben Funktionsverlauf notiert ?

Ich mach mich mal ran, es so zu probieren. Deine Test anfrage von oben kommt kam komplett an. Nur war mein database code nicht in der Lage diesen zu verarbeiten ^^
Habe in der zwischen Zeit leider was kaputt programmiert. 

Vielen Dank

**Comment by JirkaDellOro** [comment]
ggf. musst Du die Anführungszeichen drin lassen

**Comment by ivenios** [comment]
Okay, jetzt funktioniert alles. 

jap, damit ich das am ende wieder Parsen kann, aber als %__ sollte es ja eigentlich gehen 

Danke nochmal
