### ISSUE TITLE
Error bei Seite-Laden

### ISSUE THREAD

**Issue by klinkewitzn** [JirkaDellOro/EIA2-Inverted#226]
Hallo, bei mir erscheint dieser Fehler:
![fehlerNew](https://user-images.githubusercontent.com/56318063/89175751-a5abf500-d588-11ea-9972-630c60d8b4f3.PNG)
Ich weis nicht was er zu bedeuten hat. Es gehen trotzdem noch alle Funktionen.

**Comment by JirkaDellOro** [comment]
Der Browser möchte gerne ein kleines Icon zu deiner App im Tab darstellen, kriegt es aber nicht vom Browser, da es nicht existiert. Mann kann
- es ignorieren
- ein favicon.ico neben die html-Datei legen
- `<link rel="icon" href="data:,">` in den Kopf der HTML-Datei schreiben (ausprobieren, habe ich selbst eben erst ergoogelt)

**Comment by KohlerAl** [comment]
Ich habe in meiner html Datei ein Icon eingefügt (hab das mal auf Instagram gesehen). Ich habe folgendes geschrieben: 
   
 <link rel="icon" href="Konzeption/Magic_Potion2.png" type="image/x-icon">

Bei mir funktioniert es, habe es bis jetzt aber nur in Chrome getestet
