### ISSUE TITLE
Es wird nichts in der Collection gespeichert

### ISSUE THREAD

**Issue by k-poschmann** [JirkaDellOro/EIA2-Inverted#228]
Hallo,

beim abspeichern eines Bildes, kommt bei MongoDB nichts in der Collection an. Laut Heroku besteht aber eine Verbindung. Ich kann auch kein Bild auswählen, da keine DatabaseList kreiert wird (?). Ich finde den Fehler in meinem Code einfach nicht, da das abspeichern in die Datenbank vor ein paar Tagen noch funktionierte...

Über Hilfe bedanke ich mich!
 Repo: https://github.com/k-poschmann/poschmannEia2/tree/master/Aufgaben/Abschlussaufgabe_Zauberbild
Anwendung: https://k-poschmann.github.io/poschmannEia2/Aufgaben/Abschlussaufgabe_Zauberbild/index.html
Konzept: https://github.com/k-poschmann/poschmannEia2/blob/master/Aufgaben/Abschlussaufgabe_Zauberbild/Konzept/Konzept_Zauberbild.pdf

**Comment by AnnaLotz** [comment]
Ist `hfucocktailbar` die richtige Heroku App, an die du senden willst?

**Comment by k-poschmann** [comment]
jap^^ ich hab den Namen damals leider unglücklich gewählt aber es die richtige App

**Comment by KohlerAl** [comment]
Du schaust in Server.ts, ob deine url getPicture, findPicture oder insertName enthält. Nur in den drei Fällen machst du was.

Wenn du in connectServer.ts Daten speichern willst, verwendest du folgenden Code: 
let response: Response = await fetch(url + "?" + query + "&" + canvasquery + "&" + _title);

Da die url keine der drei Zeichenketten von oben enthält, passiert auch nichts.

**Comment by k-poschmann** [comment]
ok ich habe es im Code jetzt soweit angepasst. Jetzt bekomme ich aber leider wieder "Fail to fetch". In der Datenbank ist jetzt was angekommen :) Danke dafür schonmal.

![Bildschirmfoto 2020-08-03 um 15 40 09](https://user-images.githubusercontent.com/56409026/89189219-fa0e9f00-d59f-11ea-9ed7-75a3ebc129fa.png)
