### ISSUE TITLE
operation was aborted 

### ISSUE THREAD

**Issue by beliema** [JirkaDellOro/EIA2-Inverted#229]
New Issue: 
nach drücken meines Speichern Buttons wird mir in der Konsole angezeigt, dass die Operation aborted wurde: 
<img width="1440" alt="Bildschirmfoto 2020-08-03 um 14 57 22" src="https://user-images.githubusercontent.com/48830827/89184935-bca71300-d599-11ea-9901-abf6b9fef560.png">

Mir ist nicht klar, was das bedeutet und wie ich diesen Fehler beheben kann. 

Konzept:
[EIA2Abschluss2.pdf](https://github.com/JirkaDellOro/EIA2-Inverted/files/5016073/EIA2Abschluss2.pdf)

Link zum Code:  https://github.com/beliema/EIA2Abschlussaufgabe
Link zur Anwendung:  https://beliema.github.io/EIA2Abschlussaufgabe/Client/zauberbild.html

**Comment by JirkaDellOro** [comment]
Der Nachricht ist zu entnehmen, dass `generatepage2` in Zeile 407 versagt, also beim fetch von Heroku. Dein Herokuserver scheint nicht zu laufen oder zu crashen, weshalb der Client dann abbricht. Schau also zunächst, dass der Herokuserver auch wirklich läuft.
