### ISSUE TITLE
im debugger variablen sehen

### ISSUE THREAD

**Issue by jonathanweissenberger** [JirkaDellOro/EIA2-Inverted#23]
ich kann im Debugger die Variablen wie im Lehrvideo L01_V2_Debugger_041019.mp4 nicht sehen. Gibts dafür eine Lösung?
![Variablen Debugger](https://user-images.githubusercontent.com/48829433/66640994-2f658d00-ec1a-11e9-9e90-8127c66a3a61.jpg)

**Comment by Plagiatus** [comment]
Prof. Dell'Oro arbeitet im Video mit Chrome, du bist soweit ich das sehe auf Firefox, der die Variablen nicht direkt hinter der Zeile anzeigt.

Du kannst aber trotzdem mit der Maus darüber fahren oder rechts den Reiter "Geltungsbereich" aufklappen, da siehst du die Variablen auch. Eine weitere Alternative ist es, die zu überwachenden variablen in die Liste "Ausdruck beobachten" ganz oben Recht hinzuzufügen.

Oder du nutzt eben auch Chrome.

**Comment by JirkaDellOro** [comment]
Kann dieser Issue geschlossen werden?

**Comment by jonathanweissenberger** [comment]
Ja kann geschlossen werden , danke Von meinem Huawei-Mobiltelefon gesendet-------- Originalnachricht --------Betreff: Re: [JirkaDellOro/EIA2-Inverted] im debugger variablen sehen (#23)Von: JirkaDellOro An: JirkaDellOro/EIA2-Inverted Cc: jonathanweissenberger ,Author Kann dieser Issue geschlossen werden?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/JirkaDellOro/EIA2-Inverted/issues/23?email_source=notifications\u0026email_token=ALURH6M4BFXTZJOEHGGAYZTQS77HRA5CNFSM4I7XK3R2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEDU4M6I#issuecomment-552191609",
"url": "https://github.com/JirkaDellOro/EIA2-Inverted/issues/23?email_source=notifications\u0026email_token=ALURH6M4BFXTZJOEHGGAYZTQS77HRA5CNFSM4I7XK3R2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEDU4M6I#issuecomment-552191609",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Plagiatus** [comment]
Die Person die das Issue öffnet sollte es auch wieder schließen wenn es erledigt ist ;)

**Comment by JirkaDellOro** [comment]
@jonathanweissenberger : bitte das nächste Mal also selbst schließen
