### ISSUE TITLE
Serverprobleme...

### ISSUE THREAD

**Issue by schuchte** [JirkaDellOro/EIA2-Inverted#230]
Hallo zusammen!

Ich weiß nicht genau wo das Problem liegt, aber ich bekomme ständig unschöne Fehlermeldungen (siehe Screenshot) wenn ich versuche meine Daten in der Datenbank zu speichern.

![grafik](https://user-images.githubusercontent.com/56271810/89193193-ea925480-d5a5-11ea-9fa2-db39f7026130.png)

Hoffe mir kann jemand helfen...!

Link zur Anwendung :  https://schuchte.github.io/EIA2/EIA%202%20Endabgabe/zauberbild.html
Repo : https://github.com/schuchte/EIA2/tree/master/EIA%202%20Endabgabe

**Comment by MarkusDamm** [comment]
Hallo Tanja,
bei dir liegt es wahrscheinlich am gleichen wie [hier](https://github.com/JirkaDellOro/EIA2-Inverted/issues/203#issuecomment-665174858)

**Comment by schuchte** [comment]
Hallo Markus, habe den Link rausgeschmissen und neu gepusht. Leider funktioniert es trotzdem immer noch nicht :/

**Comment by JirkaDellOro** [comment]
**Niemals** Leerzeichen in Ordnerpfade und Dateinamen basteln.

**Comment by schuchte** [comment]
Dankee Jirka! Es klappt.
Leerzeichen sind böse, ich merks mir.
