### ISSUE TITLE
Dokumentation zur Einrichtung

### ISSUE THREAD

**Issue by FrankeSa** [JirkaDellOro/EIA2-Inverted#231]
Hallo zusammen,

kurze Frage: Wenn ich die Dokumentation über Heroku und MongoDB anlege. Kann ich davon ausgehen, dass der Nutzer schon alle Konten hat, oder muss ich dort auch Beschreiben wie man sich anmeldet, was man anklicken muss etc? Ich hab bisher nur, was nötig ist um meine Anwendung zum laufen zu bringen.

**Comment by JirkaDellOro** [comment]
Das genügt.

**Comment by FrankeSa** [comment]
Ok. Danke.
