### ISSUE TITLE
gedraggtes Object erscheint versetzt auf dem Canvas

### ISSUE THREAD

**Issue by t0mmy93** [JirkaDellOro/EIA2-Inverted#232]
Hallo Zusammen,
 
beim Draggen des gelben Vierecks sollte laut meinem Code das Viereck kopiert und an den Curser X/Y Koordinaten eingefügt werden.  Das Viereck wird auf dem Canvas angezeigt, jedoch erscheint es nicht auf den Curser Koordinaten sondern versetzt nach unten links. 

Mir wurde gesagt das es sich mit dem Befehl crc.translate( Xpos, Ypos) eventuell beheben lässt (hat bei mir nicht geklappt)

Die Grad und Drop functionen sind hardgecoded zum Testen, funktionieren die Funktion schreibe ich sie um, sodass sie für alle Geometrien anwendbar sind. 

Konzept: https://t0mmy93.github.io/Abgabe_2020_die_Echte/EIA2_Abgabe/Konzept/TestKonzept.pdf

Index.html: https://t0mmy93.github.io/Abgabe_2020_die_Echte/EIA2_Abgabe/Code/index.html

**Comment by JirkaDellOro** [comment]
Wichtig ist
- dass Du die Objekte ordentlich in einem lokalen Koordinatensystem zeichnest. Wenn Du sie dann auf 0,0 positionierst, erscheinen sie in der linken oberen Ecke und , sofern deren Ursprung in deren Mitte liegt, sogar nur das rechte untere Viertel davon. 
- dass Du die Mauskoordinaten auf Canvaskoordinaten umrechnest oder gleich als solche beziehst. Siehe dazu den Blackmailer Companion oder eiaSteroids

**Comment by t0mmy93** [comment]
Danke, ich habe die Lektionen  angeschaut. Den Fehler habe ich nicht gelöst. Es scheint als würden alle Koordinaten nicht dem entsprechen was sollten.  Die Manipulation der angeklickten Objekte  geht soweit gut.
