### ISSUE TITLE
Startklar?

### ISSUE THREAD

**Issue by JirkaDellOro** [JirkaDellOro/EIA2-Inverted#234]
Bitte hier kurz reinposten, wenn Du startklar im Sinne der Aufgaben "L00_Preparation" bist. 

Falls Du aber auf Probleme gestoßen bist, diese bitte nicht hier reinposten und damit den Thread kapern, sondern einen neuen Issue dafür öffnen. Wir freuen uns darüber!

**Comment by manzijes** [comment]
I'm ready :rainbow:

**Comment by fionavi** [comment]
startklar :raised_hands:

**Comment by Michele-Chantal** [comment]
Startklar :octocat:

**Comment by ayaan99** [comment]
startklar 👍

**Comment by Cocoze** [comment]
startklar :clap:

**Comment by LercheKa** [comment]
Startklar

**Comment by LercheKa** [comment]
Startklar :ok_hand:

**Comment by MoStein** [comment]
Startklar

**Comment by nina1827** [comment]
Startklar :)

**Comment by RueJohannes** [comment]
Startklar :fast_forward:

**Comment by amandaauer** [comment]
Startklar

**Comment by helenareimold** [comment]
Startklar

**Comment by baslerja** [comment]
Startklar

**Comment by AnnetteWdm** [comment]
Startklar ;)

**Comment by tonybree** [comment]
Ready 👍

**Comment by Aileen3011** [comment]
🐘 🐶 🐹 startklar 🦒 🐤 🙈

**Comment by Seppel2014** [comment]
Ready to go :santa:

**Comment by selinawasinger** [comment]
Startklar  💚

**Comment by Lum7n** [comment]
Ready👍🏼

**Comment by hahnlili** [comment]
Bereit

**Comment by sophiejoy777** [comment]
ready 😄

**Comment by SaraVo306** [comment]
Startklar :dizzy:

**Comment by jonathanweissenberger** [comment]
Startklar  :ok_hand:

**Comment by sade-baba** [comment]
bin ready  :sunflower:

**Comment by Lemon-Pie** [comment]
Aller Anfang ist schwer,
zunächst sind alle Buchseiten leer.
Ist dir dann doch was eingefallen,
behalt die Übersicht vor allem.
Und jetzt da es mir gefällt,
schreibe ich zum starten: "Hallo Welt".

**Comment by halisco** [comment]
Startklar

**Comment by nina1827** [comment]
bin startklar

**Comment by breitjacqueline** [comment]
Startklar :thumbsup: :dancer:

**Comment by vtechms** [comment]
"Ich bin startklar"

**Comment by ElaFantaSia** [comment]
Startklar! 💥

**Comment by voelkely** [comment]
startklar :)

**Comment by AlessCh** [comment]
Startklar :sleeping: :flushed: :crying_cat_face:

**Comment by michellewillmann** [comment]
Startklar

**Comment by marcok06** [comment]
Let's fetz

**Comment by aylanemr** [comment]
ready to fly :airplane:

**Comment by MareikeMe** [comment]
startklar

**Comment by NadinePerisic** [comment]
Startklar!!!

**Comment by s-wdh** [comment]
startklar! ❄️

**Comment by sebifyy** [comment]
startklar!
