### ISSUE TITLE
Github greift auf altes repository zu

### ISSUE THREAD

**Issue by nina1827** [JirkaDellOro/EIA2-Inverted#236]
Als ich den Steckbrief bei https://webuser.hs-furtwangen.de/~del/EIA2/index.php hochgeladen hab, hab ich beim Pages-Link https://nina1827.github.io/Steckbrief/ benutzt. Hierbei hat Github den alten Ordner ( von dem repository hier https://github.com/nina1827/nina1827.github.io ) für den Steckbrief verwendet und nicht den von https://github.com/nina1827/EIA2-tasks, den ich eigentlich nutzen wollte. Hierbei frage ich mich, ob ich das nachträglich noch anpassen kann
(Wäre evt. Donnerstag besser klärbar?)

**Comment by AnnaLotz** [comment]
Bist du denn schon auf der Kursseite registriert? Ich kann keinen Eintrag mit "Nina" finden, oder ist das hier nur ein "Deckname"? ;) 
Du hast bei deinen Links leider noch nicht den Richtigen dabei. (Ich vermute mal, du willst auf dieses Verzeichnis verweisen [https://github.com/nina1827/EIA2-tasks/tree/master/Steckbrief](url)) Das Schema sieht immer so aus: "deinGitHubName.github.io/RepositoryName/Verzeichnis..." Bei dir wäre das also folgender: [https://nina1827.github.io/EIA2-tasks/Steckbrief/](url) Und nicht vergessen, bei den settings im Repository pages zu aktivieren!
Falls du schon auf der Kursseite registriert bist, muss du Jirka einfach eine kurze Mail mit dem richtigen Link schreiben, er kann den Link anpassen.

**Comment by nina1827** [comment]
Nina ist mein Internet-Name, auf der Kursseite heiße ich Katharina Müller :,D 
auf jeden Fall danke <3 dann schicke ich die Mail mit dem richtigen Link (deine Vermutung war richtig ;) ) 

ich habe pages aktiviert, nur bin ich bei den settings davon nicht komplett sicher, ob ich sie richtig habe 
![image](https://user-images.githubusercontent.com/48830860/95244410-35cd1b80-0812-11eb-9ea7-f3d559873695.png)
(ich hoffe, das Bild klappt so? habe es per Snipping tool kopiert und einfach mal eingefügt xD)

**Comment by JirkaDellOro** [comment]
Ich habe es repariert.
