### ISSUE TITLE
Anmeldung zur Kursseite ist korrekt nur das Bildmaß stimmt nicht

### ISSUE THREAD

**Issue by FrankeSa** [JirkaDellOro/EIA2-Inverted#237]
Hallo zusammen,

beim Anmelden zur Kursseite zeigt es mir an, dass das Bildformat nicht passt. Aber die Maße meines Bildes stimmen und es ist das Gleiche wie letztes Semester XD  Ich weiß nicht mehr was man da machen muss, damit es trotzdem klappt....

**Comment by AnnaLotz** [comment]
Welchen Pfad hast du denn angegeben? Und in welchem Repository ist dein Steckbrief?

**Comment by FrankeSa** [comment]
Hi,

der Dennis konnte mir gerade helfen :) Jetzt hat es geklappt, danke :D
