### ISSUE TITLE
Verlinkung auf der Seite funktioniert nicht

### ISSUE THREAD

**Issue by helenareimold** [JirkaDellOro/EIA2-Inverted#238]
Hi :)

Ich schaffe es einfach nicht meine Aufgabe hochzuladen. Ich verlinke sie wie immer in Visual Studio Code, sobald ich sie aber dann auf der Kursseite öffne, kommt immer ein anderer Link: 
https://helenareimold.github.io/Steckbrief/Aufgabe 00/Übung 1.html

Aber ich habe den Ordner "Aufgabe 00" nicht im Steckbrief Ordner und trotzdem kommt das? Lösche ich Steckbrief im Link raus, komme ich auch auf den richtigen Link aber anders nicht ?? Packe ich den "Aufgabe 00" Ordner in den Steckbrief Ordner, kann ich das ganze genau 1x öffnen, dann wird der Link schon zu https://helenareimold.github.io/Steckbrief/Steckbrief/Aufgabe 00/Übung 1.html

Was mache ich falsch?

**Comment by manzijes** [comment]
Ich habe mir gerade deine Steckbrief.html angesehen. Du hast so wie ich sehe die Aufgabe mit einem relativen Pfad verlinkt, der so lautet: ../Aufgabe 00/Übung 1.html. Mit der Angabe ".." verweist du auf eine andere Ebene. Dadurch könnte das Problem mit dem zusätzlichen "Stekckbrief" im Link entstanden sein. 
Ich würde dir empfehlen, die Aufgabe mit einem absoluten Pfad mit URL zu verlinken, also im Steckbrief einfach den direkten Link zu der Aufgabe anzugeben. Ich glaube bei dir lautet er https://helenareimold.github.io/Aufgabe%2000/%C3%9Cbung%201.html

**Comment by helenareimold** [comment]
oh wow es hat funktioniert. Bisher hat das anders zwar auch immer geklappt aber umso besser 👍 vielen Dank!

**Comment by JirkaDellOro** [comment]
Noch ein paar wichtige Tipps zu den Verzeichnis und Dateinamen, die schließlich den Pfad bilden:
- vermeidet Umlaute und Sonderzeichen wie ß
- vermeidet Leerzeichen

Umlaute vermeidet ihr, indem ihr konsequent Englisch schreibt, Leerzeichen indem ihr Binnenmajuskel oder den Unterstrich "_" nutzt. Also z.B. statt `Aufgabe 00/Übung 1.html` schreibt ihr `Task_00/Exercise1.html`
