### ISSUE TITLE
Registrierung Steckbrief funktioniert nicht 

### ISSUE THREAD

**Issue by JennisGrief** [JirkaDellOro/EIA2-Inverted#239]
Guten Tag allerseits, 
ich wollte gestern abend endlich mal die Registrierung auf der Kursseite hinter mich bringen, bekomme aber immer wieder die Fehlermeldung das die Maße meines Bildes nicht stimmen (selbst nachdem ich die Maße angepasst habe) 
![portrait](https://user-images.githubusercontent.com/48830880/95650012-26372680-0ae1-11eb-8654-4e8420a475c6.jpg)
Ich hab es hier mal dazugepackt, danke schonmal für etwaige Hilfen 👍

**Comment by AionixX** [comment]
Hi,
Komm doch mal auf den Discord Server und schreib mich dort an dann können wir gemeinsam drüber schauen

**Comment by JennisGrief** [comment]
Hat sich erledigt mir wurde geholfen, danke  :)
