### ISSUE TITLE
Fehlermeldung für TS Lint 

### ISSUE THREAD

**Issue by maxbuchwald** [JirkaDellOro/EIA2-Inverted#24]
In VS Code wird mir diese Fehlermeldung angezeigt: 
"Failed to load the TSLint library for 'c:/Users/maxbu/OneDrive/Documents/VS Code/EIA2/EIA2/Aufgabe_01/Boxes.ts'
To use TSLint, please install tslint using 'npm install tslint' or globally using 'npm install -g tslint'.
Be sure to restart your editor after installing tslint."

Hat dies damit zu tun, dass meine TS- Datein nicht in JS kompiliert werden?

**Comment by obiwan1337** [comment]
Hat Du die Befehle in einem Terminal ausgeführt? Bekommst du einen neuen Fehler, wenn du einen der beiden versuchst? 
Es hat nichts mit der Kompilation der Dateien zu tun.

**Comment by obiwan1337** [comment]
Ist das Problem inzwischen gelöst?

**Comment by JirkaDellOro** [comment]
Kann das weg?

**Comment by JirkaDellOro** [comment]
Max?

**Comment by JirkaDellOro** [comment]
Ich gehe davon aus, dass Max sich ausgeklingt hat... tschüss!
