### ISSUE TITLE
Fehler Steckbrief Registrierung 

### ISSUE THREAD

**Issue by michellewillmann** [JirkaDellOro/EIA2-Inverted#240]
Wenn ich meinen Steckbrief registrieren will, kommt jedes mal die Meldung:
Code korrekt...

Fehler: steckbrief.htm in
https://michellewillmann.github.io/EIA2/Steckbrief
ist nicht lesbar oder nicht existent

jedoch habe ich beide Datein im Steckbrief Ordner.

**Comment by KohlerAl** [comment]
Hast du Pages für das Repo aktiviert? Wenn ich bei dem Link, den du angegeben hast, "steckbrief.htm" anhänge, wird die Seite nicht gefunden. Für dein Bild dasselbe. Theoretisch müssten die beiden Dateien dann angezeigt werden...

**Comment by JirkaDellOro** [comment]
Hurra, Alida ist mit an Bord!

@michellewillmann : wenn es geklappt hat, gib ihr bitte entsprechende Rückmeldung (auch wichtig für die Motivation externer Helfer) und schließe den Issue.

**Comment by michellewillmann** [comment]
Danke dir, daran hat's gelegen! @KohlerAl

**Comment by KohlerAl** [comment]
Freut mich, dass ich helfen konnte :) @michellewillmann
