### ISSUE TITLE
Aufgabe L01 Boxes

### ISSUE THREAD

**Issue by breitjacqueline** [JirkaDellOro/EIA2-Inverted#242]
Was macht das let ... of bei der zweiten for-Schleife ? 
Im Internet hab ich bisher nichts gefunden, was mir weiterhilft.

**Comment by JirkaDellOro** [comment]
Eine for..of-Schleife iteriert über die Elemente bzw. Werte eines Arrays, ob simpel oder assoziativ. Die Laufvariable referenziert bzw. erhält also pro Durchlauf einen Wert aus dem Array, bis alle Werte einmal drangekommen sind. Das ist ein etwas eleganteres Konstrukt als dies mit einer simplen for-Schleife zu machen, was aber auch möglich wäre. Im Booklet findest Du das Aktivitätsdiagramm dazu.

**Comment by breitjacqueline** [comment]
Das erklärt einiges, danke!

**Comment by JirkaDellOro** [comment]
👍  Wenn der Issue für dich geklärt ist, klicke bitte unten auf "Close" um ihn zu schließen.
