### ISSUE TITLE
L02 noch nicht freigegeben

### ISSUE THREAD

**Issue by RueJohannes** [JirkaDellOro/EIA2-Inverted#243]
Hallo,

ich sehe die Aufgabe L02 im Wiki noch nicht.

**Comment by JirkaDellOro** [comment]
Danke für den Hinweis, ist nun auch in das Inhaltsverzeichnis integriert. Wie im Workshop gezeigt, kann man zur Not auch immer über dem Inhaltsverzeichnis auf "Pages" klicken, da sieht man alle Aufgaben. Aber gerne mich sofort anstupsen.
