### ISSUE TITLE
Zwei Eingabeformulare in ein Ausgabefenster? 

### ISSUE THREAD

**Issue by Sahertia** [JirkaDellOro/EIA2-Inverted#244]
Mr. Jirka empfiehlt uns in seiner Mail für verschiedene Infomationen verschiedene Eingabe + Ausgabefenster zu benutzen. 

Ist es jedoch syntaktisch möglich/sinnvoll beide Formulare im selben Ausgabefenster darzustellen?

**Comment by JirkaDellOro** [comment]
Das ist möglich, Du kannst auf einer Webseite beliebig viele Formulare haben. Ob es sinnvoll ist, hängt von der Anwendung ab.

**Comment by JirkaDellOro** [comment]
Kann das weg? Bitte schließen...
