### ISSUE TITLE
Listener

### ISSUE THREAD

**Issue by Sahertia** [JirkaDellOro/EIA2-Inverted#245]
Was ist der Unterschied zwischen einem Event-listener und einem Change-listener? 

Ist der Change-listener ein Event-listener?

**Comment by JirkaDellOro** [comment]
Korrekt. Stelle dir einen Event-Listener vor, wie ein Ohr, das an ein DOM-Element geheftet werden kann und auf ein bestimmtes Ereignis horcht und reagiert. Die Reaktion ist der Aufruf des angegebenen Event-Handlers. Change ist lediglich ein solches Ereignis, ein Change-Listener ist also ein Event-Listener der auf das Change-Event reagiert.

**Comment by JirkaDellOro** [comment]
Kann das weg? Bitte schließen...
