### ISSUE TITLE
Übung Async05

### ISSUE THREAD

**Issue by Aileen3011** [JirkaDellOro/EIA2-Inverted#246]
ich habe den Code von Ela benutzt (aus dem Workshop) um die Übung in der Lektion auszuprobieren, allerdings funktioniert es bei mir nicht.
In der Konsole steht nur:  Start, vor fetch und end
Und der Text fehlt,ich versteh aber nicht warum, vielleicht kann mir da ja jemand weiterhelfen.

**Comment by JirkaDellOro** [comment]
Aus der Hüfte geschossen: fetch scheint keine Antwort zu erhalten. Hast Du eine aktive Internetverbindung wenn Du testest?

**Comment by Aileen3011** [comment]
Ja die Internetverbindung steht, habe es auch schon öfters probiert, aber es geht einfach nicht

**Comment by JirkaDellOro** [comment]
Den URL geprüft, dass auch wirklich die richtige Adresse gefetched wird? Hast Du den Code bei dir im Repository? Dann kann ich reinschauen.

**Comment by JirkaDellOro** [comment]
...oder wir gucken per discord gemeinsam rein

**Comment by Aileen3011** [comment]
Ja die Adresse funktioniert denke ich. Ich habe es jetzt in mein Repository gepusht. übung05

**Comment by JirkaDellOro** [comment]
Nein, da ist tatsächlich etwas faul: es fehlt der Doppelslash nach `https:`

**Comment by Aileen3011** [comment]
ja das war's, jetzt funktioniert es. Danke
