### ISSUE TITLE
Error Ausgabe beim "node NameDesSkripts.js" 

### ISSUE THREAD

**Issue by voelkely** [JirkaDellOro/EIA2-Inverted#247]
![grafik](https://user-images.githubusercontent.com/48826808/99246516-b44fac80-2805-11eb-8577-0f773b95b350.png)

habe alles so gemacht wie im Skript angegeben und auch die Video anleitung befolgt jedoch erhalte ich immer ein Error. Woran kann das liegen? Anscheinend scheint es die "Test.js" datei nicht zu finden obwohl es sie gibt...

**Comment by voelkely** [comment]
Fehler gefunden!

**Comment by JirkaDellOro** [comment]
Super! Was wars? Vielleicht stolpert noch jemand anderes drüber...

**Comment by voelkely** [comment]
@JirkaDellOro habe vergessen das in einem neuen terminal auf dem Ordner zu öffnen damit dieses "node" erscheint, erst dann hat es funktioniert
