### ISSUE TITLE
Zwei FormElements 

### ISSUE THREAD

**Issue by Sahertia** [JirkaDellOro/EIA2-Inverted#248]
Wie kann man zwei FormElements im gleichen fieldset nebeneinander, anstatt untereinander platzieren? 

Mein Ansatz war mit zwei <span>FormElements</span>, aber ja, sieht nicht so nice aus.

**Comment by manzijes** [comment]
Vielleicht wenn du im style "display inline" benutzt?

**Comment by JirkaDellOro** [comment]
Ja, das machst Du mit CSS. `display: inline` oder `display: inline-block` sollte funktionieren, vielleicht ist es noch geschickter gleich mit einem Grid-Layout zu arbeiten. Es gibt bestimmt auch noch andere Möglichkeiten z.B. mit Flex etc.

**Comment by JirkaDellOro** [comment]
Kann das weg? Bitte schließen...
