### ISSUE TITLE
npx serve ergibt Error

### ISSUE THREAD

**Issue by maikeklemm** [JirkaDellOro/EIA2-Inverted#249]
Wenn ich den temporären Server installieren will kommt nur diese Fehlermeldung. Was kann ich da machen?

![image](https://user-images.githubusercontent.com/48826824/99709973-45da4b00-2aa0-11eb-9003-bdc8e0713a47.png)

**Comment by JirkaDellOro** [comment]
Kommst Du mal auf Discord? ich bin gerade da

**Comment by JirkaDellOro** [comment]
Kann das weg? Bitte schließen...
