### ISSUE TITLE
Steckbrief Datei kann nicht geladen werden

### ISSUE THREAD

**Issue by TobMer** [JirkaDellOro/EIA2-Inverted#25]
Hi,
wenn ich versuche meine Aufgabe von L01 mit der grafischen Darstellung hochzuladen und wiederzugeben kommt nur, dass die Datei nicht geladen werden konnte. Obwohl ich den Pfad im Steckbrief angegeben habe.

Lg Tobi

**Comment by AnnaLotz** [comment]
Der Link aus deinem Steckbrief ist nicht ganz richtig. Der Link zu den Aufgaben fängt immer mit <githubusername>.github.io an (die eckigen klammern sind durch das zu ersetzen, was drin steht), bei dir steht aktuell nur github/EIA2... Unter https://tobmer.github.io/EIA2/Darstellung/Tracetable.jpg kann ich eine Abgabe von dir finden.

**Comment by TobMer** [comment]
Achso. In meinem Steckbrief hab ich dies nun aktualisiert und dann zeigt mir Github den Fehler an, dass "Authentication failed" an mit mehreren Optionen. Das war schonmal so aber ich weiß nicht wie das gefixt wurde... leider.

**Comment by AnnaLotz** [comment]
Wo wird der Fehler angezeigt, wenn du den Link im Steckbrief öffnest?

Auf der Kursseite ist für mich weiterhin folgender falscher Link: https://github/EIA2/Darstellung/Tracetable.jpg
Sicher dass du den veränderten Steckbrief gepusht hast?

**Comment by Plagiatus** [comment]
wenn du Fehlermeldungen bekommst, dann solltest du diese auch hier hin schreiben, ohne den genauen Wortlaut stochern wir nur im Nebel. Mit der Fehlermeldung ist es in 99% der Fälle einfacher dir zu helfen.

**Comment by JirkaDellOro** [comment]
Kann das weg?
