### ISSUE TITLE
Alert Ausgabe besser gestalten

### ISSUE THREAD

**Issue by FrankeSa** [JirkaDellOro/EIA2-Inverted#250]
Hallo zusammen,

wie kann ich nochmal die Ausgabe des Servers im Alert-Fenster schöner gestalten? Bzw. eines der beiden Ausgaben entfernen?
<img width="327" alt="Screenshot 2020-11-21 132128" src="https://user-images.githubusercontent.com/56167839/99877211-d75ecf80-2bfc-11eb-8ccc-6a35a3be2ae7.png">

Ich möchte z.B. nur den json-String angezeigt bekommen.

**Comment by JirkaDellOro** [comment]
Der Alert zeigt lediglich an, was er vom Server als Antwort erhält. Du musst also schauen, was der Server per `write` in die Antwort hineinschreibt. Ich nehme an, was Du nicht willst sind die Infos, die er in der Schleife hineinschreibt, wenn er die einzelnen Schlüssel-Werte-Paare untersucht.

**Comment by manzijes** [comment]
Vielleicht hilft dir noch, dass du in einem alert Zeilenumbrüche mit “\r\n” machen kannst.

**Comment by FrankeSa** [comment]
Hallo,
hat funktioniert, Danke :)
Ich habe einfach die for-Schleife aus kommentiert.
<img width="518" alt="Screenshot 2020-11-25 172041" src="https://user-images.githubusercontent.com/56167839/100254489-aa832300-2f42-11eb-87a4-e3c7eccec61b.png">

Und @manzijes Danke für den Tipp ;-)
