### ISSUE TITLE
Gitignore

### ISSUE THREAD

**Issue by AlessCh** [JirkaDellOro/EIA2-Inverted#251]
Beim Explorer kann ich den Ordner node_modules sehen, aber wenn ich in die Codeverwaltung gehe und diese "gitignore"-n möchte, sehe ich den Ordner nicht? Wie tue ich den Ordner denn gitignore-n?

![node_module](https://user-images.githubusercontent.com/64133065/99880879-6af0ca00-2c16-11eb-9ca4-f374096d4526.JPG)
![node_module2](https://user-images.githubusercontent.com/64133065/99880880-6c21f700-2c16-11eb-9cdf-59da9244072c.JPG)

**Comment by JirkaDellOro** [comment]
Hattest Du schon etwas "gitignore"-d? Sonst gibt es die Datei nämlich noch nicht. und Du musst sie anlegen. Entweder, indem Du etwas "gitignore"-st mit der rechten Maustaste und "add to gitignore" oder indem Du eine Datei mit Namen ".gitignore" selbst anlegst.

**Comment by AlessCh** [comment]
Oh okay, Dankeschön! Ich hab jetzt die Datei ".gitignore" erstellt, aber ich verstehe noch nicht wie ich den Ordner node_modules als Ganzes ignorieren lassen kann
![image](https://user-images.githubusercontent.com/64133065/99884426-7d76fd80-2c2e-11eb-8b52-fcdc74320237.png)

**Comment by AlessCh** [comment]
Okay hab es rausgefunden! :)

**Comment by JirkaDellOro** [comment]
Schreib' noch kurz, was Du gemacht hast um das Problem zu lösen und schließe dann den Issue, bitte.

**Comment by AlessCh** [comment]
Ich habe die Datei .gitignore geöffnet und den Ordernamen "node_modules" reingeschrieben und gespeichert.
