### ISSUE TITLE
Error Ausgabe in Server Konsole nach Einfügen von Connection-String

### ISSUE THREAD

**Issue by voelkely** [JirkaDellOro/EIA2-Inverted#253]
Sobald ich den kopierten Connection-String in meinen Server Code an die Stelle des URL für die Datenbank einfüge, erhalte ich eine Error Meldung und auch im Atlas wird mir nichts angezeigt... Hatte noch jemand so ein Problem?

![grafik](https://user-images.githubusercontent.com/48826808/100124642-30886680-2e7c-11eb-9ca5-88d8cbf28842.png)

**Comment by JirkaDellOro** [comment]
Ist der Code in deinem Repository auf dem aktuellen Stand?

**Comment by voelkely** [comment]
ja, habe grade aber bemerkt das ich das passwort falsch geschrieben (also nicht übersetzt) hatte und des daran lag
