### ISSUE TITLE
Senden und Laden der Daten [Error]

### ISSUE THREAD

**Issue by FrankeSa** [JirkaDellOro/EIA2-Inverted#254]
Hallo,

das zurückholen der Daten habe ich im letzten Workshop glücklicherweise hinbekommen :)) 

Nun habe ich das Abschicken und Laden versucht etwas zu verfeinern.... Ich habe eine Funktion geschrieben (retrieveRecipes) die ein Command=retrieve an die Serverpage anhängt. In der Funktion handleRequest im Server soll geschaut werden, was nun verlangt wird ein Rückruf oder ein Speichern. 

Das hat auch mal zumindest soweit funktioniert, dass im Alert die gespeicherten Rezepte ausgegeben wurden. 
Nun habe ich in meiner Datenbank alle Dokumente gelöscht, um die DB mit neuen Dokumenten zu füllen.

Jetzt bekomme ich viele Error-Meldungen. 
![image](https://user-images.githubusercontent.com/56167839/101519190-2d649e80-3983-11eb-99ca-c73133f3d7dc.png)
Der Server erkennt, dass ich Daten speichere oder sende. 

In der Datenbank kommt das gespeicherte Rezept auch an.

Nur beim zurück holen, zeigt es mir im Alert ein leeres Array an.

In der Console bekomme ich folgende Meldungen:
![image](https://user-images.githubusercontent.com/56167839/101519490-859ba080-3983-11eb-873a-0814a30d2b75.png)

Ich habe die Anwendung auch mal über npx Serve aufgemacht, aber da bekomme ich die gleiche Fehlermeldungen. 

Woran liegt es?

**Comment by JirkaDellOro** [comment]
"Request timeout" scheint darauf hinzudeuten, dass dein Server zu lange braucht um eine Antwort zu verfassen, vielleicht weil die Datenbankabfrage nicht klappt. Wenn Du deinen Server lokal startest und auf den zugreifst, müsstest Du bessere Fehlerausgaben bekommen können.

**Comment by FrankeSa** [comment]
Okay. Das mit dem leeren Array habe ich gelöst. Ich habe nach allen Rezepten gefragt, in denen Grün darin vorkommt. Und ich hatte noch kein Rezept mit grün...deshalb das leere Array.

Jetzt gibt er mir aber kein Alert mehr mit den versendeten Daten zurück. Warum...

Und da ich alles lokal getestet habe, bekomme ich nach dem Drücken des Senden Buttons keine Fehlermeldungen mehr in der Konsole.

**Comment by JirkaDellOro** [comment]
Da sollten wir per discord reinschauen. Corinna müsste greifbar sein, ansonsten können wir auch einen Termin gegen 13.00 Uhr ausmachen.

**Comment by AionixX** [comment]
Ich bin ansonsten auch gerade am PC. Kannst mich also einfach anschreiben in Discord

**Comment by JirkaDellOro** [comment]
Sarah...?

**Comment by FrankeSa** [comment]
Sorry...ich hatte eure Nachrichten erst nach 13 Uhr gelesen und hab dann dem Dennis auf Discord geschrieben.
Aber es hat heute dann leider nicht mehr für einen Termin gereicht....

**Comment by JirkaDellOro** [comment]
Und nun?

**Comment by JirkaDellOro** [comment]
Kann das weg? Bitte schließen...
