### ISSUE TITLE
Problem mit vscode

### ISSUE THREAD

**Issue by Sahertia** [JirkaDellOro/EIA2-Inverted#255]
Folgende Meldung wird im Terminal angezeigt, wenn ich zwischen build und watch mode switch:

tsc : Die Datei "<lokaler_Dateipfad_zensiert>" kann nicht geladen werden, da die Ausführung von Skripts auf diesem System deaktiviert ist. Weitere Informationen finden Sie unter "about_Execution_Policies" (https:/go.microsoft.com/fwlink/?LinkID=135170).
In Zeile:1 Zeichen:1
+ tsc -p '<lokaler_Dateipfad>
+ ~~~
    + CategoryInfo          : Sicherheitsfehler: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess

In der PROBLEMS Console wird mir für jede Datei welche in im üblichen Repository liegt die Meldung angezeigt: 

Not using the local TSLint version found for '<lokaler_Dateipfad_zensiert>'
To enable code execution from the current workspace you must enable workspace library execution.

Meine .ts Datei werden nicht mehr compiled.

Can somebody help me?

**Comment by JirkaDellOro** [comment]
Das ist ein Problem der Powershell. Schau hier:

https://github.com/JirkaDellOro/Prima/wiki/TypeScript-kompiliert-nicht%3F

**Comment by JirkaDellOro** [comment]
Kann das weg? Bitte schließen...
