### ISSUE TITLE
Inverted Classroom Videos

### ISSUE THREAD

**Issue by Aileen3011** [JirkaDellOro/EIA2-Inverted#256]
Bei mir funktionieren die Videos nicht im Inverted Classroom. Habe den Laptop schon neu gestartet und Wlan funktioniert auch. Habe es auch schon auf verschiedenen Devices probiert. Hat jemand auch das Problem?

**Comment by JirkaDellOro** [comment]
Es gibt bei Hetzner wohl gerade Probleme, auf deren Server liegen die Videos. Der Server wurde kürzlich neu gestartet, ich gehe davon aus, dass der Zustand nicht lange anhält.
