### ISSUE TITLE
snowflake.js kann nicht gefetcht werden

### ISSUE THREAD

**Issue by MoStein** [JirkaDellOro/EIA2-Inverted#257]
Diese Meldung erscheint im Browser bei der snowflake.js. Diese ist richtig im HTML verlinkt und Alicia und ich konnten nicht ausmachen woran das liegt. 

Die Dateien sind im Repository und im Steckbrief unter Implementation  bei L09 zu finden. 
Vielen Dank 

![Bildschirmfoto 2021-01-07 um 13 17 21](https://user-images.githubusercontent.com/48826900/103893551-c3f4be80-50ed-11eb-9d8d-7a476e207906.png)

**Comment by JirkaDellOro** [comment]
Bitte poste immer Links. Wenn ich suchen muss, kostet das Zeit und ich bin vielleicht am falschen Ort.

Was ich aber gefunden habe startet bei mir ganz normal und ich kann den Fehler nicht reproduzieren.

**Comment by JirkaDellOro** [comment]
Was war's?

**Comment by MoStein** [comment]
Ich weiß es nicht, es ist nicht noch mal aufgetreten
