### ISSUE TITLE
Unklare Fehlermeldung Code

### ISSUE THREAD

**Issue by voelkely** [JirkaDellOro/EIA2-Inverted#259]
die if schleife wird mir rot markiert und das ist die Fehlermeldung:  "This condition will always return 'false' since the types '() => void' and 'boolean' have no overlap."

Weiß jemand was das bedeutet? 

![grafik](https://user-images.githubusercontent.com/48826808/104810940-5f75e580-57f8-11eb-922b-c785f7fef837.png)

**Comment by JirkaDellOro** [comment]
http://if-schleife.de/

wie ist den `stop` deklariert und definiert?

**Comment by voelkely** [comment]
let stop: boolean = true;

**Comment by JirkaDellOro** [comment]
Ich habe einmal dein Projekt geklont, bekomme einige Fehler aber nicht diesen. Poste bitte einen Link auf den Code

**Comment by voelkely** [comment]
Meinst du den hier?  

https://voelkely.github.io/EIA2/Aufgabe_L11/Aufgabe/indexSki.html

**Comment by JirkaDellOro** [comment]
Nein, ich hätte einen Information gebraucht, dass das Problem in der Datei Lift.ts steckt. Ich habe es nun gefunden. 

`stop` ist eine Javascript bekannte Funktion, damit kann man den Ladeprozess des Browserwindows unterbrechen. Du hast zwar eine Variable namens `stop` deklariert, allerdings in deiner Main-Datei und ohne sie zu exportieren, so dass sie in anderen Programmteilen auch bekannt ist. Sie ist daher in Lift.ts nicht bekannt und deswegen wird angenommen dass Du die stop-Funktion meinst eine Funktion ist aber kein boolscher Wert und kann deswegen nie `false` sein, deine Bedingung kann also nie zutreffen. Das sagt die Fehlermeldung auch so aus.

Das war jetzt etwas tricky.

**Comment by voelkely** [comment]
ah okay, ich habs verstanden! habe die variable jetzt umbenannt und erhalte keine fehlermeldung mehr. Danke für deine Hilfe :)
