### ISSUE TITLE
animation schneeflocke

### ISSUE THREAD

**Issue by FrankeSa** [JirkaDellOro/EIA2-Inverted#260]
Hallo zusammen,

ich habe jetzt schon verschiedenes ausprobiert, dass meine Schneeflocken schön von oben nach unten oder wenigstens irgendwie durch das Bild schwirren. Allerdings sieht das Endergebnis nicht sehr schön aus https://frankesa.github.io/EA2-Inverted/Wiederholung/Canvas/index.html 
An welcher Schraube muss ich drehen, damit die Flocken von oben nach unten in einer angemessenen Geschwindigkeit fallen?
Nach meinem Verständnis gebe ich der Schneeflocke in der Snow.ts Datei in Zeile 14 eine Startposition mit x:600 und y:50, dennoch hängt sie oben in der 0,0 Ecke !?

Ich komm einfach nicht darauf, wo mein Fehler liegt, deshalb brauche ich eure Hilfe.
https://github.com/FrankeSa/EA2-Inverted/tree/master/Wiederholung/

**Comment by AnnaLotz** [comment]
Damit die Schneeflocke(n) sich von oben nach unten bewegt, muss diese Bewegung in der velocity fest gelegt sein. Anstatt den Vektor in Snow Z. 17 random zu erstellen, könntest du erst einmal mit fest gelegten Werten herumprobieren. In Z. 16 gibst du der Flocke eine Velocity (0,0). Versuche da mal andere Werte, um eine Bewegung nach unten zu erstellen und Kommentiere Z. 17 aus. Welche Werte machen für x und y Sinn, um eine Abwärts-Bewegung zu erzeugen?!

**Comment by FrankeSa** [comment]
Hi Anna,
danke für deine Antwort. Ich habe deine Rat befolgt und für mein Verständnis müsste bei der Velocity in die X-Richtung null stehen und irgendein Wert für y nach unten. Ich habe mit den Werten herumprobiert aber es zeichnet nur zwei Punkte die abwechselnd flackern... Ich habe auch ab der Funktion createSnowflake den debugger ausprobiert. Und bekomme in der UpDate Funktion einmal angezeigt: 
![image](https://user-images.githubusercontent.com/56167839/105057723-cb18b680-5a75-11eb-95ee-0afd7e05ea92.png)
da sind alle Werte auch so, wie ich sie angelegt habe.  Beim weiteren Klicken mit "step over next function call" zeigt es mir das hier an:
![image](https://user-images.githubusercontent.com/56167839/105058206-40848700-5a76-11eb-9383-5de8cbfcc0f5.png)
Das bei position vector x = 400 ist, liegt vermutlich daran, dass es mit der Zeit (_time) 0,2 multipliziert wurde, oder?
Diese Werte werden mir immer angezeigt, nur das dann irgendwann ein zweiter Punkt (Schneeflocke) gezeichnet wird an einer anderen Stelle auf dem Canvas!?   Er bewegt die Schneeflocke nicht richtig, aber wieso?

**Comment by FrankeSa** [comment]
P.S. Sorry für die großen Ausschnitte der Bilder...ich sehe erst jetzt wie groß und übersichtlich das ist... :(

**Comment by KohlerAl** [comment]
Hi Sarah, 
ich hab mir grade mal deinen Code angeschaut und in der add-Methode in der Vector.ts multiplizierst du die Zahlen, ich vermute, was du dort eigentlich machen willst ist addieren. Du startest mit der y-Position 200, beim ersten Update wird durch das multiplizieren 400 draus, beim nächsten Update wird daraus 800 und weil das dann größer ist als der Canvas, ziehst du die Höhe des Canvas ab. Die Höhe deines Canvas ist 600, das bedeutet du landest wieder bei 200. Das würde erklären, warum deine Schneeflocken immer an zwei Stellen zu "kleben" scheinen.

**Comment by FrankeSa** [comment]
Hey Danke Alida,

dein Tipp hat mir geholfen. Das war die Ursache. Jetzt verteilen sich die punkte wenigstens. Allerdings hab ich noch nicht herausgefunden, warum die Punkte bei mir nun von oben links nach unten rechts schwirren?
