### ISSUE TITLE
Feuerwerk Superklasse und Subklasse

### ISSUE THREAD

**Issue by FrankeSa** [JirkaDellOro/EIA2-Inverted#261]
Hallo,

ich habe eine Frage zu meiner Überlegung. Ganz generell besteht ein Feuerwerk ja aus einer Explosion mit vielen Partikeln.
Deshalb habe ich mir überlegt, dass ich eine Superklasse z.B. Explosion mache und als Subklasse den Partikel. Die Superklasse hat dann z.B. eine Position und eine Geschwindigkeit. Und die Subklasse, erbt dann diese eigenschaften + jeweils eine individuelle lifeteime. So mal als erster Ansatz. 

Ergibt das so Sinn?

**Comment by JirkaDellOro** [comment]
Hallo Sarah,

- Ganz generell besteht ein Feuerwerk ja aus einer Explosion mit vielen Partikeln.
  - es gibt wahrscheinlich noch andere Möglichkeiten, aber ich würde auch diesen Gedanken verfolgen  
- Deshalb habe ich mir überlegt, dass ich eine Superklasse z.B. Explosion mache und als Subklasse den Partikel
  - es erscheint mir nicht intuitiv, dass ein Partikel eine spezielle Explosion sein soll. Aber wenn Du Explosion und Partikel als Objekte bzw. Klassen identifiziert hast, kannst Du schauen, was sich generalisieren lässt und eine abstrakte Superklasse konzipieren.
