### ISSUE TITLE
Console Fehlermeldungen CORS

### ISSUE THREAD

**Issue by FrankeSa** [JirkaDellOro/EIA2-Inverted#262]
Hallo,
das Laden und Abspeichern von Daten habe ich lokal getestet und es funktioniert wie gewünscht. Nun habe ich alle Pfade von lokal auf Heroku und Mongo geändert, um es dort auch zu testen. Da bekomme ich aber Fehlermeldungen.
In der Konsole auf **localhost5000 mit über npx serve** bekomme ich diese Meldung.
![image](https://user-images.githubusercontent.com/56167839/106473835-8b55c400-64a4-11eb-8b0c-6787dd2b1d72.png)
Auf der Konsole über die **Index-Datei ohne npx serve**, bekomme ich das
![image](https://user-images.githubusercontent.com/56167839/106474141-e25b9900-64a4-11eb-8cb1-d5cf8950197f.png)

Kein Ahnung woran das liegt??? Ich habe den Pfad zu MongoDB kontrolliert und der müsste stimmen. Der Server verbindet sich regulär -> Build succeeded!  aber crashed eben nachdem ich Daten laden oder speichern will. In der DB kommt nichts an.

Und PS: die erste Fehlermeldung exports is not defined bekomme ich immer angezeigt. Sie behindert mich nicht aber wenn ich sie wegbekommen könnte wäre es auch gut.  

Link: Anwendung https://frankesa.github.io/EIA2_Abschlussarbeit/Index.html
Link: Repo https://github.com/FrankeSa/EIA2_Abschlussarbeit

**Comment by JirkaDellOro** [comment]
Wieso kommt auf der Browserkonsole eine Meldung von Server.js?

**Comment by FrankeSa** [comment]
Keine Ahnung. Das ist die Meldung, die ich meinte mit **exports is not defined**. Ich weiß aber nicht warum mir das angezeigt wird.
Und auch nicht die anderen Fehler....

**Comment by JirkaDellOro** [comment]
Ich kann mir gut vorstellen, dass das andere Folgefehler sind. Nochmal: welche Software soll im Browser laufen und soll dein Server im Browser laufen?

**Comment by FrankeSa** [comment]
Nein,  mein Server soll nicht im Browser laufen. In der ServerDatei ist der Code der den Server und die Datenbank abdeckt und die MainDatei nimmt diese Daten entgegen und verarbeitet sie und/oder stellt sie dar.  Ich bin überrascht das dieser Fehler auftritt, denn ich bin die Schritte genauso wie in den Lektionen durchgegangen.  Ich bin mir nicht ganz sicher, ob ich deine Frage, welche Software im Browser laufen soll richtig verstanden habe.  Die für den Client, denke ich mal.

**Comment by JirkaDellOro** [comment]
Du hast die Frage richtig verstanden und auch die Antwort ist korrekt. 

Nun ist die nächste Frage: was musst Du tun, damit ein Javascript-Code im Browser läuft, wie, wann und warum kommt der da rein?

**Comment by FrankeSa** [comment]
Also... das die erste Fehlermeldung mit exports is not defined in Server.js ausgegeben wurde, ist nun behoben. Das lag daran, das ich in der Index-Datei das Server.js Script eingebunden hatte. Danke, für den Hinweis, Jirka :) Allerdings bleiben die letzten beiden Meldungen noch bestehen. Obwohl in der handleRequest im Header die Freigbabe für CORS drinsteckt, wird hier wieder auf CORS verwiesen. Warum...? 
![image](https://user-images.githubusercontent.com/56167839/106638279-ffb36480-6583-11eb-9339-7c622444f8fb.png)

**Comment by JirkaDellOro** [comment]
Bist Du dir sicher, dass dein Server auf Heroku läuft? Wenn ich
https://sarahabschlussarbeit.herokuapp.com/
im Browser eingebe, sehe ich eine Application-Error-Meldung von Heroku

**Comment by FrankeSa** [comment]
Ich habe heute morgen nochmal die Verbindung zu Heroku und Mongo geprüft und nun wird mir keine Fehlermeldung mehr in der Konsole angezeigt.
