### ISSUE TITLE
Uncaught TypeError: form is null 

### ISSUE THREAD

**Issue by FranziskaFuchs** [JirkaDellOro/EIA2-Inverted#263]
Hallo zusammen,

ich bin gerade dabei für meine Endabgabe, das Formular zu programmieren, allerdings wird mir in der Benutzerkonsole immer wieder der 
Uncaught TypeError: form is null
    handleLoad file:///C:/Users/franz/OneDrive/Documents/Uni/4.Semester/Endabgabe-Feuerwerk/Endabgabe/form_f.js:8 ausgegeben.

Ich konnte bisher leider nicht herausfinden woran das liegt.
Mein bisheriger Code und mein Repository für die Endabgabe sind in meinem Steckbrief verlinkt.

Der dazugehörige Typescript Code findet sich in der Datei form_f.ts . 
Schon mal vielen dank für die Hilfe.

LG
Franziska Fuchs

**Comment by JirkaDellOro** [comment]
Der Klassiker ist, dass das Formular im DOM nicht gefunden werden kann, z.B. weil eine id nicht stimmt oder es gar nicht angelegt wurde.

Gerne schau' ich in deinen Code, poste dazu bitte immer die passenden Links in den Issue, sowohl zum Code als auch zur Laufzeitanwendung auf Pages.

**Comment by FranziskaFuchs** [comment]
Vielen Dank. 
Das hier wäre der Link zu meinem Code:
https://github.com/FranziskaFuchs/Endabgabe-Feuerwerk/blob/master/Endabgabe/form_f.ts

Und der Link zu meiner Anwendung:

https://franziskafuchs.github.io/Endabgabe-Feuerwerk/Endabgabe/index.html

**Comment by JirkaDellOro** [comment]
Danke, so kann ich mit dem Debugger dem Programm beim Laufen zuschauen und sofort den Fehler sehen. Du lässt nach einem HTMLDivElement mit der id "form" suchen. Das gibt es aber nicht, wir haben also den oben angesprochenen Klassiker. In der HTML-Datei sehe ich dies:
```html
    <form> 
    <div> 
        <form id = "form">
```
Ich denke, diese Struktur ist unnötig komplex, wahrscheinlich würde dir die erste Zeile reichen und Du lässt einfach nach einem HTMLFormElement suchen oder holst es dir per `document.forms[0]`

**Comment by FranziskaFuchs** [comment]
Vielen Dank für deine Hilfe, jetzt klappt es :)

**Comment by JirkaDellOro** [comment]
Schließe dann bitte diesen Issue, wenn er nicht mehr gebraucht wird
