### ISSUE TITLE
Geschwindigkeit der Partikel

### ISSUE THREAD

**Issue by FrankeSa** [JirkaDellOro/EIA2-Inverted#264]
Hallo,

ich möchte, dass auf ein Click auf den Canvas fünf Partikel erscheinen, von dem jedes einzelne in eine andere Richtung fliegen soll. 

Das habe ich nun auch so hinbekommen. Allerdings bewegen die Partikel sich so schnell, dass man sie kaum richtig sehen kann. Woran liegt das? 
Link zur Anwendung: https://frankesa.github.io/EIA2_Abschlussarbeit/Index.html

**Comment by JirkaDellOro** [comment]
Hier geht es nicht um Geschwindigkeit, sondern die Partikel bewegen sich gar nicht. Ich kann mir vorstellen, was der Fehler ist, aus didaktischer Sicht wunderbar. Du nimmst die Position des Mauszeigers und übergibst sie bei der Konstruktion der Partikel. Erinnere dich an die erste Lektion, da ging es unter anderem darum, dass komplexe Daten bei der Übergabe nicht kopiert, sondern lediglich referenziert werden. Das heißt, alle deine Partikel, die mit der gleichen Position konstruiert werden, greifen auf dasselbe Positionsobjekt zu. Jeder verschiebt beim Zeichnen diese Position ein Stück und malt sich dann an die Stelle auf dem Canvas, der nächste verschiebt von dort aus. Deswegen entstehen deine Kreise auch nicht zentrisch.

Lösung: Du musst die Positionswerte im Partikelkontruktor kopieren in einen neuen Vektor.

Mir sind dabei noch ein paar Sachen aufgefallen:
- der `_timeslice` wird nicht genutzt
- `pointer` im Partikel ist unintuitiv
- der große Switch im Hauptprogramm ist überflüssig. Du kennst ja die Struktur deines Formulars und kannst daher gleich auf die Informationen zugreifen, ohne über das Form-Objekt zu iterieren, also einfach
```typescript
          quantity = Number(formData.get("Quantity"));
          lifetime = Number(formData.get("ExplosionSize"));
          color = String(formData.get("Particlecolor"));
          ...
```

**Comment by FrankeSa** [comment]
Ok, danke für die Rückmeldung.  Also dann im Konstruktor z.B. so...
      this.position = _position;
            let newPosition: Vector = new Vector(this.position.x, this.position.y);
   this.velocity = _velocity;
            let newVelocity: Vector = new Vector(this.velocity.x, this.velocity.y);

**Comment by FrankeSa** [comment]
Und bei der Shape, wo es mehrere Formen gibt, da muss ich dann einen switch machen, oder? Oder gibt es da auch eine einfachere Variante?

**Comment by JirkaDellOro** [comment]
> Und bei der Shape, wo es mehrere Formen gibt, da muss ich dann einen switch machen, oder? Oder gibt es da auch eine einfachere Variante?

da ist er sinnvoll

**Comment by JirkaDellOro** [comment]
> this.position = _position;
> let newPosition: Vector = new Vector(this.position.x, this.position.y);

Nein, einfach
```typescript
this.position = new Vector(_position.x, _position.y);
...
```

**Comment by JirkaDellOro** [comment]
Aber... haben wir nicht der Vector-Class extra eine `copy`-Methode genau hierfür spendiert? Das Problem hatte ich sogar in einem Video vorgeführt...

**Comment by FrankeSa** [comment]
Danke, für die Hilfe. Ich hab das so umgesetzt und nun bewegen sich die einzelnen Partikel, wie gewünscht. :)In der move -Methode habe ich dann folgendes geschrieben. 
let offset: Vector = new Vector(this.velocity.x, this.velocity.y);
            offset.scale(_timeslice);
            this.position.add(offset);
