### ISSUE TITLE
formData

### ISSUE THREAD

**Issue by FranziskaFuchs** [JirkaDellOro/EIA2-Inverted#265]
Hallo,

bei der programmierung von formData, ist in folgender Zeile, formData unterringelt und es heißt dann :FormData is not an array or string type.

for (let entry of formData)

Dabei kann ich leider meinen Fehler nicht finden.

**Comment by JirkaDellOro** [comment]
Das ging schnell... was war das Problem?

**Comment by FranziskaFuchs** [comment]
Ich habe nur ausversehen, dass Issue zu Closed hinzugefügt, habe aber noch mal ein neus gepostet in dem auch mein Code verlinkt ist :)

**Comment by JirkaDellOro** [comment]
Achso. Du kannst durch den Button unten Issues auch wieder öffnen
