### ISSUE TITLE
formData-Fehler

### ISSUE THREAD

**Issue by FranziskaFuchs** [JirkaDellOro/EIA2-Inverted#266]
Bei der Programmierung von formData, wird mir in Zeile 21 immer der Begriff formData unterringelt und es heißt dann formData is not an array type or a string type.

Zeile 21: for (let entry of formData)

Der Fehler befindet sich in der Datei form_f.ts , bei mir in Zeile 21.
Ich konnte leider nicht herausfinden woran das liegt und dadurch kann ich auch nicht auf die Daten des Formulars zugreifen.

https://github.com/FranziskaFuchs/Endabgabe-Feuerwerk

https://franziskafuchs.github.io/Endabgabe-Feuerwerk/Endabgabe/index.html

**Comment by JirkaDellOro** [comment]
Formdata ist ein komplexes Objekt mit vielen Funktionen, die eingetragenen Daten befinden sich darin unter `entries`. Es kann sein, dass der Browser trotzdem weiß was Du vorhast und es funktioniert, aber TypeScript darauf hinweist. Schreibe also einmal
```typescript
 for (let entry of formData.entries)
```
und sage bescheid ob es damit noch Probleme gibt.

**Comment by FranziskaFuchs** [comment]
Jetzt wird entries uterringelt und es heißt : 
Property 'entries' does not exist on type 'FormData'

Es funktioniert leider immer noch nicht.

**Comment by JirkaDellOro** [comment]
Prüfe bitte, ob in deiner tsconfig.json folgende Zeilen die gleichen Einträge haben:
```json
    "target": "ESNEXT", /* Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017','ES2018' or 'ESNEXT'. */
    "module": "commonjs", /* Specify module code generation: 'none', 'commonjs', 'amd', 'system', 'umd', 'es2015', or 'ESNext'. */
```
und lass' mich wissen, was die Konsole ausspuckt, wenn Du `tsc -v` eingibst

**Comment by FranziskaFuchs** [comment]
Die beiden Zeilen haben die gleichen Einträge.

Und die Konsole gibt mir folgendes aus: 

Uncaught ReferenceError: tsc is not defined
    <anonymous> debugger eval code:1

**Comment by JirkaDellOro** [comment]
Oh... ich meinte die Konsole in VSCode, das Terminal

**Comment by JirkaDellOro** [comment]
Ist ansonsten die `tsconfig.json` identisch mit der des Kurses?

**Comment by FranziskaFuchs** [comment]
ich hab selbst noch einmal recherchiert wie entries aufgebaut ist und hinter entries haben anscheinend zwei Klammern gefehlt, jetzt wird mir mein entry in der Konsole ausgegeben. 
So hat es jetzt funktioniert.
for (let entry of formData.entries());

Tausend Dank für deine Hilfe !

**Comment by JirkaDellOro** [comment]
ja, das hatte ich nicht mehr auf dem Schirm, dass `entries` eine Methode ist und keine Eigenschaft. Da hätten die auch einen get-Accessor machen können...
