### ISSUE TITLE
response string vom server, als array weiterverarbeiten?

### ISSUE THREAD

**Issue by maikeklemm** [JirkaDellOro/EIA2-Inverted#268]
Wenn ich alle Raketen abfrage, die in meiner Datenbank vorhanden sind bekomme ich einen String zurück. Ich möchte die Inhalte des Strings jetzt aber in meinem Hauptprogramm einzeln weiterverarbeiten. Ich hab mit "JSON.parse" probiert den string umzuwandeln aber es kommt nur " [object Object],[object Object]" raus. Was kann ich tun um auf die einzelnen keys und values der raketen in meiner datenbank zuzugreifen?

**Comment by JirkaDellOro** [comment]
Bitte Links posten zur Laufzeitanwendung auf Pages und an die richtige Stelle ins Repository.

**Comment by maikeklemm** [comment]
Laufzeitanwendung: https://maikeklemm.github.io/EIA-2/Endabgabe/Client/index.html

Repository: https://github.com/maikeklemm/EIA-2/blob/main/Endabgabe/Client/main.ts

die funktion in der ich die serverantwort bekomme heißt findRockets und die in der ich die Inhalte weiterverarbeiten möchte heißt createButtons

**Comment by JirkaDellOro** [comment]
Gratulation zur soweit gediehenen Anwendung. Auch das angesprochene Problem ist lediglich eines der Browserkonsole, die nicht so komplexe Arrays ausgeben mag.  So etwas sieht man sich besser im Debugger an, da erhalte ich das folgende Bild und kann sehen, dass die Daten ordentlich erhalten und geparsed wurden:
![image](https://user-images.githubusercontent.com/6279994/107555179-24888700-6bd7-11eb-859a-26649a14f7e1.png)

**Comment by maikeklemm** [comment]
Ah okay super, danke!
