### ISSUE TITLE
Response-Methode

### ISSUE THREAD

**Issue by amandaauer** [JirkaDellOro/EIA2-Inverted#269]
Hii ich habe Probleme bei der Anfrage und Antwort. Wie bekomme ich nochmal bei einer Anfrage eine Antwort zurück? Also wie genau funktioniert nochmal die Response-Methode?

**Comment by JirkaDellOro** [comment]
Hast Du dir das nochmal in den Lektionen angeschaut und kannst Du deine Frage präzisieren? An welcher Stelle steigst du aus?

Siehe https://github.com/JirkaDellOro/EIA2-Inverted/tree/master/L06_Server#handlerequest

**Comment by JirkaDellOro** [comment]
Hat es sich selbst erklärt?
