### ISSUE TITLE
Event-Listener

### ISSUE THREAD

**Issue by Eleonora2709** [JirkaDellOro/EIA2-Inverted#27]
Hallo,

bei dem User Interface am Beispiel Cocktailbar verstehe ich nicht, weshalb der Listener "input" genau für den Slider festgelegt wird. Kann mir das jemand erklären?

https://jirkadelloro.github.io/EIA2-Inverted/L03_FormElements/Material/CocktailBar_UI-Scribble.jpg
Danke

**Comment by JirkaDellOro** [comment]
Ein `change`-Event wird erst erzeugt, wenn der Slider losgelassen wird. Es ist aber gewünscht, dass die Mengenanzeige sich bereits verändert, während der Slider bewegt wird. `input` wird bei jeder Bewegung gefeuert.

**Comment by JirkaDellOro** [comment]
Kann dieser Issue geschlossen werden oder gibt es weitere Fragen?
