### ISSUE TITLE
Super- & Sub-Klasse

### ISSUE THREAD

**Issue by breitjacqueline** [JirkaDellOro/EIA2-Inverted#270]
Hallo, ist es für die Abgabe zwingend erforderlich, dass es eine Superklasse gibt ?

**Comment by JirkaDellOro** [comment]
Es wäre schon wichtig, dass Du dein Verständnis des objektorientierten Designs nachweist und es gibt hier auch einige sinnvolle Möglichkeiten der Anwendung.
