### ISSUE TITLE
Partikel-Typ wird falsch übergeben

### ISSUE THREAD

**Issue by FrankeSa** [JirkaDellOro/EIA2-Inverted#271]
Hallo,

bei meiner Anwendung, können die Partikel verschiedene Formen haben. Nun habe ich aber festgestellt, dass wenn ich aus "star" klicke, zeichnet er mir die Form vom Popcorn. Ich habe mit dem Debugger geschaut, ob ich nachvollziehen kann warum. Dabei habe ich gesehen, dass in der Funktion CreateObjekt der richtige Typ aus dem Formular geholt wird (also star) aber schon bei der Konsolenausgabe in Main Zeile 73 wird der falsche Type ausgegeben. Und auch der falsche Typ im Konstruktor. Ich habe Schreibfehler überprüft oder die Schreibweise der variablen für die Übergabe der Werte, aber ich kann mir nicht erklären warum der Typ bei star nicht passt. Bei allen anderen Typen passt alles.   Außerdem Zählt er die Typen in der Konsole unablässig hoch (siehe Bild) eigentlich sollte doch dort nur die Anzahl stehen, die auch ausgewählt wurde.  
<img width="353" alt="Screenshot 2021-02-10 153647" src="https://user-images.githubusercontent.com/56167839/107524291-e62ea000-6bb5-11eb-9f34-4788beb72d6f.png">
https://frankesa.github.io/EIA2_Abschlussarbeit/Index.html

**Comment by sailerco** [comment]
Ändert sich etwas, wenn du in der Main.ts Z.66 ein break hinzufügst?
Es kann sein, das es in den nächsten Case überschwappt.
![image](https://user-images.githubusercontent.com/63914083/107526464-2a22a480-6bb8-11eb-8c19-fea808b02c3c.png)

**Comment by sailerco** [comment]
Ach und das hochzählen: jedes Mal, wenn du einen neuen Frame zeichnest, machst du einen console.log, wodurch es an der Stelle zu so einer hohen Zahl kommt.

**Comment by FrankeSa** [comment]
Juhuuu!!!! Das war es! Ich habe den break gesetzt und das gewünschte Ergebnis erhalten :) Vielen Dank! Und auch für den Hinweis mit den Frames..
