### ISSUE TITLE
Localhost oder Onlineservice

### ISSUE THREAD

**Issue by Aileen3011** [JirkaDellOro/EIA2-Inverted#272]
Soll Mongo DB im Localhost genutzt werden oder als Online Service, da bei dem Online Service die geforderte Anleitung zur Installation gar nicht benötigt wird Oder? (Gleiches gilt für den Server?)

**Comment by JirkaDellOro** [comment]
Es soll als Online-Service laufen. Die lokale Installation erleichtert die Entwicklung und das Testing enorm, daher ist es sehr empfehlenswert, erst damit zu arbeiten und erst die fertige Software auf die Online-Plattformen zu schieben.

**Comment by Aileen3011** [comment]
Okay. Und in der Aufgabenstellung steht man soll „Eine kurze Anleitung zur Installation der Anwendung unter Berücksichtigung der erforderlichen Dienste (z.B. Heroku, MongoDB etc.)“ schreiben, ich verstehe nicht was damit gemeint ist? Soll man beschreiben wie man MongoDB, etc. installiert? Oder für was soll man eine Anleitung schreiben ?

**Comment by JirkaDellOro** [comment]
Beschreibe, was jemand wie machen muss, um deine Software bei sich selbst, bei seinem eigenen Heroku-Service und mit seiner eigenen Datenbank, betreiben will. Stell' dir vor, Du hast die Software nicht geschrieben, um sie selbst zu betreiben, sondern im Auftrag eines Kunden oder einer Agentur, und die wollen die auf ihrer eigenen Infrastruktur installieren. Gehe davon aus, dass dort bekannt ist, wie man Heroku und Mongo selbst nutzt bzw. dass sie das natürlich selbst nachlesen können. Aber wie deine Software aufgebaut ist, wissen die natürlich nicht. Deswegen musst Du für die notwendigen Anpassung eine kleine Anleitung schreiben. Das werden wahrscheinlich nur eine Handvoll Sätze sein.

**Comment by Aileen3011** [comment]
Okay alles klar danke.
