### ISSUE TITLE
Partikel werden nicht dargestellt, Problem mit Klassen

### ISSUE THREAD

**Issue by fionavi** [JirkaDellOro/EIA2-Inverted#273]
Hallo,
ich habe zuerst meine Explosion in der main Datei zeichnen lassen und dort hat es funktioniert. Dann wollte ich es sinnvoll in verschiedene Klassen aufteilen aber seitdem sind die Partikel nicht mehr zu sehen.
Laut Konsolenausgabe gibt es aber keine Errors und die Methoden scheinen aufgerufen zu werden. Deshalb weiß ich nicht, wo der Fehler liegt.

Ordner: https://github.com/fionavi/EIA2-Endaufgabe/tree/main/Client2Kopie
Canvas: https://fionavi.github.io/EIA2-Endaufgabe/Client2Kopie/Firework.html

**Comment by AnnaLotz** [comment]
Der Link zum canvas funktioniert nicht, vermutlich hast du für das neue Repository unter Settings Pages noch nicht aktiviert :)

**Comment by AnnaLotz** [comment]
Rein durch den Code kann ich das Problem gerade leider nicht finden. Zwei Kleinigkeiten jedoch: 
- In Dateinamen sollten keine Leerzeichen sein, dein Hauptscript solltest du also umbenennen, z.B. stattdessen einen Unterstrich _ verwenden.
- Im html sollte die Reihenfolge der scripte immer folgende sein: Superklassen, Subklassen und zuletzt das hauptscript.

**Comment by fionavi** [comment]
Okay danke, ich habe es in den Settings aktiviert und die Ladereihenfolge geändert

**Comment by AnnaLotz** [comment]
Also ich komme noch nicht direkt dahinter, mir ist aber folgendes beim code verfolgen aufgefallen:
das `particles`-Array wird zu keiner Zeit gefüllt, in der update wird die for-Schleife also nie ausgeführt (man sieht auch, dass der console.log "ist in for schleife von update" nie aufgerufen wird). Die einzige Stelle, an der also etwas spannendes passiert, ist in der funktion `createRound`, wo eine Instanz der Klasse RoundParticle erstellt wird (und die 2 Methoden aufgerufen werden). Die Übergabeparameter scheinen hier etwas durcheinander zu sein, im constructor nimmst du position und velocity als number entgegen, obwohl die als Vektor vermutlich mehr Sinn machen würden. Verfolge da nochmal genau den Weg über die Sub- und Superklasse, welcher von den mitgegebenen Werten (0, 0, 1, 1) aus dem Hauptscript in welchem Wert landen.

Kann es sein, dass in der RoundParticle.draw schlichtweg der finale Zeichenbefehl fehlt? Lasse dir ansonsten auch mal die Position der Partikel ausgeben, falls diese nicht auf dem canvas ist, kann man sie logischerweise einfach nicht sehen.

**Comment by fionavi** [comment]
Ich habe die Übergabeparameter im Constructor jetzt verändert und ich habe mir die Position der Partikel angeben lassen, die müssten auf dem Canvas sein, sie sind also einfach nicht sichtbar. Da ich aber die draw-Methode zuerst in meiner main Datei hatte, sie da funktioniert hat, und jetzt wo ich sie in meine Klasse kopiert habe, nicht mehr funktioniert, verstehe ich nicht wieso sie nicht gezeichnet werden und finde den Fehler leider nicht.

**Comment by fionavi** [comment]
ich habe die neu erstellte Instanz nun auch in func createRound in das Array aufgenommen, sodass in der func update die for-Schleife durchlaufen wird. Trotzdem sieht man nichts. Das Problem liegt also höchstwahrscheinlich in den Methoden, ich kann es aber nicht erkennen

**Comment by JirkaDellOro** [comment]
Wenn ich mir den Code anschaue, dann sehe ich zwei Stellen, an denen Du wahrscheinlich eine Zeichnung erwartest:
- Explosion.explode
- Particle.draw

In erster wird ein leerer Pfad gezeichnet, in zweiter fehlt der Zeichenbefehl `fill` oder `stroke`
