### ISSUE TITLE
Fehlermeldung in VSC beim pushen

### ISSUE THREAD

**Issue by FrankeSa** [JirkaDellOro/EIA2-Inverted#274]
Hallo zusammen,

wenn ich versuche etwas auf meinem Inverted-Repository zu pushen über VSC, dann bekomme ich folgende Fehlermeldungen:
<img width="485" alt="Fehlermeldung" src="https://user-images.githubusercontent.com/56167839/107668560-19922d00-6c91-11eb-8c55-ac12f1e68abc.png">
<img width="647" alt="Fehlermeldung2" src="https://user-images.githubusercontent.com/56167839/107668567-1b5bf080-6c91-11eb-8a91-1e6a0ca72f04.png">

Wenn ich eine kleine Änderung in einer Datei ändern möchte, dann "lädt" es ewig und dann kommen die Fehlermeldungen. 

Hatte jemand auch schon dieses Problem und wie kann ich es beseitigen?

**Comment by AnnaLotz** [comment]
Der Error sagt mir so direkt nichts, aber im Zweifel einfach mal zuerst pullen, falls es irgendwo Konflikte geben sollte. (Vorher vllt noch kurz den neu erarbeiteten Code temporär woanders speichern, damit nicht verloren geht).

**Comment by JirkaDellOro** [comment]
Habe ich auch noch nie gesehen. Ich nutze in VSCode jetzt immer "Sync" was automatisch erst pullt und dann pusht

**Comment by sailerco** [comment]
War denn deine Internetverbindung stabil genug? Vielleicht liegt es auch an so etwas.

**Comment by FrankeSa** [comment]
An der Internetverbindung kann es nicht liegen. Ich habe es heute morgen mit zuerst "pull" versucht und dann push und die Fehlermeldung trat wieder auf. Ich habe recherchiert und herausgefunden, dass die Datenmenge zu groß ist. Ich kann mir schon denken weshalb... Jedenfalls habe ich in Foren Lösungsvorschläge gefunden wir z.B. die zulässige Datenmenge zu erhöhen. **git config --global http.postBuffer 157286400** Oder eine eine andere Version zu erzwingen **$ git config --global http.version HTTP/1.1 After it push was ok and I have changed HTTP version to 2 again: $ git config --global http.version HTTP/**

Ich habe über das Inverted_reposetory immer die Aufgaben im Steckbrief auf die Kursseite verlinkt. Die Endabgabe wird auch auf der Kursseite verlinkt. Kann ich diesen Steckbrief auch über mein anderes Repo (für die Abschlussarbeit) mit der Kursseite verbinden?  Ich möchte nämlich die oben erwähnten Lösungsvorschläge nicht einfach so ausprobieren und alles nur noch schlimmer machen...so kurz vor der Endabgabe XD

**Comment by JirkaDellOro** [comment]
Da es einfache HTML-Links sind, kannst Du alles mit allem verbinden, egal wo es sich befindet. 

Aber ich bin schon überrascht, wie Du so ein großes Repository erzeugen konntest. Jedenfalls war es allein deswegen schon gut, ein eigenes Repo für die Abschlussarbeit zu erstellen.

**Comment by FrankeSa** [comment]
Das heißt, ich nehme einfach die Steckbriefdatei und das bild in das AbschlussarbeitRepo und pushe von dort aus den Steckbrief auf die Kursseite?

**Comment by JirkaDellOro** [comment]
Nein, die Kursseite ist mit deinem aktuellen Steckbrief verlinkt. Was Du machen solltest, ausgehend von der Annahme, dass Du aktuell einen Klon deines inverted Repos auf deinem Rechner hast:
1. lösche das Github-Repo (bei Settings ganz unten)
2. lege ein Github-Repo mit dem gleichen Namen neu an
3. klone es auf deinen Rechner an einen neuen Ort
4. kopiere die Daten, die Du behalten willst, in diesen Klon, entsprechend der Struktur die Du hattest
5. synchronisiere
6. lösche deinen alten Klon und arbeite mit dem neuen weiter

**Comment by JirkaDellOro** [comment]
Hat's geklappt?

**Comment by FrankeSa** [comment]
Ich hab es noch nicht versucht. Ich hab jetzt mal den Ordner in dem ich den Steckbrief zur Kursseite hatte in mein Abschlußarbeit Repo hineingezogen. Kann ich nicht einfach den Steckbrief in dem neuen Repo neu auf der Kursseite verlinken?

**Comment by JirkaDellOro** [comment]
Schon... bedeutet mehr Arbeit für mich, weniger für dich. Wäre für ich aber vertretbar

**Comment by FrankeSa** [comment]
Also, deine oben genannten Schritte habe ich nun alle abgearbeitet und mein neues Repo hat nun alle Daten des alten Repos. 
Das neue heißt auch wie das alte, nur liegt es an einen neuen Ort auf meinem Rechner.  Jetzt habe ich aber auf der Kursseite gesehen das mein Pfad nicht mehr erkannt wird. 404 Error File not found. Muss ich nun doch mein Steckbrief neu registrieren?

**Comment by JirkaDellOro** [comment]
Hast Du das Repo auch auf Pages publiziert?

**Comment by FrankeSa** [comment]
Hatte ich tatsächlich nicht gemacht, aber nun nachgeholt und jetzt klappt´s. Danke!
