### ISSUE TITLE
Server: Fehlermeldung 

### ISSUE THREAD

**Issue by FranziskaFuchs** [JirkaDellOro/EIA2-Inverted#276]
Hallo,

ich bin gerade dabei meinen Server zu machen. Allerdings bekomme ich einige Fehlermeldungen, wenn ich die unterschiedlichen Button klicke, die eigentlich die Dateien an den Server schicken sollten, bzw. mit denen man sie sich zurück holen könnte.

Das sind die Fehlermeldungen, die mir in der Konsole ausgegeben werden.

> GEThttps://fireworkendabgabe.herokuapp.com/?rocketName=&ExplosionSize=1&Lifetime=10&Color=red&Amount=10&ParticleType=rectangle&ParticleSize=10
> CORS Missing Allow Origin
> 
> Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf https://fireworkendabgabe.herokuapp.com/?rocketName=&ExplosionSize=1&Lifetime=10&Color=red&Amount=10&ParticleType=rectangle&ParticleSize=10. (Grund: CORS-Kopfzeile 'Access-Control-Allow-Origin' fehlt).
> 
> Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource.

Außerdem bekomme ich folgende Fehlermeldung in Heruko wernn ich dort auf open app klicke:

 n the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command
 heroku logs --tail

Meine Links: 
https://github.com/FranziskaFuchs/Endabgabe-Feuerwerk
https://franziskafuchs.github.io/Endabgabe-Feuerwerk/Client/index.html

**Comment by JirkaDellOro** [comment]
Funktioniert deine Anwendung bei dir lokal? Wenn dein Server nicht läuft, worauf die zweite Meldung hindeutet, ist die erste Meldung eine Folge davon. Poste gerne hier die Log-Ausgaben von Heroku, sowohl vom Build-Prozess wie auch von der App.

**Comment by FranziskaFuchs** [comment]
Der Server hat lokal bereits funktioniert und mir wurde auch in der Application Logs Ausgabe  “Build succeeded” ausgegeben. Aber jetzt funktionert es nicht mehr und ich bekomme folgende Ausgabe.

Das ist die Ausgabe des Application Logs:

2021-02-13T15:28:11.255820+00:00 app[web.1]: npm ERR! Exit status 1

2021-02-13T15:28:11.255971+00:00 app[web.1]: npm ERR! 

2021-02-13T15:28:11.256118+00:00 app[web.1]: npm ERR! Failed at the package_feuerwerk@1.0.0 start script.

2021-02-13T15:28:11.256213+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

2021-02-13T15:28:11.262706+00:00 app[web.1]: 

2021-02-13T15:28:11.262887+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:

2021-02-13T15:28:11.263000+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2021-02-13T15_28_11_256Z-debug.log

2021-02-13T15:28:11.309340+00:00 heroku[web.1]: Process exited with status 1

2021-02-13T15:28:11.374362+00:00 heroku[web.1]: State changed from up to crashed

2021-02-13T15:29:48.674487+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=fireworkendabgabe.herokuapp.com request_id=cd579e79-50e9-4f35-b07a-5adcd2bf2da6 fwd="87.156.73.227" dyno= connect= service= status=503 bytes= protocol=https


Das hier wird mir angezeigt, wenn ich die App aufrufe:
Application Error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command
heroku logs --tail

**Comment by FranziskaFuchs** [comment]
Ich hatte in meiner Mongodb noch meine IP Adresse und habe diese jetzt mit 0.0.0.0/0 ersetzt.
Dadurch bekomme ich jetzt folgende Ausgabe bei Application Logs: 



-----> Building on the Heroku-20 stack

-----> Node.js app detected

       

-----> Creating runtime environment

       

       NPM_CONFIG_LOGLEVEL=error

       NODE_VERBOSE=false

       NODE_ENV=production

       NODE_MODULES_CACHE=true

       

-----> Installing binaries

       engines.node (package.json):  unspecified

       engines.npm (package.json):   unspecified (use default)

       

       Resolving node version 14.x...

       Downloading and installing node 14.15.5...

       Using default npm version: 6.14.11

       

-----> Restoring cache

       - node_modules is checked into source control and cannot be cached

       

-----> Installing dependencies

       Prebuild detected (node_modules already exists)

       Rebuilding any native modules

       

       > node@15.8.0 preinstall /tmp/build_067f8871_/node_modules/node

       > node installArchSpecificPackage

       

       + node-linux-x64@15.8.0

       added 1 package in 3.015s

       found 0 vulnerabilities

       

       @types/mongodb@3.6.7 /tmp/build_067f8871_/node_modules/@types/mongodb

       @types/bson@4.0.3 /tmp/build_067f8871_/node_modules/@types/bson

       @types/node@14.14.27 /tmp/build_067f8871_/node_modules/@types/node

       mongodb@3.6.4 /tmp/build_067f8871_/node_modules/mongodb

       bl@2.2.1 /tmp/build_067f8871_/node_modules/bl

       readable-stream@2.3.7 /tmp/build_067f8871_/node_modules/readable-stream

       core-util-is@1.0.2 /tmp/build_067f8871_/node_modules/core-util-is

       inherits@2.0.4 /tmp/build_067f8871_/node_modules/inherits

       isarray@1.0.0 /tmp/build_067f8871_/node_modules/isarray

       process-nextick-args@2.0.1 /tmp/build_067f8871_/node_modules/process-nextick-args

       safe-buffer@5.1.2 /tmp/build_067f8871_/node_modules/readable-stream/node_modules/safe-buffer

       string_decoder@1.1.1 /tmp/build_067f8871_/node_modules/string_decoder

       safe-buffer@5.1.2 /tmp/build_067f8871_/node_modules/string_decoder/node_modules/safe-buffer

       util-deprecate@1.0.2 /tmp/build_067f8871_/node_modules/util-deprecate

       safe-buffer@5.2.1 /tmp/build_067f8871_/node_modules/safe-buffer

       bson@1.1.5 /tmp/build_067f8871_/node_modules/bson

       denque@1.5.0 /tmp/build_067f8871_/node_modules/denque

       require_optional@1.0.1 /tmp/build_067f8871_/node_modules/require_optional

       resolve-from@2.0.0 /tmp/build_067f8871_/node_modules/resolve-from

       semver@5.7.1 /tmp/build_067f8871_/node_modules/semver

       node@15.8.0 /tmp/build_067f8871_/node_modules/node

       node-bin-setup@1.0.6 /tmp/build_067f8871_/node_modules/node-bin-setup

       node.js@0.0.1-security /tmp/build_067f8871_/node_modules/node.js

       memory-pager@1.5.0 /tmp/build_067f8871_/node_modules/memory-pager

       saslprep@1.0.3 /tmp/build_067f8871_/node_modules/saslprep

       sparse-bitfield@3.0.3 /tmp/build_067f8871_/node_modules/sparse-bitfield

       Installing any new modules (package.json)

       audited 27 packages in 0.435s

       

       1 package is looking for funding

         run `npm fund` for details

       

       found 0 vulnerabilities

       

       

-----> Build

       

-----> Caching build

       - node_modules

       

-----> Pruning devDependencies

       audited 27 packages in 0.472s

       

       1 package is looking for funding

         run `npm fund` for details

       

       found 0 vulnerabilities

       

       

-----> Build succeeded!

-----> Discovering process types

       Procfile declares types     -> (none)

       Default types for buildpack -> web

-----> Compressing...

       Done: 110.2M

-----> Launching...

       Released v11

       https://fireworkendabgabe.herokuapp.com/ deployed to Heroku

Allerdings ist die App ausgabe noch immer dieselbe und in meiner Konsole wird mir derselbe Fehler ausgegeben.

**Comment by JirkaDellOro** [comment]
Im App-Log steht
2021-02-13T15:28:11.256213+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Scroll bitte nach oben und schau was da steht. Wenn ich mich richtig erinnere, kann man das Log-File auch herunterladen, dann kannst Du es komplett hier anhängen.

**Comment by FranziskaFuchs** [comment]
MIttlerweil erhalte ich von meinem Log eine andere Ausgabe, meine Anwendung kann allerdings immer noch nicht auf den Server zugreifen und die App Ausgabe funktioniert auch immer noch nicht. Hättest du vielleicht noch einen Tipp in welche richtung mein Fehler gehen könnte?

**Comment by JirkaDellOro** [comment]
Lass uns auf Discord gehen

**Comment by JirkaDellOro** [comment]
Hat's geklappt mit dem neuen Datenbank-User?
