### ISSUE TITLE
Frage zu Canvas

### ISSUE THREAD

**Issue by helenareimold** [JirkaDellOro/EIA2-Inverted#277]
Hello :)

ich hätte eher eine Frage als ein Problem. Ich bin gerade an meinem Canvas Teil, dabei ist mir aufgefallen, dass beim ersten Klick auf die Leinwand der Mond immer grau umrandet wird (habe ihn nur gefüllt), danach verschwindet es wieder. Ich wollte nur fragen woran das liegen könnte, bevor ich weitermache und der Mond evtl. mit weiteren Objekten verknüpft wird etc. Einfach mit strokeStyle = "black" geht es nicht.
Danke schon mal! :)

Meine Datei:
https://github.com/helenareimold/helenareimold.github.io/tree/master/ENDABGABE/Client
https://github.com/helenareimold/helenareimold.github.io/blob/master/ENDABGABE/Client/main.ts

**Comment by JirkaDellOro** [comment]
Auf die Schnelle, ohne in deinen Code zu schauen: irgendwann kommt nachdem Du den Mond gefüllt hast wohl noch ein `stroke`-Befehl. Vielleicht schon direkt beim Mondmalen? An anderer Stelle wird vielleicht dann die Linienfarbe gesetzt, weshalb der Mond beim nächsten Zeichnen einen Rand erhält. 

Wenn Du einen Link zur App auf Pages schickst, schauen wir rein.
