### ISSUE TITLE
tsconfig.json (?)

### ISSUE THREAD

**Issue by Sahertia** [JirkaDellOro/EIA2-Inverted#280]
![Screenshot (7)](https://user-images.githubusercontent.com/43846894/107878803-46cf1d00-6ed5-11eb-8cca-243077513c70.png)

Seit der Installation via npm von Types von MongoDB & Node usw. will meine tsc: watch / build nicht mehr, what happened?

**Comment by sailerco** [comment]
Kommt der gleiche Fehler wenn du auf Terminal gehst und dann "Run Build Task"?
![image](https://user-images.githubusercontent.com/63914083/107955269-dfc96b00-6f9d-11eb-981f-3651653d11a8.png)

**Comment by JirkaDellOro** [comment]
Hatte sich das nicht erledigt @Sahertia ? Dann bitte den Issue schließen
