### ISSUE TITLE
Rakete wird im Canvas nicht dargestellt

### ISSUE THREAD

**Issue by FranziskaFuchs** [JirkaDellOro/EIA2-Inverted#281]
Hallo, 
in meiner firework.ts wird meine Rakete erstellt und je nachdem welchen Typ der Nutzer auswählt soll einer der switch-cases ausgeführt werden und dann im anschluss die Rakete gezeichnet werden. Wenn ich mir den Typ ausgeben lasse, wird der richtige von der main.ts an die firework.ts übergeben, das wird mir auch in der Konsole angezeigt und ich bekomme keinerlei Fehlermeldungen.Allerdings geht es nicht durch die Cases hindurch und wählt dann den richtigen aus, es springt immer sofort zu default. Und gibt dann Wrong Type aus und zeichnet eben keine Rakete.

Hättest du vielleicht einen Tipp woran das liegen könnte?

https://github.com/FranziskaFuchs/Endabgabe-Feuerwerk
https://franziskafuchs.github.io/Endabgabe-Feuerwerk/Client/index.html

**Comment by JirkaDellOro** [comment]
Ich denke schon:           

In deinem `switch` lässt Du `_particleType` gegen eine Zahl  prüfen
```typescript 
 switch (_particleType) {
                case 0:   ....
```
der Parameter wird auch im Kontruktor brav als Zahl deklariert
```typescript 
        constructor(_position: Vector, _particleType: number, _color: string, _speed: number, _amount: number, _particleRadius: number, _lifetime: number) {
```
Der zweite Parameter beim Aufruf ist `ExplosionValue` (hier solltest Du an der Namensgebung arbeiten, sie widerspricht dem Styleguide und es ist auch unintuitiv, dass aus ExplosionValue particleType wird)
```typescript 
      let firework: Firework = new Firework(tempPosition, ExplosionValue, LifetimeValue, ColorValue, AmountValue, TypeValue, particleSizeValue * fps / 2);
```
`ExplosionValue` aber ist vom Typ `any` also nicht spezifiziert. Der `value` eine HTMLInputElementes ist aber immer vom Typ `string`
 ```typescript 
       let ExplosionValue: any = ExplosionTarget.value;
```

Deswegen ist es wichtig, sich über die Typen Gedanken zu machen und nur in absoluten Ausnahmefällen `any` zu nutzen. Ändere den Typ von `ExplostionValue` zu `number` und  VSCode wird dich sofort darauf aufmerksam machen, dass hier etwas nicht stimmt.

**Comment by FranziskaFuchs** [comment]
Ich habe die Typen jetzt angepasst und mit 

let explosionValue = Number(explosionTarget);

versucht aus dem String Wert eine Number zu machen, damit der Wert anerkannt wird. In VS bekomme ich auch keine Fehlermeldung, aber wenn ich das Programm laufen lasse, wird mir beim klicken auf den Canvas in der Konsole NaN zurückgegeben, weshalb es anscheinend immer noch den falschen Typen bekommt. 

Bin ich damit auf dem richtigen Weg oder sollte ich einen ganz anderen Ansatz versuchen?

**Comment by sailerco** [comment]
Du nimmst das gerade noch das gesamte HTMLElement und versuchst es zu einer Nummer zu machen:
    
```ts
let explosionTarget = document.getElementById("explosion");
let explosionValue = Number(explosionTarget);
```
Das geht natürlich nicht. Stattdessen musst du auf den Value zugreifen. (Falls explosion ein InputElement ist)

```ts
let explosionTarget = document.getElementById("explosion");
let explosionValue = Number(explosionTarget.value);  
```

**Comment by FranziskaFuchs** [comment]
Danke dir für diesen Tipp, dadurch wird mir jetzt der ausgewählte Typ als Zahl in der Konsole angezeigt und nicht mehr NaN, allerdings wendet mein Code immer noch nicht den richtigen case an und wählt immer noch "wrong type".
Dann wird wahrscheinlich immer noch der falsche Typ übergeben oder?

**Comment by sailerco** [comment]
Ah du überprüfst ja _particleType in dem Switch Case! ParticleType ist ein Select Element bei dir und die values sind keine Zahlen oder? In dieser Zeile gibt dir debugger auch ein NaN aus. 
```ts
let particleTypeTarget: HTMLSelectElement = <HTMLSelectElement>document.getElementById("particleType");
let particleTypeValue = Number(particleTypeTarget.value);
```
Probiere hier mal ein einfach console.log(particleTypeTarget.value)
Es könnte sein das dann keine Zahl ausgegeben wird.

**Comment by FranziskaFuchs** [comment]
Nein die Zahlen sind als String definiert und der wird mir dann auch in der console ausgegeben.
Also console.log(particleTypeTarget.value) gibt mir dot aus .

Muss ich dann die values vom Particle Type Select Element verändern?

**Comment by sailerco** [comment]
Du kannst die Values des Select Elements zu Zahlen ändern (Also statt "Rechteck" z.B. "1") oder du übergibst dem constructor ein String (also particleTypeTarget.value), und fragst dann im switch case Worte statt Zahlen ab.
```ts
constructor(_position: Vector, _particleType: string, _color: string, _speed: number, _amount: number, _particleRadius: number, _lifetime: number) {

//code

switch(_particleType) {
        case "Rechteck": //code
        case "dot":
```
_particleType muss dann natürlich auf vom Typ String sein

**Comment by FranziskaFuchs** [comment]
Vielen Lieben dank für deine Hilfe! Jetzt wird meine Rakete dargestellt.
