### ISSUE TITLE
Problem mit tslint

### ISSUE THREAD

**Issue by theresagut** [JirkaDellOro/EIA2-Inverted#283]
<img width="1440" alt="Bildschirmfoto 2021-02-15 um 14 41 04" src="https://user-images.githubusercontent.com/43847022/107953831-f5d62c00-6f9b-11eb-9d0e-3ccb2d1de406.png">
Hi, bei mir zeigt es diese Fehlermeldung an.. Ich hab es installiert aber kann von meinem Laptop nicht drauf zu greifen. Könnt ihr mir helfen?

**Comment by sailerco** [comment]
Kannst du mal den kompletten Fehlercode zeigen? Hattest du TSLint davor nicht installiert?

**Comment by theresagut** [comment]
<img width="1179" alt="Bildschirmfoto 2021-02-15 um 14 56 55" src="https://user-images.githubusercontent.com/43847022/107955420-0edfdc80-6f9e-11eb-8f94-7b0ce03dfa4a.png">
ja klaro hier der Fehlercode: 


Ich hatte es auf jeden fall installiert aber es hat mir trotzdem die Fehlermeldung angezeigt. Dann wollte ich es eben nochmal installieren aber das geht nicht

**Comment by sailerco** [comment]
Unten rechts kannst du mal auf Manage Libary Execution klicken und schauen was dir da vorgeschlagen wird.

Kannst du mal die Admin Rechte von dem File überprüfen?

**Comment by theresagut** [comment]
<img width="495" alt="Bildschirmfoto 2021-02-15 um 15 47 07" src="https://user-images.githubusercontent.com/43847022/107960544-11920000-6fa5-11eb-8ae9-f0784951653f.png">
dann kommt das

**Comment by sailerco** [comment]
Enable das mal

**Comment by theresagut** [comment]
<img width="1184" alt="Bildschirmfoto 2021-02-15 um 16 04 03" src="https://user-images.githubusercontent.com/43847022/107962606-6df61f00-6fa7-11eb-8579-0acaa4e0afa4.png">
dann hab ich trotzdem noch diese Fehlermeldung

**Comment by sailerco** [comment]
Dann probier nochmal bitte "npm install tslint".

Ich befürchte jedoch das nochmal das selbe passiert..

**Comment by theresagut** [comment]
der fehlercode bleibt der selbe...

**Comment by theresagut** [comment]
ich kann auch mein neuen Ordner (habe es nochmal neu strukturiert) nicht auf github pushen *HILFEEEE*

**Comment by theresagut** [comment]
beziehungsweise es pusht aber es wird mir in github nicht angezeigt

**Comment by JirkaDellOro** [comment]
In der Beschreibung zur Extension steht
```plaintext
Workspace Library Execution
By default this extension will not load TSLint or custom rules from your workspace if you are using a global version of TypeScript. This is done for security reasons. The extension always allows using globally installed versions of TSLint (npm install -g tslint).

To use enable using a local TSLint install and custom rules from the workspace, you must either:

Use a workspace version of TypeScript that is installed alongside TSLint.

Enable workspace library execution by running the TSLint: Manage Workspace Library Execution command.

If the extension detects a workspace version of TSLint, it will show a warning in the editor and in the status bar. You can click on the status bar entry to configure Workspace Library Execution as well.
```

Sehr sicher hat es nichts mit dem Pushen auf Github zu tun . Ich schlage eine Discord oder Alfaview-Sitzung vor

**Comment by theresagut** [comment]
ich hab ab sofort Zeit :sparkles:

**Comment by theresagut** [comment]
theresagut
#4643 

das ist mein Discord Account name

**Comment by JirkaDellOro** [comment]
https://discord.gg/MHJS5ZZb
