### ISSUE TITLE
Steckbrief wird nicht upgedatet

### ISSUE THREAD

**Issue by amandaauer** [JirkaDellOro/EIA2-Inverted#284]
Ich wollte meine Endabgabe hochladen und sie ist auch sichtbar auf der Kursseite, aber wenn man die Verinkung anklicken will, führt es zu einem Error 404. DIe Seite findet den Link nicht und ich bin seit einer Stunde am Hochladen...

**Comment by AnnaLotz** [comment]
Es sieht so aus, als hättest du ein neues Repository für die Endabgabe gemacht, hast du dort auch "pages" unter den settings aktiviert?

**Comment by amandaauer** [comment]
Hat funktioniert danke!

**Comment by JirkaDellOro** [comment]
@amandaauer Magst Du den Issue dann schließen, bitte?
