### ISSUE TITLE
Sommer 21: Startklar

### ISSUE THREAD

**Issue by JirkaDellOro** [JirkaDellOro/EIA2-Inverted#285]
Bitte hier kurz reinposten, wenn Du startklar im Sinne der Aufgaben "L00_Preparation" bist.

Falls Du aber auf Probleme gestoßen bist, diese bitte nicht hier reinposten und damit den Thread kapern, sondern einen neuen Issue dafür öffnen. Wir freuen uns darüber!

**Comment by AlexanderGritzfeld** [comment]
Bin bereit (hoffe ich)

**Comment by rauvanja** [comment]
Startklar ;)

**Comment by LuciaRot** [comment]
Ich bin startklar :smile:

**Comment by AlessCh** [comment]
Startklar :frog:

**Comment by Kindazure** [comment]
Hi ich bin startklar :fire:

**Comment by LercheKa** [comment]
Startklar :ok_hand:

**Comment by hannahdue** [comment]
Ich bin startklar :raising_hand:

**Comment by tschuulez** [comment]
Startklar :tropical_fish:

**Comment by Lisawa23** [comment]
Startklar :)

**Comment by stinglmo** [comment]
Startklar :)

**Comment by dinomujicc** [comment]
Startklar Chef

**Comment by TimNees** [comment]
Ich bin startklar :raised_hands:

**Comment by himmelju** [comment]
Ich bin startklar :)

**Comment by katrinmasson** [comment]
Startklar! :honeybee:

**Comment by halisco** [comment]
Startklar:)

**Comment by sophiealexandra2** [comment]
Startklar 😸

**Comment by Faiiler** [comment]
I'm ready captain :shipit:

**Comment by huuthien1999** [comment]
Startklar :alien:

**Comment by MonaKabelka** [comment]
Startklar :hatched_chick:

**Comment by neelerau** [comment]
Startklar :grin:

**Comment by evabreuninger** [comment]
startklar :)

**Comment by tonybree** [comment]
_"Code korrekt...

Das Portrait hat das falsche Maß! Gefordert sind 85 x 110 Pixel"_

Das Portrait, welches ich hochgeladen habe, hat eigentlich die richtige Größe.
Meinen Steckbrief sehe ich aber nicht, vielleicht brauche ich einfach noch ein wenig Geduld. :sweat_smile:

**Comment by AlexanderGritzfeld** [comment]
Nach anfänglichen Strapazen und Kopfzerbrechen nun auch am Bord Käptn

**Comment by sarahmohring** [comment]
startklar  :koala:

**Comment by Tristan-Trefz** [comment]
Ich bin startklar :100:

**Comment by tonybree** [comment]
Startklar 😄

**Comment by MonkeyFist97** [comment]
Ready to Rock´n´Roll! 👊

**Comment by vschwan** [comment]
startklar 🐐

**Comment by misterhko** [comment]
Ebenso startklar :metal:

**Comment by Max108fr** [comment]
Startklar :)

**Comment by MariiaKolkutova** [comment]
Startklar :)

**Comment by christinadae** [comment]
startklar ...

**Comment by nina1827** [comment]
Nach einigen Schwierigkeiten auch starklar :revolving_hearts:

**Comment by fionavi** [comment]
startklar :turtle:

**Comment by celinesophie** [comment]
Startklar ✨

**Comment by MartinFuhr-design** [comment]
Startklar :)

**Comment by LukasMuschal** [comment]
Ich bin ready 👍

**Comment by EdwinBrill** [comment]
Startklar 

( Φ ω Φ )

**Comment by LaraMMue** [comment]
Startklar! :sunflower:

**Comment by Louciandra** [comment]
Startklar 👍

**Comment by hahnlili** [comment]
Startklar
