### ISSUE TITLE
Anmeldung Kursseite (Wiederholer)

### ISSUE THREAD

**Issue by halisco** [JirkaDellOro/EIA2-Inverted#286]
Hallo Jirka,

Da ich auf der Kursseite bereits angemeldet bin habe ich keinen Zugriff auf die aktuellen Kursseite, sondern sehe noch die Steckbriefe vom letzten Semester. In der Aufgabe L00 ist ja der selbe Link zur Kursseite aufgeführt.
Soll ich einfach einen neuen Steckbrief registrieren? oder wie komm ich sonst auf die aktuelle Kursseite?
Danke:)

**Comment by JirkaDellOro** [comment]
Hallo... nein, Du bist zu schnell. Ich muss die Kursseite noch vorbereiten, es gibt keine aktuelle. Mache ich morgen früh

**Comment by halisco** [comment]
Alles klar, Danke für die Info.
