### ISSUE TITLE
Portrait hat die falschen Maße

### ISSUE THREAD

**Issue by LercheKa** [JirkaDellOro/EIA2-Inverted#288]
Ich bekomme immer diese Meldung "Code korrekt... Das Portrait hat das falsche Maß! Gefordert sind 85 x 110 Pixel", wodurch ich meinen Steckbrief nicht registrieren kann. Hab 3 verschiedene Bilder mit den richtigen Maßen versucht, eins davon war aus dem Startpaket und das andere hab ich letztes Semester verwendet.

**Comment by KohlerAl** [comment]
Hallo :)
Die Fehlermeldung mit dem falschen Bild taucht auch auf, wenn der falsche Link verwendet wurde. Hast du denn den Pages-Link verwendet?
