### ISSUE TITLE
L00: Aufklappbare Menüs nicht direkt erkennbar

### ISSUE THREAD

**Issue by AnnaLotz** [JirkaDellOro/EIA2-Inverted#289]
In L00 habe ich nur durch Zufall bemerkt, dass man die zwei Punkte ausklappen kann.
![image](https://user-images.githubusercontent.com/37657636/111487603-cb14fa00-8738-11eb-8cc4-1677c49541b1.png)
![image](https://user-images.githubusercontent.com/37657636/111487657-d7995280-8738-11eb-8864-e43631149263.png)

@JirkaDellOro Dies sollte vllt. farblich oder irgendwie anders hervorgehoben werden.

**Comment by JirkaDellOro** [comment]
Ist schon so etwas wie ein Easteregg, aber eigentlich soll da ein Klapp-Pfeilchen sein. Das Stylesheet der Pages-Version scheint den zu vernichten.

@DavidNiemann : schau da mal in einer ruhigen Minute rein

**Comment by JirkaDellOro** [comment]
Hoppla, das ging schnell 👍
