### ISSUE TITLE
Startklar? Nö

### ISSUE THREAD

**Issue by tonybree** [JirkaDellOro/EIA2-Inverted#290]
_"Code korrekt...

Das Portrait hat das falsche Maß! Gefordert sind 85 x 110 Pixel"_

Das Portrait, welches ich hochgeladen habe, hat eigentlich die richtige Größe.
Meinen Steckbrief sehe ich aber nicht, vielleicht brauche ich einfach noch ein wenig Geduld. 😅

**Comment by AlexanderGritzfeld** [comment]
Bei mir war das selbe Problem. Nicht den .com Link verwenden der im Browser steht, sondern den von GitHub Pages. Findest du in den Settings von GitHub

**Comment by AlexanderGritzfeld** [comment]
Der Link sollte dann so aussehen https://alexandergritzfeld.github.io/EIA2/  dann noch den Ordnernamen im Link manuell hinzufügen wo der Krempel liegt und dann wird (vielleicht, hoffentlich, eventuell)

**Comment by tonybree** [comment]
Jo das hab ich gemacht

**Comment by AlexanderGritzfeld** [comment]
> 
> 
> Jo das hab ich gemacht

Hat's geklappt?

**Comment by tonybree** [comment]
also ich habs von Anfang an so gemacht und die Fehlermeldung kam trotzdem

**Comment by AlexanderGritzfeld** [comment]
Hast du Lust kurz in einen Discord Call zu kommen? Vielleicht kann ich helfen?

**Comment by tonybree** [comment]
hmm muss es Discord sein? Hab nämlich keinen Account.. :D

**Comment by AlexanderGritzfeld** [comment]
Okay alfaview? Raum 19 wäre frei

**Comment by tonybree** [comment]
komme
