### ISSUE TITLE
Fehlermeldung beim aktualisieren der Steckbriefdatei

### ISSUE THREAD

**Issue by nina1827** [JirkaDellOro/EIA2-Inverted#292]
Da ich an einem neuen PC bin, wird diese Fehlermeldung wohl zustande kommen, habe aber danach auch in vsc dazu eine Fehlermeldung erhalten
![Fehlermeldung Github](https://user-images.githubusercontent.com/48830860/111601844-0e23ab80-87d3-11eb-82b6-074135a5cfa9.PNG)
![Fehlermeldung vsc](https://user-images.githubusercontent.com/48830860/111601846-0ebc4200-87d3-11eb-847a-f4766e83a95e.PNG)

**Comment by JirkaDellOro** [comment]
Gucken wir am besten gleich im Praktikum nach

**Comment by nina1827** [comment]
alles klaro :D
