### ISSUE TITLE
Aufgabe Boxes Debugger

### ISSUE THREAD

**Issue by hannahdue** [JirkaDellOro/EIA2-Inverted#295]
Huhu, 
kein wirkliches Problem, mehr Verständnisfrage: wenn bei der aktuellen Aufgabe "Boxes" die erwartete Ausgabe mit der tatsächlichen Ausgabe des Codes komplett übereinstimmt, wie soll man dann Aufgabenteil 4 mit dem Debugger machen, bzw. fällt das dann weg? Oder einfach den gesamten Code durchgehen? 
Ich bin mir nicht sicher, wo ich sinnvoll Breakpoints setzen muss.
Danke für jede Hilfe :)

**Comment by JirkaDellOro** [comment]
Spiele einfach mit dem Debugger herum. Die TraceTable zu bauen war lediglich eine Übung um zu verstehen, was der Debugger macht. In Zukunft wirst Du ihn nutzen, um deine Programmabläufe zu verfolgen. Dafür ist es natürlich absolut wichtig, mit ihm auch umgehen zu können.
