### ISSUE TITLE
Gelbe Ampel trotz Qualification

### ISSUE THREAD

**Issue by YasminElbahar** [JirkaDellOro/EIA2-Inverted#296]
hey Herr Dell'oro

Ich habe Sie vor 4 Wochen angeschrieben, da Sie meine Gruppe auf grau ändern sollten, da ich qualifiziert bin. Leider habe ich keine Rückmeldung erhalten. Heute öffne ich zufällig die Gruppe und stelle fest, dass ich eine gelbe Ampel bekommen habe. Ich habe die Alida angeschrieben und sie meinte, dass ich wahrscheinlich mit ner Roten-Ampel trotzdem zugelassen werde. Es gibt mehrere Leute, die einfach ihr Repository verlinkt haben und immer noch auf grün stehen. Soll ich mir sorgen machen ? also bzw. dass man alles neu abgeben muss. Ich brauch nur eine Bestätigung halt, dass ich nicht jede Woche die aufgaben abgeben soll.
LG

Yasmin Elbahar

**Comment by JirkaDellOro** [comment]
Hallo Yasmin,

qualifizierte Wiederholer hatten die Wahl, sich einer Gruppe anzuschließen und sich von den Betreuern auch Kommentare für die Lösungen der Wochenaufgaben abzuholen, solange sie diese abgeben, oder in die graue Gruppe zu gehen und auf Hilfestellung durch die Betreuer zu verzichten. Beides ist für die bereits erreichte Qualifikation nicht relevant. 

Von dir hatte ich keine Nachricht erhalten, dass Du explizit in die graue Gruppe möchtest. Ich ändere deine Zugehörigkeit jetzt. Alida hat nicht die Möglichkeit Ampeln zu schalten oder Gruppenzugehörigkeiten zu verändern, das kann nur ich.
