### ISSUE TITLE
Event Inspector Eventlistener 

### ISSUE THREAD

**Issue by hannahdue** [JirkaDellOro/EIA2-Inverted#297]
Hallo, ich rätsele etwas hilflos mit den Eventlistenern in der aktuellen Aufgabe herum.

Es geht um die Eventlistener für den Klick auf die unterschiedlichen Elemente. Grundsätzlich funktioniert alles, aber ich habe momentan den Eventlistener an alle Elemente einzeln gehängt: das document, den body und die divs. Wenn ich nun auf ein div klicke (das am tiefsten verschachtelte), bekomme ich logischerweise drei Ausgaben in der Konsole, eine vom document, eine vom body und eine vom div.
Wenn ich aber nur dem document einen Eventlistener anhänge, wird eben als Target auch immer nur das Document angezeigt, egal, ob ich auf ein div klicke oder sonstwohin. Und mit der Schleife durch NodeListOf die div-Elemente kann ich ja nur auf die divs zugreifen.

Nun meine eigentliche Frage: Gibt es einen Weg, nur das Element abzufangen, auf den wirklich geklickt wurde? Oder ist es letztendlich auch egal, wenn drei Konsolenausgaben kommen?

Link zur Aufgabe: https://hannahdue.github.io/EIA2/L02/EventInspector/EventInspector.html
Link zum Code: https://github.com/hannahdue/hannahdue.github.io/blob/master/EIA2/L02/EventInspector/EventInspectorScript.ts

Danke!

**Comment by JirkaDellOro** [comment]
Offensichtlich scheinst Du alles gut verstanden zu haben, das eigentliche Ziel wäre damit erreicht. 

> Wenn ich aber nur dem document einen Eventlistener anhänge, wird eben als Target auch immer nur das Document angezeigt, egal, ob ich auf ein div klicke oder sonstwohin. 

Diese Aussage sollte eigentlich nicht korrekt sein, das Target muss immer das angeklickte Element sein, unabhängig von der Position des Listeners. Schau da nochmal nach. 

> Gibt es einen Weg, nur das Element abzufangen, auf den wirklich geklickt wurde?

Die Frage verstehe ich leider nicht. Du fängst ja Ereignisse ab, nicht Elemente.

> Oder ist es letztendlich auch egal, wenn drei Konsolenausgaben kommen?

Das war die Absicht der Aufgabenstellung, so könnt ihr nochmal nachvollziehen, wie das Ereignis durch das DOM läuft.

**Comment by JirkaDellOro** [comment]
Wenn es keine Fragen mehr gibt: Issue bitte schließen

**Comment by hannahdue** [comment]
Danke! Das hat soweit auf jeden Fall weitergeholfen.
