### ISSUE TITLE
Bonusaufgabe L02_EventListener

### ISSUE THREAD

**Issue by AlexanderGritzfeld** [JirkaDellOro/EIA2-Inverted#298]
"Platziere in einem der beiden Div-Elemente einen Button. Bei Klick auf den Button soll ein Custom-Event erzeugt werden, das den DOM-Graphen aufsteigt, vom document abgefangen und auf der Konsole ausgegeben wird."

Kann mir das bitte jemand genauer erläutern? 😅 Ich check nicht so ganz was das von mir will.

**Comment by JirkaDellOro** [comment]
An welcher Stelle genau steigst Du aus?

**Comment by AlexanderGritzfeld** [comment]
Custom-Event; DOM-Graph und wie das vom document abgefangen wird.

**Comment by JirkaDellOro** [comment]
Ein Custom-Event, von einem Element "dispatched", kann die DOM-Hierarchie hochbubbeln wie ein Klick und auf einem der Elternelemente gehört werden.

Mit unsere Mehrgenerationenhaus-Metapher: stell' dir vor einer bastelt in seinem Zimmer selbst ein Paket und schickt es raus.

Hilft das?

**Comment by Lum7n** [comment]
Und wie genau fange ich es dann beim document ab, bei mir geht der path immer bis zum window?

**Comment by JirkaDellOro** [comment]
Einfach dem document einen Listener spendieren, der darauf hören kann

**Comment by JirkaDellOro** [comment]
Hat's geklappt?

Wenn es keine Fragen dazu mehr gibt: Issue bitte schließen
