### ISSUE TITLE
SetInterval läuft nicht weiter

### ISSUE THREAD

**Issue by hannahdue** [JirkaDellOro/EIA2-Inverted#299]
Hallo, ich habe eine Frage zur Funktion setInterval. Ich möchte eine Variable (timer) jede Sekunde um eins hochzählen. Die folgende Funktion habe ich dazu geschrieben (sie wird ausgelöst indem auf Start geklickt wird, die Variable timer wurde zuvor schon als number = 0 deklariert). Jedoch passiert das immer nur einmal, die Zahl wird also nicht jede Sekunde weiter hochgezählt, sondern nur jedes Mal dann, wenn ich auf Start klicke. Woran liegt das?
(noch was, von welchem Typ wäre startTimer?)
<img width="556" alt="Bildschirmfoto 2021-04-23 um 19 45 41" src="https://user-images.githubusercontent.com/56439564/115910030-a107d380-a46c-11eb-82c1-a69930dd0960.png">
Danke schonmal!!

**Comment by JirkaDellOro** [comment]
Klassiker... Du gibst bei `setInterval` gerade nicht die Funktion an, sondern deren Ergebnis, also nichts. 

PS: deklariere bitte die Funktion daher auch mit `void`, wir wollen `any` so gut wie möglich vermeiden.
