### ISSUE TITLE
Eventlistener an mehrere Elemente dranhängen

### ISSUE THREAD

**Issue by hannahdue** [JirkaDellOro/EIA2-Inverted#300]
Huhu, ich bin's nochmal... 😅 Ich scheitere gerade dabei, allen Memorykarten einen Eventlistener für einen Klick bzw. Pointerup oder was auch immer anzuhängen. Entweder erreiche ich nur das letzte oder erste Span, was durch die Schleife in den DOM gezeichnet wird. Kann mich vage erinnern, dass ich das Problem schonmal hatte und habe es damals mit der Mitgabe von Ids gelöst. Klappt aber grade auch nicht so wie ich es versucht habe. Für einen Tipp hier wäre ich sehr dankbar :)

Link zum ganzen Code: https://github.com/hannahdue/hannahdue.github.io/blob/master/EIA2/L02/Memory/MemoryScript.ts

<img width="843" alt="Bildschirmfoto 2021-04-23 um 21 52 45" src="https://user-images.githubusercontent.com/56439564/115923350-660e9b80-a47e-11eb-8481-57c69f257564.png">

**Comment by hannahdue** [comment]
Falls in Zukunft nochmal bei jemandem so ein Problem auftaucht: sine Lösung war, statt mit innerHTML mit createElement und appendChild zu arbeiten, dann hat's geklappt.

**Comment by JirkaDellOro** [comment]
Es ist grundsätzlich guter Stil mit createElement etc. zu arbeiten, dann kann VSCode auch helfen. Bei innerHTML kann man völligen Blödsinn unentdeckt reinschreiben... allerdings ist es kompakt,
