### ISSUE TITLE
Verknüpfung zweier HTML Seiten mit Skript

### ISSUE THREAD

**Issue by hannahdue** [JirkaDellOro/EIA2-Inverted#302]
Huhu, ich stehe gerade (schon eine Weile ehrlich gesagt haha) dem Schlauch, wie man die Startseite mit der Memory-Seite verbinden soll, so dass der Code weiterläuft. Ist es ein Code für beide Seiten? Funktioniert das überhaupt, grade mit zwei Load Funktionen? Oder sind es auch zwei Skripte? Wenn ja, wie bekomme ich die Werte aus der Startseite (in Variablen gespeichert) in das zweite Skript? 
Oder sollte man gar nicht zwei separate HTML Seiten machen sondern bei Klick auf den Start Button dynamisch eine neue Seite aufbauen?
Große Verwirrung grade. 😅 Bin für jede Hilfe dankbar.

**Comment by JirkaDellOro** [comment]
Es gibt unterschiedliche Ansätze. Zwei "Load-Funktionen" passen nicht, die würden ja zusammen aufgerufen. Es müssen nicht zwei separate HTML-Seiten sein, nein. Nach Klick auf Start kann das Formular einfach verschwinden und die Karten erscheinen.

**Comment by hannahdue** [comment]
Danke!
