### ISSUE TITLE
Memory Karteninhalt sichtbar/unsichtbar toggle

### ISSUE THREAD

**Issue by hannahdue** [JirkaDellOro/EIA2-Inverted#303]
Huhu, ich habe ein Problem mit dem Darstellen oder eben Verstecken des Karteninhaltes, also bei mir dem Buchstaben.
Meine Karten sind Span-Elemente, die über createElement und appendChild ins Spielfeld kommen. Aktuell ist bei umgekehrten Farben einfach Hintergrundfarbe und Schriftfarbe gleich, genau so, wie wir es eben nicht machen sollten. :D 

Mein Gedanke war jetzt, in diese Span-Elemente nochmal ein Span-Element mit dem Textinhalt des Buchstaben anzuhängen, welchem ich dann den visibilty "hidden" mitgeben kann oder eben "visible". Irgendwie klappt dann aber gar nichts mehr und ich finde nicht heraus, woran es liegt. Wie kann man das vielleicht sonst lösen? 
(Es geht hauptsächlich um die Funktionen create Cards und turnCards)

Link zum Code: https://github.com/hannahdue/hannahdue.github.io/blob/master/EIA2/L03/MemorySettings/script/MemorySettings_script.ts
Link zur Anwendung:  https://hannahdue.github.io/EIA2/L03/MemorySettings/MemorySettings.html

**Comment by JirkaDellOro** [comment]
Schnellschuss ohne den Code gesehen zu haben: der Gedanke ist gut und richtig, Du musst aber aufpassen, dass bei einem Klick auf den Buchstaben dieser Span das target ist und nicht die Karte, die dessen Elternelement ist. Also dann currentTarget statt target nutzen, wenn deine Listener an den Karten installiert sind.

**Comment by hannahdue** [comment]
Hat laaange gebraucht haha aber dann doch tatsächlich geklappt. Danke!
