### ISSUE TITLE
Memory Karten nicht doppelt anklicken

### ISSUE THREAD

**Issue by hannahdue** [JirkaDellOro/EIA2-Inverted#304]
Ich schon wieder, ich hau jetzt einfach mal alle Fragen raus, die so auftauchen, vielleicht klärt sich ja hier das ein oder andere.

1. Wie kann ich verhindern, dass man eine Karte zweimal anklickt? Da ich die Werte der angeklickten Karte speichere und dann vergleiche, wird hier zweimal der Wert der Karte mitgegeben und so ist das hier logischerweise immer ein match und die einzelne Karte verschwindet... Das sollte natürlich nicht passieren.

2. Kann man generell verhindern, dass irgendwas anderes angeklickt wird, während man die zwei Sekunden auf den Vergleich der Karten wartet? Solange die Klicklistener deaktivieren oder irgendwie sowas?

**Comment by manzijes** [comment]
Ich denke beides kann sich über eine If-Bedingung lösen lassen in der Funktion, die bei Klick ausgeführt wird.

**Comment by JirkaDellOro** [comment]
> ich hau jetzt einfach mal alle Fragen raus, die so auftauchen  

Endlich! Danach lechzen wir doch die ganze Zeit

Und Jessica hat absolut recht. Du kennst die Karte, die zuerst geklickt wurde und Du weißt, dass Du den Timer startest. Beide Informationen kannst Du in Variablen speichern und im Handler abfragen. Wenn die Karte schon geklickt war oder der Timer gerade läuft, soll der Handler einfach beenden.

**Comment by hannahdue** [comment]
Ich hab's noch nicht ganz verstanden. Welcher Handler soll beenden? Ist damit die Funktion gemeint, die aufgerufen wird, wenn ich eine Karte anklicke?
Und wie kann ich speichern, dass der Timer gestartet wird? Es ist ja nichts, was direkt gestartet wird, sondern eher eine Pause, die abgewartet wird, bis etwas gestartet wird (set timeout für zwei Sekunden). 😅

**Comment by manzijes** [comment]
Ja, ich denke die Funktion war gemeint.
Du kannst die Information, ob der Timer gerade läuft, in einer booleschen Variable speichern. Solange der Timer läuft, gibst du ihr den Wert true. Sonst gibst du ihr den Wert false. Diesen booleschen Wert kannst du in einer If-Bedingung benutzen.
Das wäre zumindest mein Ansatz, ich hoffe das hilft dir weiter.

**Comment by hannahdue** [comment]
Danke! Ja, das macht Sinn. Und wie verhindere ich dann den Klick auf eine weitere Karte (wenn bereits zwei angeklickt wurden)? Hast du von allen Karten den Eventlistener entfernt und ihn danach wieder hinzugefügt oder wie kann man das machen?

**Comment by manzijes** [comment]
> Danke! Ja, das macht Sinn. Und wie verhindere ich dann den Klick auf eine weitere Karte (wenn bereits zwei angeklickt wurden)? Hast du von allen Karten den Eventlistener entfernt und ihn danach wieder hinzugefügt oder wie kann man das machen?

Natürlich gibt es nicht nur eine Lösung dafür. Aber ich sag mal: Wie viele Karten bereits geklickt wurden ist eine Information, die du ebenfalls ganz einfach speichern und verwenden kannst.

**Comment by stinglmo** [comment]
andere Möglichkeit: Du sagst, dass deine Karten nur aufgedeckt werden können, wenn die Länge des Arrays in das du die Karten pushst nicht größer als 2 ist, sie die verdeckte Klasse haben und damit du nicht auf eine Karte doppelt klicken kannst musst du noch sagen, dass die gezogene Karte nicht die Karte ist, die sich an erster Stelle im Array befindet

**Comment by hannahdue** [comment]
Danke für eure Hilfe! :) Hat jetzt geklappt, mit deinem ersten Tipp, Mona 😊
