### ISSUE TITLE
Uncaught SyntaxError: Unexpected token ':'

### ISSUE THREAD

**Issue by Tristan-Trefz** [JirkaDellOro/EIA2-Inverted#305]
Guten Tag,

Beim laden meiner Seite bekomme ich diesen error "Uncaught SyntaxError: Unexpected token ':'" - ich komme aber nicht dahinter was das Problem ist.

Ich habe ein screenshot von dem Error und meinem Code angehaengt.

Bin für jede Hilfe dankbar

![skript fehler](https://user-images.githubusercontent.com/72923157/116681188-ec5e3c80-a9ac-11eb-9615-806a80bf9677.PNG)
![form skript](https://user-images.githubusercontent.com/72923157/116681308-1c0d4480-a9ad-11eb-95be-9e6de9515625.PNG)
![form HTML](https://user-images.githubusercontent.com/72923157/116681351-292a3380-a9ad-11eb-9c3c-1e210bfa7ab9.PNG)

Tristan

**Comment by JirkaDellOro** [comment]
Hast Du sicher kompiliert`? Der Browser reagiert auf Fehler im Javascript-Kompilat, versucht dir aber die Zeile in der Typescript-Datei anzuzeigen. Wenn die nicht miteinander korrelieren, wirkt das seltsam

**Comment by Tristan-Trefz** [comment]
oh maaaaan!

 Ja der Kompiler war am laufen aber ich hatte die .ts datei in meiner HTML seiter verlinkt anstatt .js! Danke fuer den Hinweis :)
