### ISSUE TITLE
Auf Radiobutton zugreifen

### ISSUE THREAD

**Issue by halisco** [JirkaDellOro/EIA2-Inverted#306]
Hallo habe kurz eine Frage zur Implementation der aktuellen Aufgabe.
Wie kann ich auf einen gewählten RadioButton über mein Script zugreifen? Bei Elementen wie dem Number-Stepper oder der Range kann ich ja einfach auf den aktuellen value zugreifen. Aber wie schaffe ich es auszuwerten welcher RadioButton gewählt ist und welcher nicht? Ich habe hierfür keine richtige Lösung gefunden...

**Comment by JirkaDellOro** [comment]
Das Formdata-Objelt speichert den Wert einer Radiobutton-Gruppe so wie die anderen auch mit `Name der Gruppe` und dem `Wert des selectierten Elements`. Wenn Du das HTMLElement brauchst, muss Du suchen welches dieser Gruppe das Attribute `checked` besitzt. Siehe auch den Code `FormElements.ts` der Übungen in der Lektion.

**Comment by halisco** [comment]
Danke... Die Antwort hat mir den richtigen Anstoß gegeben! 👍
