### ISSUE TITLE
Type 'FormData' is not an array type or a string type

### ISSUE THREAD

**Issue by Tristan-Trefz** [JirkaDellOro/EIA2-Inverted#307]
Guten Tag,

Wenn ich versuche mein _document.form[0]_ auszuwerten mithilfe von _for (let entry of formData)_ bekomme ich in VS Code den error "Type 'FormData' is not an array type or a string type". Im browser wird _entry_ als undifined angegeben und es gibt keine Ausgabe in der Konsole.

Auf Google konnte ich auch nichts dazu finden, also bin ich um jede Hilfe dankbar!

Tristan
![Screenshot (177)](https://user-images.githubusercontent.com/72923157/116780509-9e653980-aa7d-11eb-87ea-0e934c21fc55.png)
![Screenshot (176)](https://user-images.githubusercontent.com/72923157/116780511-9efdd000-aa7d-11eb-8be9-13ce48807a97.png)

**Comment by JirkaDellOro** [comment]
Kommt bekannt vor. Probier' mal:

`for (let entry of formData.entries())`

und prüfe, welche TypeScript-Version bei dir läuft

**Comment by Tristan-Trefz** [comment]
Leider kam bei _for (let entry of formData.entries())_ in VS Code der Error: Property 'entries' does not exist on type 'FormData'.

Nach etwas rumgooglen habe ich in meiner tsconfig.json datai die Target von es5 zu es6 geaendert welches den error verschwinden lassen hat - allerdings ist _entry_ immernoch undifined und eine Konsolenausgaben gibt es auch nicht.

Meine TS Version ist 4.1.3

**Comment by Tristan-Trefz** [comment]
Es funktioniert jetzt, bin mir nicht sicher wieso aber hat sich geklaert!

**Comment by Tristan-Trefz** [comment]
Es funktioniert jetzt, bin mir nicht sicher wieso aber hat sich geklaert!
