### ISSUE TITLE
Lektion 8

### ISSUE THREAD

**Issue by stinglmo** [JirkaDellOro/EIA2-Inverted#308]
Ich bin bei dem Test zum CanvasRenderingContext auf das Problem gestoßen, dass ich die folgenden Zeilen nicht so übernehmen konnte, weil das Ergebnis auch hätte null sein können. 

let canvas: HTMLCanvasElement = document.querySelector("canvas");
let crc2: CanvasRenderingContext2D = canvas.getContext("2d");

Dementsprechend muss man (wie bereits gelernt) überprüfen, ob es (in dem Fall) ein CanvasElement gibt, richtig? 

let canvas: HTMLCanvasElement | null = document.querySelector("canvas");
let crc2: CanvasRenderingContext2D;
if (canvas)
crc2 = <CanvasRenderingContext2D>canvas.getContext("2d");

so wird mir jedenfalls nichts unterstrichen. Ist das dann so immer zu verwenden? oder wie kann ich sonst das Canvas anfordern und eine Referenz darauf speichern? 

Danke schonmal im Voraus :)

**Comment by GinaCrivellin** [comment]
Hatte das gleiche Problem, und bei mir ging es als ich in die Script-Angabe im HTML "defer" mit rein  gemacht habe. :)

**Comment by JirkaDellOro** [comment]
Das sind zwei unterschiedliche Aspekte.

Bitte benutzt nicht mehr `defer`, sondern holt euch den Canvas in einem Load-Handler, dann ist das HTML interpretiert und der Canvas existiert.

Monas Frage bezieht sich auf die Warnung des Compilers, dass es ja sein könnte, dass auch nach der Interpretation kein Canvas existiert, weil vielleicht gar kein entsprechender Tag in der HTML-Datei angegeben ist. Und Mona, so wie Du es schreibst ist es genau richtig. Es gibt aber noch andere Optionen:

1.
```typescript
let canvas: HTMLCanvasElement = <HTMLCanvasElement>document.querySelector("canvas");
crc2 = canvas.getContext("2d");
```
Der Ausdruck in den spitzen Klammern ist eine sogenannte Type-Assertion. Damit gibst Du an, dass TypeScript was auch immer das Ergebnis von `querySelector` ist, als HTMLCanvasElement betrachten soll und übernimmst die Verantwortung. Alternativ kannst Du auch hinten dran `as HTMLCanvasElement` schreiben.

2.
```typescript
let canvas: HTMLCanvasElement | null = document.querySelector("canvas");
crc2 = canvas!.getContext("2d");
```
Das ist noch knapper und sehr unauffällig. Mit dem Ausrufezeichen gibst Du dem Compiler den Hinweis, dass `canvas` auf keinen den Wert `null` hat und der Fall nicht betrachtet werden soll.

Probier' mal....

**Comment by stinglmo** [comment]
Vielen Dank für die ausführliche Antwort!

**Comment by stinglmo** [comment]
Die erste Variante hatte ich auch schon ausprobiert, weil du uns das so ja auch schon mal erklärt hast, allerdings funktioniert das nur, wenn ich beim crc2 ebenfalls sage, dass es als CanvasRenderingContext2D existiert. 

let canvas1: HTMLCanvasElement = <HTMLCanvasElement>document.querySelector("canvas");
crc2 = <CanvasRenderingContext2D>canvas1.getContext("2d");

**Comment by stinglmo** [comment]
Also so: 

let canvas1: HTMLCanvasElement = <HTMLCanvasElement>document.querySelector("canvas");
crc2 = <CanvasRenderingContext2D>canvas1.getContext("2d");

**Comment by JirkaDellOro** [comment]
> wenn ich beim crc2 ebenfalls sage, dass es als CanvasRenderingContext2D existiert.  

Ich verstehe leider nicht, wie Du das meinst.

**Comment by stinglmo** [comment]
"<CanvasRenderingContext2D>" das müsste ich ebenfalls schreiben bevor ich die Referenz auf crc2 speichere. Hatte ich auch so eingegeben, aber irgendwie wird das, sobald ich es abschicke unsichtbar :D

**Comment by stinglmo** [comment]
okay, jetzt wird es auch einfach gelöscht :D Erneuter Versuch:
`<CanvasRenderingContext2D>`

**Comment by stinglmo** [comment]
`<CanvasRenderingContext2D>` das müsste ich ebenfalls schreiben bevor ich die Referenz auf crc2 speichere. Hatte ich auch so eingegeben, aber irgendwie wurde das gelöscht, weil ich es nicht als Codeblock hier auf GitHub geschrieben habe :D

**Comment by JirkaDellOro** [comment]
Achso. Ja, wird dasselbe sein, das kann man auch hier lesen:
https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/getContext

"returns a drawing context on the canvas, or null"

**Comment by JirkaDellOro** [comment]
Das Ganze passiert im Übrigen nur, weil wir den Linter und den Compiler so scharf eingestellt haben, dass sie ständig mit erhobenem Zeigefinger arbeiten. Nervt manchmal, aber so lernt man, was eigentlich passiert und muss nicht die Fehler erst im Nachhinein suchen.

**Comment by stinglmo** [comment]
Okay Dankeschön :)
