### ISSUE TITLE
Pattern

### ISSUE THREAD

**Issue by GinaCrivellin** [JirkaDellOro/EIA2-Inverted#309]
Ich habe eine Frage zu den Patterns, die man mit dem Canvas erstellen kann.

Das Beispiel in der Lektion war:

let pattern: CanvasRenderingContext = document.createElement('canvas').getContext('2d');
pattern.canvas.width = 40;
pattern.canvas.height = 20;

pattern.fillStyle = '#fec';
pattern.fillRect(0, 0, pattern.canvas.width, pattern.canvas.height);
pattern.moveTo(0, 10);
pattern.lineTo(10, 10);
pattern.lineTo(20, 0);
pattern.lineTo(30, 0);
pattern.lineTo(40, 10);
pattern.lineTo(30, 20);
pattern.lineTo(20, 20);
pattern.lineTo(10, 10);
pattern.stroke();

crc2.fillStyle = crc2.createPattern(pattern.canvas, 'repeat');
crc2.fillRect(0, 0, canvas.width, canvas.height);

In der ersten Zeile: 
"let pattern: CanvasRenderingContext = document.createElement('canvas').getContext('2d');" wird eine let angelegt, und mit dem "create Element" ein Canvas erstellt.

Schreibe ich aber:
let canvas: HTMLCanvasElement = document.querySelector("canvas")!;
let pattern: CanvasRenderingContext2D = canvas.getContext("2d")!;
also erstelle ich die beiden getrennt, entsteht das Pattern bei mir nicht.

Macht die erste Schreibweise also etwas anderes? Ich dachte es würde auf das Gleiche heraus kommen wenn ich die beiden einzelnd erstelle. Oder liegt es an etwas anderem? :)

**Comment by JirkaDellOro** [comment]
Du musst unterscheiden zwischen dem Canvas, mit dessen Hilfe Du das Pattern erstellst, und dem, auf dem Du es dann anwenden willst. 

Deswegen wird in der Lektion extra ein Canvas erzeugt, der mit der Variable `pattern` referenziert und auf dem das Pattern definiert wird. Das so definierte Pattern kommt dann aber mit `crc2.fillStyle` zum Einsatz, und dieser Context bezieht sich dann auf einen anderen Canvas, der vielleicht mit `querySelector` im DOM gefunden wurde.

**Comment by GinaCrivellin** [comment]
Okay Super, Danke
