### ISSUE TITLE
Lektion 05 Fetch & Promises

### ISSUE THREAD

**Issue by TobMer** [JirkaDellOro/EIA2-Inverted#31]
Hallo,

zu der Lektion 05 habe ich eine Frage.
Es geht eher um das Verständnis. Leider ist die Erklärung bei Fetch & Promises etwas unklar. 
Also was das macht und wofür es da ist.
(Ja ich habe es mir bestimmt 5 mal durchgelesen)

Daher freue ich mich über eine kleine Übersetzung. Dankeee.

Lg

**Comment by JirkaDellOro** [comment]
Poste hier bitte den Textabschnitt, von dem Du sprichst

**Comment by JirkaDellOro** [comment]
Oder kannst Du das nicht so genau umreißen?

In der Zwischenzeit: mag sich jemand an eine Erklärung versuchen und Tobias helfen? Ich laufe Gefahr mich einfach nur zu wiederholen, andere Blickwinkel sind vielleicht hilfreicher...

**Comment by MarkusDamm** [comment]
Mit der Funktion __fetch__ wird vom Programm eine URL aufgerufen und dabei versucht von der jeweilig aufgerufenen Seite eine __Response__ zu erhalten.
Bei der Cocktailbar beispielsweise nutzen wir __fetch__ um unseren Server aufzurufen. Dabei geben wir noch einen __Query-String__ mit, welcher die Informationen unseres Formulars enthält. Dieser __Query-String__ wird vom Server verarbeitet und dann daraus die Antwort des Servers erstellt. Genau diese Antwort ist dann die __Response__, die wir durch __fetch__ erhalten wollten.

Hoffentlich kannst du das so nachvollziehen 🙏

**Comment by Plagiatus** [comment]
Eine promise kann man sich genau so vorstellen wie es übersetzt heißt: Ein Versprechen.

Ein Versprechen von der aufgerufenen Funktion, dass sie irgendwann zu dir zurück kommt, mit dem Ergebnis (oder einem Error). Weil das ganze aber ja asynchron abläuft (das Programm also nicht darauf wartet), musst du abwarten, bis das Versprechen "eingelöst" wird. Mit dem Schlüsselwort `Promise.then()` kannst du der Promise sagen, was sie machen soll, sobald sie dann mal fertig ist mit arbeiten.

**Comment by JirkaDellOro** [comment]
@TobMer: hat sich beim Verständnis etwas gebessert oder hast Du kein Interesse mehr?

**Comment by TobMer** [comment]
Das heisst ich muss immer Promise mit angeben wenn ich ein Fetch benutze?

**Comment by JirkaDellOro** [comment]
Wo?

**Comment by TobMer** [comment]
![fetch](https://user-images.githubusercontent.com/48830884/69009633-8b2cdf80-0957-11ea-9755-15d5b450e262.PNG)

Hier ist ein teil vom code von der Cocktailbar.
Da ist das Fetch und Promise dabei.
Vielleicht wäre es für mich verständlicher wenn man den Code erklärt.

**Comment by JirkaDellOro** [comment]
Ok, das hat nur bedingt mit dem `fetch` zu tun. Wichtiger ist, dass die Funktion als asynchron gekennzeichnet ist mit `async`. Das bedeutet, dass diese Funktion nicht, wie synchrone Funktionen, durchläuft und das Endergebnis liefert, sondern dass sie intern EventListener installiert und asynchrone Prozesse startet, die irgendwann in der Zukunft erst getriggert bzw. beendet werden. Daher liefert die Funktion kein eindeutiges Endergebnis, sondern ein Versprechen (Promise), dass automatisch weiter bearbeitet wird, wenn die entsprechenden Ereignisse eintreten. 

Diesem Versprechen könnte man dafür Informationen anheften um festzulegen, was im Erfolgs- oder Misserfolgsfall zu tun ist. Im Beispiel wird aber kein Ergebnis erwartet (void) und auch keine weitere Information gegeben. Dass trotzdem Promise genutzt wird, ist durch die Markierung `async` erzwungen.

**Comment by TobMer** [comment]
Vielen Dank für die schnelle Antwort.
Ist schon etwas verständlicher geworden.
Ich geb die Hoffnung noch nicht auf [¬º-°]¬

**Comment by JirkaDellOro** [comment]
Das solltest Du auch nicht. Dank async/await können wir die Promises derzeit einfach als eine syntaktische Notwendigkeit ansehen ohne sie weiter zu untersuchen. Sie werden auch für den Rest des Kurses keine Rolle spielen.

Wenn der Issue für dich abgearbeitet erscheint: bitte schließen
