### ISSUE TITLE
Schatten von Formen wird in mehrere Funktionen übergeben

### ISSUE THREAD

**Issue by JuliaKaeppeler** [JirkaDellOro/EIA2-Inverted#310]
Hallo, folgendes Problem:
            crc2.shadowBlur = 10;
            crc2.shadowColor = "black";
ist in nur einer Funktion generiert, wird aber auch in andere Funktionen übernommen, sodass all meine Formen einen Schatten bekommen haben, aber es sollten nur die Rechtecke einen Schatten bekommen.
Frage: Wieso? Welche Möglichkeiten gibt es, dass Problem aus dem Weg zu schaffen?

**Comment by JirkaDellOro** [comment]
Ich denke, das ist eine Stil-Angabe und der Stil gilt, bis ein anderer definiert wird. Du kannst auch `crc2.save( )` ausführen lassen, bevor Du diesen Stil definierst und nach der Verwendung wieder `crc2.restore( )` aufrufen. Es wird dabei nämlich nicht nur die Transformationsmatrix gespeichert und wiederhergestellt, sondern auch alle Zeichenstile.

**Comment by JuliaKaeppeler** [comment]
Vielen Dank, teste ich!
