### ISSUE TITLE
Zufällige Größe von Bäumen

### ISSUE THREAD

**Issue by hannahdue** [JirkaDellOro/EIA2-Inverted#311]
Hallo, ich habe Bäume in meinem Bild die ich eigentlich größer werden lassen will, je weiter vorne sie stehen. Habe es versucht mit einer Bedingung, die an y geknüpft ist, aber irgendwie funktioniert das nicht so... Weiß vielleicht jemand, wo der Haken ist?
Hier ist der Code (relevante Funkion ist drawTrees): https://github.com/hannahdue/hannahdue.github.io/blob/master/EIA2/L08/GenerativeArt/GenerativeArt_script.ts
Und die Anwendung: hannahdue.github.io/EIA2/L08/GenerativeArt/GenerativeArt.html
Danke schonmal!

<img width="355" alt="Bildschirmfoto 2021-05-06 um 17 26 03" src="https://user-images.githubusercontent.com/56439564/117324550-31dca700-ae90-11eb-9e60-90c3fc1a4134.png">

**Comment by JirkaDellOro** [comment]
Ich fürchte, deine if-else-Kaskade ist falsch herum aufgebaut. Ist y>200 treffen auch alle anderen Bedingungen zu...

**Comment by hannahdue** [comment]
Hah, ja das wars! Danke!
