### ISSUE TITLE
Canvas Alley: Bäume bewegen sich nicht mit der Straße

### ISSUE THREAD

**Issue by hannahdue** [JirkaDellOro/EIA2-Inverted#312]
Hallo, bei den Übungen zur aktuellen Lektion mit dem Landschaftsbild funktioniert was bei mir nicht so, wie es sollte: das Ende der Straße wird nun zwar um einen zufälligen Wert zwischen -200 und 200 hin und her verschoben, die Bäume bewegen sich aber eben nicht mit. In der Aufgabenstellung steht ja, man soll überlegen, warum sie sich mitbewegen. Weiß jemand, woran das liegt? Hier der Code:
<img width="872" alt="Bildschirmfoto 2021-05-10 um 13 16 52" src="https://user-images.githubusercontent.com/56439564/117651549-5ab3b380-b192-11eb-98d9-4a5cae7742e3.png">
Danke!

**Comment by JirkaDellOro** [comment]
Du postest den Code für die Straße. Bei der ist aber wohl alles in Ordnung, oder? Wie sieht der Code für die Bäume bei dir aus?

**Comment by hannahdue** [comment]
Den hab ich aus deinem Code übernommen und unverändert gelassen.
