### ISSUE TITLE
Blumen von hinten nach vorne malen

### ISSUE THREAD

**Issue by stinglmo** [JirkaDellOro/EIA2-Inverted#314]
Ich würde gerne mit einer for-Schleife die Blumen von hinten nach vorne malen. 
Also die Y-Werte nacheinander durchgehen und jedes mal dann einen neuen zufälligen x-Wert erstellen lassen. 

Auskommentiert habe ich die For-Schleife die mal funktioniert hat, aber jetzt habe ich durch die Methode einiges geändert und bekomme es nicht mehr hin. 

Danke schon mal für die Hilfe :)

<img width="693" alt="Bildschirmfoto 2021-05-25 um 13 12 28" src="https://user-images.githubusercontent.com/72876317/119488767-34c60b80-bd5b-11eb-91d9-3b24be16226e.png">
<img width="583" alt="Bildschirmfoto 2021-05-25 um 13 11 37" src="https://user-images.githubusercontent.com/72876317/119488772-368fcf00-bd5b-11eb-9464-305c84541b2c.png">

**Comment by DavidNiemann** [comment]
Es macht für mich recht wenig Sinn in der Klasse eine Methode setRandomPosition zu haben.
Anstelle von y gibst du dem Objekt die Höhe mit. X lässt du zufällig generieren, wie du es schon gemacht hast. Die Methode kannst du eigentlich raus machen.

**Comment by stinglmo** [comment]
Ich habs, perfekt danke :)
