### ISSUE TITLE
Draw-Methode bei Klassen für Canvas Objekte

### ISSUE THREAD

**Issue by hannahdue** [JirkaDellOro/EIA2-Inverted#315]
Hallo, mir ist nicht ganz klar, wann ich zum constructor noch eine draw Funktion brauche... Kann ich nicht eigentlich z.B. eine Blume direkt zeichnen, wenn ich eine neue Blume erstelle? Kann es sein, dass man eine zusätzliche Draw-Methode nur braucht, wenn die Objekte sich bewegen, also ständig neu gezeichnet werden müssen, ohne dabei jedes Mal ein neues Objekt zu kreieren...?
Dann müsste ja für Objekte, die sich nicht bewegen, ein constructor reichen, der sie auch direkt aufs canvas zeichnet oder? Oder wird das trotzdem getrennt (wenn ja wieso)?
Danke schonmal! 
Liebe Grüße Hannah

**Comment by DavidNiemann** [comment]
Man sollte für jedes Objekt eine draw-Methode haben, weil sobald ein bewegendes Objekt sich darin befindet muss das komplette Bild oder mindestens der Teil wo das Objekt befindet neu gemalt werden, sonst ist das Objekt an den alten und an der neuen Position zu sehen. Wie man auch am Ende des Videos [L09_V3_ImplementationAsteroids](http://games.hs-furtwangen.de/EIA2_Video/L09_V3_ImplementationAsteroids.mp4) sehen kann.

**Comment by JirkaDellOro** [comment]
Da habt ihr beide Recht. 

@hannahdue Wenn Du weißt, dass etwas nur im Hintergrund eingebacken ist, und Du den Hintergrund als Bild abspeicherst und für die Animation als festes Bild wiederverwendest, könntest Du es auch direkt im Konstruktor zeichnen lassen. Allerdings ist es auch dann immer noch aufgeräumter, wenn es eine draw-Methode besitzt, die vom Konstruktor aus aufgerufen wird. Prinzipiell müsste man so etwas auch gar nicht in eine Klasse räumen, sondern könnte es in einer Funktion `createBackground` im Hauptprogramm zeichnen lassen. Da ist es mehr eine Frage des Stils und der Übersichtlichkeit.

**Comment by hannahdue** [comment]
Okay, danke für die Hinweise!
