### ISSUE TITLE
Error bei Typ Vector

### ISSUE THREAD

**Issue by hannahdue** [JirkaDellOro/EIA2-Inverted#316]
Hallo, neues Problem: ich wollte nun mal versuchen, die Wolke über eine Klasse zu zeichnen. Wenn ich aber eine neue Wolke erstellen will, kommt folgende Fehlermeldung:
<img width="987" alt="Bildschirmfoto 2021-05-26 um 17 21 25" src="https://user-images.githubusercontent.com/56439564/119686959-189f9880-be47-11eb-9f56-fa63c7a95606.png">
Ich verstehe nicht, wie ich die Parameter für die Position mitgeben soll. Der zweite ist doch auch ein Vektor, und dort meckert er nicht.
So sieht der constructor aus:
<img width="744" alt="Bildschirmfoto 2021-05-26 um 17 21 49" src="https://user-images.githubusercontent.com/56439564/119687105-3a008480-be47-11eb-911d-55ba9c4530c2.png">
Kann mir jemand sagen, woran das liegt, bzw. wie ich das lösen kann?
Danke!

**Comment by DavidNiemann** [comment]
Für mich sieht es aus als hattest du ein Interface Vector gehabt und es mit der Klasse ersetzt. In dem Fall musst du für die Vektoren neue Objekte erzeugen.
 `let cloud1: Cloud = new Cloud(new Vector(1150, 80), new Vector(120, 40), 15, 40);`

**Comment by hannahdue** [comment]
Okay, danke. Soll ich dann das Interface komplett löschen und alles mit diesem new Vector machen? Oder braucht es beide? Wenn ja, woher weiß das Programm, ob ich das Interface oder die Klasse meine? 😅 Bzw. wann würde ich denn was benutzen?

**Comment by DavidNiemann** [comment]
Ein Interface benutzt man, wenn man nur eine Struktur angeben will, sodass man nichts vergisst.
Eine Klasse kann noch zusätzlich noch Methoden haben. 

Also du kannst das Interface löschen.
Soweit ich weiß wird bei gleicher Benennung immer die Klasse genommen, wen du das Interface benutzen willst, musst du es umbenenne.

**Comment by hannahdue** [comment]
Okay, Dankeschön! :)
