### ISSUE TITLE
Hintergrund ohne random?

### ISSUE THREAD

**Issue by hannahdue** [JirkaDellOro/EIA2-Inverted#317]
Hallo nochmal, ich habe folgendes Problem: um die Wolken ziehen zu lassen, müsste ja für jeden frame das Hintergrundbild neu gezeichnet werden. Dabei sind jedoch Zufallswerte mit drin, weil ich nicht für jeden einzelnen der tausenden Grashalme und Blumen Farbe und Form einzeln festlegen kann... Wenn ich also nun im Intervall den Hintergrund neu zeichnen lasse, um darauf die Wolke neu zeichnen zu lassen, verändert sich ständig die ganze Wiese... 😐 gibt's eine Möglichkeit, nur die Wolke allein zu entfernen und wieder neu zu zeichnen? Oder wie könnte ich hier sonst herangehen? 
Hier ist das Programm: hannahdue.github.io/EIA2/L09/Blumenwiese2/Blumenwiese.html
Und der Code, falls notwendig: https://github.com/hannahdue/hannahdue.github.io/blob/master/EIA2/L09/Blumenwiese2/script/Blumenwiese_script.ts
Danke schonmal.

**Comment by JirkaDellOro** [comment]
Hallo Hannah, ich habe in der Aufgabenstellung einen deutlichen Hinweis untergebracht. Schon gesehen?

**Comment by hannahdue** [comment]
Hallo, tatsächlich - entschuldige. War beim ersten Lesen vor der Aufgabe wohl noch nicht so relevant und in der Zwischenzeit vergessen 😅 Danke für den Hinweis!

**Comment by JirkaDellOro** [comment]
Kein Thema. Schließen wenn durch, bitte
