### ISSUE TITLE
Blumenwiese beleben

### ISSUE THREAD

**Issue by halisco** [JirkaDellOro/EIA2-Inverted#318]
Ich komme nicht weiter mit der aktuellen Aufgab bzw. kriege es garnicht erst hin.
Ich hab keine Ahnung was ich machen soll und wie das richtigen mit den Klassen funktioniert. Ich bin komplett raus.. 
Habe mir die Videos bestimmt schon 10 mal angeschaut aber es bringt mir einfach nichts.

**Comment by JirkaDellOro** [comment]
Die Fehlermeldung ist recht unspezifisch. Wie weit bist Du denn gekommen? Hast Du die Übungen in der Lektion gemacht? Poste mal einen Link auf deinen aktuellen Code und ich stupse mal deinen Betreuer an. Hast Du dir auch mal die Lösungen der anderen zu OldMacDonald angeschaut?

**Comment by AionixX** [comment]
Hey Halis, Wenn du willst können wir uns morgen Mittag gerne mal ne Weile zusammen setzten und das ganze durch sprechen. Schreib mir einfach auf Discord dann schauen wir uns das an :)

**Comment by halisco** [comment]
Ja habe ich alles gemacht.. ich bin überhaupt nicht weit gekommen. Ich kriege es nicht mal mein bisheriges Program Klassenorientiert umzustrukturieren, dort hänge ich noch..

**Comment by halisco** [comment]
Morgen mittag wäre super! @AionixX

**Comment by AionixX** [comment]
Perfekt, dann schreib mir einfach nochmal wenn du soweit bist morgen.

**Comment by halisco** [comment]
@AionixX könntest du heute um 14:30Uhr, also in einer halben Stunde? Und wo soll das ganze Stattfinden?

**Comment by AionixX** [comment]
Ich hab noch bis ca 15:30Uhr Fachschaftssitzung. Bist dua uf dem Discord Server?

**Comment by halisco** [comment]
Ja später geht auch klar... ja bin ich.

**Comment by AionixX** [comment]
@halisco Falls alles geklärt ist jetzt bitte noch den Issue schließen :)
