### ISSUE TITLE
Reference Error & TypeError

### ISSUE THREAD

**Issue by Tristan-Trefz** [JirkaDellOro/EIA2-Inverted#319]
Hallo, ich bin kurz davor die Aufgabe abzuschliessen aber komme leider nicht weiter wegen diesen zwei Fehlermeldungen. (screenshots im Anhang)

Code ist in meiner Repository und im Steckbrief verlinkt.

Danke im Vorraus,

Tristan
![Screenshot (178)](https://user-images.githubusercontent.com/72923157/120069036-124a3000-c084-11eb-8d5f-4db1f54514e2.png)
![Screenshot (179)](https://user-images.githubusercontent.com/72923157/120069037-137b5d00-c084-11eb-9e61-a3d8c7c6a900.png)

**Comment by AionixX** [comment]
Hey, also wenn ich mir deinen Code von Github ziehe kommen bei mir diese Fehlermedlungen gar nicht. Was aber definitiv ein Problem ist, ist das du all deine Funktionen inerhalb der handleLoad Funktion geschrieben hast. Wenn ich da die Fehlende Klammer hinzufüge kommen andere Fehlermeldungen. Versuche dir anzugewöhnen zwischen drinn immer mal wieder Strg+Shift+F zu drücken für die Auto Formatierung.

**Comment by DavidNiemann** [comment]
Probiere mal:
für den ersten Fehler verschiebe einfach flowerColors an den Anfang das Skript.
Für den zweiten musst du noch imageData Initialisieren.

`imageData =   render.getImageData(0, 0, canvas.width, canvas.height);`

Die Zeile muss kommen, nachdem alles was sich nicht bewegt schon gezeichnet wurde.

**Comment by Tristan-Trefz** [comment]
Danke David, hat beides geklappt! Aber wieso musste ich flowerColors nach oben schieben? 

@AionixX bei mir kommt nur so ne komische Suche wenn ich Strg+Shift+F druecke...

**Comment by DavidNiemann** [comment]
flowerColors stand zwar vor der Funktion drawFlowers wo flowerColors benutzt wurde, aber weil der Funktionsaufruf am Anfang war, wurde flowerColors noch gar nicht initialisiert.

**Comment by JirkaDellOro** [comment]
Ist das durch? Dann bitte schließen.
