### ISSUE TITLE
Wie auf Methode der Subklasse zugreifen?

### ISSUE THREAD

**Issue by hannahdue** [JirkaDellOro/EIA2-Inverted#320]
Hallo, 
meine Tiere sind in einem Array (animals) gespeichert. Sie sind vom Typ Animal (Superklasse) und werden als new Cow etc (Subklasse) konstruiert. Wenn ich dann das Array durchlaufe, kann ich für jedes "animal of animals" die Methoden von Animal, also eat und sing ausführen lassen. Wenn ich dann aber probiere, animal.doSpecialAction() ausführen zu lassen bekomme ich eine Fehlermeldung: Property 'doSpecialAction' does not exist on type 'Animal'.

Wie kann ich die Methoden der Subklasse ausführen?

Hier der Code: https://github.com/hannahdue/hannahdue.github.io/tree/master/EIA2/L10/script

Danke schonmal!

**Comment by JirkaDellOro** [comment]
Du bist jetzt schon recht tief im nächsten Teil der Lektion und nutzt Polymorphie. Eigentlich sprechen wir nächste Woche darüber, aber ich kann es dir jetzt schon erklären. Nehme ich korrekt an, dass es ein Designtime-Error und kein Runtime-Error ist?

Es ist ja tatsächlich so, dass Animal die Methode doSpecialAction nicht kennt, denn sie ist nur in den Subklassen vorhanden. TypeScript geht davon aus, dass in deinem Array reine Animals sind, die folglich keine Spezialaktion haben. Zur Laufzeit aber würde es funktionieren, weil das Array dann ja mit Objekten der Subklassen besetzt ist, die sehr wohl die Methode kennen. Die Lösung für dich ist, dass Du in Animal auch eine Methode doSpecialAction implementierst, die einfach nichts tut (schreib' nur einen Kommentar in den Rumpf). Dann ist der Compiler zufrieden und dein System ist kohärent. Da zur Laufzeit dann aber die Objekte der Subklassen zum Einsatz kommen, werden deren Spezialaktionen genutzt, die Methode erscheint also "überschrieben".

**Comment by hannahdue** [comment]
Perfekt, danke! Ist doch schön, wenns mal eine supereinfache Lösung für etwas gibt. 😄
