### ISSUE TITLE
Designtechnischer Rat gesucht mit Blumen und Gräsern

### ISSUE THREAD

**Issue by hannahdue** [JirkaDellOro/EIA2-Inverted#322]
Hallo, wir hatten am Dienstag ja überlegt, wie ich mir merken kann, wo die Blumen stehen, damit ich sie bei jedem Update wieder dorthin zeichnen kann (und später anfliegen), und sie nicht jedes Mal neu an eine zufällige Stelle gezeichnet werden. Nun ist es bei meiner Blumenwiese ja so, dass ich auch Gräser zwischen den Blumen habe, und die ganze Wiese in Schichten gezeichnet wird (siehe hier: https://hannahdue.github.io/EIA2/L10/Blumenwiese_inheritance/Blumenwiese_inheritance.html). Deswegen haben meine Blumen gar keine Position bis jetzt, und wenn ich mir die Position irgendwie merke, würden ja alle in der gleichen Größe (weil der scale-effekt der Funktion drawMeadow/drawMeadowLayer dann wegfällt) und vor allem vor die Gräser gezeichnet werden...

Kann ich das mit dem skalieren irgendwie elegant lösen und es dann mit den Gräsern genauso machen, sodass die ganze Wiese einfach bei jedem Update neu an die gespeicherten Stellen (die Überlegung wäre, dafür ein extra Wiesen-Array anzulegen) gezeichnet wird? Oder werden das zu viele Zeichenbefehle, um es fünfzig mal pro Sekunde zu zeichnen?

Oder verabschiede ich mich lieber einfach von dem Gras und mache für die kommenden Aufgaben einfach den Hintergrund und dann die Blumen drauf, ohne die ganzen Schichten, Gras etc.? 😅

Danke für Anregungen, mein Kopf ist grade irgendwie verknotet hier...

**Comment by JirkaDellOro** [comment]
Du hast wirklich sehr schönes Gras! Es wäre schade, da ganz darauf zu verzichten. Alle Probleme, die Du ansprichst, scheinst Du aber richtig erkannt zu haben. Da wir in zwei Dimensionen unterwegs sind, stoßen animierte dreidimensionale Darstellungen genau wegen solcher Verdeckungen bald an Grenzen. Dann geht man gleich auf drei Dimensionen, was aber unseren Rahmen weit sprengen würde.

Um deine Wiese möglichst zu erhalten hätte ich folgende Vorschläge, wobei der zweite auf den ersten aufbaut.
1. Du zeichnest erst das Gras und backst das in den Hintergrund ein, nur die Blüten malst Du dann dynamisch darüber. Der Stil müsste dabei einigermaßen erhalten bleiben, aber die Verdeckungen der Blüten durch Gras geht dabei verloren.  
2. um den Verdeckungseffekt doch noch wenigstens anzunähern, stattest Du die vorderen Blumen zusätzlich noch mit zwei, drei Grashalmen aus, welche über die Blüte gemalt werden. Aufgrund der stark vertikalen Ausrichtung der Halme erwarte ich, dass es nicht auffällt, dass sie über vordere Halme gezeichnet werden.

**Comment by hannahdue** [comment]
Danke, das war hilfreich. Hab es jetzt umgebaut, hat geklappt und man sieht es kaum! :)
