### ISSUE TITLE
Nektarlevel bei meinen Tulpen

### ISSUE THREAD

**Issue by stinglmo** [JirkaDellOro/EIA2-Inverted#323]
Hello :) 
Mein Nektarlevel verändert sich nur bei den Mohnblumen und Sonnenblumen und nicht bei den Tulpen. Eigentlich habe ich alles gleich gemacht, aber irgendwo muss noch ein Fehler sein den ich nicht finde. Wenn jemand Lust hat drüber zu schauen, würde es mich freuen :)
Danke!

**Comment by JirkaDellOro** [comment]
Herzlich gern, wenn doch nur Links zum Code und zur App da wären... ☹️

**Comment by JirkaDellOro** [comment]
Setze mal einen Breakpoint auf Zeile 122 im Browser-Debugger und drücke fortwährend F8. Was fällt dir auf?

**Comment by stinglmo** [comment]
sorry, ich hätte dazuschreiben können, dass die aktuelle Version gepusht ist. 
Also wenn ich das mit dem Breakpoint in Zeile 122 mache sehe ich, dass die Tulpe häufiger erscheint als die Sonnenblumen und Mohnblumen aber gemalt wird immer erst nach einer Weile. So wirklich was anfangen kann ich damit aber leider nicht...

**Comment by stinglmo** [comment]
Also ich habe jetzt das Erstellen der Tulpen mit in die Forschleife der anderen gepackt, jetzt ändert es sich aber trotzdem merkwürdig und wird am Ende trotzdem grün :D

(Aktuelle Version habe ich gerade gepusht)

**Comment by JirkaDellOro** [comment]
"sorry, ich hätte dazuschreiben können, dass die aktuelle Version gepusht ist."  
wichtiger ist, dass Du bei den Issues Links mit reinpostest, so dass wir ganz schnell in deinem Code sind  

"aber gemalt wird immer erst nach einer Weile"  
so scheint es, tatsächlich wird aber natürlich bei jedem draw--Aufruf etwas gezeichnet.

"Also ich habe jetzt das Erstellen der Tulpen mit in die Forschleife der anderen gepackt"
Gut, dann ist dir wahrscheinlich aufgefallen, dass 30 Tulpen an exakt der gleichen Stelle gezeichnet wurden. Insgesamt hattest Du über 1000 Blumen, aber zu sehen war viel weniger. Was passiert jetzt aber immer noch 5 mal?

**Comment by stinglmo** [comment]
5 Mal wird jetzt jede Blume an die selbe Stelle gemalt ... 
habs geändert, jetzt funktioniert es auch :) Danke!
