### ISSUE TITLE
Bienen verschwinden auf mysteriöse Weise...

### ISSUE THREAD

**Issue by hannahdue** [JirkaDellOro/EIA2-Inverted#324]
Hallo,
ich habe gerade bemerkt, dass bei mir zehn Bienen am Anfang entstehen, nach einer Weile aber nur noch sechs übrig sind. Ich kann mir irgendwie nicht erklären, warum das...
Fällt es irgendjemandem hier auf? Für einen Hinweis wäre ich echt dankbar. 😅
Anwendung: https://hannahdue.github.io/EIA2/L11/Blumenwiese_advanced/Blumenwiese_advanced.html
Main: https://github.com/hannahdue/hannahdue.github.io/blob/master/EIA2/L11/Blumenwiese_advanced/script/Main.ts
Bee: https://github.com/hannahdue/hannahdue.github.io/blob/master/EIA2/L11/Blumenwiese_advanced/script/Bee.ts

Danke! Liebe Grüße
Hannah

**Comment by JirkaDellOro** [comment]
Sind nur weniger Bienen sichtbar oder tatsächlich weniger im Array? Was passiert mit den Bienen, wenn Sie unten oder oben vom Canvas fliegen?

**Comment by hannahdue** [comment]
Nein, im Array sind weiterhin alle. Na eigentlich kommen sie auf der anderen Seite wieder rein, die meisten Bienen machen das ja auch. Nur 3-4 irgendwie nicht.

**Comment by JirkaDellOro** [comment]
Oben und unten auch?

**Comment by JirkaDellOro** [comment]
Habe gerade in deinen Bienen-Code geschaut, in Zeile 97 stimmt etwas nicht, das könnte es sein...

**Comment by hannahdue** [comment]
Ohja, wunderbar, jetzt klappts! Danke, ist mir überhaupt nicht aufgefallen.
