### ISSUE TITLE
Hilfe, meine Bienen gehorchen nicht!

### ISSUE THREAD

**Issue by hannahdue** [JirkaDellOro/EIA2-Inverted#325]
Hallo,
ich hab ein komisches Problem mit den Bienen: im Moment geht es darum, dass sie zu einer Blume fliegen sollen. Sie kennen ihr Ziel und steuern es an mit dem vorgeschlagenen Ansatz, allerdings landen sie zielsicher immer irgendwo vollkommen anders. Ich kann mir vorstellen, dass es mit dem Blumen zu tun haben könnte, also dem scale/translate derer Positionen, bin mir aber nicht sicher. Selbst wenn, wo genau ist hier dann das Problem? 

Hier ist die Anwendung: https://hannahdue.github.io/EIA2/L11/Blumenwiese_advanced_2/Blumenwiese_advanced_2.html
Bienen-Code: https://github.com/hannahdue/hannahdue.github.io/blob/master/EIA2/L11/Blumenwiese_advanced_2/script/Bee.ts
Blumen-Code: https://github.com/hannahdue/hannahdue.github.io/blob/master/EIA2/L11/Blumenwiese_advanced_2/script/Flower.ts
Main: https://github.com/hannahdue/hannahdue.github.io/blob/master/EIA2/L11/Blumenwiese_advanced_2/script/Main.ts

Sieht jemand, woran es liegt?
Danke schonmal!

**Comment by JirkaDellOro** [comment]
Magst Du mal gerade in dm16 kommen oder auf Discord?

**Comment by hannahdue** [comment]
Bin in dm16

**Comment by JirkaDellOro** [comment]
Bitte kurze Lösungsbeschreibung absetzen und schließen.

**Comment by hannahdue** [comment]
Es lag an einer Transformation, die außerhalb in einer anderen Funktion durchgeführt wurde, wodurch die y-Werte verschoben waren. Diese wurde dann in die entsprechende Funktion eingefügt. Außerdem musste der y-Wert des Richtungsvektors der Biene auch mit der Skalierung der Blume verrechnet werden, hier war nur eine Klammer falsch gesetzt.
