### ISSUE TITLE
Feste Position der einzelnen Spieler

### ISSUE THREAD

**Issue by doganerd** [JirkaDellOro/EIA2-Inverted#326]
Hallo, ich bin gerade dabei die Spielerposition der Fußballer zu bestimmen und habe Probleme damit festzulegen, dass jeder Spieler an einer festen Position steht.
Ich bin mir unsicher, ob ich dafür für jeden Spieler eine neue Funktion aufbauen muss, da man mit einer random Funktion ja keine Kontrolle hätte, wo die Spieler letztendlich stehen müssen.

Hier der Link zu meinem Repo: https://github.com/doganerd/doganerd.github.io/tree/master/endaufgabe
https://doganerd.github.io/endaufgabe/fussballfeld.html

**Comment by JirkaDellOro** [comment]
Am besten wäre es, wenn ich dein Konzept finden könnte, dann kann ich gezielt und gerne helfen. 

Grundsätzlich kann ich aber schon mitteilen, dass Extramethoden nicht wirklich geschickt wären. Dann müsste man entweder eine Extraklasse für jeden Spieler oder viel Logik in die Spielerklasse nur dafür implementieren. Eigentlich brauchst Du doch nur eine Datenstruktur mit einer Menge an Informationen über mögliche Positionen auf dem Spielfeld, aus der sich die Spieler dann bedienen können.

**Comment by doganerd** [comment]
Ich konnte das Problem heute nachmittag lösen :) Habe jetzt eine feste Position für jeden Spieler und bin jetzt dabei die Animation bzw. Interaktion zu erstellen. Dennoch dankeschön!

**Comment by JirkaDellOro** [comment]
Top. Bitte Issue schließen, wenn er fertig ist.
