### ISSUE TITLE
"Property 'changeState' does not exist on type 'Window'"

### ISSUE THREAD

**Issue by GinaCrivellin** [JirkaDellOro/EIA2-Inverted#327]
Hey :)

Ich hab ein Problem mit einem Timeout, den ich in einem Eventlistener in meiner Klasse setze.

Ich habe in einem Switch case, in einem Case einen eventlistener gesetzt, der einen Timeout aufrufen soll.
Ich habe probiert die Funktion des Timeouts gleich hinten hin zu schreiben, aber auch die Funktion außerhalb des switch Case in der Klasse zu definieren.
Aber egal wie ich es versuche, das Stichwort "this", was ich für den Aufruf der Funktion außerhalb des eventlisteners brauche  funktioniert nicht mehr.
Alida meinte es ist weil das "this" sich jetzt nicht mehr auf meine Klasse bezieht sonder auf das Window wie der Fehler auch angibt.
Gibt es da eine Lösung das "this" wieder auf den Player zu beziehen?

Hier ist der Code:

case PlayerState.GotBall:
                    
                    this.setVelocity(new Vector(0, 0));

                    getBall().setVelocity(new Vector(0, 0));

                    window.addEventListener("click", function tempListener(event: MouseEvent): void {
                        moveBall(event);

                        resumeGame();
                
                        this.setTimeout(() => {
                            this.changeState();
                        },              3000);
                        
                        window.removeEventListener("click", tempListener);
                    });

                    break;

**Comment by JirkaDellOro** [comment]
Ganz knapper erster Versuch der Hilfe, morgen habe ich mehr Zeit:
- wir hatten über das this-Problem gesprochen und als Lösungsoptionen `bind` und Arrow-Functions diskutiert. Schau mal in Lektion 12, da steht einiges darüber. Vielleicht genügt dir das schon, ansonsten poste hier erneut.

**Comment by GinaCrivellin** [comment]
Hab es mit einer variable außerhalb des eventlisteners gelöst, der ich "this" zuweise und die ich dann statt this im listender aufrufe :) trotzdem danke!
