### ISSUE TITLE
Wahrnehmungsradius

### ISSUE THREAD

**Issue by doganerd** [JirkaDellOro/EIA2-Inverted#329]
Hallo, ich habe noch eine kurze Verständnisfrage:

In der Aufgabenstellung steht, dass die Spieler einen Wahrnehmungsradius von 30m haben sollen. Das heißt ja dann, dass der Durchmesser 60m ist und sich die Spieler relativ weit bewegen können oder? (Also wenn man von einem Spielfeld der Größe 100m ausgeht)

**Comment by JirkaDellOro** [comment]
Unterscheide zwischen Wahrnehmungsradius und Bewegungsradius. Bewegen können sie sich überall hin.

**Comment by doganerd** [comment]
Aha, dankeschön!
