### ISSUE TITLE
Entwickeln mit Node.js unverständlich

### ISSUE THREAD

**Issue by TobMer** [JirkaDellOro/EIA2-Inverted#33]
![Aufagbe 6_schwierig erklärt](https://user-images.githubusercontent.com/48830884/69092469-ba714880-0a4c-11ea-8104-3d2158ae12fb.PNG)

Die Anweisung zu diesem Text ist etwas unverständlich. Ich weiß leider nicht wie das funktionieren soll. Ein Bild oder eine genauere Beschreibung dazu wäre etwas besser. Habe es ausprobiert aber ging leider nicht. :)

**Comment by JirkaDellOro** [comment]
Wie hast Du es ausprobiert? Hast Du eine Konsole geöffnet und es eingetippt? Was wurde dir daraufhin angezeigt?

**Comment by JirkaDellOro** [comment]
PS: nicht die Browserkonsole, sondern eine Systemkonsole...!

**Comment by TobMer** [comment]
Im Visual Studio Code. War mir aber laut der Arbeitsanweisung nicht ersichtlich wie das funktioniert.
Deshalb wollte ich hier nachfragen.

**Comment by JirkaDellOro** [comment]
Ist das geklärt? -> bitte schließen

Oder hast Du einen konkreten Vorschlag für eine Textänderung in der Lektion? Dann gerne her damit...!

**Comment by TobMer** [comment]
Genau. Ich hatte Probleme erstmal zu verstehen was mit " Entwicklungsmaschine" gemeint war.
Wieso und was ist genau npm? Und dann der Schritt mit der Repository übernehmen der packgage.json Datei. Die 2 Schritte vielleicht ein bisschen genauer beschreiben. Ansonsten passt es.
Lg
