### ISSUE TITLE
Form lädt Seite neu?

### ISSUE THREAD

**Issue by AlexanderGritzfeld** [JirkaDellOro/EIA2-Inverted#330]
Hi, mein Problem ist, dass sobald ich den "Bestätigen"- Knopf miéines Forms drücke dieser zwar aller gewünschten Funktionen ausführt und sich schließt, allerdings tut es scheinbar nach sehr kurzer Zeit die Seite neu laden, wodurch alles wieder zurückgesetzt wird.
Weiß jemand woran das liegen könnte?

Hier die Funktion, die durch den Knopf aufgeführt wird:

 start.addEventListener("click", startGame);

    function startGame(): void {
        
        formData = new FormData(document.forms[0]);
        color1 = <string>formData.get("team1Color")?.toString();
        color2 = <string>formData.get("team2Color")?.toString();

        drawTeam(22);
        animate();

        console.log("Nach Start: " + color1, color2);
        
        startFormForm.classList.add("is-hidden");

        //something();
        
    } //end function startGame

**Comment by KohlerAl** [comment]
Ich vermute, es liegt nicht an deinem Code sondern an deinem HTML. Buttons sind, wenn nichts anderes angegeben wird, Submit-Buttons. Wenn du nicht möchtest, dass sich die Seite neu lädt, musst du das Attribut type="button" zu deinem Button hinzufügen.

**Comment by AlexanderGritzfeld** [comment]
Oh mein Gott jetzt klappt es DANKE!

**Comment by JirkaDellOro** [comment]
Alida ist schon gut, aber ist Gott nicht vielleicht übertrieben? Und nicht gegendert...  😄
