### ISSUE TITLE
portrait

### ISSUE THREAD

**Issue by Christina242** [JirkaDellOro/EIA2-Inverted#331]
Wenn ich mich registrieren will wird mir der Fehler angezeigt, dass die Maße von meinem Portrait nicht korrekt sind, aber mein Portrait hat genau die Maße 85x110 Pixel. Was muss ich ändern?

**Comment by Christina242** [comment]
Habs hinbekommen, vielen Dank!

**Comment by JirkaDellOro** [comment]
Gratulation! Erster Issue im neuen Semester 🍾 👏 

Wenn er zu deiner Zufriedenheit beantwortet wurde, bitte unten auf "Close" klicken. Sonst denken wir immer, dass da noch etwas zu tun ist...
