### ISSUE TITLE
Steckbrief wird nicht hochgeladen

### ISSUE THREAD

**Issue by rauvanja** [JirkaDellOro/EIA2-Inverted#333]
Folgende Meldungen erschienen nach der Registrierung: "Code korrekt", "Das Porträt hat das falsche Maß! Gefordert sind 85x110 Pixel"

Wird dann den Steckbrief nicht hochgeladen? 
Das von mir hochgeladene Bild entspricht jedoch den Maßen 85x110 und hatte ich in den letzten 2 Semester auch verwendet. Woran liegt es dann?

**Comment by JirkaDellOro** [comment]
Hat es geklappt? Dann bitte den Issue schließen, Vanja.

**Comment by rauvanja** [comment]
Ja hat geklappt, vielen Dank ;) hab gar nicht an die geschlossenen Issue’s gedacht.
