### ISSUE TITLE
Error in der Browserkonsole 'interest-cohort'

### ISSUE THREAD

**Issue by Aam-Do** [JirkaDellOro/EIA2-Inverted#334]
"Error with Permissions-Policy header: Unrecognized feature: 'interest-cohort'."
Scheint mit Features zur Privacy zu tun haben, die momentan entwickelt werden. Stört das Programm nicht, aber das Auge.
In Github noch keine Funktion gefunden, das irgendwie zu beheben. Der Error verändert sich zu einem 404 wenn die McAfee Browser-Extension aktiviert ist.

**Comment by JirkaDellOro** [comment]
Welche Chrome-Version hast Du?

**Comment by JirkaDellOro** [comment]
Ich schätze, die Warnung wird mit einem der nächsten Updates verschwinden. Liegt nicht in unserem Einflussbereich
