### ISSUE TITLE
Verlinkung zum Zufallsgedicht funktioniert nicht?

### ISSUE THREAD

**Issue by Fatihh61** [JirkaDellOro/EIA2-Inverted#335]
Hey 👋 die Verlinkung direkt zu meinem Zufallsgedicht über die webuser Page funktioniert nicht, wieso ist das so? Ich weiß, dass ich den github.io Link benötige aber von wo kann ich den herbekommen?

Hier der Link zu meinem Repository: https://github.com/Fatihh61/EIA2

Habe es im Steckbrief verlinkt gehabt.

**Comment by JirkaDellOro** [comment]
Potzblitz, das kannte ich noch nicht...

**Comment by Fatihh61** [comment]
Habe es jetzt hinbekommen und die Verlinkung funktioniert. Dankeschön :D
