### ISSUE TITLE
"FormData" ist kein Array- oder Zeichenfolgetyp??

### ISSUE THREAD

**Issue by Fatihh61** [JirkaDellOro/EIA2-Inverted#336]
![EIA2](https://user-images.githubusercontent.com/80823905/140551930-be1871ba-0a3d-482f-9176-b4367ec77d32.png)

Ich hab die Online-Cocktailbar aus der aktuellen Workshop Lektion programmiert aber mir wird ein Fehler angezeigt, obwohl ich alles wie im Video gemacht habe und dort wird kein Fehler angezeigt. 

Weiß jemand was zu tun ist und wieso der Fehler kommt?

Aktuelle Lektion: https://jirkadelloro.github.io/EIA2-Inverted/L03_FormElements/

**Comment by JirkaDellOro** [comment]
Hier wurde das Code-Interface nach dem Video-Dreh geändert, glaube ich. Schreib' mal `formData.entries()`

**Comment by Fatihh61** [comment]
Habe es mal in sämtlichen Zeilen mit formData.entries() probiert. Es zeigt mir dennoch den gleichen Fehler an.

**Comment by JirkaDellOro** [comment]
1. wie stellt sich mein Code bei dir dar? Repository klonen und einfach den Code-Ordner in VSCode öffnen
2. nutzt Du die für den Kurs vorgeschriebenen Konfigurationsdateien?

**Comment by Fatihh61** [comment]
Also ich hab die Konfigurationsdateien doch nicht gehabt, hab sie jetzt aber reingepackt und es funktioniert :D
