### ISSUE TITLE
Canvas wird nicht gefunden

### ISSUE THREAD

**Issue by janzonca** [JirkaDellOro/EIA2-Inverted#339]
main.ts :
`namespace Doenerbude {
    
    // Wir holen uns das Canva aus dem DOM, 
    let canvas: HTMLCanvasElement = <HTMLCanvasElement>document.querySelector("canvas");
    console.log(canvas)
    // Wir holen uns den Kontext vom Canva
    let ctx = canvas.getContext("2d");
    // Wir erstellen das Lager
    var o = new Onion(new Position(100,100))
    // und zeichnen das Lager
    o.draw(ctx!);
}`

index.html:
```
<!DOCTYPE html>
<html lang="de">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Endabgabe</title>
  <link rel="stylesheet" href="style.css">
  <script src="enums.js"></script>
  <script src="grocery.js"></script>
  <script src="drawable.js"></script>
  <script src="main.js"></script> 
</head>
  <body>
    <canvas id="canvas" width="1600px" height="800px"></canvas>
  </body>
</html>
```

Fehlermeldung:
<img width="786" alt="Bildschirmfoto 2022-01-30 um 21 54 56" src="https://user-images.githubusercontent.com/64201766/151717447-47363078-4c2d-4fa2-a215-49cf031070af.png">

**Comment by manzijes** [comment]
hast glaub nur das id symbol (#) vergessen beim querySelector erste zeile

**Comment by janzonca** [comment]
> hast glaub nur das id symbol (#) vergessen beim querySelector erste zeile

meinst du ..:("#canvas")?
Das hilft leider nicht

**Comment by manzijes** [comment]
vielleicht hilft es wenn du dir das canvas erst holst, nachdem der DOM geladen ist, so in load 
event listener

**Comment by JirkaDellOro** [comment]
Das wäre zumindest der Klassiker...

**Comment by janzonca** [comment]
Ja, es klappt jetzt! Danke
