### ISSUE TITLE
Heroku - Dateipfad bei package.json klappt nicht

### ISSUE THREAD

**Issue by aliciaTED** [JirkaDellOro/EIA2-Inverted#34]
Hi :)

wir besprechen das zwar ziemlich sicher morgen im Praktikum, aber in der Lektion steht, dass man ein Issue posten soll, wenn die package.json nicht klappt... so here we go!

Ich hab einfach alles so gemacht, wie es in der Lektion im Abschnitt "Heroku" erklärt ist, weiß allerdings nicht genau, welcher Pfad zu welcher Datei angegeben werden soll... Der Pfad zur package.json? Oder zur CocktailBar.js? Ein lokaler Pfad? (Vermutlich eher nicht.) Oder ein "GitHub-Pfad"? 
![image](https://user-images.githubusercontent.com/48830896/69281288-4ec3e280-0be8-11ea-98ab-933175e62223.png)
^ um diesen Abschnitt geht es übrigens ^

Und so habe ich unter anderem versucht, es zu lösen: 
![image](https://user-images.githubusercontent.com/48830896/69281673-fc36f600-0be8-11ea-84de-47c564598848.png)

(Es geht in erster Linie um Zeile 9 und was man hinter "test:" schreiben muss.)

Danke schon mal für die Hilfe und ist auch okay, wenn das erst morgen im Praktikum geklärt wird :D 

- Alicia

**Comment by MarkusDamm** [comment]
Gesucht ist hier der relative Pfad von der _package.json_ zur JS-Datei des Servers. Das würde in deinem Fall vermutlich in etwa so aussehen: __./L006/Server/Server.js__, genau könnte ichs aber erst mit deiner exakten Verzeichnisstruktur sagen. So ein relative Pfad funktioniert sowohl lokal als auch wenn deine Dateien auf GitHub sind.

**Comment by JirkaDellOro** [comment]
Kläre zudem noch zwei Dinge:
- ist in der Lektion von einem Eintrag hinter "test" die Rede?
- was siehst Du im Browserfenster, wenn Du den Pfad eingibst, den Du gerade hinter "test" eingetragen hast? Siehst Du wirklich nur den Inhalt der js-Datei?

**Comment by aliciaTED** [comment]
Es hat jetzt funktioniert, ich habe vergessen, "test" mit "start" zu ersetzen und hatte zudem den falschen Pfad angegeben. Jetzt steht in Zeile 9 folgendes:
![image](https://user-images.githubusercontent.com/48830896/69334204-84a1af00-0c5a-11ea-823d-9465677f61b7.png)

Und in der Console bekomme ich das hier ausgegeben: 
![image](https://user-images.githubusercontent.com/48830896/69334258-9e42f680-0c5a-11ea-89b2-26fdf8e7890d.png)

Danke für die Hilfe! :)
