### ISSUE TITLE
Error: Vector is not a constructor

### ISSUE THREAD

**Issue by fionavi** [JirkaDellOro/EIA2-Inverted#340]
Hallo, 
ich versuche gerade in meinem Hauptprogramm eine meiner Unterklassen aufzurufen, dabei erscheint jedoch in der Konsole die Fehlermeldung "Uncaught TypeError: Doener.Vector is not a constructor
    at new Worker (Worker.ts:8:29)
   at HTMLButtonElement.startGame (main.ts:109:29)"

Ich habe schon viel gegoogelt und ausprobiert, aber ich kann den Fehler leider nicht beheben.
Kann mir jemand weiter helfen?
Danke schonmal im Voraus!

https://github.com/fionavi/Doenerwetter

**Comment by Fatihh61** [comment]
Hast du in deiner html die Unterklasse verlinkt?

**Comment by Fatihh61** [comment]
Hab mal reingeschaut und da ist gar nichts verlinkt bei dir in der html :D

**Comment by fionavi** [comment]
Oh wow, an das Offensichtlichste hab ich dann wohl nicht gedacht.. :D danke dir!

**Comment by JirkaDellOro** [comment]
@Fatihh61 👍
