### ISSUE TITLE
String[ ] vergleichen

### ISSUE THREAD

**Issue by Aam-Do** [JirkaDellOro/EIA2-Inverted#341]
Ich sitze grade an der Logik für die Überprüfung der Bestellung. Meine Customer sollen ihre Bestellung als string-Array speichern, und der Döner seine Zutaten auch. Wenn der Nutzer die Bestellung abschließt müssen die Zutaten ja mit der Bestellung abgeglichen werden, um zu erkennen, ob alles da ist, was der Kunde wollte.

Meine erste Idee ist, beide Arrays alphabetisch zu sortieren und einfach mit == zu vergleichen. Das würde (wahrscheinlich) so auch funktionieren und reichen. 

Ich würde aber gerne implementieren, dass der Customer sauer wird, wenn eine Sache fehlt, und richtig sauer, wenn mehr als zwei Sachen fehlen oder zu viel sind. Da reicht ja das bloße Vergleichen nicht mehr. Vielleicht fände ich auch eine Gewichtung cool, also wenn z.B. das Brot oder der Yufkafladen fehlt, wird der Customer pissiger, als wenn der Mais fehlt. Wie kann ich so einen Vergleich gut machen, ohne dass ich für jeden Fall eine Ausnahme coden muss?

**Comment by JirkaDellOro** [comment]
Es ist auf jeden Fall schon ein sehr guter Ansatz, dass Du zwei Datensätze hast, die Du vergleichen kannst!

Statt alphabetisch zu sortieren und dann zu vergleichen, kannst Du auch die Liste des Customers durchgehen und die gefundene Zutat aus der Dönerliste splicen. Klappt das, war sie auch drin. Bleiben am Ende noch Zutaten auf der Dönerliste übrig, waren die zu viel...

**Comment by Aam-Do** [comment]
I see... makes sense. Kann ich mit den Ausnahmebehandlungen sowas machen wie, salopp ausgedrückt: "okay, merks dir (Variable), geh aber zurück und mach trotzdem weiter"?

**Comment by JirkaDellOro** [comment]
Achso, zum splicen musst Du ja vorher die Position finden. Also weißt Du bereits ob Du splicen kannst und brauchst es ggf. gar nicht erst probieren. Mir kommt auch gerade noch die Idee, dass Du ohne splicen auskommst. Wenn alles drin ist, was der Customer will, aber die Dönerliste länger ist, weißt Du auch das Zeug zu viel ist, nur halt nicht was....

**Comment by Aam-Do** [comment]
Ich glaube es formt sich ein Konzept
