### ISSUE TITLE
Uncaught TypeError: Cannot create property 'innerHTML' on string 'height: 100px;'  

### ISSUE THREAD

**Issue by fionavi** [JirkaDellOro/EIA2-Inverted#342]
Hallo,
ich habe nochmal ein kleines Problem. Ich würde gerne einen Balken bei den Containern anbringen, der anzeigt wie voll sie noch sind. Deshalb wollte ich zu Beginn vom Spiel die Eingaben vom Spielenden übernehmen, der den Füllstand zu Beginn ja bestimmen kann.

Ich wollte das machen, indem ich einfach die formData bei "Füllmenge" nehme und ins HTML oder in CSS bei "height" vom Balken einfüge.

Es funktioniert aber leider nicht mit:    variable.innerHTML = "XYZ"
Deshalb wollte ich fragen, ob der Ansatz an sich überhaupt machbar ist und es gerade nur an einem kleiner Fehler scheitert, oder ob ich einen neuen Ansatz suchen sollte?

https://github.com/fionavi/Doenerwetter/tree/main/doenerwetter
(Mein Versuch ist in der main.ts in Zeile 94 - 98)

**Comment by JirkaDellOro** [comment]
Hm... über die Klasse onionStockChart scheinst Du auf ein div-Element zugreifen zu wollen. Wenn dies deinen Balken repräsentieren soll, müsstest Du an dessen `style` die height-property ändern und es muss noch entsprechend per CSS aus der automatischen Formatierung herausgenommen werden. `innerHTML` würde jedenfalls nur den Text innerhalb des div-Elementes ändern. Der Titel des Issues deutet auf ein zusätzliches Problem hin, da wird scheinbar versucht `innerHTML` eines Strings zu manipulieren, was der aber gar nicht besitzt.

Bevor wir hier ins Detail gehen: wäre es eine Alternative meter-Elemente zu nutzen? Die erzeugen gleich eine grafische Ausgabe und lassen sich über ihre Eigenschaft `value` leicht manipulieren.

**Comment by fionavi** [comment]
Okay, ich hab es jetzt mit den meter elements geschafft. Danke!
