### ISSUE TITLE
Click Listener funktioniert nicht

### ISSUE THREAD

**Issue by fionavi** [JirkaDellOro/EIA2-Inverted#344]
Hallo,

ich wollte für die Bestellungsbearbeitung click-Listener auf Buttons installieren, damit die Zutaten per Click hinzugefügt werden.
Ich habe die Click-Listener in meiner Startfunktion installiert, aber die Funktionen werden einfach direkt aufgerufen - ohne auf den click zu warten.
Weiß jemand woran das liegen kann?

https://github.com/fionavi/Doenerwetter/blob/main/doenerwetter/main.ts

(Aufruf in Zeile 116 - 120,
Funktionen ab Zeile 716)

**Comment by Fatihh61** [comment]
Leg mal den Eventlistener aus Zeile 32 in handleLoad rein und probier es nochmal.

**Comment by JirkaDellOro** [comment]
Klassiker... Du schreibst z.B. 
`document.querySelector("#addB").addEventListener("click", addBread());`

Durch die Klammern hinter addBread rufst Du an dieser Stelle die Funktion auf und versuchst, deren Ergebnis als Handler zu installieren. An den anderen Stellen hast Du es interessanterweise richtig gemacht.

**Comment by JirkaDellOro** [comment]
Eigentlich hätte dir TypeScript hier schon auf ein Problem aufmerksam machen müssen. War die Stelle nicht rot unterstrichen?

**Comment by JirkaDellOro** [comment]
Das ist nicht gut, damit bist Du einer wichtigen Hilfe beraubt. Welche TypeScript-Version hast Du installiert? 
`tsc -v`
