### ISSUE TITLE
array1[0] Vergleich mit array2[0] stimmt nicht

### ISSUE THREAD

**Issue by fionavi** [JirkaDellOro/EIA2-Inverted#345]
Hallo nochmal,

ich habe gerade eine Funktion erstellt, worin die Bestellung vom Kunden mit dem zubereiteten Gericht verglichen wird. Obwohl beide identisch sind, geht die if-Schleife immer zum else-Fall, der nur eintreffen soll wenn sie ungleich sind.
Ich verstehe nicht, wieso er die beiden als ungleich erkennt, wenn sie in der Konsole als gleich angezeigt werden.

![image](https://user-images.githubusercontent.com/64150827/153426176-72742120-41f2-4716-b612-a9d35a93a6ed.png)

https://github.com/fionavi/Doenerwetter/blob/main/doenerwetter/main.ts
(cashUpOrder Funktion bei Zeile 794)

**Comment by fionavi** [comment]
Ich habe es mal in void geändert :D
ich habe es versucht, aber im debugger konnte ich den Fehler leider nicht finden.

**Comment by JirkaDellOro** [comment]
Poste einen Link auf die laufende Applikation auf Pages, bitte. Dann schau ich mal im Debugger rein.

Zum verbotenen Wort: ich meinte www.if-schleife.de
