### ISSUE TITLE
Programm hängt sich auf wenn worker laufen soll

### ISSUE THREAD

**Issue by fionavi** [JirkaDellOro/EIA2-Inverted#347]
Hallo,

ich habe gerade eine neue Funktion walkThere erstellt, durch die der Worker gezielt zu einer bestimmten Position laufen soll. Ich habe es mit if-Abfragen, in denen for-Schleifen sind gemacht, die x und y solange verändern, bis sie den gewünschten Wert erreichen. In der Update Funktion im Hauptprogramm steht der Befehl, der den Worker dann auch gleich zeichnen lassen soll. Im Live Server zeigt es in der Konsole, dass der x-Wert verändert wird, allerdings nicht nur bis der Wert erreicht wurde sondern unendlich oft.
Dabei hängt sich die Anwendung auch jedes mal auf.

Ordner mit Dateien im Repository: https://github.com/fionavi/Doenerwetter/tree/main/test
Anwendung: https://fionavi.github.io/Doenerwetter/test/doener.html

die walkThere Funktion wird in container.ts in Zeile 43 aufgerufen und ab Zeile 46 ausgeführt.
Die update Funktion steht in main.ts  abZeile 481

**Comment by JirkaDellOro** [comment]
Das ist schon eine recht nette Darstellung. Was muss ich tun um den Arbeiter zu schicken?

**Comment by JirkaDellOro** [comment]
ok, refillBread...

Ich sehe ein Problem bei der Formulierung der for-Schleifen. Da steht:
`for (workers[0].position.x < _x; workers[0].position.x++;) {`
der erste Teil stellt keinen sinnvollen Startzustand her und der zweite Teil keine sinnvoll Laufbedingung dar. Vielleicht muss einfach das letzte Semikolon ganz nach vorne, so dass sich alles um eine Position in der Schleifendefinition verschiebt. Dann hast Du keine Definition für einen Startzustand, was in Ordnung ist, wenn dieser anderweitig hergestellt ist, aber sinnvolle Laufbedingung und eine sinnvolle Veränderung pro Iteration.

**Comment by JirkaDellOro** [comment]
Noch ein paar grundsätzliche Tipps: ich denke, diese Positionsüberprüfungen wären eigentlich Aufgabe einer Worker-Instanz. Jetzt wird das erledigt im Code der Container-Datei, das erscheint unintuitiv. Außerdem trifft es immer Worker[0]. Weiterhin wirst Du die Bewegung wahrscheinlich nie sehen können, weil Du innerhalb einer Schleife zeichnest und der Browser nicht dazu kommt das Bild zu aktualisieren, bis die Schleifen abgearbeitet sind. Bleibe bei dem bekannten Schema, dass wir eine Aktualisierungsmethode im Hauptprogramm haben, die zeitgesteuert aufgerufen wird und alle beweglichen Instanzen aufruft zum Bewegen und Zeichnen.

**Comment by fionavi** [comment]
Okay danke, ich habe jetzt die move Methode in Worker.ts mit den if-Abfragen gefüllt.
Die update Funktion rufe ich mit Klick auf "refill" erneut als Intervall auf, wo ich gleichzeitig x und y als Parameter übergebe - das macht aber glaube ich nicht so viel Sinn.
Der Worker bewegt sich jetzt nämlich nur pro Klick ein bisschen weiter anstatt nach einem klick kontinuierlich in Bewegung zu sein.
Ich weiß nicht, wie ich die Parameter sonst am besten an Update übergeben sollte, damit der worker normal zur gewünschten Position läuft.

**Comment by fionavi** [comment]
Jetzt hat es sich erledigt, ich konnte eine Lösung finden:)
