### ISSUE TITLE
clearInterval funktioniert nicht

### ISSUE THREAD

**Issue by Aam-Do** [JirkaDellOro/EIA2-Inverted#348]
Ich habe ein Interval für die mood-Steuerung von Kundis und Mitarbeiteris, welches ich gelegentlich stoppen möchte. Ich habe gelesen, dass der return Wert einer setInterval Funktion die id ausgibt, mit der man das Interval "clearen" kann. Leider funktioniert es nicht so wie ich es gehofft hatte und macht trotzdem weiter, wenn man dem Kunden das Essen gegeben hat.  Ich nehme an, es liegt daran, dass ein neues erstellt wird und ich nicht auf die id des alten zugreife. Muss ich eine Variable machen, um das Interval gezielt an- und auszuschalten? Geht das in einer Klasse, wenn ich aus unterschiedlichen Methoden darauf zugreifen will? Wenn ja, wie :D?

https://github.com/Aam-Do/EIA2_Endabgabe/blob/master/DoenerDream/Scripts/Customer.ts
gesetzt wird das Intervall in Zeile 23 und clearen will ich es in Zeile 54 und 81

**Comment by JirkaDellOro** [comment]
Guckst Du hier: https://developer.mozilla.org/en-US/docs/Web/API/setInterval

Deine Vermutungen sind korrekt. Einschalten mit der gleichen ID geht nicht, zumindest wüsste ich nicht wie. Du machst dann ein Neues. Wenn jede Instanz deiner Klasse seine eigene Intervallsteuerung haben soll, kann sich jede die ID für das individuelle Intervall merken...

**Comment by Aam-Do** [comment]
Scheint zu funktionieren 👍
