### ISSUE TITLE
Installation MongoDB

### ISSUE THREAD

**Issue by kretschmerlea** [JirkaDellOro/EIA2-Inverted#35]
Ich habe Probleme beim herunterladen bzw. installieren des MongoDBs. In der Lektion steht, man soll ihn nicht als Service installieren. Lade ich ihn jedoch runter (habe geschätzt welcher der richtige ist) und will ihn installieren, wird angezeigt: "Install as as service". Nun weiß ich nicht, ob ich das falsche runtergeladen  oder die Erklärung falsch verstanden habe. Diese könnte glaube ich ein bisschen ausführlicher sein, damit man weiß wo man jetzt genau draufklicken muss um am Ende die richtige Version installieren zu können.

**Comment by JirkaDellOro** [comment]
Bist Du auf einem Mac unterwegs? Dann wäre Markus der richtige Ansprechpartner. Bei Windows könnte gleich ich helfen.... hoffentlich.

**Comment by kretschmerlea** [comment]
Habe einen Windows.

**Comment by JirkaDellOro** [comment]
Ok, ich folge der Anleitung "Install MongoDB Community Edition"

Da kommt man zum Download Center, da sucht man sich sein Operating System und dann kann man noch wählen zwischen ZIP und MSI. ZIP wäre eigentlich ganz gut, dann kannst Du es einfach entpacken und hinlegen, wo Du es haben möchtest. Ich lade jetzt mal den MS-Installer....

**Comment by JirkaDellOro** [comment]
😴 ...

**Comment by JirkaDellOro** [comment]
Zwischendrin: da sich die Webseiten und Details immer ändern, wird eine detailliertere Anleitung schnell veralten und dann sogar noch mehr Verwirrung stiften...

**Comment by JirkaDellOro** [comment]
Also der Installer fragt dich zuerst ob er als Service installiert werden soll, das wählst Du ab. Auf der nächsten Seite machst Du auch das Häkchen bei Compass weg.

**Comment by JirkaDellOro** [comment]
Ich installiere bei mir erstmal nicht weiter, ich habe es ja schon. Sag' bescheid wie es weiter läuft. Die ZIP-Option steht auch offen.

**Comment by kretschmerlea** [comment]
Alles klar. Vielen Dank. Habe mir jetzt mal den ZIP Ordner runtergeladen. Muss ich damit jetzt noch was machen außer alles auspacken? Also Installations-mäßig?

**Comment by JirkaDellOro** [comment]
Wahrscheinlich nicht. Lege in deinem EIA2-Projekt einen Ordner dafür an und schiebe den entpackten Inhalt dort hinein. Sag' bescheid, wenn Du darin das bin-Verzeichnis mit mongod und mongo siehst

**Comment by kretschmerlea** [comment]
Habe es auch nochmal als MSI versucht und bin Ihrer Anleitung gefolgt, aber irgendwas ist anscheinend schiefgelaufen, weil als ich es öffnen wollte, ich wählen sollte zwischen: change, repair oder remove. Benutze jetzt einfach den ZIP-Ordner.

**Comment by JirkaDellOro** [comment]
Und achte darauf, dass Du .gitignore anpasst und den Ordner exkludierst. Wir brauchen MongoDB nicht in den Repositories

**Comment by kretschmerlea** [comment]
Alles klar. Im bin-Ordner habe ich mongo.exe und mongod.exe gefunden.

**Comment by JirkaDellOro** [comment]
Cool, dann solltest Du dem Video weiter folgen können. Achte auf --dbpath um anzugeben, wo Du deine Datenbank anlegen möchtest

**Comment by kretschmerlea** [comment]
Bei mir schließt sich das mongod immer gleich. Irgendwas scheint wohl schiefgelaufen zu sein. Das schau ich dann aber morgen. Weiß jetzt nicht woran das wieder liegt.

**Comment by JirkaDellOro** [comment]
--dbpath angegeben? Backslashes ( \ ) verwendet?

**Comment by kretschmerlea** [comment]
Eben den Teil habe ich auch bei der Anleitung nicht ganz verstanden. Wo muss ich dieses --dbpath angeben/eingeben? Und wo soll dieser Ordner am Ende liegen? Einfach in meinem EiA2-Repository?

**Comment by JirkaDellOro** [comment]
Letztlich kannst Du es machen wie Du möchtest. Ich habe gerade zwei Ordner auf dem Desktop gehabt. Einen leeren. wo die Datenbank reinsoll, und einen daneben, in den ich den Inhalt des Zipfiles hineingeschoben habe. Nennen wir einmal den einen "Database" und den anderen "MongoDB".

In der letzten Lektion hast Du gelernt, dass Du ein Konsolenprogramm mit seinem Namen aufrufst, z.B. "node". Dann kannst Du, mit Leerzeichen getrennt, noch weitere Informationen dazugeben. Genauso läuft es jetzt auch

MongoDB\bin\mongod ist das Programm, dass Du aufrufst, und zwar mit den beiden Parametern --dbpath und Database. Also
`MongoDB\bin\mongod --dbpath Database`

**Comment by JirkaDellOro** [comment]
Wenn Mongo den Parameter --dbpath findet, geht es davon aus, dass der nächste Parameter der Pfad zum Datenbankordner ist und wird versuchen dort die Daten abzulegen.

Du kannst Du die Ordner auch in deinem EIA-Projekt anlegen, dann ist alles beisammen, aber dann solltest Du git anweisen sie zu ignorieren.

**Comment by JirkaDellOro** [comment]
Ist das geklärt? -> bitte schließen

Oder hast Du einen konkreten Vorschlag für eine Textänderung in der Lektion? Dann gerne her damit...!

**Comment by JirkaDellOro** [comment]
????

**Comment by kretschmerlea** [comment]
Tut mir leid, hab vergessen den issue zu löschen. Also ja er kann weg, hab
nur gerade keinen Laptop zur Hand.

JirkaDellOro <notifications@github.com> schrieb am Fr. 13. Dez. 2019 um
19:29:
