### ISSUE TITLE
da stimmt noch immer was mit meinem Repository nicht

### ISSUE THREAD

**Issue by Ronja-Burger** [JirkaDellOro/EIA2-Inverted#359]
... und ich weiß nicht was. github desktop läuft jetzt, aber im Browser werden die js- und ts-Dateien nicht mehr angezeigt.

**Comment by JirkaDellOro** [comment]
Jetzt ist mehr Info erforderlich. Poste hier bitte Links zum Code auf Githuh und der Anwendung auf Pages, dann finden wir das Problem sicher ganz schnell

**Comment by Ronja-Burger** [comment]
jetzt tut es wieder irgendwie 🤷🏼‍♀️
