### ISSUE TITLE
//display mouse position and event's target in splan-Element//Aufgabe L02_1

### ISSUE THREAD

**Issue by joschareuther** [JirkaDellOro/EIA2-Inverted#360]
Hi, ich bin noch bei Aufgabe L02_1. Folgendes Problem:
Ich möchte die Mauspositionen von x und y auf meinem span-Element anzeigen lassen, habe hierfür im HTML-Dokument (https://github.com/joschareuther/EIA2SoSe22/blob/main/L02_Events/L02.1.html) folgendes span-Element erstellt:    

 span class="span"
            Mausposition
        p X-Position:  h5 id="X-Position"  /h5 /p
        p Y-Position:  h5 id="Y-Position"  /h5  /p
    /span

Dann will ich in TS (https://github.com/joschareuther/EIA2SoSe22/blob/main/L02_Events/A02.1Script.ts) mit den ID-Selektoren die Mauspositionen anzeigen lassen:
Dafür habe ich zwei neue Variablen deklariert und eine neue Funktion, welche die Zahlen von _event.clientX an den ID-Selektoren X-Position übergeben soll. 

1. Gibt es noch eine schnellere Möglichkeit sich die Mauspositionen auf dem span anzeigen zu lassen?

2.Und warum funktioniert meine Methode bisher nicht? Das span hat auch aufgehört meiner Maus zu folgen, dabei habe ich die Funktionen doch extra getrennt. Liegt es daran, dass ich diese gleichzeitig zu dem Eventlistener MouseMove aufrufe?

Habe die Sachen auf GitHub gepusht, damit man reinschauen kann. Werde die Änderung aber auch wieder rückgängig machen können wenn ich was Besseres finde.

**Comment by JirkaDellOro** [comment]
Bitte immer in den Issues gleich die Links posten, damit man nicht suchen muss. Manche Helfer haben auch keinen Zugang zur Kursseite.

**Comment by JirkaDellOro** [comment]
Hast Du allzeit die Browserkonsole offen, so dass Du Fehlermeldungen sehen kannst?

**Comment by JirkaDellOro** [comment]
1. was meinst Du mit "schneller"? In der Ausführung oder beim Coden?
2. Dein Programm startet so:
```typescript

namespace UIScribble {
    window.addEventListener("load", handleLoad);
    var _xposition: string =  _event.clientX; 
```
wenn Du _xposition definierst, ist _event nicht bekannt. Das Ereignisobjekt wird von einem Listener einem Handler übergeben, wenn das Ereignis eintritt. Bei dir steht die Zeile aber im Hauptprogramm, ganz unabhängig vom Eventhandling...

Noch ein Paar Sonderbarkeiten fallen mir auf, die Du gleich korrigieren solltest
- UIScribble ist kein guter Name für die Lösung der Aufgabe
- der Unterstrich soll laut Guidelines für Parameter verwendet werden
- `var` sollte nicht verwendet werden
- in Zeile 7 steht
   `document.addEventListener("mousemove", setInfobox, myFunction(_xposition, yposition));`
   TypeScript sollte dir hier einen Fehler schon im Code anzeigen, tut es das nicht?
- In Zeile 32 steht
   `console.log(MouseEvent, EventTarget, EventSource);`
   Du solltest eine Ausgabe erhalten, allerdings wahrscheinlich nur den Hinweis, dass Du versuchst dir browserinternen Strukturen der angegebenen Objekttypen auszugeben. Du willst wahrscheinlich lieber in des Object reinschauen, das von dem Parameter _event referenziert wird.

**Comment by JirkaDellOro** [comment]
So wortkarg? Konntest Du mit meinen Anmerkungen etwas anfangen und deine Probleme lösen?

**Comment by JirkaDellOro** [comment]
Meine Frage zu 1. ist auch noch unbeantwortet

**Comment by joschareuther** [comment]
> So wortkarg? Konntest Du mit meinen Anmerkungen etwas anfangen und deine Probleme lösen?

Hi Jirka,
ich hab das Issue geschlossen, weil ich die Anzeige für die Mauspositionen nun anders angegangen bin und lösen konnte. Ich lasse die Anzeige nun in der Funktion setInfobox mit der Anweisung .innerHTML angezeigen.(https://github.com/joschareuther/EIA2SoSe22/blob/main/L02_Events/A02.1Script.ts). Den namespace habe ich auch umbenannt.

Mit meiner Lösung davor war ich auf dem Holzweg, da ich laut UI-Scribble ja auch keine weiteren Funktionen definieren sollte (https://github.com/JirkaDellOro/EIA2-Inverted/wiki/L02_EventInspector). Ich habe versucht in dem span-Element in HTML Texte einzubauen, die ich dann anhand neuer Variablen und neuer Event-Listener manipulieren kann, so wie wir das in EIA1 in Aufgabe 6 getan haben (https://github.com/joschareuther/WS2021-22/blob/main/Aufgabe06/Aufgabe06.html), hier das zugehörige ts-Dokuement: https://github.com/joschareuther/WS2021-22/blob/main/Aufgabe06/Script06.ts

Dann bin ich aber auf die Anweisung .innerHTML gestoßen und dachte, es müsste auch wesentlich weniger umständlich funktionieren (das meinte ich mit "schneller") und hab die Anweisung dann in die setInfobox-Funktion eingebaut, (ohne dabei neue Variablen, neue Event-Listener und eine neue Funktion definieren zu müssen) bis es funktioniert hat, was

**Comment by JirkaDellOro** [comment]
Alles klar, deine Lösung scheint nun auch dem Konzept zu entsprechen. 

Du solltest unbedingt Auto-Formatieren (Alt+Shift+F) bevor Du deinen Code einreichst. Derzeit ist er für uns nicht gut zu lesen.
