### ISSUE TITLE
Thunkable Google Sheet Artikel auswählen 

### ISSUE THREAD

**Issue by FodorLisa** [JirkaDellOro/EIA2-Inverted#362]
Ich habe meine App in Thunkable soweit fertig. Ich habe aktuell nur das Problem, dass ich es nicht hinbekomme, dass nur die Artikel angezeigt werden, die im Google Sheet bei "Einkaufen" mit "Ja" angegeben sind (siehe Bilder). 
Aktuell werden noch alle Artikel hinzugefügt. 
Über einen Gedankenanstoß wäre ich sehr froh :smile: :innocent:
![Google Sheet](https://user-images.githubusercontent.com/92039731/165548638-f7b1f6a8-f2e9-421e-971b-5bcf1d3b9a24.png)
![Thunkable](https://user-images.githubusercontent.com/92039731/165548641-734f373a-aa33-4661-ae7f-2ed298212f27.png)

**Comment by JirkaDellOro** [comment]
Habe ich noch nicht gemacht. Wie ich Foren entnehme, gibt es leider keinen Filter beim DataView. Ein Lösungsansatz scheint zu sein, die Daten zu holen, zunächst lokale Datasources mit der Auswahl davon zu füllen und diese dann anzuzeigen.
