### ISSUE TITLE
CanvasClasses Animation

### ISSUE THREAD

**Issue by joschareuther** [JirkaDellOro/EIA2-Inverted#365]
### Hi zusammen,

ich sitze gerade immer noch an der Strandanimation und komme nicht weiter.

Die Klassen habe ich definiert, die Objekte sind instanziert und auf die Oberfläche gezeichnet und nun möchte ich, dass einige Objekte anfangen sich zu bewegen, sobald das Benutzeri auf die Canvas-Oberfläche klickt.

1. Dafür habe ich im Main.ts(https://github.com/joschareuther/EIA2SoSe22/blob/main/L09_Klassen/L09.2StrandClasses/StrandMain.ts#L24) einen Load-Listener installiert, sobald die Seite läd, werden die Objekte nacheinander gezeichnet. 
Nachdem alle Objekte gezeichnet sind, speichere ich das Canvas-Bild mit crc2.getImageData 
(https://github.com/joschareuther/EIA2SoSe22/blob/main/L09_Klassen/L09.2StrandClasses/StrandMain.ts#L60)

2. Dann habe ich einen Click-Listener auf das Canvas installiert(https://github.com/joschareuther/EIA2SoSe22/blob/main/L09_Klassen/L09.2StrandClasses/StrandMain.ts#L66) innerhalb meiner HandleClick-Funktion nutze ich die crc2.putImageData und rufe danach die Bewegungs-Methoden meiner Klassenobjekte auf (https://github.com/joschareuther/EIA2SoSe22/blob/main/L09_Klassen/L09.2StrandClasses/StrandMain.ts#L68).

**Beispiel Sonne: Ich will dass die Sonne untergeht**
1.Instanzierung:
let newSun: Sun = new Sun({ x: 250, y: getRandom(30, 100)}, 20);
(https://github.com/joschareuther/EIA2SoSe22/blob/main/L09_Klassen/L09.2StrandClasses/StrandMain.ts#L12)
2. Zeichnung - Methode: draw();
 newSun.draw();
(https://github.com/joschareuther/EIA2SoSe22/blob/main/L09_Klassen/L09.2StrandClasses/StrandMain.ts#L37)
3. Bewegung - Methode: sink();
newSun.sink();
(https://github.com/joschareuther/EIA2SoSe22/blob/main/L09_Klassen/L09.2StrandClasses/StrandMain.ts#L74)

**Die sink-Methode sieht gerade so aus:**
(https://github.com/joschareuther/EIA2SoSe22/blob/main/L09_Klassen/L09.2StrandClasses/Sun.ts#L28)
        sink(): void {
            console.log("Sink!");                                                                   // Konsolen-Ausgabe zur Überprüfung
            this.position.y += this.dy;                                                          // Y -Position + Geschwindigkeit dy
            if (this.position.y - 50 > height || this.position.y + 50 < 0) {     // Schleife, sobald sich die Position am Rand des Canvas befindet
                this.dy = - this.dy;                                                                // dann wird Geschwindigkeit dy umgedreht
            }

**Problem:**
Die Konsolen-Ausgabe funktioniert, das Klick-Event und die Methode also auch, warum bewegt sich die Sonne noch um keinen Pixel? 
 :(

**Eigene Ideen:**
1. Die sink-Methode ist falsch und die Idee mit Y -Position + Geschwindigkeit dy ist falsch.
2. die Speicherung und Überschreibung des Canvas funktioniert noch nicht mit crc2.getImageData. Ich habe noch nicht verstanden, an welcher Stelle man #crc2.getImageData (und crc2.putImageData) richtig einsetzt. (vor oder nach dem Load-Listener?)
(https://github.com/joschareuther/EIA2SoSe22/blob/main/L09_Klassen/L09.2StrandClasses/StrandMain.ts#L60)
4. Irgendwas anderes stimmt noch nicht...

#277 #42 #201

**Comment by JirkaDellOro** [comment]
Setze mal einen Breakpoint in die Zeichenmethode der Sonne und schaue, wie oft und wann sie aufgerufen wird.

Außerdem:
- in der Methode arbeitest Du mit einem Parameter, der von außen mitgegeben muss. So ergibt die Objektorientierung wenig Sinn, denn die Sonne hat doch selbst ihr Position.
- Mach' für jede Klasse eine eigene Datei

**Comment by joschareuther** [comment]
1. Ich hab jetzt für jede Klasse eine eigene Datei erstellt
2. Die Zeichenmethode der Sonne wird eigentlich nur einmal aufgerufen, habe das auch mit dem Debugger ausprobiert
3. Welcher Parameter muss von außen mitgegeben werden?

**Comment by joschareuther** [comment]
2. Ja, das leuchtet ein, die Animation funktioniert jetzt.
3.  Das verstehe ich noch nicht so ganz, das heißt ich soll die Sonne in meiner Main-Funktion erschaffen, ohne ihr die Positions-Parameter mitzugeben?

**Comment by joschareuther** [comment]
3. Ahh verstehe, hab ich geändert👍🏼

Vielen Dank für die Hilfe!

**Comment by JirkaDellOro** [comment]
Super. Wenn es hier nichts mehr zu tun gibt, schließe bitte den Issue
