### ISSUE TITLE
Problem mit Visual Studio Code

### ISSUE THREAD

**Issue by rauvanja** [JirkaDellOro/EIA2-Inverted#366]
<img width="233" alt="Problem" src="https://user-images.githubusercontent.com/48831038/176260170-10b3d820-dd1d-4fd8-bc89-3aee1fa8d2b9.png">

In meinem neuen Repository erstellt es mir keine .js und .js.map Dateien mehr. 
Im Steckbrief allerdings schon. (siehe Bild)

Ich habe die selben Dateien in beiden Ordnern. Was kann ich tun?
Hab den Fehler auch schon gegoogelt aber bin nicht weitergekommen.

**Comment by JirkaDellOro** [comment]
Erste Vermutung: Du hast die watch nicht gestartet bzw im falschen Ordner. STRG+SHIFT+B

**Comment by rauvanja** [comment]
Okay Problem behoben...Danke! Habe die watch im falschen Ordner gestartet...
