### ISSUE TITLE
Fehler bei Steckbriefregistrierung

### ISSUE THREAD

**Issue by c-kocheise** [JirkaDellOro/EIA2-Inverted#367]
Wenn ich meinen Steckbrief registrieren möchte kommt folgende Fehlermeldung:

Code korrekt...

Fehler: steckbrief.htm in
https://c-kocheise.github.io/EIA2_WISE/
ist nicht lesbar oder nicht existent

Was habe ich beim Steckbrief falsch gemacht?

**Comment by KohlerAl** [comment]
Hey, der Link muss auf den Ordner zeigen, in dem dein Steckbrief und das Bild liegen. Die Dateien müssen beide EXAKT so heißen wie in dem Startpaket, auch die Dateiendungen müssen identisch sein (htm, nicht html). Außerdem musst du, falls du das noch nicht gemacht hast in den Einstellungen des Repos github pages aktivieren.

**Comment by c-kocheise** [comment]
Das /Steckbrief hat es gelöst. Danke für die schnelle Hilfe! :)

**Comment by KohlerAl** [comment]
gerne :) super, dass es geklappt hat!
