### ISSUE TITLE
Installation MongoDB - Problem bei Packages

### ISSUE THREAD

**Issue by aliciaTED** [JirkaDellOro/EIA2-Inverted#37]
Hallo :)

ich habe leider auch ein Problem mit der Installation von MongoDB. Da ich die Erklärung in der Lektion ebenfalls etwas zu unausführlich fand, habe ich versucht, das Programm anhand der Beantwortung von Leas Issue zu installieren. Allerdings kann ich MongoDB nicht mal herunterladen, da ich im Download Center kein Package (in Screenshot rot umkreist) auswählen und dadurch den Download-Button (schwarz umkreist) nicht betätigen kann. (Bei Klick darauf geschieht einfach nichts.) Die weiteren Download-Optionen (blau umkreist) führen nur zu 25.000 Dateien, in denen ich kein mongo oder mongod Programm finden konnte.
![image](https://user-images.githubusercontent.com/48830896/69580161-4eef2400-0fd4-11ea-9a0c-1c298d96bd1d.png)
Wenn ich Packages anklicke, um (ich nehme an) den Zip-Ordner oder MSC auszuwählen, wird nur der untere Rand der Box blau. Also so:
![WhatsApp Image 2019-11-25 at 22 42 50](https://user-images.githubusercontent.com/48830896/69580637-3fbca600-0fd5-11ea-88b4-f2b7759cf512.jpeg)

Ich weiß nicht, woran es liegt, dass ich die Packages nicht auswählen kann. Ich habe die Seite bereits mehrmals geladen/aufgerufen und auch meinen Laptop neu gestartet, allerdings funktioniert es immer noch nicht. 

Danke schon einmal für die Hilfe!

Alicia

**Comment by JirkaDellOro** [comment]
Hallo Alicia,

das ist sonderbar. Ich habe eben reingeschaut und die Seite verhält sich normal. Ich habe den ZIP-Download gestartet und den Link herauskopiert:
https://www.mongodb.com/dr/fastdl.mongodb.org/win32/mongodb-win32-x86_64-2012plus-4.2.1.zip/download

Schau mal, ob damit der Download bei dir startet

**Comment by aliciaTED** [comment]
Ich konnte MongoDB nun downloaden, allerdings stehe ich nun, glaube ich, vor dem gleichen Problem wie Lea: Wenn ich die mongod.exe Datei öffnen möchte, geht nur kurz ein schwarzes Fenster auf, dann schließt es sich wieder, ohne dass etwas anderes passiert. Ich habe auch versucht, über --dbpath darauf zuzugreifen und eine Datenbank anzulegen, allerdings scheint VSC meinen Pfad zur mongod-Datei nicht zu erkennen. (Habe ich das richtig verstanden, dass --dbpath in einem neuen Terminal von VSC ausgeführt werden soll?)
Diese Fehlermeldung wird mir angezeigt: 
![image](https://user-images.githubusercontent.com/48830896/69613355-b9827d00-1031-11ea-92f7-2717e24ae05f.png)
Und das hier ist meine Ordnerstruktur für MongoDB bzw. der Pfad zur mongod.exe-Datei:
![image](https://user-images.githubusercontent.com/48830896/69613440-dcad2c80-1031-11ea-9403-84440eb4958f.png)
Den Database-Ordner habe ich in meinem Ordner für Lektion 7 erstellt. 

Ich habe zudem auch mehrmals versucht, die Datenbank über die Konsole meines Betriebssystems zu erstellen, dann bekomme ich allerdings folgende Meldung(en):
![image](https://user-images.githubusercontent.com/48830896/69613980-bb990b80-1032-11ea-92d8-271ae78cb3b9.png)

Also irgendwie komme ich an der Stelle nicht weiter...

**Comment by Plagiatus** [comment]
Es ist eigentlich egal welche Konsole du öffnest, der wichtige Punkt hier ist, dass der Pfad zur `mongod.exe` nicht als solcher erkannt wird und Windows darum denkt du willst den _Befehl_ `MongoDB` ausführen. 

In deinem Befehl solltest du
```
MongoDB/MongoDB_files/bin/mongod
```
mit dem tatsächlichen Pfad auf deinem Computer ersetzen. Keine Ahnung wohin du das installiert hast, aber es wird so oder so ähnlich aussehen:
```
"C:\Program Files\MongoDB\MongoDB_files\bin\mongod"
```
(wenn Leerzeichen im Pfad sind so wie bei mir, dann müssen `"` drum herum)

**Comment by aliciaTED** [comment]
Danke, ich habe es jetzt hinbekommen!
