### ISSUE TITLE
GitHub.io nicht zu finden

### ISSUE THREAD

**Issue by Shinigou** [JirkaDellOro/EIA2-Inverted#370]
wo finde ich die Web-URL (GitHub.io), die mich direkt zu meinem Ordner (wo sich Steckbrief und co befindet) bringt?

**Comment by JirkaDellOro** [comment]
Du musst unter Settings auf Github den Export auf Pages aktivieren, dort wird dann auch die URL angezeigt.

**Comment by Shinigou** [comment]
Habe ich soweit auch gemacht, der Link führt mich dann aber nicht direkt in den Ordner, passt das dann so?

**Comment by JirkaDellOro** [comment]
Wenn Du die Steckbriefdateien in einen Ordner gelegt hast, was gut ist, musst Du den Ordnernamen noch mit angeben. Wenn Du ins Praktikum kommst, können wir das auch zusammen machen.
