### ISSUE TITLE
L06 Localhost wird im Web nicht angezeigt

### ISSUE THREAD

**Issue by TobMer** [JirkaDellOro/EIA2-Inverted#38]
Hello,

gerade versuche ich bei der L06 ab dem Video: Implementation 2 die jeweiligen Schritte abzuarbeiten. Leider lässt sich ab dem Punkt wo  ich im Web : Localhost:5001 eingebe keine Seite mit dem jeweiligen Text in Visual Studio Code aufrufen. Es steht dran ,dass die Website nicht verfügbar ist.
Ich würde gerne noch die L06 fertig bekommen und freue mich auf Hilfe im Praktikum.

Lg

**Comment by JirkaDellOro** [comment]
Soll diese Adresse in VSCode geladen werden?
