### ISSUE TITLE
Neuer GitHub Repository Link

### ISSUE THREAD

**Issue by AnnaWint** [JirkaDellOro/EIA2-Inverted#382]
@JirkaDellOro eine kurze Erinnerung an unser Gespräch - Mein Repository für EIA2 sollte auf der Teamseite durch das Neue ersetzt werden. Ich habe dir den neuen Link per E-Mail zugesendet.

Vielen Dank im Voraus

Grüße Anna

**Comment by JirkaDellOro** [comment]
Sollte erledigt sein, bitte prüfen und ggf. diesen Issue schließen.
