### ISSUE TITLE
TypeError in der Konsole

### ISSUE THREAD

**Issue by JonasAtzenhofer** [JirkaDellOro/EIA2-Inverted#384]
<img width="351" alt="Screenshot 2022-10-20 170723" src="https://user-images.githubusercontent.com/102148532/196987146-c6ef1f84-1683-481d-b035-6b2d02e600b8.png">

In der Konsole bekomme ich diesen Error. Mein Code zeigt aber keine Fehlermeldungen an. 

<img width="505" alt="Screenshot 2022-10-20 171044" src="https://user-images.githubusercontent.com/102148532/196987842-b543e6f0-faf4-4798-be8d-e8e44958257e.png">

**Comment by Robert99s** [comment]
Lass den Inhalt in der Klammer leer -> function handleLoad(): void {
Vielleicht liegt es daran :)

**Comment by JirkaDellOro** [comment]
@Robert99s 
> Lass den Inhalt in der Klammer leer -> function handleLoad(): void { Vielleicht liegt es daran :)
Das würde funktionieren, aber da es ein Handler ist, passt es schon, dass er ein Event entgegen nimmt, auch wenn er es gar nicht auswertet.

@JonasAtzenhofer 
Bitte den Issue schließen, wenn gelöst.
