### ISSUE TITLE
Seite reload bei Click auf Button

### ISSUE THREAD

**Issue by yank05** [JirkaDellOro/EIA2-Inverted#385]
N'abend

ich komm irgendwie nicht so wirklich drauf, wieso die Seite neu läd, wenn man auf "Add Item" klickt... 
Hier meine sonst fertige Abgabe die es betrifft: https://yank05.github.io/EIA2_WiSe22_23/A03_ShoppingList/index.html

LG

**Comment by KohlerAl** [comment]
Buttons sind, wenn man nichts anderes angibt, Submit-Buttons. Du musst beim button noch das Attribut type="button" hinzufügen, dann sollte es gehen  :)

**Comment by yank05** [comment]
Perfekt daran lags. Danke!
