### ISSUE TITLE
Aufgabenstellung 4

### ISSUE THREAD

**Issue by JuliaBefus** [JirkaDellOro/EIA2-Inverted#386]
Hallo,
wir verstehen nicht, ob und wenn ja, was wir coden müssen. Könnte man uns im Allgemeinen die ganze Aufgabe noch etwas ausführlicher erklären?

Danke im Voraus!

**Comment by MarkusDamm** [comment]
Hallo Julia,
kurz gesagt soll die Einkaufsliste nun nicht mehr im HTML fest geschrieben sein, sondern durch Code erstellt werden. Dafür wäre es hilfreich einen Eintrag aus der Liste als einzelnes Objekt anzulegen. Ein Interface kann dabei sehr gut helfen.

**Comment by JirkaDellOro** [comment]
Es ist der Transfer zu leisten von der Lektion L04, wo das an der Cocktailbar durchexerziert wird, auf die aktuelle Aufgabe der Einkaufsliste. 

Gerne Fragen etwas spezifizieren und detaillieren.
