### ISSUE TITLE
Verlinkung in EIA2-Inverted/L02_Events/ 

### ISSUE THREAD

**Issue by ArminaMusic** [JirkaDellOro/EIA2-Inverted#387]
Die Verlinkung im Bereich DOM-Manipulation zu der [DOM-Klassenhierarchie] funktioniert nicht. 

Nur als Hinweis.

**Comment by JirkaDellOro** [comment]
In welcher Lektion?

**Comment by ArminaMusic** [comment]
Ah tut mir leid, dachte der Titel sei deutlicher zu erkennen. Lektion Inverted/L02_Events/ im Bereich der DOM-Manipulation.

**Comment by JirkaDellOro** [comment]
Ausgerechnet dort hatte ich nicht gesucht. 

Du hast dir die Lektion auf Github angeschaut, nicht auf Pages (github.io), korrekt? Der relative Pfad wird dort anders aufgelöst, jetzt habe ich den absoluten eingesetzt.

Bitte prüfen und Issue schließen, wenn es funktioniert.

**Comment by ArminaMusic** [comment]
Ja genau, ich schau mit das immer direkt auf Github ein. Jetzt funktioniert es auch! Super danke!
