### ISSUE TITLE
Abgabe 4: Was genau müssen wir programmieren?

### ISSUE THREAD

**Issue by yank05** [JirkaDellOro/EIA2-Inverted#388]
Moin,

wir müssen in der neuen Aufgabe als Aktivitätsdiagramme schon Prozesse darstellen, dass die hinzugefügten Items in die Datenstruktur hinzugefügt werden, dargestellt werden usw. Die Datenstruktur muss in VSC stehen, müssen wir die ganzen Aktivitäten, die dann möglich sein sollen (Item hinzufügen, löschen, editieren usw.) auch schon komplett implementieren?

Grüße und Danke

**Comment by JirkaDellOro** [comment]
Danke für die konkrete Frage.

Ja, wobei es genügt, nur das DOM zu manipulieren. Die literal abgelegten Daten werden nur zum initialen Aufbau der Seite genutzt.

Bitte Issue schließen, wenn die Frage damit zufriedenstellend beantwortet ist.
