### ISSUE TITLE
CORS policy blockiert fetch 

### ISSUE THREAD

**Issue by yank05** [JirkaDellOro/EIA2-Inverted#389]
Wenn ich in meinen Webspace den Link zur Data.json angebe und er daraus das erste schon vorexistierende Item fetchen soll bekomme ich eine Meldung, dass das wegen CORS nicht möglich ist.

Wie umgehe ich das bzw. ist das überhaupt der richtige Weg?

**Comment by KohlerAl** [comment]
Öffnest du deine HTML Datei direkt im Browser oder verwendest du den Live-Server? siehe https://jirkadelloro.github.io/EIA2-Inverted/L05_Client/#cocktailbar-bestellung-versenden unter Lokaler File Server

**Comment by yank05** [comment]
Funktioniert mit Live-Server und Lokalem File Server nicht, auch auf GitHub Pages und auch auf einem anderen Computer in anderem Browser nicht, wird immer blockiert wegen der "Gleiche-Quelle-Regel".

**Comment by JirkaDellOro** [comment]
Ist das noch relevant? Es sollen nun alle Daten von MingiDB geliefert werden...

**Comment by yank05** [comment]
Ich muss doch, wenn ich von der Datenbank etwas auslesen möchte in Typescript in dem fetch-Befehl die URL der Datenbank angeben, oder?

**Comment by JirkaDellOro** [comment]
Korrekt, dazu noch den entsprechenden Query-String

**Comment by yank05** [comment]
Ja, das blockiert CORS auch.

**Comment by JirkaDellOro** [comment]
Welchen Browser nutzt Du?

**Comment by yank05** [comment]
Das Problem löst sich, wenn man das Add-On "CORS unblock" für Chrome installiert und aktiviert, dann funktioniert es.

**Comment by yank05** [comment]
Ja, ist aktuell.

**Comment by JirkaDellOro** [comment]
In handleLoad lässt Du folgende Anweisung ausführen:
```typescript
        let response: Response = await fetch("https://webuser.hs-furtwangen.de/~koenigya/Database/dataList.json"); 
```
Du versuchst also, die Datei, die unter der Hoheit der Datenbank steht, selbst zu laden. Das ist nicht zulässig. Die Datenbank soll dir die Daten liefern!

**Comment by yank05** [comment]
Achso okay daran liegts. Hab es jetzt mit einem command gemacht, das funktioniert. Danke!
