### ISSUE TITLE
Sschneeflocken werden nicht angezeigt

### ISSUE THREAD

**Issue by JonasAtzenhofer** [JirkaDellOro/EIA2-Inverted#391]
Ich verstehe nicht warum meine Schneeflocken nicht angezeigt werden.

Die Konsole gibt einen Fehler aus, den ich ebenfalls nicht nachvollziehen kann 
<img width="1274" alt="Screenshot 2022-12-16 214052" src="https://user-images.githubusercontent.com/102148532/208185480-e4bbba6d-8888-4d98-8ee3-32bef7c0003f.png">

**Comment by JonasAtzenhofer** [comment]
Problem hat sich gelöst

**Comment by JirkaDellOro** [comment]
Schreibe gerne kurz, was das Problem war. Vielleicht hilft das auch anderen.

**Comment by JonasAtzenhofer** [comment]
Ich hatte vergessen in meiner Draw Funktion für die Schneeflocken, den CanavsRenderingContext meine ImageData zuzuweisen
