### ISSUE TITLE
Fehler mit extends

### ISSUE THREAD

**Issue by yank05** [JirkaDellOro/EIA2-Inverted#392]
Hi
Was bedeutet: "Snowflake.ts:2 Uncaught TypeError: Class extends value undefined is not a constructor or null". Ich bin eigentlich davon ausgegangen, dass er Movable nicht finden kann, weswegen ich in der HTML-Datei Moveable vor die beiden Subklassen gestellt habe damit es als erstes läd, allerdings funktioniert mein Main File dann nicht mehr richtig.

Mein Code bis jetzt: https://github.com/yank05/EIA2_WiSe22_23/tree/main/A10.2_PolymorphieAnimation
Danke im Voraus

**Comment by JirkaDellOro** [comment]
Die Idee mit der Reihenfolge ist richtig und gut. Korrigiere sie und nimm auch die `defer`s raus. Die brauchen wir nicht mehr und sie können sogar Probleme machen.

Beschreibe, was "funkioniert mein Main File nicht" bedeuten soll. Ich sehe in 

```typescript
        crc2.putImageData(background, 0, 0); 
        crc2.fillRect(0, 0, crc2.canvas.width, crc2.canvas.height);
        for (let index = 0; index < Moveables.length; index++) {
            let snowflake: Snowflake = <Snowflake>Moveables[index];
            snowflake.move(1 / 50); 
            snowflake.draw(snowflake.object); 
        }
```

dass 
1. nach der Restauration des Hintergrundes mit fillRect der Verlauf über alles drübergemalt wird. 
2. der Name des Arrays nicht den Stilvorgaben entspricht
3. die Type-Assertion `<Snowflake>` überflüssig ist und Du einfach nur eine Variable vom Typ Moveable bräuchtest
4. der Pfad `snowflake.object` nicht definiert ist

**Comment by yank05** [comment]
Ja, das ist alles noch nicht so ganz fertig, ging nur darum das es dann gar nicht mehr ausgeführt wird, jetzt passt es, danke!
