### ISSUE TITLE
Serverdaten umwandeln

### ISSUE THREAD

**Issue by LizHengsteler** [JirkaDellOro/EIA2-Inverted#396]
Ich habe eine Collection angelegt und kann neue Einträge erzeugen und mein Problem ist im Moment, dass ich zwar Zugriff auf meine Datenbank von meiner main.ts aus habe und die Daten gesendet werden, ich aber nicht auf diese zugreifen kann. Wir holen das json als .text und parsen es dann. Daraufhin wollen wir es in einem interface array abspeichern, was aber nicht klappt:(. Wir vermuten, dass wir eine Ebene zu weit oben sind, aber wissen nicht, wie wir noch eine Ebene tiefer in die geliefterten Daten kommen, wo unsere Werte color, radius und form gespeichert sind. https://github.com/LizHengsteler/EIA2-Endabgabe https://lizhengsteler.github.io/EIA2-Endabgabe/index.html

**Comment by JirkaDellOro** [comment]
Ihr könnt von Hand zur Prüfung in die erzeugten JSON-Dateien von MingiDB reinschauen. Ihr solltet aber nie im Programm die Dateien direkt laden, sondern euch von der MingiDB liefern lassen per `find`. Macht ihr das so?

**Comment by JirkaDellOro** [comment]
Schicke immer bitte einen Link auf die App mit, dann kann ich schneller testen

**Comment by JirkaDellOro** [comment]
Macht ihr, und es funktioniert auch alles. Das Ergebnis ist ein assoziatives Array, da gibt es kein Element "0". Das ist das einzige Problem.

**Comment by JirkaDellOro** [comment]
Konnte man im Debugger gut sehen...

**Comment by LizHengsteler** [comment]
vielen Dank haben es geschafft
