### ISSUE TITLE
Server/Aktualisierungsfehler

### ISSUE THREAD

**Issue by Anykhet** [JirkaDellOro/EIA2-Inverted#397]
Guten Tag,

ich habe eine Frage bezüglich meines Servers. Der Server funktioniert zwar, also da steht success, aber wenn ich ein Feuerwerk speicher dann wird es bei meinem Server nicht aktualisiert und wird nicht gespeichert. Was soll ich jetzt machen? 
Der Server und der Code funktionieren, aber es wird nicht aktualisiert.
Vielen Dank im Voraus.

Mit freundlichen Grüßen
Aanya Khetarpal

**Comment by Anykhet** [comment]
Update: hat sich doch erledigt :))

**Comment by JirkaDellOro** [comment]
Super!
