### ISSUE TITLE
Mongo Shell  Show dbs

### ISSUE THREAD

**Issue by TobMer** [JirkaDellOro/EIA2-Inverted#40]
Ich weiß ist zwar etwas spät aber besser spät als nie.

Bei der L07 bin ich bei der Mongo Shell Aufgabe. Ich muss "show dbs" im Terminal eingeben.
Da kommt bei mir aber nur diese Nachricht ->siehe bild
![Unbenannt](https://user-images.githubusercontent.com/48830884/69921809-35e3e880-1496-11ea-9939-92e6ea99462d.PNG)

was kann ich tun und was passiert da und wieso geht das nicht?!

Vielen Dank.

**Comment by MarkusDamm** [comment]
Moin Tobi,
das Terminal, in dem der Befehl eingegeben werden soll ist hier die Mongo Shell. Bedeutet, du startest mit einem Terminal zuerst mongod und mit einem zweiten Terminal dann mongo. Der Befehl soll dann im zweiten Terminal, was nun die Mongo Shell ist, eingegeben werden.

Bei dir hat der Befehl nicht funktioniert, weil du ihn in einem einfachen Terminal ausgeführt hast und nicht in einer Mongo Shell. Wie mir scheint hast du auch vor _show dbs_ versucht _mongod_ im selben Terminal auszuführen. Das hat nicht geklappt, weil der Pfad zur Datenbank mit __--dbpath Entsprechender/Ordner__ wahrscheinlich nicht angegeben wurde.

**Comment by TobMer** [comment]
Servus Markus :)
In welcher Konsole gebe ich dann was ein ? (・_・;)

**Comment by TobMer** [comment]
Also es kommt immer : Commando not found.
Und wie bei Jirkas Video sieht meine 2. Konsole auch ganz anders aus.

**Comment by JirkaDellOro** [comment]
Die Konsole (das Terminal) ist ein einfaches Programm, dass letztlich nur Texte interpretiert, die Du eingibst. Wenn Du damit ein Programm startest, wie beispielsweise dein eigenes in Lektion 06, kann dieses Programm Ausgaben auf dem Terminal machen. Es kann aber auch Eingaben entgegen nehmen. Das bedeutet, dass Du dann deine Texte nicht mehr an das Terminal schickst, sondern an das Programm, dass jetzt über das Terminal kommuniziert.

Deswegen mache ich auch mehrere Terminals auf, an dem einen hängt mein Server, an dem anderen der Mongo-Server und am dritten die Mongo-Shell. Deine Texteingaben wie "show dbs" machst Du im Terminal der Mongo-Shell, nachdem Du sie in einem Terminal gestartet hast. Damit sie Wirkung zeigen, muss in einem anderen der Mongo-Server laufen.

Schau dir das Video nochmal an und achte genau darauf, welches Terminal für was zuständig ist.

**Comment by JirkaDellOro** [comment]
Kann das weg?

**Comment by TobMer** [comment]
Ich schließe es mal. Danke Lg
