### ISSUE TITLE
not a constructor

### ISSUE THREAD

**Issue by yank05** [JirkaDellOro/EIA2-Inverted#400]
Hallo,

hier mein Repository: https://github.com/yank05/EIA2_Endabgabe

warum lässt mich das Hauptprogramm in Zeile 110 keine neue Explosion erstellen und zeigt als Fehlermeldung "Firework.Explosion is not a constructor?"

Danke schonmal für die Hilfe

**Comment by JirkaDellOro** [comment]
Wenn Du mir einen Link auf die App schickst, lass' ich sie mal laufen und debugge.

Aus der Hüfte: prüfe die Reihenfolge, in der die Skripte geladen werden.

**Comment by yank05** [comment]
Die Reihenfolge probiere ich gerade schon rum, habe schon die main mal nach ganz unten gesetzt, hilft leider nicht. 

Hier mal die Seite: https://yank05.github.io/EIA2_Endabgabe/index.html

**Comment by JirkaDellOro** [comment]
Die Konsole zeigt mir sofort:
Vector.js:1          Failed to load resource: the server responded with a status of 404 ()
Explosion.js:1          Failed to load resource: the server responded with a status of 404 ()

**Comment by JirkaDellOro** [comment]
Beachte, dass der Pages-Server sehr viel strikter ist als der Localhost. Du musst also Groß-/Kleinschreibung prüfen, solltest keine Leer- und Sonderzeichen nutzen, am besten alles auf Englisch benennen etc.

**Comment by yank05** [comment]
Habs gefunden, bei der relativen Verlinkung hat ein Punkt gefehlt. Vielen Dank!
