### ISSUE TITLE
Endabgabe Feuerwerk - Serverproblem

### ISSUE THREAD

**Issue by VivienPeschke** [JirkaDellOro/EIA2-Inverted#403]
Ich habe den Server laut Anleitung installiert und habe nun versucht, die Werte der Formdata Elemente auf den Server zu speichern. Nach mehreren Möglichkeiten des ausprobierens und googelns kann ich leider doch nicht herausfinden, woran das noch liegen könnte.. Folgende Fehlermeldung erscheint in der Konsole:

<img width="905" alt="Bildschirm­foto 2023-02-12 um 19 37 22" src="https://user-images.githubusercontent.com/92156265/218330231-7dcee35f-2a9c-4f0d-a369-f98b12928a94.png">

Die Fehlermeldung kommt nach dem "click" auf den Button Rocket 1. In der Server Class ist die Domain zur Rockets.json verlinkt. Wie bekomme Ich es nun hin, dass ich die Daten auf meinen Server bekomme?

**Comment by JirkaDellOro** [comment]
Es muss wahrscheinlich heißen 
`.../Database?command=....`

**Comment by VivienPeschke** [comment]
Ich habs ausprobiert aber es kommt noch immer der selbe Fehler... Der Code ist auch aktuell gepushed in meinem Repo EIA2 Endabgabe Feuerwerk WiSe22 23
