### ISSUE TITLE
L09 - Canvas wird nicht angezeigt

### ISSUE THREAD

**Issue by KevinBlumtritt** [JirkaDellOro/EIA2-Inverted#41]
Hallo zusammen,

ich habe ein Problem bei der Einbindung des Canvas Hintergrunds, den ich in Aufgabe 08 erstellt habe.
Die animierten Schneeflocken habe ich bereits erstellt, diese funktionieren soweit ganz gut. Wenn ich diese nun aber mit meiner Canvas Datei verbinden möchte, wird das Canvas Bild nur sehr kurz, für einen Frame, angezeigt und verschwindet dann wieder. Die Schneeflocken werden dann ohne das Hintergrundbild weiter animiert. Ich habe in der Konsole nachgeschaut, dort scheinen alle Canvas Elemente (Berge, Schneemann, Wolken etc.) generiert zu werden.  Weiß jemand woran es liegen könnte, dass diese trotzdem nicht sichtbar sind?

Danke schonmal im Voraus
Kevin

**Comment by MarkusDamm** [comment]
Das liegt sicher daran, dass du den Canvas leerst ohne ihn wieder herzustellen. Falls du den Hintergrund speicherst solltest du ihn bevor die Schneeflocken gezeichnet werden wieder herstellen.

**Comment by KevinBlumtritt** [comment]
Danke, habe ein wenig recherchiert und mit getImageData und putImageData hat's dann funktioniert.
