### ISSUE TITLE
Guten Abend

### ISSUE THREAD

**Issue by CEpicwav** [JirkaDellOro/EIA2-Inverted#410]
Ich bin soweit fertig mit allem, leider jedoch kann ich meinen Steckbrief nicht  festlegen.
Angezeigt wird mir das:

Code korrekt...

Fehler: steckbrief.htm in
https://cepicwav.github.io/Sommersemester-2023/steckbrief
ist nicht lesbar oder nicht existent

was kann man da machen? sollte eigentlich alles so stimmen meines erachtens

**Comment by JirkaDellOro** [comment]
Dein Steckbrief ist da, was ist das Problem... außer das Du sehr spät dran bist?

Zur Frage auf dem Steckbrief: korrekt

**Comment by CEpicwav** [comment]
Guten Tag,Leider habe ich das Ticket vergessen zu schließenDanke trotz allem für die schnelle Rückmeldung!Am 26.03.23, 16:52 schrieb JirkaDellOro ***@***.***>:

   
  Dein Steckbrief ist da, was ist das Problem... außer das Du sehr spät dran bist? 
  Zur Frage auf dem Steckbrief: korrekt

**Comment by JirkaDellOro** [comment]
Dann schließ doch jetzt... na ich mach' mal.
