### ISSUE TITLE
Mir wird nichts im Span auf der Webseite angezeigt

### ISSUE THREAD

**Issue by LenaMarie1903** [JirkaDellOro/EIA2-Inverted#413]
Ich habe die Index.HTML im Browser mit dem LiveServer geöffnet. Jedoch werden mir die Inhalte des Spans mit der Mouseposition etc. nicht angezeigt. Ich habe die Index.HTML schon in mehreren Browser geöffnet, überall das selbe.

https://github.com/LenaMarie1903/EIA_2

**Comment by KohlerAl** [comment]
Hey, 
du suchst in Zeile 30 nach dem span. Das machst du mit getElementById und du suchst nach "#span0". Da du getElementById verwendest, brauchst du das # gar nicht, es reicht "span0". Da du danach schaust, ob span null ist (und das ist es in deinem Fall gerade, weil es kein span mit der ID "#span0" gibt, wird der Code danach nicht ausgeführt. Wenn du das # entfernst, sollte es gehen :)
PS: bitte bei solchen Problemen immer einen Link zu github pages hinzufügen damit wir direkt sehen, mit welcher Datei es Probleme gibt und wir nicht im Repo suchen müssen. Und auf Pages können wir direkt testen :)

**Comment by LenaMarie1903** [comment]
Hey,
Ich hab den # entfernt in Zeile 30 aber es hat nichts gebracht. 
https://github.com/LenaMarie1903/EIA_2
 https://lenamarie1903.github.io/EIA_2/A2/index.html

**Comment by LenaMarie1903** [comment]
Vielen Dank !!!!!!!!!!!!!
