### ISSUE TITLE
....Bisschen viele Koordinaten ausgegeben

### ISSUE THREAD

**Issue by maddyhansen** [JirkaDellOro/EIA2-Inverted#414]
Also an sich klappt das Teil, aber irgendwie schmeißt mir der Span sämtliche Koordinaten in einer wundervollen Liste aus. Kann mir jemand erklären was ich falsch gemacht hab? Danke schonmal im voraus!

https://github.com/maddyhansen/EIA2/tree/main/02_Aufgabe
https://maddyhansen.github.io/EIA2/02_Aufgabe/main.html

**Comment by KohlerAl** [comment]
Hey, das Problem ist, dass du, statt einem span jedes mal einen neuen Text zu geben, jedes mal ein neues Span erzeugst. Die lange Liste sind einfach ganz viele Spans nacheinander. Wenn du stattdessen ein Span im HTML erstellst und das dann selektierst , sollte sich dein Problem lösen :)

**Comment by maddyhansen** [comment]
Danke, ich probiers aus!

**Comment by JirkaDellOro** [comment]
@maddyhansen bitte Issue schließen wenn erledigt.
