### ISSUE TITLE
console log gibts nicht aus

### ISSUE THREAD

**Issue by maddyhansen** [JirkaDellOro/EIA2-Inverted#417]
Hallo! :)
Alles passt, bin eigentlich fertig. Beim Klick auf den Button gibt es aber den console log nicht aus. Finde schlichtweg den Fehler nicht. Kann mir jemand helfen? Danke im voraus!

https://maddyhansen.github.io/EIA2/02_Aufgabe/main.html
https://github.com/maddyhansen/EIA2/tree/main/02_Aufgabe

**Comment by maddyhansen** [comment]
Ja, am Custom Event bin ich noch dran :)

Leider läuft der immer noch nicht, auch wenn ich Zeile 39 in handleload ziehe. Ich hab die Gummientchenmethode, Neustart probiert und auch alle Links gecheckt. Hab dann nochmal meine tslint Datei abgecheckt, aber meine vorherige Aufgabe funktioniert einwandfrei. Weiß ehrlich gesagt nicht, was ich noch machen soll... Alles läuft perfekt bis meine function btn. :/

**Comment by KohlerAl** [comment]
Okay, ich glaub ich habs gefunden... du musst dem Span ein bisschen offset geben (also die Position vom Event +15 oder +20 auf beiden Koordinaten). Aktuell klickt man die ganze Zeit aufs Span, deswegen wird die Funktion vom Button nicht getriggert, weil man die ganze Zeit aufs Span und nicht auf den Button klickt.

**Comment by maddyhansen** [comment]
Also ich hab das mit offset versucht, aber irgendwie will das nicht wegen meinem Style was ich eingefügt habe. Wenn ich Offset sowie style auskommentiere, hängt das ding zwar nicht an der Maus, aber der Button läuft...

**Comment by KohlerAl** [comment]
Oh, ich meinte nicht als css Attribut, sondern in den Zeilen 31 und 32 statt positionx + "px" schreibst du dann positionx+ 20 + "px" (und das gleiche dann für y)

**Comment by maddyhansen** [comment]
OHHH ES FUNKTIONIERT! DANKE!

**Comment by KohlerAl** [comment]
Gerne, freut mich, dass es jetzt funktioniert :)
