### ISSUE TITLE
CustomEvent Benutzung

### ISSUE THREAD

**Issue by brotherbroadway** [JirkaDellOro/EIA2-Inverted#418]
Ich verstehe nicht genau, wie man das CustomEvent benutzen soll.
Bei mir wird der composedPath() beim Buttonclick in der Konsole ausgegeben ohne CustomEvent, muss ich es dann trotzdem noch einbauen? 😅

**Comment by JirkaDellOro** [comment]
Es geht vor allem um die Nutzung des CustomEvents, es ist eine Übung. In der Lektion ist ein kleines Beispiel, das helfen könnte.

**Comment by brotherbroadway** [comment]
Ok, ich werde versuchen es damit einzubauen 👍
