### ISSUE TITLE
Ist meine Konsoleausgabe vom CutomEvent richtig?

### ISSUE THREAD

**Issue by LenaMarie1903** [JirkaDellOro/EIA2-Inverted#419]
Ich habe nun das CustomEvent erstellt, jedoch bin ich mir nicht sicher, ob die Konsolenausgabe richtig ist. Wenn nicht wie müsste ich diese schreiben, damit das ganze CustomEvent ausgegben wird?
https://github.com/LenaMarie1903/EIA_2
https://lenamarie1903.github.io/EIA_2/A2/index.html

**Comment by KohlerAl** [comment]
Hey, das Ganze sollte eigentlich so aufgebaut sein, dass das document einen Listener für das custom Event bekommt und die Funktion, die aufgerufen wird, wenn der Listener getriggert wird, gibt das Event in der Konsole aus :)

**Comment by LenaMarie1903** [comment]
Ich habe das nun abgeändert, hab aber nun ein Fehler. Und beim ersten Mal wird mir in der Konsole Minka nicht ausgegeben.

**Comment by KohlerAl** [comment]
Welcher Fehler taucht denn genau auf? Ich habe keine Fehlermeldung in der Konsole, die Konsolenausgabe sieht bei mir so aus und Minka wird auch beim ersten klick ausgegeben. 
![image](https://user-images.githubusercontent.com/56314717/229295489-6387e076-1e97-4d46-ae2d-bc0160ef908c.png)

Mach das mit der Funktion, die beim custom Event aufgerufen wird, aber lieber in einer separaten Funktion, nicht in einer anonymen Funktion.

**Comment by LenaMarie1903** [comment]
Der Fehler ist in VSC. Und ja ich habe das mit Minka gelöst
 bekommen. Aber wenn ich es jetzt richtig verstehe ist alles richtig, ich sollte nur noch die zweite Funktion einführen?
