### ISSUE TITLE
Frage zu L09

### ISSUE THREAD

**Issue by TobMer** [JirkaDellOro/EIA2-Inverted#42]
So jetzt schaffe ich es zeitlich mal zu L09 und nehme gerne die Möglichkeit ein Issue zu dieser Lektion zu stellen.

Ich habe alle Videos durchgeschaut und mir gerade unsicher wie ich genau anfangen soll mein Canvas mit den Animation zu implementieren.

In den Asteroid Videos ist : Main, Path., Asteroid und Vector angegeben.
Klar , wenn ich snowflakes und birds animieren will muss ich die als Klasse definieren und exportieren.
Aber was ist genau die Main und Path Datei?
Ist die Main Datei der Canvas Code den ich in L08 erstellt habe?

Ich bin da leider nicht so ganz mitgekommen und weiß nicht wie ich anfangen soll.
Schöne Feiertage und die Weihnachtskarte war nice

**Comment by JirkaDellOro** [comment]
> Klar , wenn ich snowflakes und birds animieren will muss ich die als Klasse definieren und exportieren. 
 
Das ist schon einmal richtig und gut.

Die Path-Datei war für Asteroids passend, da ich mir die Vertices der Objekte rausgefummelt habe und dort zentral ablegen konnte. Das kann man aber auch anders machen. Da ihr viel farbiger unterwegs seid ist es eher nicht angebracht, Pfade irgendwo zentral zu sammeln. Sämtliche Pfad- und Zeichenanweisungen werden eher in den Zeichenmethoden der einzelnen Klassen untergebracht.

Die Main-Datei, also das Hauptprogramm, kannst Du aus der alten Main entwickeln. Du verschiebst die objekt- bzw. klassenbezogenen  Bestandteile in die entsprechenden Klassendateien. Was dann übrig bleibt wird, entsprechend refaktoriert, zur neuen "Main"

**Comment by TobMer** [comment]
Alles klar.
Jetzt habe ich im Video gesehen, dass du in der Index Datei diesen Code hast: 
<meta http-equiv="Y-UA-Compatible" content="ie=edge">
was macht der genau?

Was kommt dann zum Beispiel in der Klasse "Snowflake " rein? also ich habe zwar die Klasse erstellt aber was soll im " Main " vom Code "Snowflake" drin sein, sodass beides passt?
🗡 LG

**Comment by JirkaDellOro** [comment]
Leider fehlt in deiner Frage der Code.

Wenn Main der "Halter" der Schneeflocken sein soll, werden dort die Flocken kreiert, gespeichert und ihre Methoden aufgerufen. Trifft das schon deine Frage?

**Comment by TobMer** [comment]
Oh da habe ich vergessen den Code einzufügen:
<meta http-equiv="Y-UA-Compatible" content="ie=edge">
. Den meinte ich.

Also setze ich die move und draw in die Klasse von Snowflake ein. 
Und die Funktion von Snowflake in den Main?(Halter)
Lg

**Comment by JirkaDellOro** [comment]
> meta http-equiv="Y-UA-Compatible" content="ie=edge"

Das baut VSCode selbst, wenn ich automatisch die HTML-Datei erzeugen lasse. Müsste ich selbst googeln, es ist wohl aber wieder eine Extrawurst für den Microsoft-Browser.


> Und die Funktion von Snowflake in den Main?(Halter)

Was meinst Du mit "die Funktion von Snowflake"?
