### ISSUE TITLE
Custom-Event Fehler.

### ISSUE THREAD

**Issue by Jovolunas85** [JirkaDellOro/EIA2-Inverted#421]
Mir wird ein Fehler angezeigt, den ich zwar schon verstehe aber nicht weiß wie ich ihn löse. Außerdem wird mir trotz des Fehlers der Wert ausgegeben.
Also 'e.detail.name' wird mir als Fehler angezeigt aber trotzdem wird mir in der Konsole  ausgegeben : " true 'Julian' ".

https://github.com/Jovolunas85/EIA2/blob/main/A02_event_inspector/script.ts
https://jovolunas85.github.io/EIA2/A02_event_inspector/index.html

**Comment by JirkaDellOro** [comment]
Ich empfehle, bei den Konstruktionen zu bleiben, die wir in der Lektion behandeln.

` (e) =>console.log(e.bubbles,e.detail.name)`

leuchtet wahrscheinlich nicht besser ein, ist nicht besser zu lesen und nutzt nicht mehr die Typ-Annotation, wegen der wir TypeScript einsetzen wollen.


Außerdem installierst Du gerade bei jedem Klick einen neuen Listener, und das Event steigt auch nicht in der Hierarchy auf, sondern wird von `document` an sich selbst geschickt.

Hattest Du zunächst konzipiert?

**Comment by Jovolunas85** [comment]
Dann habe ich wohl nicht ganz verstanden wie das mit dem Custom Event funktioniert

**Comment by Jovolunas85** [comment]
Also ich verstehe Custom Event  nicht

**Comment by Jovolunas85** [comment]
Bzw. wie das mit der Hierarchy funktioniert

**Comment by Jovolunas85** [comment]
Also eigentlich verstehe ich jetzt nichts mehr

**Comment by JirkaDellOro** [comment]
Wenn Du auf einem Element ein CustomEvent losschickst, läuft es genauso durch die Hierarchie wie z.B. der Mausklick.

Wenn sich TypeScript beschwert, dann wahrscheinlich, weil die Typdeklaration noch angepasst werden muss. Nur CustomEvents haben die "Schublade" `detail`...

**Comment by JirkaDellOro** [comment]
Hilft das?
