### ISSUE TITLE
Mein Datum wird nicht richtig angezeigt wenn ich ein neues ToDo erstellen möchte

### ISSUE THREAD

**Issue by Jovolunas85** [JirkaDellOro/EIA2-Inverted#422]
Eigentlich sollte im Input-Element von datetime-local: value="2023-04-29T14:00" sein. Deswegen habe ich in der Typescirpt Datei 
"newDate.value = todolist[i].date;" geschrieben wobei das date einmal den Wert "2023-04-29T14:00" und "2023-04-21T12:23" hat. Ich weiß nun leider nicht wie ich mir das richtig als Datum-Input-Element anzeigen lassen.

https://github.com/Jovolunas85/EIA2/tree/main/A03_todo
https://jovolunas85.github.io/EIA2/A03_todo/index.html

**Comment by KohlerAl** [comment]
Hey, aktuell erstellst du in deinem Code ein Element mit dem Tag "datetime-local". Das gibt es aber nicht. Was du brauchst ist ein input-Element vom typ datetime-local :)

**Comment by Jovolunas85** [comment]
Also 'input[type="datetime-local"]' hat nicht funktioniert

**Comment by KohlerAl** [comment]
Du speicherst dir das neu erstellte HTML-Element ja in einer Variablen, nachdem du das Element erstellt hast, setzt du dann mit setAttribute das attribut "type" auf "datetime-local"
