### ISSUE TITLE
Icon ändern & Zugriff auf let i (der for-Schleife)

### ISSUE THREAD

**Issue by Jovolunas85** [JirkaDellOro/EIA2-Inverted#423]
In Zeile 96 habe ich versucht einen EventListener auf das newDone  Icon zu installieren aber es hat nicht funktioniert und ich komme nicht weiter.

In function Create Todo() bräuchte ich theoretisch Zugriff auf 'let i' aber wenn ich versuche das in der for-Schleife durchzuführen geht es nicht und ich weiß nicht woran es liegt.

https://jovolunas85.github.io/EIA2/A03_todo/index.html
https://github.com/Jovolunas85/EIA2/tree/main/A03_todo

**Comment by JirkaDellOro** [comment]
Wenn ich das Programm starte kommt die folgende Fehlermeldung in der Konsole:
![image](https://user-images.githubusercontent.com/6279994/232092666-e79dd5ee-9425-4dad-baa6-45f57e817fc7.png)
sieht aus, als könnte kein Element mit der id `edit` gefunden werden.
Hat das schon damit zu tun?

**Comment by Jovolunas85** [comment]
Also es müsste was mit "todolist[i].done = !todolist[i].done;" zu tun haben denn das "console.log("hallo");" in Zeile 101 wird ausgegeben.
Außerdem habe ich das mit dem querySelector auskommentiert aber trotzdem wird der Fehler bei mir angezeigt.

**Comment by JirkaDellOro** [comment]
Problem erkannt und gelöst? Schreibe bitte noch einen kurzen Kommentar hier, damit wir wissen, was los war. Das hilft uns.
