### ISSUE TITLE
Pushen wird endlos ausgeführt

### ISSUE THREAD

**Issue by Jovolunas85** [JirkaDellOro/EIA2-Inverted#424]
Die Funktion arrayPush (in Zeile 179) wird endlos ausgeführt und ich weiß nicht warum.

https://jovolunas85.github.io/EIA2/A03_todo/index.html
https://github.com/Jovolunas85/EIA2/tree/main/A03_todo

**Comment by JirkaDellOro** [comment]
Wie immer: schreibe bitte eine kurze Erklärung der Lösung
