### ISSUE TITLE
Daten aus Datenbank sind nicht (richtig) verknüpft

### ISSUE THREAD

**Issue by Schwer5** [JirkaDellOro/EIA2-Inverted#425]
wenn ich meine data.ts Dateien in mein main ts einfüge funktioniert alles. Wenn man diese aus der main.ts aber auskommentiert, funktioniert es nichtmehr.Die data.ts ist nicht verknüpft. Ich weiß nicht ob da was mit dem namespace nicht funktioniert oder was anderes... 

`https://github.com/Schwer5/EIA2_SoSe_22-23/tree/main/A04_Aufgabenliste_Formular`

**Comment by KohlerAl** [comment]
Hast du denn alle Dateien auch im html verlinkt? Und in der richtigen Reihenfolge? In diesem Fall erst die Data.ts, dann die main.ts

**Comment by Schwer5** [comment]
:) hab die data.ts garnicht verlinkt 
Danke
