### ISSUE TITLE
Fehlermeldung und splicen aus der ToDo Liste

### ISSUE THREAD

**Issue by Jovolunas85** [JirkaDellOro/EIA2-Inverted#426]
Mir wird zum einen angezeigt (in Zeile 195), dass cDiv kein child von wrapper ist. Jedoch habe ich in Zeile 171 geschrieben: wrapper.appendChild(cDiv) was auch ausgeführt wird. Ich weiß nicht warum mir der Fehler angezeigt wird.

Zum anderen weiß ich nicht wie ich den Unterpunkt in "todolist" splicen soll (also wie ich die Stelle an der gespliced werden soll angebe). Das gleiche Problem habe ich auch mit dem bearbeiten Button.  

https://jovolunas85.github.io/EIA2/A03_todo/index.html
https://github.com/Jovolunas85/EIA2/tree/main/A03_todo

**Comment by JirkaDellOro** [comment]
Dein Code wird langsam etwas schwierig nachzuvollziehen. Die definierst Funktionen innerhalb von Funktionen, das sollte vermieden werden. Auch anonyme Funktionen solltest Du nur verwenden, wenn Du dich gut auskennst. Es würde mich wundern, wenn Du das so konzipiert hast, so hatte ich es nicht gezeigt. Eine gute Konzeption dagegen führt zu gutem und stabilem Code. Es wird sicher sehr viel leichter, wenn Du die Funktionen auf einer Ebene und unabhängig voneinander hältst, so wie ich es vormache.

Die Zeilen 171 und 195 liegen in zwei verschiedenen Funktionen, die zu unterschiedlichen Zeiten bzw. aufgrund unterschiedlicher Ereignisse aufgerufen werden, es gibt hier keinen direkten Zusammenhang zur Laufzeit. Ich kann mir gut vorstellen, dass Du dich damit durcheinander bringst.  

Noch ein paar Tipps:
statt
```typescript
        if (taskinput.value != "") {
            if (commentinput.value != "") {
                if (personinput.value != "") {
                    if (deadlineinput.value != "") {
```
könntest Du Early-Outs schreiben und vermeidest die tiefe Einrückung, die das Debugging erschwert. Da Du ohnehin die gleiche Meldung ausgibst, kannst Du auch einen Einzeiler mit logischer Verknüpfung machen, also
```typescript
if (taskinput.value =="" || comen.... ) {
  // ausgabe
  return
}
```

**Comment by JirkaDellOro** [comment]
Hat das geholfen?

**Comment by Jovolunas85** [comment]
Ja

**Comment by Jovolunas85** [comment]
Vielen Dank

**Comment by JirkaDellOro** [comment]
Gut und danke, dass Du hier dazu eine Rückmeldung gibst. Für uns Helfer ist es wichtig zu wissen, ob die Hilfe fruchtet und wie. Außerdem freut es uns, wenn's klappt. Deswegen hatte ich das schon in deinen anderen Issues angemerkt.
