### ISSUE TITLE
Probleme beim laden 

### ISSUE THREAD

**Issue by maddyhansen** [JirkaDellOro/EIA2-Inverted#427]
Hallo! :) Ich finde mein Problem nicht...
 Wenn ich auf Add drücke, lädt es und alles wird Neu geladen, aber die Task wird nicht angezeigt. Hilfe...? 

https://github.com/maddyhansen/EIA2
https://maddyhansen.github.io/EIA2/04_Aufgabe/main.html

**Comment by JirkaDellOro** [comment]
Klassiker!

Ein Button in einem Formular ist automatisch ein Submit-Button und bewirkt das Versenden der Formulardaten. Das sieht man auch oben im URL, in dem nun plötzlich die Daten mit eingetragen sind.

Du musst dem Type-Attribut des Buttons einen anderen Wert zuweisen, die Optionen werden dir wahrscheinlich angeboten.

**Comment by maddyhansen** [comment]
Danke schön!:)
