### ISSUE TITLE
Wie kann ich spezifische Einträge lokal ansprechen?

### ISSUE THREAD

**Issue by brotherbroadway** [JirkaDellOro/EIA2-Inverted#428]
Bisher hatte ich die Data in der JSON als als einen TaskItem[] von "thisList" abgespeichert gehabt.

Nun mit dem Server ist es aber kein Array mehr, und da jeder Eintrag jetzt eine ID hat, weiß ich aber nicht, wie ich die lokal mit dem Interface ansprechen kann...

Bisher hatte ich das über allTheTasks.thisList.owner z.B. gemacht, aber das funktioniert jetzt nicht mehr.

Und ich kann sie auch nicht über den Eintrag allServerTasks[0].owner z.B. ansprechen, da es kein Array mehr ist...

![image](https://user-images.githubusercontent.com/10756742/235232607-10167438-38ca-4f92-8aaf-43ad69d11df7.png)

**Comment by JirkaDellOro** [comment]
Was ist deine Lösung? Das kann anderen helfen...
