### ISSUE TITLE
Frage zur Abschlussarbeit (CharacterEditor)

### ISSUE THREAD

**Issue by RolandHeer** [JirkaDellOro/EIA2-Inverted#43]
Sehr geehrte EIA2 Begeisterten!

Während des Bearbeitens der Abschlussarbeitsaufgabe, kam mir bezüglich der Umsetzung eine Frage auf. In den, der Abschlussarbeit vorangestellten, Aufgaben, wurde eine Datenbank genutzt um die Anzeige der diversen Charaktereigenschaftsoptionen mit Informationen zu versehen. Dies war in der Aufgabenstellung nötig und einer festen Einprogrammierung überlegen, da somit ein potentieller Spielleiter diese Eigenschaften neu definieren und oder andere hinzufügen kann. Da mit der Endabgabe die neue Funktion des "Live-Charakterzeichnens" hinzukommt, ist diese Funktion allerdings nicht mehr zu gewährleisten, da in diesem Fall die ganzen zu zeichnenden Objekte fehlen würden.
Ist es in diesem Falle möglich und nicht vielleicht sogar besser, die Daten direkt im Html / im dazu gehörigen Skript zu definieren?

Hochachtungsvoll,
Roland Heer

**Comment by JirkaDellOro** [comment]
Um das zu berücksichtigen, entwickelt man eine Struktur, die es erlaubt, neue Elemente auch mit Ihrer Darstellung einzupflegen.  So genügt ein weiteres Bitmap (mit der Angabe des lokalen Ursprungs) oder eine weitere Funktion im Zeichencode, um ein neues Element darzustellen. Für die Aufgabenstellung genügt es, wenn diese Struktur im Prinzip angelegt ist.
Wird ein Objekt der Datenbank hinzugefügt, die grafische Darstellung aber noch nicht eingepflegt, soll ein "Default"-Objekt an dessen Stelle dargestellt werden, so dass ins Auge fällt, dass hier noch etwas fehlt...
