### ISSUE TITLE
Problem mit Ts Compiler

### ISSUE THREAD

**Issue by MStolz0** [JirkaDellOro/EIA2-Inverted#443]
mir ist letztens der PC abgeschmiert und seitdem hab ich folgendes Problem:
![fm](https://github.com/JirkaDellOro/EIA2-Inverted/assets/102662298/7582ba31-4818-4966-9da4-0e3e2ac641a8)

**Comment by JirkaDellOro** [comment]
Stelle VSCode so ein dass das einfache Command-Prompt dein Standard-Terminal ist und nicht die Powershell. Anleitung auf Google...
   
   
   
    MStolz0 ***@***.***> hat am 11.04.2024 12:06 CEST geschrieben:
    
   
     
    
   
     
    
     
   mir ist letztens der PC abgeschmiert und seitdem hab ich folgendes Problem:fm.PNG (view on web)
