### ISSUE TITLE
Error bei Servereinrichtung

### ISSUE THREAD

**Issue by AleaFlesch** [JirkaDellOro/EIA2-Inverted#45]
Bei der Einrichtung des Servers erschienen bei mir bei der Überprüfung im Terminal mithilfe von npm start viele Errors.

Da Markus mir auch nicht weiterhelfen konnte, hoffe ich, dass Sie mir helfen können.

Danke und liebe Grüße!

<img width="557" alt="Bildschirmfoto 2020-02-07 um 18 05 07" src="https://user-images.githubusercontent.com/43847138/74049622-c4b03c80-49d4-11ea-8491-059206789a0e.png">

**Comment by JirkaDellOro** [comment]
ist "EIA2/EIA2/" im Pfad korrekt?

**Comment by JirkaDellOro** [comment]
PS: Issues lesen alle, nicht nur ich. Daher am besten ohne Anrede posten oder mit @JirkaDellOro , falls ich angesprochen werden soll

**Comment by AleaFlesch** [comment]
@JirkaDellOro Super danke, der Pfad war tatsächlich falsch
