### ISSUE TITLE
Abgabe auf GitHub sichtbar?

### ISSUE THREAD

**Issue by MaximilianoRottenanger** [JirkaDellOro/EIA2-Inverted#457]
Hallo, ich habe nun alle Änderungen des fertigen Gedichts commited und mit git:Push auf GitHub hochgeladen. Ich hoffe das passt soweit und ist für euch einsehbar. Vielen Dank

**Comment by JirkaDellOro** [comment]
Wenn Du einen Issue postest, bitte inkludiere Links zu deiner Arbeit, damit man gleich von hier aus darauf zugreifen kann

**Comment by JirkaDellOro** [comment]
...du hast auch keinen Link in Felix gepostet. Wie soll ich deine Abgabe sehen?

**Comment by MaximilianoRottenanger** [comment]
hallo jirka, ich habe gerade gemerkt, dass das im felix nicht richtig aussieht. ich änder das jetzt. hier trotzdem nochmal der link zu meiner abgabe: https://github.com/MaximilianoRottenanger/EIA2_Repository/tree/main/A01_RandomPoem
Mit freundlichen Grüßen,
 Maximiliano

**Comment by JirkaDellOro** [comment]
Poste immer einen Link zum Code und einen zum lauffähigen Programm, und zwar bitte so, dass man einfach draufklicken kann.
