### ISSUE TITLE
Server Einrichtungsproblem

### ISSUE THREAD

**Issue by theresagut** [JirkaDellOro/EIA2-Inverted#46]
Bei der Einrichtung des Heroku Server erschien nach dem ich npm start gemacht habe dieser error bei manual deploy. Siehe Bild 
<img width="1440" alt="Bildschirmfoto 2020-02-07 um 18 01 04" src="https://user-images.githubusercontent.com/43847022/74049727-07721480-49d5-11ea-90fa-528cfd4dfbb5.png">

**Comment by JirkaDellOro** [comment]
Zumindest in deinem EIA2-Repository kann ich keine Datei package.json finden. Diese muss auf der obersten Ebene liegen, damit Heroku weiß was geschehen soll.

**Comment by theresagut** [comment]
stimmt, das habe ich gerade gesehen. Allerdings kann ich nichts pushen obwohl es in vsc abliegt.

**Comment by JirkaDellOro** [comment]
Was passiert wenn man pusht? Ist auch schon ein Commit getätigt worden?

**Comment by theresagut** [comment]
ja, ein Commit wurde getätigt.

**Comment by theresagut** [comment]
hier sieht man es nochmal. Der Endabgabe Ordner ist in vsc aber nicht in git obwohl keine push und commits vorliegen

<img width="1440" alt="Bildschirmfoto 2020-02-08 um 14 12 11" src="https://user-images.githubusercontent.com/43847022/74085795-2deb8a80-4a7d-11ea-96d5-09c16f08dcb8.png">

**Comment by JirkaDellOro** [comment]
Ist das auch wirklich das Verzeichnis, das mit Github synchronisiert wird? Ist es überhaupt unter git-Kontrolle? Wie sieht es aus, wenn man in VSC den SourceControl-View anschaut?

**Comment by theresagut** [comment]
hat geklappt!

**Comment by JirkaDellOro** [comment]
Ha, jetzt will ich es aber schon noch wissen: was war das Problem?

**Comment by Plagiatus** [comment]
laut bild würde ich vermuten, dass da einfach noch 2 commits nicht gepusht waren (siehe unten links).

**Comment by JirkaDellOro** [comment]
Aber warum konnte Theresa nicht pushen?

**Comment by theresagut** [comment]
Ich habe mein Rechner und VSC neu gestartet und danach hat es funktioniert.
