### ISSUE TITLE
Birds triggern Futter

### ISSUE THREAD

**Issue by TobMer** [JirkaDellOro/EIA2-Inverted#47]
Nabend. Wie kann ich meine Birds so triggern, dass die zu dem geworfenen Futtern hingehen und stehen bleiben?

**Comment by JirkaDellOro** [comment]
Da gibt es viele Möglichkeiten. Schreibe hier mal deine Ideen dazu auf, dann kann ich dich etwas lenken.

**Comment by TobMer** [comment]
Ich denke mal, dass die Birds wissen sollen , hey hier liegt das Birdfood und zu dieser Position muss ich hin. Also muss ich denke bei der Klasse Birds eine Verbindung zu dem Birdfood herstellen. Dann soll ja das Food nach ner Zeit verschwinden ( ich denke SetTimeout hilft da) und die Birds ziehen weiter.

**Comment by JirkaDellOro** [comment]
Ja, das passt schon im Groben. Du musst noch weitere Fragen beantworten:
- was ist Birdfood eigentlich?
- wie finden die Vögel heraus, dass welches da ist und wo? Oder bekommen die das mitgeteilt? Alle, oder nur bestimmte?
- was machen sie, wenn sie am Futter angekommen sind?
- verschwindet das Futter, unabhängig von den Vögeln? Wenn ja, warum? Oder verbrauchen die Vögel es?

**Comment by TobMer** [comment]
Ich habe eine neue Klasse mit Birdfood erstellt. 
Das Design ähnlich wie bei den Snowflakes.
Dann bei den Birds zwei neue Funktionen erstellt, dass die zu ihrer aktuellen Positionen an eine neue hinfliegen.  Diese mit einem SetTimeout so erstellt , dass die ein paar sek. bei dem Futter bleiben und weiterfliegen.
Also es geht.

**Comment by JirkaDellOro** [comment]
Ist das nicht schön? Und ich habe dir eigentlich nur Fragen gestellt...
