### ISSUE TITLE
Problem beim Serverzugriff

### ISSUE THREAD

**Issue by melreinhardt** [JirkaDellOro/EIA2-Inverted#48]
Schönen guten Abend Herr @JirkaDellOro,

ich stehe hier vor einem kleinen Problem.
Beim Abruf meines Servers wird leider nicht dieser und schon gar nicht dessen Inhalt geladen sonder die Struktur einer Github-Page. 

https://melreinhardt.github.io/mrhdt.eia2/Vogelhaus/startingPage.html
https://github.com/melreinhardt/mrhdt.eia2/tree/master/Vogelhaus

![Screenshot (16)](https://user-images.githubusercontent.com/48826848/74107949-3e7f2c00-4b75-11ea-8fec-0386628ad558.png)

**Comment by JirkaDellOro** [comment]
Ich habe mir das im Debugger der Browserkonsole angeschaut. Zeile 11 in Highscore.ts sieht so aus:
`let response: Response = await fetch(url + "?" + query);`

Das ist auch OK so, aber `url` ist `undefined` zur Laufzeit. Das erklärt auch das Verhalten, da `fetch`, in Ermangelung eines vollständigen URL, nun die aktuelle Seite lädt und als Text darstellt.

Wo wird die Variable `url` definiert?

**Comment by melreinhardt** [comment]
Die Variable ist in Canvas.ts definiert

**Comment by MarkusDamm** [comment]
Das Canvas-Skript ist aber nicht in der startingPage.html verlinkt. Dadurch wird auch url nicht für das Highscore-Skript definiert

**Comment by melreinhardt** [comment]
Ich habe die url jetzt auch in der highscore.ts definiert. Leiderfunktioniert es immer noch nicht

**Comment by melreinhardt** [comment]
ok nvm es klappt mein fehler
