### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by MelinaWa** [JirkaDellOro/EIA2-Inverted#49]
Hallo, 

ich habe auch Probleme bei der Servereinrichtung. Siehe Bild. 

Außerdem bekomme ich immer wieder eine Fehlermeldung, die dann auslöst, dass im .git ordner auf meinem Rechner dauernd neue FETCH_HEAD-DESKTOP-9987AJV Dateien erstellt werden.

Kann mir da jemand helfen? Danke 

![git](https://user-images.githubusercontent.com/43846707/74134992-ca339f80-4beb-11ea-8894-992b5242ef7b.JPG)
![npm start](https://user-images.githubusercontent.com/43846707/74134997-cb64cc80-4beb-11ea-8940-0ac0277714df.JPG)
![Unbenannt](https://user-images.githubusercontent.com/43846707/74135003-cc95f980-4beb-11ea-8faa-16736642bebe.JPG)

**Comment by LukasBrauschHFU** [comment]
Ist inzwischen gelöst. Das Problem mit den Errors hat existiert, weil es Leerzeichen in dem Pfad zu den Skripts gab und weil MongoDB nicht installiert war.

Das 2. Problem gab es, weil das Projekt direkt im OneDrive bearbeitet wurde

**Comment by Plagiatus** [comment]
Da sind zwei Probleme: 
1. kann der server nicht starten. Leider ist die eigentliche Fehlermeldung wahrscheinlich weiter oben. Außerdem wird das so auf dem Server nicht funktionieren, da auf dem Server eine andere Dateistruktur vorliegt, du wirst also einen relativen Pfand angeben müssen.
2. grätscht dir OneDrive dazwischen, das mit dem FETCH_HEAD liegt alleine daran, dass OneDrive sich da einmischt. vllt kannst du OD ja für den .git ordner ausschalten?

**Comment by MelinaWa** [comment]
Danke! Ja, ich hab auch gemerkt, dass das mit OneDrive ein Problem ist. Ich hab den Pfad geändert und konnte das Problem mit dem Server mit Lukas Hilfe lösen. Ich glaube es funktioniert jetzt.
