### ISSUE TITLE
Datenbankeinträge

### ISSUE THREAD

**Issue by melreinhardt** [JirkaDellOro/EIA2-Inverted#50]
Es jetzt 4 Eintrage erstellt - leider noch nicht richtig aber es wurden welche erstellt. Nun werden nach Bestätigung des Prompts keine Einträge mehr erstellt. Hat jemand eine Idee warum?

https://github.com/melreinhardt/mrhdt.eia2/tree/master/Vogelhaus

**Comment by JirkaDellOro** [comment]
Bitte einen Link zur lauffähigen App angeben....

**Comment by melreinhardt** [comment]
oh, entschuldigung
https://melreinhardt.github.io/mrhdt.eia2/Vogelhaus/startingPage.html
jetzt müsste es funktionieren 
github war zu langsam
jetzt funktioniert es nur nicht die starting page in dem gleichen tab wieder zu laden

**Comment by JirkaDellOro** [comment]
Man muss Github und Heroku eine Minute Zeit geben, um sich abzustimmen

Das Neulade-Problem kann ich nicht nachvollziehen.

Wann kommt eigentlich die Futter-Interaktion etc?

**Comment by melreinhardt** [comment]
wenn man die leertaste drückt

**Comment by JirkaDellOro** [comment]
Cool. Hätte ich allerdings auch lesen können...
