### ISSUE TITLE
Application Error

### ISSUE THREAD

**Issue by AleaFlesch** [JirkaDellOro/EIA2-Inverted#51]
Bei der Heroku Einrichtung erscheint trotz erfolgreichem Deploy, wenn man auf View klickt ein Application Error. Dieses Problem haben viele von uns uns Markus findet leider keine Lösung für das Problem. Können Sie @JirkaDellOro uns vielleicht helfen?

Meine package.json müsste auf der richtigen Ebene liegen und die Verlinkung zur server.js Datei stimmt auch.

Hier ein paar Impressionen:

<img width="1375" alt="Bildschirmfoto 2020-02-10 um 16 33 38" src="https://user-images.githubusercontent.com/43847138/74164136-a55b1e80-4c23-11ea-988d-538f3ca5f29b.png">

<img width="613" alt="Bildschirmfoto 2020-02-10 um 16 32 23" src="https://user-images.githubusercontent.com/43847138/74164101-9c6a4d00-4c23-11ea-82c1-fd9b6164dce4.png">

<img width="1317" alt="Bildschirmfoto 2020-02-10 um 16 32 33" src="https://user-images.githubusercontent.com/43847138/74164153-aa1fd280-4c23-11ea-89ad-e49d9c2454e4.png">

<img width="1276" alt="Bildschirmfoto 2020-02-10 um 16 42 55" src="https://user-images.githubusercontent.com/43847138/74164743-772a0e80-4c24-11ea-8eff-7ca188a89601.png">

**Comment by JirkaDellOro** [comment]
Ich schätze dass es daran liegt, dass unter `dependencies` in der package.json der Eintrag für MongoDB fehlt. Heroku weiß dann nicht, dass es mit MongoDB arbeiten soll...

**Comment by JirkaDellOro** [comment]
Vergleiche die package.json-Datei aus dem Inverted-Classroom

**Comment by aliciaTED** [comment]
Ich habe den gleichen Fehler, allerdings hab ich bei dependencies drinstehen, dass es mit MongoDB arbeiten soll. Meine Package.json ist auf der obersten Ebene von meinem Repository für EIA2, den Pfad habe ich mehrfach überprüft. 

Diese Fehlermeldungen befinden sich in meinem Log, es scheint wohl irgendein Problem mit der Start-Datei meines Servers zu geben, allerdings weiß ich wirklich nicht, woran es liegt, weil der Pfad ja richtig sein sollte... Markus hat da heute auch drübergeschaut und wusste nicht, woran es liegt. 
Wenn die Heruko-App nicht funktioniert, kann ich leider nicht wirklich an der Pflichtaufgabe zur Datenbank weiterarbeiten bzw. diese nicht testen... 

![image](https://user-images.githubusercontent.com/48830896/74174126-b1e77300-4c33-11ea-8abf-ffec08fe2d76.png)
![image](https://user-images.githubusercontent.com/48830896/74174283-f2df8780-4c33-11ea-9cfb-9744dcf2fd2e.png)
![image](https://user-images.githubusercontent.com/48830896/74174337-0b4fa200-4c34-11ea-9513-30a08c2c2f62.png)


Danke schon einmal für die Hilfe!

**Comment by Plagiatus** [comment]
Ich sehe in deinem Repository in `/Endabgabe/Vogelhaus_Predator_v1/` nur eine `server.js`, keine `Server.js`

**Comment by aliciaTED** [comment]
oh, danke, die Dateien hat es aus irgendeinem Grund nicht in mein Repository gepusht... (sind definitiv nicht in .gitignore, also keine Ahnung, was da los war). Danke, danke, danke, auf jeden Fall, jetzt funktioniert es!

**Comment by AleaFlesch** [comment]
Das hat mir tatsächlich in der package.json gefehlt..
Der Application Error ist jetzt weg, allerdings werden mir jetzt zwei geschweifte Klammern angezeigt. Ist das gewünscht? 😄

<img width="656" alt="Bildschirmfoto 2020-02-10 um 21 59 59" src="https://user-images.githubusercontent.com/43847138/74189739-3c8a9b00-4c51-11ea-8f0f-66ca013d6848.png">

<img width="810" alt="Bildschirmfoto 2020-02-10 um 21 59 45" src="https://user-images.githubusercontent.com/43847138/74189691-28469e00-4c51-11ea-8b2b-034be04eabc9.png">

<img width="1242" alt="Bildschirmfoto 2020-02-10 um 21 59 36" src="https://user-images.githubusercontent.com/43847138/74189744-3eecf500-4c51-11ea-8f60-b5a78df41d00.png">

**Comment by AleaFlesch** [comment]
Also die Klammern erscheinen beim klicken auf View

**Comment by JirkaDellOro** [comment]
Es sieht aus. als würde der Query-String, wahrscheinlich geparsed als JSON, ausgegeben, und der ist leer. Folglich erscheinen nur die umschließenden Klammern. Was passiert, wenn ein Query-String angegeben wird?

**Comment by AleaFlesch** [comment]
Habs ausprobiert, bei Ergänzung wird diese in MongoDB ausgegeben. Müsste also alles passen :)
Danke!
