### ISSUE TITLE
Sortierung der Datenbank nach Punktzahl

### ISSUE THREAD

**Issue by MarkusDamm** [JirkaDellOro/EIA2-Inverted#53]
Jetzt noch eine kurze Frage zum Titel. Ich habe diese Mongo-Doku gefunden, die ich relevant fand: http://mongodb.github.io/node-mongodb-native/3.1/api/Cursor.html#sort

Hat sich für mich so angehört, als würde es die Datenbankeinträge nach meinem eingespeichertem score sortieren können. Hab es also auf meinem Server genutzt (Line 73) : https://github.com/MarkusDamm/EIA-2.1/blob/master/LLast/server/server.ts

Das Ergebnis: die Einträge sind immer noch in der Reihenfolge, in der sie erstellt wurden. Ist alles gewatched, gepusht und deployed. Woran könnte es also liegen? 
Habe auch eine andere Schreibweise probiert, welche mir empfohlen wurde, die so aussah: cursor.sort({ score: -1 })

**Comment by JirkaDellOro** [comment]
Das ist dein Code
```typescript
        let cursor: Mongo.Cursor = entries.find();
        cursor.sort("score", -1);    // not sorting
        _response.end();
```

Ich sehe hier mehrere Fehlerquellen:
1. Du rufst `find` hier synchron auf, der Cursor ist höchstwahrscheinlich noch gar nicht geladen, wenn er sortieren soll
2. Du nutzt den Cursor gar nicht weiter, nachdem er sortiert wurde
3. Du gibst kein Ergebnis weiter, die response wird einfach beendet.

**Comment by MarkusDamm** [comment]
zu 1. VSCode sagt mit wenn ich await vor entries.find(); setzte "'await' has no effect on the type of this expression.", weshalb ich dem quickfix gefolgt bin und das "unnötige" await löschte. Nach dem Denkanstoß kam die Erleuchtung.

zu 2 und 3: Ich dachte, .sort() sagt direkt der Datenbank, dass sie sich sortieren soll. Noch Erleuchtet habe ich dem cursor gesagt, dass er sich, bevor sein Inhalt als Antwort gespeichert wird, sortieren soll. So steht's jetzt an richtiger Stelle:

        let cursor: Mongo.Cursor = await entries.find();
        cursor = cursor.sort("score", -1);
        let answer: Promise<any[]> = await cursor.toArray();

und funktioniert! Danke :-)

**Comment by JirkaDellOro** [comment]
Ich frage mich, ob die Zuweisung erforderlich ist oder ob nicht auch einfach
`cursor.sort("score", -1);`
funktionieren würde

**Comment by MarkusDamm** [comment]
Das wird wohl etwas sein, was ich erst nach der bestanden Prüfung testen werde.
Vielleicht geht .sort() und .toArray() auch direkt in einer Zeile :thinking:
