### ISSUE TITLE
Steckbrief nicht lesbar

### ISSUE THREAD

**Issue by Jonas915** [JirkaDellOro/EIA2-Inverted#68]
Guten Morgen,
ich habe gerade versucht mich auf der Kursseite zu registrieren und habe folgende Antwort angezeigt bekommen:
"Code korrekt...

Fehler: steckbrief.htm in
https://github.com/Jonas915/eia2_SoSe20/tree/master/Steckbrief
ist nicht lesbar oder nicht existent"

Wie kann ich den Fehler beheben?
Danke & ein schönes Wochenende
Jonas :)

**Comment by JirkaDellOro** [comment]
Hallo Jonas,

github.com liefert immer die ganze Github-Seitenumgebung mit. Wenn Du nur den Steckbrief haben willst, musst Du den Pages-Export deines Repositories nutzen.  Das ist ein simpler Fileserver, der eben nur genau die angefragte Datei liefert. 

Schau unter Settings->Pages und frage dann weiter, wenn das nächste Problem auftaucht.

**Comment by obiwan1337** [comment]
Guten Mittag,
hat es geklappt mit der pages aktivierung? 
evtl. solltest du die Datei kleinschreiben wie auch "portrait.jpg", da es ja nach "steckbrief.htm" zu fragen scheint.

**Comment by KohlerAl** [comment]
Hallo, 
bei mir stimmt auch irgendwas mit dem Link nicht. Mein Link sieht so aus: https://github.com/KohlerAl/EIA2/blob/master/steckbrief.htm   . Ich finde aber den Filesever nicht :( . Wie genau muss denn der Link aussehen? 

LG Alida :)

**Comment by AnnaLotz** [comment]
Hallo zusammen,

wenn ihr in eurem Repository oben rechts auf "Settings" geht und dort bis "GitHub Pages" runter scrollt, solltet ihr den Link sehen. Im Link muss dann natürlich noch auf entsprechenden Ordner verwiesen werden...
Falls ihr dort keinen Link stehen habt, bei "source" den Masterbranch aktivieren.

**Comment by hannahdue** [comment]
Hallo,
Ich habe diesen Link benutzt und trotzdem kam bei mir die gleiche Meldung...
Verstehe nicht, was mit "musst Du den Pages-Export deines Repositories nutzen" gemeint ist?
LG Hannah

**Comment by KohlerAl** [comment]
> wenn ihr in eurem Repository oben rechts auf "Settings" geht und dort bis "GitHub Pages" runter scrollt, solltet ihr den Link sehen. Im Link muss dann natürlich noch auf entsprechenden Ordner verwiesen werden...
> Falls ihr dort keinen Link stehen habt, bei "source" den Masterbranch aktivieren.

Das hab ich gerade probiert, aber es funktioniert leider immer noch nicht :(

**Comment by Plagiatus** [comment]
Welchen Link gebt ihr denn ein als Link zum Steckbrief?

**Comment by JirkaDellOro** [comment]
Pages braucht immer 1 bis 2 Minuten

**Comment by KohlerAl** [comment]
https://kohleral.github.io/EIA2/steckbrief.htm

Das ist der Link der mir unter Pages angezeigt wurde

**Comment by AnnaLotz** [comment]
Wie sehen eure Links denn aus? Außerdem ist zu beachten, dass der Link nicht auf eine spezifische Datei führt, sondern auf den Ordner, in dem Steckbrief und Portrait drin sind.

**Comment by hannahdue** [comment]
https://hannahdue.github.io/EIA2/steckbrief/steckbrief.htm

Das ist mein Link zum Steckbrief.
Anna, meinst du wir sollen nur den Link zum Steckbrief-Ordner verwenden? Nicht zum Steckbrief selbst?

**Comment by AnnaLotz** [comment]
Genau. Der Link führt also erstmal auf eine leere Seite, aber die Kursseite kann von dort aus die beiden Dateien finden.

**Comment by KohlerAl** [comment]
Danke Anna, der Link scheint jetzt zu funktionieren. Jetzt habe Ich nur noch das Problem dass das Bild nicht passt

**Comment by Jonas915** [comment]
Also ich habe es so probiert, wie Anna gesagt hat und habe das selbe Problem noch immer.
Das hier ist die GitHub-Pages URL  zu meinem Repo: https://jonas915.github.io/eia2_SoSe20/
Darin befindet sich ein Ordner "Steckbrief" mit den Dateien, die wie auch in der Vorlage klein geschrieben sind.

**Comment by Jonas915** [comment]
Leider wird der Link nicht gefunden.. woran kann das liegen?

**Comment by JirkaDellOro** [comment]
Du hast Steckbrief groß geschrieben....

**Comment by AnnaLotz** [comment]
@Jonas915 an den Link muss noch der Name vom Ordner dran, dann passt es

**Comment by Jonas915** [comment]
..und der muss dann klein geschrieben werden, richtig? Also der Ordnername

**Comment by AnnaLotz** [comment]
Der Ordnername so wie in deinem Github, die Dateinamen so wie sie auf der Kursseite gefordert werden. Natürlich darauf achten, dass du sie richtig hochgeladen hast.

**Comment by hannahdue** [comment]
Okay, jetzt klappts. Nur das Problem mit dem Foto wie bei allen anderen auch.

**Comment by Jonas915** [comment]
Bei mir habe ich jetzt auch eine Erfolgsmeldung 👍 
Ich habe den Ordner, in dem Bild & Steckbrief liegen klein geschrieben und den Aktivierungscode aus der Mail nicht über copy-paste eingefügt.

**Comment by Jonas915** [comment]
Ich würde das issue erst einmal nicht closen, falls noch andere das Problem bekommen sollten..

**Comment by michellewillmann** [comment]
Guten Abend, 
ich hab das selbe Problem mit meinem Steckbrief und zwar ist dieser nicht lesbar oder nicht existent. 
Ich hab in Settings>Pages schon geschaut und da lautet mein Link https://michellewillmann.github.io/EIA2/
und Source ist auch auf master branch gestellt. Der Steckbrief wird auch nicht auf der Kursseite angezeigt.

**Comment by JirkaDellOro** [comment]
@michellewillmann  Wie ich sehe hast Du zwei Repositories und in jedem einen Steckbrief. Welchen willst Du verwenden? Beachte, dass Du den ganzen Pfad angeben musst. In deinem EIA2-Repository hast Du ihn tiefer vergraben...

**Comment by michellewillmann** [comment]
@JirkaDellOro Achso also kann ich das michelle.github.io Repository löschen und nur das EIA2 repository verwenden.

**Comment by JirkaDellOro** [comment]
Für unser Modul wird zunächst das EAI2-Repository ausreichen. An deiner Stelle würde ich das andere nicht löschen, denn da ist ja Zeug drin, das Du vielleicht einmal nachschlagen möchtest. Was mich eher wundert ist Folgendes:

- Der Inhalt des persönlichen Repositories scheint sich auf EIA1 zu beziehen. Er wäre besser in einem Repository mit Namen EIA1 aufgehoben.
- michellewillmann.github.io ist dein persönliches Repo, wenn Du magst, kannst Du hier eine persönliche Website hosten. Ich mache das selbst auch, ist sehr praktisch!
- der Steckbrief-Ordner in EIA2 liegt wiederum in einem Ordner der den gleichen Namen hat wie dein persönliches Repository. Das ist total irritierend...

**Comment by michellewillmann** [comment]
jaa ich war selbst irritiert von den Ordnern. 
Ich habe jetzt seperate Repositories erstellt und nur noch in dem EIA2 Repository befindet sich mein Steckbrief.

**Comment by michellewillmann** [comment]
@JirkaDellOro 
jaa ich war selbst irritiert von meinen Ordner. 
Ich habe jetzt seperate Repositories erstellt und nur noch in dem EIA2 Repository befindet sich mein Steckbrief.

**Comment by JirkaDellOro** [comment]
Das sieht gut aus. Kriegst Du jetzt auch die Registrierung hin?

**Comment by michellewillmann** [comment]
Der Code war diesmal korrekt. Die Bildgröße war jedoch nicht ganz richtig, aber das habe ich jetzt noch korriegiert.

**Comment by JirkaDellOro** [comment]
Steht deiner Registrierung nun noch etwas im Wege?

**Comment by michellewillmann** [comment]
Ne, hat jetzt alles funktioniert. Vielen Dank!
