### ISSUE TITLE
Bildgröße wird nicht erkannt

### ISSUE THREAD

**Issue by k-poschmann** [JirkaDellOro/EIA2-Inverted#69]
Hallo,

Auch ich habe versucht mich bei der Kursseite zu registrieren: 
"Code ist korrekt...
Das Portrait hat das falsche Maß! Gefordert sind 85 x 110 Pixel"

bekomme ich angezeigt.
Habe nochmals mein Bild geprüft, doch mein portrait.jpg hat die gegebenen Maßen.
Wie kann ich den Fehler beheben?

Vielen Dank :)

**Comment by luziagu** [comment]
Hei, ich habe auch die gleiche Problemmeldung bekommen. 
Bei mir stimmen aber auch die geforderten Maße. 

Über Problemlösungen würde ich mich auch sehr freuen :)

**Comment by schneine** [comment]
Hallo, 
bei mir ebenfalls...
Weiß nicht woran es liegt. 
Freue mich auch über eine Problemlösung :)

**Comment by AnnaLotz** [comment]
@JirkaDellOro hier scheint was beim Bildchen-Größen-Registrierer falsch zu laufen

**Comment by JirkaDellOro** [comment]
Postet eure Portraits mal hier rein bitte, dann können wir das überprüfen.

**Comment by KohlerAl** [comment]
https://github.com/KohlerAl/EIA2/blob/master/Steckbrief/portrait.jpg

**Comment by JirkaDellOro** [comment]
Danke, damit kann ich etwas forschen gehen...

**Comment by JirkaDellOro** [comment]
@KohlerAl Hmm... ich habe nun deinen Steckbrief unter Pseudonym problemlos registriert...

**Comment by JirkaDellOro** [comment]
Probiere es bitte nochmal, dann lösche ich den falschen später raus

**Comment by JirkaDellOro** [comment]
PS: welchen Pfad hast Du angegeben? Den von dem Post oben oder einen anderen?

**Comment by KohlerAl** [comment]
https://github.com/KohlerAl/EIA2/tree/master/Steckbrief

Ich habe diesen Link angegeben, in dem Ordner Steckbrief sind dann das html Dokument und das Bild

**Comment by JirkaDellOro** [comment]
Ahhh... Du musst den Pages-Link benutzen!

**Comment by KohlerAl** [comment]
https://kohleral.github.io/EIA2/Steckbrief

Den hier? Wenn ich den im Browser angebe wird mir angezeigt dass die Seite nicht existiert

**Comment by JirkaDellOro** [comment]
Gibt mal die Dateinamen noch mit an um zu prüfen, ob Portrait und Steckbrief auffindbar sind. Wenn ja, dann ist das exakt der richtige Pfad!

**Comment by KohlerAl** [comment]
Okay, mit dem anderen Link hat es funktioniert. Ich habs zwar mit dem Link auch schon mal probiert, aber diesmal hab ich den Aktivierungscode von Hand eingegeben.

Danke für die Hilfe :)

**Comment by k-poschmann** [comment]
Hat bei mir jetzt auch geklappt! Vielen Dank :)

**Comment by schneine** [comment]
bei mir kommt immer noch dasselbe, das Bild hat die falsche Maße
link den ich benutze: 
https://github.com/schneine/EIA2/tree/master/Steckbrief 
oder 
https://github.com/schneine/EIA2/Steckbrief
mit beiden Links kommt die gleiche Fehlermeldung

**Comment by JirkaDellOro** [comment]
@schneine Schau mal ab hier https://github.com/JirkaDellOro/EIA2-Inverted/issues/69#issuecomment-608524332

**Comment by schneine** [comment]
https://schneine.github.io/EIA2/Steckbrief

mit diesem Link?

Pfad zum Portrait: 
https://github.com/schneine/EIA2/blob/master/Steckbrief/portrait.jpg

oder muss ich das Bild schon beim hochladen in der Größe haben und nicht erst in css formatieren?

**Comment by JirkaDellOro** [comment]
Das Bild muss auf jeden Fall zuvor auf die richtige Größe gebracht werden, wir wollen nicht unnötig Bandbreite nutzen. 

Und der Pfad muss auf github.io verweisen. Das ist der simple File-Server der nur die Dateien ausliefert ohne die ganze Github-Umgebung.

**Comment by schneine** [comment]
Okay jetzt hat es geklappt, hätte echt früher drauf kommen sollen .. naja jetzt weiß Ichs für die Zukunft. 
Vielen Dank für die schnelle Hilfe!

**Comment by k-poschmann** [comment]
Ich würde den Issue dann schließen
