### ISSUE TITLE
Steckbrief wird nicht angezeigt

### ISSUE THREAD

**Issue by buluthil** [JirkaDellOro/EIA2-Inverted#70]
Hii :) 

mein Steckbrief wird auf der Seite nicht angezeigt.
Als ich den Archivierungscode eingegeben habe hat sich eine neue Seite geöffnet und da stand 

code korrekt 
das Portrait hat die falsche Maßeinheiten

wird das vielleicht wegen dem nicht angezeigt ? muss ich mich nochmal neu registrieren ?

**Comment by Plagiatus** [comment]
> wird das vielleicht wegen dem nicht angezeigt? 
Ja.
> muss ich mich nochmal neu registrieren?
Ja.

**Comment by JirkaDellOro** [comment]
Bißchen einsilbig, der Lukas, aber wahrscheinlich hat er Recht...

**Comment by buluthil** [comment]
Okei vielen Dank :)
