### ISSUE TITLE
Bildgröße wird nicht erkannt

### ISSUE THREAD

**Issue by buluthil** [JirkaDellOro/EIA2-Inverted#71]
Hallo :)

meine Bildgröße wird nicht erkannt.
hier ist der Link ich weiß nicht was das Problem bist ist.
https://github.com/buluthil/buluthil.github.io/blob/master/steckbrief/portrait.jpg

**Comment by JirkaDellOro** [comment]
Welchen Pfad gibst Du bei der Registrierung an?

**Comment by buluthil** [comment]
das hier 
https://github.com/buluthil/buluthil.github.io/tree/master/steckbrief 
hier ist das Bild und Steckbrief

**Comment by obiwan1337** [comment]
Du musst den Pages Link angeben. 
Dazu muss Github pages aktiviert sein. siehe hier. [click](https://github.com/JirkaDellOro/EIA2-Inverted/issues/68#issuecomment-608431724)
Dann sollte dein Link vermutlich so aussehen -> https://buluthil.github.io/Steckbrief

**Comment by buluthil** [comment]
habe ich gemacht funktioniert leider immer noch nicht jetzt kam diese Meldung 

<img width="410" alt="Bildschirmfoto 2020-04-08 um 16 31 36" src="https://user-images.githubusercontent.com/43846406/78796428-9213c780-79b6-11ea-8df8-f2f485fcf71a.png">

**Comment by buluthil** [comment]
Okei es hat funktioniert hatte den Pfad falsch eingegeben 
Danke euch für die Hilfe :)
