### ISSUE TITLE
Anmeldung auf der Kursseite

### ISSUE THREAD

**Issue by doganerd** [JirkaDellOro/EIA2-Inverted#72]
Bei der Anmeldung auf der Kursseite wird meine Web-URL als nicht aufrufbar bezeichnet

**Comment by Plagiatus** [comment]
welche URL gibst du denn an?

**Comment by doganerd** [comment]
https://github.com/doganerd/doganerd.github.io/tree/master/EIA2

**Comment by JirkaDellOro** [comment]
Das ist nicht die Web-URL, sondern die Github-Adresse. Du musst Pages aktivieren (siehe Settings) und die Adresse von dort nehmen.

**Comment by Plagiatus** [comment]
siehe auch #71

**Comment by doganerd** [comment]
Der Link hat jetzt funktioniert aber mein Portrait ist noch nicht das richtige Maß, obwohl es genau 85x110 wie angegeben ist

**Comment by doganerd** [comment]
hat jetzt doch geklappt... sag daran, dass ich die Dateien nicht genauso genannt habe, wie im Beispiel :)
