### ISSUE TITLE
Alfaview kann nicht geöffnet werden 

### ISSUE THREAD

**Issue by klinkewitzn** [JirkaDellOro/EIA2-Inverted#73]
![Screenshot_20200411-202419_Gallery](https://user-images.githubusercontent.com/56318063/79051821-a3690800-7c32-11ea-9276-ff69cc6b26c0.jpg)
Hallo. Ich habe alfaview installiert gehabt, wenn ich das Programm aufrufe erscheint aber das hier. Was kann ich da tun? Liegt es daran, dass mein Laptop noch mit Windows 7 läuft?

**Comment by JirkaDellOro** [comment]
Was sind die Systemvoraussetzungen für den Betrieb von Alfaview. Das muss irgendwo zu finden sein.

**Comment by klinkewitzn** [comment]
![Screenshot_20200412-150942_Chrome](https://user-images.githubusercontent.com/56318063/79069608-e0cfa300-7ccf-11ea-9743-4b0576f770e8.jpg)
Also am windows 7 liegt es nicht. Dann weis ich leider nicht an was es liegt.

**Comment by klinkewitzn** [comment]
Ich habe es jetzt hinbekommen. :)
