### ISSUE TITLE
Nachzügler (Endabgabe) aus Semestern vor WS19/20

### ISSUE THREAD

**Issue by ivenios** [JirkaDellOro/EIA2-Inverted#74]
Guten Tag zusammen, 

so wie ich es verstanden habe, wird der EIA2-Inverted Classroom dieses Semester auch wieder stattfinden. 
Gilt dabei für die Nachzügler aus vorhergegangenen Semestern die unten genannte Regelung aus dem Intranet? 
Oder werden wir nur eine Endabgabe programmieren? 

Vielen Dank schon einmal im Voraus für eure Antworten. 

> Für Wiederholer vorangegangener Semester, welche im WS19/20 fehlende Teilleistungen erbringen möchten, gilt...
> 
> bei bereits bestandener Modulprüfung aber fehlender Studienleistung: die mündliche Prüfung wird unbenotet als Studienleistung durchgeführt
> bei bereits bestandener Studienleistung aber fehlender Modulprüfung: es wird eine Klausur als Prüfungsleistung angeboten

**Comment by JirkaDellOro** [comment]
Wir müssen nun unterscheiden zwischen den Leuten, die letztes Semester EIA2 erstmals besucht hatten und sich den dortigen Prüfungen unterzogen und denen, die davor teilgenommen hatten. Erstere wiederholen die Prüfungen so wie sie aktuell ablaufen, für letztere gilt die oben genannte Sonderregelung.

Unter den gegebenen Umständen kann es aber situationsbedingte Abweichungen geben.

**Comment by ivenios** [comment]
Vielen Dank für Ihre Antwort! Müssen wir das in irgendeiner Weise noch anmelden?

**Comment by JirkaDellOro** [comment]
Bringt die erforderlichen Nachweise zu den entsprechenden Prüfungen mit.

**Comment by ivenios** [comment]
Da mir das jetzt zum ersten mal passiert ist: Was sind denn die "erforderlichen Nachweise" ?

**Comment by JirkaDellOro** [comment]
Notenspiegel in dem steht, welche Leistungen bereits erbracht wurden.

**Comment by ivenios** [comment]
Perfekt vielen Dank für die Informationen.

**Comment by LukasBlea** [comment]
Guten Morgen Herr Dell'Oro,

mein Name ist Lukas Blea und ich lege dieses Semester, nach meinem bestandenen Praxissemester, ein 2B Semester ein, um mich, unter anderem, auf das Freelancing zu konzentrieren.

Meine Prüfung zu EIA2 habe ich bestanden und die Qualifikation zur Abschlussaufgabe, unter der Aufsicht von Lukas, welcher in diesem Semester das Modul geleitet hatte, erreicht. Da für mich von Anfang an klar war, dass ich ein 2B Semester einlegen werde, schob ich die Abschlussaufgabe schon direkt. Er teilte mir mit, dass ich dieses Semester somit dann nur die Abschlussaufgabe bei Ihnen wiederholen müsse. 

Nun habe ich allerdings etwas über einen "Nachweis" bei ihnen im Thread lesen können und frage mich, wie genau dieser auszusehen hat. 

Ich habe einen Screenshot meiner Ampelstufe zum Zeitpunkt der Endabgabe und eine schriftliche Konversation mit Lukas zu diesem Thema um "beweisen" zu können, dass dies bei mir wirklich der Fall ist. Hier müsste ich natürlich vorher nochmal bei Lukas nachfragen, ob er damit einverstanden ist, dass ich diesen kleinen Ausschnitt unsere Konversation teile. Im besten Fall (falls er sich noch daran erinnert), könnte er ja selbst nochmal kurz Stellung zu diesem Thema nehmen. Hierzu kann ich ihn nochmal persönlich anschreiben.

Möchten Sie dazu gerne nochmal etwas haben, oder soll ich auch diese Dinge einfach vorzeigen, wenn es dann soweit ist? Ich werde an den Vorlesungen von Ihnen auf jeden Fall teilnehmen, um den ganzen Stoff nochmal etwas zu wiederholen.

Beste Grüße
Lukas Blea
