### ISSUE TITLE
Lektion 1 Übung

### ISSUE THREAD

**Issue by YasminElbahar** [JirkaDellOro/EIA2-Inverted#75]
Hallo Jirka :)

Ich bin es Yasmin.

ich habe die Lektion durchgearbeitet und auch die Übung gelöst. ich habe trotzdem eine Frage.

In Zeile 13 der zweiten Tabelle (Minute 14:13) haben Sie "Muh" geschrieben, weil die Bedingung wahr war. also für jede wahre Bedingung haben Sie ein H und für jede falsche ein U geschrieben. warum haben Sie in Zeile 14 ein weiteres "U" geschrieben? obwohl die Bedingung wahr war. warum schreiben Sie also immer ein H und ein weiteres U, obwohl die Bedingungen wahr sind aber nicht umgekehrt?

**Comment by MarkusDamm** [comment]
Hallo Yasmin,
du hast richtig erkannt, dass das H angehängt wird, wenn die Bedingung `if (k == 1 || k == _length / 2) ` erfüllt ist. Wenn die Bedingung also nicht stimmt, dann kommt auch kein H dazu, weil Zeile 13 nicht ausgeführt wird.
Das Anhängen von dem U hat aber nichts mit der If-Abfrage zu tun. `_start += "u";`, also Zeile 14, steht außerhalb der Abfrage und wird dementsprechend unabhängig vom Ergebnis der Abfrage ausgeführt.

Beim ersten mal hatten mich auch die fehlenden geschweiften Klammern bei der If-Abfrage verwirrt. Das war bestimmt auch dein Grund für die Frage. Die geschweiften Klammern kann man weglassen, wenn, wie hier, nur die Zeile direkt nach der Abfrage ausgeführt werden soll.

**Comment by JirkaDellOro** [comment]
😃 Das habe ich extra gemacht um genau diese Frage zu provozieren. Sehr gut, Yasmin! 

Ist eine Bedingung erfüllt, wird die ihr folgende Anweisung ausgeführt. Geschweifte Klammern wiederum fassen mehrere Anweisungen zu einem Block zusammen. Folgt der Bedingung als nicht eine einzelne Anweisung, sondern ein Block von Anweisungen, so wird dieser gesamte Block ausgeführt. 

Da im Beispiel tatsächlich nur eine einzelne Anweisung ausgeführt werden soll, wären geschweifte Klammern überflüssig. Es gibt aber auch Coding-Guidelines, welche geschweifte Klammern grundsätzlich vorschreiben, in diesem Kurs gilt das nicht. Wichtig ist, dass man Auto-Formatting nutzt **(Shift+Alt+F),** dann wird nämlich alles eingerückt und man kann solche bedingten Anweisungen und Blöcke gut erkennen.

**Comment by FrankeSa** [comment]
Hallo zusammen,

ich habe auch noch ein paar Fragen zu den Übungen.

Frage 1: Unter der Überschrift Assoziatives Array... 
              Die letzte Frage: "Gib ein s[4] = [101..."    Hier wird ja ein neues Array in das bestehende gepusht. Müsste das dann nicht an der vierten Stelle sein? Also Zahl, wahr,text, 4 ? 
![Ansicht](https://user-images.githubusercontent.com/56167839/79993405-040b0700-84b5-11ea-8791-3b12ed18dc5f.jpg)

Dann bei der Frage darunter "wie kommst Du gezielt an die Information, die damit assoziiert wurde?"   Ich hab es im Programm so versucht. Geht das in die richtige Richtung? 
![Ansicht](https://user-images.githubusercontent.com/56167839/79993737-5ea46300-84b5-11ea-81c5-d047183bcaeb.jpg)

Frage 2: Was hat es mit dem namespace auf sich? Das haben wir in EIA1 noch nicht kennengelernt. 
Frage 3: Im Video zu dem AktivitätenDiagramm bei Minute 7:13 gibt es die umgedrehte Gabel. Die verweist ja auf eine andere Funktion. Müsste dann in der anderen Funktion nicht auch die Gabel auftauschen, damit der Zusammenhang ersichtlich ist?

Frage 4: Die Objektknoten am Rand sind generell für Übergabeparameter? Muss hier nicht auch gekennzeichnet werden aus welcher Funktion die Übergabe kommt?   _start  ist eine Aktivität wurde aber eckig dargestellt... also doch ein Objektknoten?

**Comment by obiwan1337** [comment]
Zu der Arrayfrage... Ich habe gerade auch nochmal etwas rumprobiert. Die 4 wird als "key" benutzt. Das mit der Ordnung die du oben als Screenshot verlinkt hast. Die Browser Konsole ordnet die 4 Werte nach Zahlen in aufsteigender Folge und Alphabetischem Wert (aufsteigend)
So war es mir möglich die gleiche Zeile Code ganz unten angezeigt zu bekommen wenn ich 's["zur"] = [101,102];' schrieb.
  Zu deiner Namespaces Frage: Das sind wie Klammern um deine Variablen, Funktionen,Objekte....
Ein Namespace wird benutzt um Überschneidungen mit anderen Scripten und Variablennamen zu verhindern. So kann der Namespace "aufgabe1" die variable _n_ enthalten und  im gleichen Dokument kann n nochmals vorhanden sein als was ganz anderes. 
`namespcae Aufgabe1{
let n: number;
}
let n: string="Hallo Welt"`

**Comment by JirkaDellOro** [comment]
Wunderbare Fragen, vielen Dank!

Frage 1: Du bist hier den Unterschieden zwischen einfachen Arrays und assoziativen Arrays auf der Spur. Die 4 ist, wie @obiwan1337 schon schrieb, nun nicht mehr eine Position, sondern ein Schlüssel. Schreib mir bitte 
- was passiert, wenn Du die Punktsyntax nutzt.
- was dir TypeScript ausgiebt, wenn Du mit der Maus über die roten Schlangenlinien fährst.
- ob es eine gute Idee zu sein scheint, eine solche Zahl als Schlüssel zu benutzen.

Frage 2: (Ergänzung zu @obiwan1337) Das ermöglicht es uns, die Ordner zu den verschiedenen Aufgaben in einem Projekt zu haben, ohne dass die Variablen in den verschiedenen Programmen für Duplikate gehalten werden.

Frage 3: Nein, dann müsste man an alle Aktivitäten eine solche Gabel zeichnen, da sie alle ja aufgerufen werden, und dann kann man sie auch wieder weglassen. Hier geht es darum, dass jemand, der das Diagramm liest sofort erkennen kann, ob an anderer Stelle die Aktivität aufgeschlüsselt wird oder nicht, bevor er sich unnötig auf die Suche macht.

Frage 4: ja, generell sind das Übergabeparameter. Da eine Aktivität von vielen Stellen aus genutzt werden kann ist eine Zuordnung zum Nutzer nicht sinnvoll. _start ist der Name des Parameters, der mit einem Objektknoten dargestellt wird. Die Aktivität heißt "createCall"

**Comment by JirkaDellOro** [comment]
Kann der Issue geschlossen werden?
