### ISSUE TITLE
Workshop link

### ISSUE THREAD

**Issue by YasminElbahar** [JirkaDellOro/EIA2-Inverted#76]
der Workshop link ist bei uns alle nicht Gültig .

**Comment by AnnaLotz** [comment]
Habe ich auch gerade gemerkt. Wir müssen wohl auf Jirka warten, bis er mit dem Ersti-Frühstück fertig ist, ich habe leider keinen Zugriff auf die Links...

**Comment by AnnaLotz** [comment]
Bis wir eine Lösung haben können wir uns in diesen Raum treffen:
https://app.alfaview.com/#/join/hochschule-furtwangen-university/fed076f0-6f13-4da9-91b1-fc0dde52b6cf/b9a45650-df81-42ba-a8fa-fc4694a99062
