### ISSUE TITLE
Steckbrief Issue Bild

### ISSUE THREAD

**Issue by weiberta** [JirkaDellOro/EIA2-Inverted#77]
Mein Problem besteht daran, dass trotz korrekter Pixelanzahl der Steckbrief nicht angenommen wird.
Beim Hochladen des Steckbriefs bekomme ich immerwieder folgende Meldung:
 

<img width="982" alt="Bildschirmfoto 2020-04-15 um 13 15 00" src="https://user-images.githubusercontent.com/48830856/79854163-55d66300-83c9-11ea-857e-e00d916c60f2.png">

**Comment by JirkaDellOro** [comment]
#68
