### ISSUE TITLE
Alfaview Konferenz

### ISSUE THREAD

**Issue by breitjacqueline** [JirkaDellOro/EIA2-Inverted#78]
Hallo
Ich habe nichts von der Konferenz heute mitbekommen, da sich mein PC ständig aufgehangen hat. Ich vermute es liegt an meiner extrem schlechten Internetverbindung. Habe hier nur DSL, wenn überhaupt 16.000er Leitung.
Was nun? Wurde die Vorlesung eventuell aufgezeichnet?

**Comment by AnnaLotz** [comment]
Leider wird von unserer Seite aus nichts aufgezeichnet. 
Bei AlfaView kann man bei den Einstellungen die Bandbreitennutzung verändern. Vllt hilft es, wenn du diese auf "minimum" stellst?

**Comment by breitjacqueline** [comment]
Okay dann werde ich das mal ausprobieren. Gibt es denn irgendeine Möglichkeit die Themen von der Konferenz zu wiederholen ?

**Comment by AnnaLotz** [comment]
Es ging heute hauptsächlich um Organisatorische Dinge. Am Ende haben wir noch gemeinsam die Übung über "Werte&Referenzen" aus L01 besprochen. Genauere Infos können dir deine Kommilitonen und Teilnehmer des Workshops heute geben ;) 

(Aufruf an alle, sich hier zu beteiligen ^^)
