### ISSUE TITLE
Verlinkung/UploadL01

### ISSUE THREAD

**Issue by schneine** [JirkaDellOro/EIA2-Inverted#79]
Hallo, 
ich wollte meine Aufgaben auf meinem Steckbrief verlinken:
 schneine.github.io/EIA2/L01/AufgabeL01.pdf
 schneine.github.io/EIA2/L01/box.html
auf der Kursseite kommt jedoch: File not found
Was ist falsch?
https://github.com/schneine/EIA2 
Zudem zeigt es mir meine .pdf Datei auf GitHub nicht an

**Comment by Plagiatus** [comment]
Hallo,
Das Problem ist, dass du deine Verlinkung relativ gesetzt hast. Relative Links sind immer relativ von der aktuellen Datei aus gesehen. Darum führt dich der relative Link `EIA2/L01/AufgabeL01.pdf` auf der Seite `https://schneine.github.io/EIA2/Steckbrief/steckbrief.htm` nach `https://schneine.github.io/EIA2/Steckbrief/EIA2/L01/AufgabeL01.pdf`, und das funktioniert natürlich nicht weil das nicht der Pfad der Datei ist.

Um das zu lösen kannst du entweder den absoluten Pfad verwenden (`https://schneine.github.io/EIA2/L01/AufgabeL01.pdf`) oder alternativ dafür sorgen, dass der relative Pfad auch wirklich zu dem Ort führt zu dem du willst: `../L01/AufgabeL01.pdf`, der Doppelpunkt steht für "einen Ordner weiter oben"

**Comment by schneine** [comment]
ah stimmt macht Sinn, vielen Dank für den Hinweis!! Hat geklappt.

**Comment by JirkaDellOro** [comment]
Gelöste Issues bitte schließen
