### ISSUE TITLE
Dateien via Terminal bei GitHub hochladen funktioniert nicht

### ISSUE THREAD

**Issue by elenajenny** [JirkaDellOro/EIA2-Inverted#80]
Hallo, 
also ich möchte gerade meine Dateien in Github pushen via Terminal und dann zeigt es mir diesen Fehler an:

 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://github.com/elenajenny/EIA2.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

Ich habe diese Befehle benutzt:
 git init
git add README.md
git commit -m "first commit"
git remote add origin https://github.com/elenajenny/testdoc.git
git push -u origin master

Kann es sein, da ich meine Steckbrief Datei per Drag and Drop hochgeladen habe und ich bereits ein repository angelegt habe, es deshalb nicht funktioniert? Und welche Befehle muss ich anwenden dass es funktioniert? 

Danke,
Elena

**Comment by JirkaDellOro** [comment]
Mach erstmal einen Pull, dann wieder einen Push. Es scheint, als hättest Du Änderungen auf Github, die noch nicht lokal eingeflossen sind.

**Comment by elenajenny** [comment]
Also habe erst pull dann push gemacht und jetzt kommt diese Meldung: 

fatal: The current branch master has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin master

**Comment by JirkaDellOro** [comment]
Es scheint daran zu liegen, und git rät dir "fetch" auszuführen um die Daten erst einmal zu dir lokal zu holen. Wenn das nicht mehr klappt, kannst Du das Repository noch einmal an eine andere Stelle neu klonen, deinen aktuellen Stand von dem alten hineinkopieren und das neue dann wieder zurück pushen. Dann löschst Du das alte und arbeitest mit dem neuen weiter.

Achte darauf, dass Du zu Beginn deiner Arbeit IMMER ein Pull ausführst um sicher zu gehen, dass deine Repositories lokal und remote auf dem gleichen Stand sind

**Comment by FrankeSa** [comment]
Hallo, 
ich versuche auch gerade eine Datei in mein Repo zu pushen und bekomme folgende Meldung: 
![Screenshot](https://user-images.githubusercontent.com/56167839/80618024-19e37380-8a43-11ea-87e5-70ef66326ed4.jpg)

Wenn ich den Befehl: git push u- origin master (von dem ich ausgehe, dass er mir meine noch nicht vorhandene Datei erstmals ins Repo pusht) kommt diese Meldung. 
![Screenshot_2](https://user-images.githubusercontent.com/56167839/80618314-7a72b080-8a43-11ea-9d73-0d52f61b24d2.jpg)

**Comment by FrankeSa** [comment]
welcher befehl muss ich in das Terminal eingeben, damit in meinem Repo z.B. ein Ordner erstellt wird "Aufgabe2" und ich darin dann meine Dateien "Blackmailor...ts" etc. pushen kann?

**Comment by JirkaDellOro** [comment]
Mit den Konsolenbefehlen von Git kenne ich mich nicht gut aus und müsste jetzt selbst recherchieren. Für unseren Kurs genügt die von VSCode angebotene Funktionalität völlig. Magst Du nicht diese benutzen?

**Comment by Plagiatus** [comment]
Ansonsten schau hier mal rein: https://stackoverflow.com/questions/4181861/message-src-refspec-master-does-not-match-any-when-pushing-commits-in-git

**Comment by FrankeSa** [comment]
Was ist mit der VSCode vorhandene Funktionalität gemeint? Bzw. wie kann ich diese nutzen.

Zu beginn von EIA1 haben wir eine Übersicht mit ein paar Befehlen bekommen wie z.B. git add, git push.... sind das nicht die Funktionalitäten?

**Comment by Plagiatus** [comment]
>Was ist mit der VSCode vorhandene Funktionalität gemeint? 

Schau mal hier:
https://code.visualstudio.com/docs/editor/versioncontrol

**Comment by JirkaDellOro** [comment]
Wenn Du in VSCode F1 drückst und dann `git` eintippst, siehst Du alle Kommandos, kannst sie mit der Maus auswählen und wirst ggf. interaktiv durchgeführt. Noch einfacher ist es, wenn Du links das SourceControl-Symbol wählst. Dann siehst Du deine Änderungen, kannst gleich die CommitMessage eingeben und mit Ctrl+Enter committen, sowie über das Drei-Punkte-Menü pullen und pushen etc.....
