### ISSUE TITLE
Steckbrief, Steckbrief nicht lesbar 

### ISSUE THREAD

**Issue by lisawl** [JirkaDellOro/EIA2-Inverted#81]
Hallöle, 
bin leider erst jetzt dazu gekommen meinen Steckbrief nochmals hochzuladen.
Bei mir kommt  die Meldung:
Code korrekt...
Fehler.: steckbrief.htm in
https://lisawl.github.io/EIA2/steckbrief/steckbrief.htm
ist nicht lesbar oder nicht existent

obwohl der link eigentlich funktionieren sollte, wenn ich auf meine pages Link klicke funktioniert er und der Pfad sollte auch richtig sein, habt ihr ne Idee?

**Comment by Plagiatus** [comment]
welchen Link hast du bei der Registrierung angegeben? siehe auch #68

**Comment by lisawl** [comment]
> welchen Link hast du bei der Registrierung angegeben? siehe auch #68

Danke, hat geklappt der Fehler war wohl, dass ich direkt auf die steckbrief Datei verwiesen hab und nicht den Ordner

**Comment by Plagiatus** [comment]
Dann Issue bitte wieder schließen

**Comment by lisawl** [comment]
> Dann Issue bitte wieder schließen

Wie schließt man es denn? finde es leider nicht

**Comment by Plagiatus** [comment]
da wo du auch kommentare schreibst, ist ein Knopf neben "kommentieren", der "schließen" bzw "kommentieren und schließen" sein sollte.
