### ISSUE TITLE
tslint install gelingt nicht

### ISSUE THREAD

**Issue by Ljubaska** [JirkaDellOro/EIA2-Inverted#82]
Hallo zusammen 

bei Eingabe in den Terminal: npm install tslint 
bekomme ich folgende Fehlermeldung 
![Bildschirmfoto 2020-04-25 um 18 49 53](https://user-images.githubusercontent.com/43846372/80286166-193c9b80-872a-11ea-8906-0072dcf26a32.png)

Meine ts Dateien bekommen keine js angehängt 👎

**Comment by JirkaDellOro** [comment]
Der Linter und der Compiler sind zwei unterschiedliche Programme. Der Linter hilft dir, ordentlichen Code zu schreiben. Der Compiler übersetzt Typescript in Javascript. Letzteren installierst Du mit

`npm install -g typescript`

Ich bin mir gerade nicht sicher, aber ich glaube den Linter kriegst Du einfach wenn Du in VSCode die Extension TSLint installierst.

**Comment by Ljubaska** [comment]
Super! Hat geklappt. Der Compiler hat gefehlt.. 
Viiiiielen Dank 👍 👍 👍
