### ISSUE TITLE
Übung 2

### ISSUE THREAD

**Issue by YasminElbahar** [JirkaDellOro/EIA2-Inverted#83]

**Comment by JirkaDellOro** [comment]
Hat es sich noch erschlossen? Wo war die Uneindeutigkeit? Vielleicht kann ich etwas verbessern...

**Comment by YasminElbahar** [comment]
ich habe mich bisschen verwirrt. und zwar habe ich zwei fragen. ich habe das remove Target from Parent, also bzw Target Event nicht so ganz gut verstanden. und meine zweite frage war , Ich habe  auch nicht verstanden, was von mir in der Übung verlangt wird. also muss ich jetzt Coden oder einfach skizzieren. und welche Problem soll ich eigentlich lösen. habs nicht so verstanden :)

**Comment by JirkaDellOro** [comment]
Kannst Du ich etwas an die für dich unverständlichen Passagen heranführen? Neben den Überschriften erscheint bei MouseOver ein kleines Link-Symbol, dessen Inhalt kannst Du hier posten, oder den Link zum Video und die Zeitangabe.

Bezüglich der Übungen: meinst Du die ganz unten?

**Comment by YasminElbahar** [comment]
Also das Event Target in die Aktivitäts diagramm minute 17:45 in L2. 

und die Übung auch noch : Löse zunächst das Problem mit dem erneuten Aufruf von placeLetter nach deleteLetter
experimentiere erst mit dem Lösungsoptionen 1 und 2.
Plane dann Lösung 3 und implementiere sie.
Erweitere die Erpresserbrief-App so dass sie auch auf Smartphone anwendbar ist
In einem weiteren Bereich sollen alle zulässigen Buchstaben zur Auswahl bereit stehen, so dass man sie per Touch aktivieren kann
Der aktuell ausgewählte Buchstabe soll in dieser Auswahl hervorgehoben erscheinen, so dass der Nutzer weiß, was er gewählt hat, bevor er den Brief ändert. also die Frage war : was ist eingentlich das Problem mit den ich mich beschäftigen soll und soll ich den Code schreiben was im video gezeigt wurde, und Sachen dann ändern ? oder muss ich die Problemlösung skizzieren und als Diagramm dann zeichnen ? 

vielen dank im Voraus.

**Comment by JirkaDellOro** [comment]
Zum Target:
siehe https://jirkadelloro.github.io/EIA2-Inverted/L02_Events#target
Ein Event-Objekt trägt die Information, auf welches Element es sich bezieht, in seinem Attribut "target". In dem Beispiel ist `target` also der Buchstabe auf den geklickt wurde. Dessen Elternelement kann man nun anweisen, dieses `target` aus seiner Kinderschar zu entfernen, so verschwindet also der Buchstabe.


Zur Übung:
- [x] Löse zunächst das Problem mit dem erneuten Aufruf von placeLetter nach deleteLetter
  - experimentiere erst mit dem Lösungsoptionen 1 und 2. 
  - Plane dann Lösung 3 und implementiere sie.   
> "experimentiere" bedeutet hier mit dem Code herumzuspielen. Der zweite Teil ist explizit angegeben.

- [x] Erweitere die Erpresserbrief-App so dass sie auch auf Smartphone anwendbar ist
  - In einem weiteren Bereich sollen alle zulässigen Buchstaben zur Auswahl bereit stehen, so dass man sie per Touch aktivieren kann
  - Der aktuell ausgewählte Buchstabe soll in dieser Auswahl hervorgehoben erscheinen, so dass der Nutzer weiß, was er gewählt hat, bevor er den Brief ändert  
> Das solltest Du natürlich zunächst zu planen versuchen. Wenn dir das gelingt, kannst Du dich auch an die Implementierung machen. Ich erhoffe mir an dieser Stelle weitergehende Fragen von euch, die bei diesen Versuchen hochkommen. Eine Lösung wird nicht kontrolliert...
