### ISSUE TITLE
Typescript wird nicht in Javascript übersetzt

### ISSUE THREAD

**Issue by Ljubaska** [JirkaDellOro/EIA2-Inverted#84]
Hallo zusammen

mein Problem hat sich leider doch noch nicht erledigt.. 
Die Typescript Dateien werden immer noch nicht in Javascript übersetzt. 
Habe den Compiler installiert mit: npm install -g typescript (erfolgreich)
dann hat es eine Datei übersetzt und das wars dann auch 👎 

Woran könnte es evtl. noch liegen?
Wäre über jede Hilfe dankbar!

**Comment by AnnaLotz** [comment]
Sind die tsconfig.json und tslint.json in deiner Ordnerstruktur drin?
Hast du oben über `Teminal>Run Build Task` die `tsc:watch` aktiviert?

**Comment by Ljubaska** [comment]
Oooohmann.. es lag an der tsc:watch 

Jetzt läufts wie am Schnürchen 👍 Danke Anna!

**Comment by Ljubaska** [comment]
Hätte doch noch eine Frage.. 

![image](https://user-images.githubusercontent.com/43846372/80537481-70e63b80-89a4-11ea-8a4a-73f67285b7f2.png)

Das hier ist die Datei die ich verlinken möchte.. 
Mit dem Link: **ljubaska.github.io/EIA2SS/AufgabeL01/AufgabeL01Boxes.pdf**
klappts nicht. Kein Link aus dem Repository lässt sich öffnen..

**Comment by Plagiatus** [comment]
Die Datei die du zu verlinken versuchst (`AufgabeL01Boxes.pdf`, gibt es nicht.

https://github.com/Ljubaska/EIA2SS/tree/master/AufgabeL01

**Comment by Ljubaska** [comment]
Hab die Datei gerade umbenannt, sorry 😅 
Sie heißt jetzt boxes.pdf und nicht mehr AufgabeL01Boxes.pdf

**Comment by Plagiatus** [comment]
Ja gut.. der Pfad scheint zu stimmen, und da boxes.html auch nicht funktioniert, würde ich vermuten daß GitHub Pages einfach gerade Ben Knacks hat. Laut Statusseite ist bei denen gerade nicht alles im grünen Bereich: https://www.githubstatus.com/

**Comment by Ljubaska** [comment]
Ok dann probier ichs morgen nochmal 👍

**Comment by Ljubaska** [comment]
Habs grad nochmal probiert.. funktioniert immer noch nicht.

**Comment by Plagiatus** [comment]
Ja, weil Pages zum Zeitpunkt des pushes nicht funktioniert hat. Entweder nochmal etwas pushen oder Pages aus und wieder ein schalten, um das Pages Update zu triggern

**Comment by Ljubaska** [comment]
👎 negativ..

**Comment by Ljubaska** [comment]
Hab sogar das Repository nochmals neu geklont. Klappt trotzdem nicht

**Comment by JirkaDellOro** [comment]
Ich habe eher den Eindruck, dass Du Pages gar nicht aktiviert hast...

**Comment by Ljubaska** [comment]
ok peinlich.. hab Pages aktiviert 👍  funktioniert! Danke.
