### ISSUE TITLE
Issue L02 Event

### ISSUE THREAD

**Issue by luziagu** [JirkaDellOro/EIA2-Inverted#85]
Wo finde ich das Issue für L02 Event? Ich sehe es ni hat mehr in der Issue-Liste.

**Comment by Plagiatus** [comment]
#57

**Comment by JirkaDellOro** [comment]
Den hatte ich für die Vorbereitung erstellt. Für konkretere Probleme bitte einen eigenen Issue mit aussagekräftigem Titel erstellen.
