### ISSUE TITLE
Memory Game

### ISSUE THREAD

**Issue by celine333** [JirkaDellOro/EIA2-Inverted#86]
Ich habe eine Frage bzgl. des Memory Spiels.
Macht es Sinn ein Array für jede der 10 Sequenzen zu erstellen, um dann durch math.random einzelne Buchstaben zu generieren? Oder bin ich da völlig auf dem falschen Weg und es geht noch einfacher?
Vielen Dank schonmal!

**Comment by JirkaDellOro** [comment]
Um die 10 (oder mehr) vorgegebenen Sequenzen einzupflegen, würde ich ein Array von 10 (oder mehr) Strings nutzen. Und random wirst Du brauchen, um die Buchstaben einer Sequenz zufällig zu reihen. Es gibt viele Wege das zu tun und Du scheinst nicht auf einem völlig falschen zu sein. Um eine genauere Aussage zu treffen, müsste ich dein Konzept kennen.
