### ISSUE TITLE
Implementation aus Blackmailor Companion zeigt Fehler

### ISSUE THREAD

**Issue by FrankeSa** [JirkaDellOro/EIA2-Inverted#87]
Hallo Jirka,

ich habe das Programm für den Erpresserbrief genauso aus deinen Video übernommen bzw. nachgebaut. Trotzdem zeigt VSC mir zwei Probleme an. 

Dadurch kann ich die Buchstaben auch nicht löschen. Ich sehe den Fehler nicht. Kannst du mir helfen? 
![Problem](https://user-images.githubusercontent.com/56167839/80617001-d6d4d080-8a41-11ea-8895-72d54fd660fd.jpg)

**Comment by JirkaDellOro** [comment]
Dir ist da ein Semikolon reingerutscht. Dieses Zeichen ist signifikant, es schließt eine Anweisung unweigerlich ab. Somit ist deine Funktion `deleteLetter` an dieser Stelle fertig deklariert. Die Definition aber bleibt aus, denn der nachfolgende Block steht plötzlich für sich alleine und wird nicht als Funktionsrumpf betrachtet.
