### ISSUE TITLE
Sequenzmemory Aufgabenstellung

### ISSUE THREAD

**Issue by breitjacqueline** [JirkaDellOro/EIA2-Inverted#88]
In der Aufgabenstellung heißt es, man soll in der UI-Skizze Angaben zu HTML-Tags, CSS-Selektoren, Signalen und Listeners geben.
Was genau ist mit Signalen gemeint ?

**Comment by JirkaDellOro** [comment]
Schau mal in die Broschüre. Signale in UML entsprechen in Javascript/DOM den Events. Da UML nicht an eine Programmiersprache gebunden ist, verwendet man hier den noch allgemeineren Begriff Signal.

**Comment by JirkaDellOro** [comment]
Bei der Konzeption in den Videos hatte ich bereits festgehalten, wo ich die Signale empfangen will, respektive wo ich Event-Listener installieren möchte.

**Comment by FrankeSa** [comment]
Ich habe bei dem Use Case Diagramm folgende grobe Pkt. notiert, die der Anwender mit dem Programm machen kann.
-Starten
- vorgefertigte Sequenz wählen
- eigene Sequenz erstellen
- Zeit auswählen
- Buchstabe auswählen

Bin ich hier auf der richten Spur?

**Comment by JirkaDellOro** [comment]
Ja, ich denke schon. Allerdings sind es Zeiten (plural). Es wird zudem hilfreich sein, wenn Du im Use-Case-Diagram schon grob die Reaktionen des Systems aus der Sicht des Nutzers skizzierst. Dann können wir erkennen, ob die Aufgabenstellung angekommen ist.
