### ISSUE TITLE
Button mit Konsole in Verbindung bringen

### ISSUE THREAD

**Issue by luziagu** [JirkaDellOro/EIA2-Inverted#90]
Hallo Zusammen, 

ich versuche gerade einen Button mit der Konsole zu verknüpfen, dies gelingt mir aber irgendwie nicht. Wo liegt der Fehler? Die Dokumente sind alle miteinander verknüpft, das habe ich überprüft. 

Danke schonmal im Voraus! :) 
![Bildschirmfoto 2020-05-01 um 13 06 37](https://user-images.githubusercontent.com/56430460/80801584-2f74ac80-8bad-11ea-8ec3-e8f277a268f2.png)

**Comment by JirkaDellOro** [comment]
In deinem Code springen mir einige Unschönheiten ins Auge, aber kein deutlicher Fehler. Bitte poste immer einen Link zu dem entsprechenden Ordner im Repository und einen auf die App. Dann kann ich mit einem Klick das fehlerhafte Verhalten reproduzieren und untersuchen.

**Comment by luziagu** [comment]
https://github.com/luziagu/EIA2/tree/master/Sequenzememory

https://github.com/luziagu/EIA2/blob/master/Sequenzememory/sequencememory.html

**Comment by luziagu** [comment]
Ich habe jetzt noch ein paar Sachen ausprobiert und auch mit dem Debugger gearbeitet. Bei mir wird nach dem EventListener alles übersprungen und der Debugger springt wieder in die HTML-Datei zurück. Was kann der Grund hierfür sein?

**Comment by JirkaDellOro** [comment]
Hier der relevante Auszug aus deinem Code
```typescript
document.addEventListener("load", function(): void {
    randomWord = document.querySelector("#randomWord");
    startGame = document.querySelector("#startGame"); 

    startGame.addEventListener("click", function(): void {
        shufflecharacters();
   });

    randomWord.addEventListener("click", function(): void {
        console.log("ich wurde geklickt"); 
    });
});
```

Und hier alles, was mir dabei ins Auge springt:  

1. das Load-Event soll vom `window` abgefangen werden, das ist wohl der Kern des Problems
2. Bitte verwende keine anonymen Funktionen, wenn nicht erforderlich.  Einfach
`startGame.addEventListener("click", shufflecharacters);` ist viel besser zu lesen, klarer und entspricht wahrscheinlich eher deinem Konzept
3. Dein Konzept konnte ich leider auf Github nicht finden, bitte stelle es immer zur Verfügung. Oft werden wir nicht helfen können, ohne es zu kennen.
4. Der Link auf die App ist der Pages-Link, in diesem Fall https://luziagu.github.io//EIA2/Sequenzememory/sequencememory.html
5. Lasse Event-Handler immer das event entgegen nehmen, auch wenn damit gar nichts gemacht wird. Damit ist beim Lesen des Codes klar, dass es sich um einen Handler handelt und ggf. kann man sofort noch entsprechende Funktionalität nachträglich implementieren.
6. In `shuffleCharacters` stehen Variablendeklarationen ohne Typangabe. Dein Linter sollte hier eigentlich motzen, tut er das nicht? Bitte korrigiere das.
7. Vergiss nicht am Ende auch Schreibfehler in den angezeigten Texten zu korrigieren.

**Comment by luziagu** [comment]
Vielen Dank Jirka für das ausführliche Feedback!
