### ISSUE TITLE
Eventlistener an Memorykarten

### ISSUE THREAD

**Issue by hannahdue** [JirkaDellOro/EIA2-Inverted#91]
Hallo,
ich habe die einzelnen Buchstabe aus der gewählten Sequenz nun folgendermaßen als Memorykarten auf der Spielfläche eingefügt:
<img width="666" alt="Bildschirmfoto 2020-05-01 um 18 36 28" src="https://user-images.githubusercontent.com/56439564/80822505-28649300-8bdb-11ea-84ec-5b7078918088.png">

Nun weiß ich nicht, wie ich an die einzelnen Spans von den Buchstaben Eventlistener anbringen kann, sodass ich sie anklicken kann und entsprechend damit weitermachen (Klasse toggeln, gucken ob richtig oder falsch...).
Kann mir da jemand weiterhelfen?
Danke! Hannah

**Comment by Plagiatus** [comment]
statt über text das span zu erschaffen, ist es vllt besser es über `document.createElement` zu machen. dadurch hast du das Element direkt in der Hand und kannst den Eventlistener hinzufügen.

**Comment by JirkaDellOro** [comment]
Leider finde ich dein Konzept nicht auf Github. Wir können nur optimal helfen, wenn wir sehen was Du vorhast. 

Statt Listener an die `span`-Elemente zu hängen könntest Du auch einen einzigen an deren Elternelement, also `memoryCards` installieren und die Clicks dort abfangen.

PS: Du hast im Code Variablendeklarationen ohne Typangabe, dein Linter meckert. Korrigiere das bitte.
