### ISSUE TITLE
ts datei 

### ISSUE THREAD

**Issue by buluthil** [JirkaDellOro/EIA2-Inverted#92]
Hallo :)

Ich habe eine neue ts Datei angelegt doch die js Dateien sind nicht zu sehen warum ?

**Comment by buluthil** [comment]
<img width="1440" alt="Bildschirmfoto 2020-05-01 um 19 13 51" src="https://user-images.githubusercontent.com/43846406/80825691-2ef60900-8be1-11ea-8ca1-8d4e99a32d04.png">

**Comment by Plagiatus** [comment]
tsc sagt in deiner Konsole "Befehl nicht gefunden". hast du den Typescript Compiler korrekt installiert?

**Comment by Plagiatus** [comment]
Außerdem würde ich dir empfehlen, dir Ordner für die einzelnen Aufgaben anzulegen, sonst gibts das schnell eine große Unübersichtliche Masse.

**Comment by buluthil** [comment]
Ich habe Node js installiert und jetzt funktioniert es danke dir :)
