### ISSUE TITLE
verwendung eines KeyCodes

### ISSUE THREAD

**Issue by FrankeSa** [JirkaDellOro/EIA2-Inverted#93]
Hallo,

ich würde gerne beim drücken der T Taste eine Funktion ausführen bzw. erstmal nur eine Ausgabe anzeigen lassen. Ich habe auf w3 schools etwas recherchiert und das hier gefunden.  
![image](https://user-images.githubusercontent.com/56167839/80866861-5a383100-8c91-11ea-9c9f-fc1929b34f88.png) 
Aktuell sieht mein code so aus.
![image](https://user-images.githubusercontent.com/56167839/80866879-72a84b80-8c91-11ea-8afe-5535cecee4b1.png)

wie ist die Anwendung richtig? 

Danke schon mal im Voraus. 

link zum Repo: https://github.com/FrankeSa/EA2-Inverted/tree/master/L02_Sequenzmemory

**Comment by JirkaDellOro** [comment]
Super, dass Du dich reinhängst und recherchierst. Folgendes passt noch nicht:
- der keyCode ist vom Typ number
- viel einfacher und intuitiver wird es sein, wenn Du einfach die Eigenschaft `key` des Events nutzt, dass ist ein String mit dem gedrückten Zeichen, dass kannst Du dann gegen dein "t" vergleichen.
- das Schlüsselwort `var` soll heutzutage nur für spezielle Zwecke genutzt werden, allgemein nimmst Du `let`
- sehr gut, dass Du nicht die Listenerinstallation im HTML implementierst, wie w3schools das blöderweise vorschlägt.

**Comment by AnnaLotz** [comment]
Du musst dich beim Beschreiben der Variable `key` auf das bestimmte Event beziehen, dass in der Funktion ankommt. Achte darauf, wie die Variable geschrieben wird, die an die Funktion übergeben wird.

**Comment by JirkaDellOro** [comment]
Siehe auch https://github.com/JirkaDellOro/EIA2-Inverted/blob/a6a5a09e787342a8b7609441e7532b3b5dace3c9/X00_Code/L02_Events/BlackmailerCompanion/BlackmailerCompanion.ts#L28

**Comment by JirkaDellOro** [comment]
> Du musst dich beim Beschreiben der Variable `key` auf das bestimmte Event beziehen, dass in der Funktion ankommt. Achte darauf, wie die Variable geschrieben wird, die an die Funktion übergeben wird.

Den Schreibfehler hatte ich noch übersehen, Anna hat ihn erwischt!
