### ISSUE TITLE
For loop wird nicht ausgeführt

### ISSUE THREAD

**Issue by maxbuchwald** [JirkaDellOro/EIA2-Inverted#94]
Leider verstehe ich nicht warum meine For Schleife bei der Funktion start Game nicht ausgeführt wird. 
Zumindest 
In den Kommentaren im Code sind meine vorherige Versuche. Bin ich damit besser gefahren? 

https://github.com/maxbuchwald/EIA2/tree/master/Aufgabe_02/Memory

Danke im Voraus!

**Comment by JirkaDellOro** [comment]
Da steht 
```typescript
        for (let i: number = 0; i > arraylength; i++)`
```
Das heißt, die Schleife wird ausgeführt, solange der Wert von `i` größer ist als der Wert von `arraylength`. `i` wird mit dem Wert 0 gestartet. Die Schleife wird also nur ausgeführt, wenn arraylength einen negativen Wert hat. Ist das so?

**Comment by maxbuchwald** [comment]
Danke hat sich dadurch geklärt
