### ISSUE TITLE
L03 FormElements – Code zum laufen bringen  

### ISSUE THREAD

**Issue by luziagu** [JirkaDellOro/EIA2-Inverted#95]
Hei! 

Ich versuche gerade den Code zur Lektion drei zum laufen zu bringen, allerdings erscheint im HTML- Dokument immer folgendes: 

![Bildschirmfoto 2020-05-04 um 08 50 25](https://user-images.githubusercontent.com/56430460/80942221-8912ec00-8de4-11ea-8627-0472360a67f3.png)

Was bedeutet dies? Ist das gewollt? 

https://github.com/luziagu/EIA2/tree/master/L03_FormElements

**Comment by JirkaDellOro** [comment]
Nein, das ist nicht gewollt und hat auch nicht in erster Linie etwas mit dem Code zu tun. Der Fehler kommt vom Live-Server-Plugin, ich konnte ihn bei mir reproduzieren. 

Bitte ziehe einfach die HTML-Datei in deinen Browser um zu testen.

**Comment by JirkaDellOro** [comment]
Ich habe gerade in der CSS-Datei geändert, `display: block` nicht für alle Elemente `*`, sondern für `body` gelten soll. LiveServer frisst das nun, vielleicht ist damit dessen Problem gelöst...

**Comment by luziagu** [comment]
Super, danke! :)
