### ISSUE TITLE
Fehlercode bei L03

### ISSUE THREAD

**Issue by DominikWieck** [JirkaDellOro/EIA2-Inverted#96]
Hi zusammen,

irgendwie bekomme ich das CSS nicht zum laufen obwohl ich alles kopiert habe. 
Folgende Fehlermeldung kommt in der Console: 

![image](https://user-images.githubusercontent.com/56441910/80984469-2e05e700-8e2e-11ea-98da-0eaee145d905.png)

Danke schonmal! :)

**Comment by JirkaDellOro** [comment]
Leider kann ich bei dir kein EIA2-Repository finden, in dem ich nachschauen könnte, was Du gemacht hast. Mir fällt bei der Fehlermeldung auf, dass scheinbar nach einer Datei "cocktail.css" gesucht wird. Üblicherweise verwende ich Großbuchstaben am Beginn des Dateinamens. Das sollte man prüfen.
