### ISSUE TITLE
Lektion_03 Formdata 

### ISSUE THREAD

**Issue by smo-haenle** [JirkaDellOro/EIA2-Inverted#97]
<img width="828" alt="Bildschirmfoto 2020-05-05 um 11 47 18" src="https://user-images.githubusercontent.com/56439337/81054045-5e995f80-8ec6-11ea-9910-01164675dda6.png">

Hey, 
hab folgendes Problem und bekomm deshalb meinen Code nicht zum laufen.
Vielleicht bin ich dumm.

Repo zu Lektion_03
https://github.com/smo-haenle/smo-haenle.github.io/tree/master/Eia2/Lektion%203

**Comment by Plagiatus** [comment]
Das ist nicht der Repo link zur Lektion 3. Das hier ist er: https://github.com/smo-haenle/smo-haenle.github.io/tree/master/Eia2/Lektion%203
Und ich nehme an du sprichst von `Cocktails.ts`?

**Comment by smo-haenle** [comment]
ouh tut mir leid, ja geht um Cocktail.ts.

**Comment by JirkaDellOro** [comment]
Verwende bitte zum Coden das vorgeschriebene Setup bezüglich der Konfiguration von Typescript und dem Linter. Melde dich wieder, falls es dann immer noch nicht geht.

**Comment by DominikWieck** [comment]
Habe dasselbe Problem :/

**Comment by JirkaDellOro** [comment]
@DominikWieck wenn Du Hilfe möchtest, stelle uns hier Zugänge zu der entsprechenden Problemstelle zur Verfügung.

**Comment by luziagu** [comment]
Auch ich habe jetzt das selbe Problem. Haben die anderen das Problem beheben können? 

Link zum Script: https://github.com/luziagu/EIA2/blob/master/Formular/script.ts
Link zum Repo: https://github.com/luziagu/EIA2/tree/master/Formular

**Comment by JirkaDellOro** [comment]
> Verwende bitte zum Coden das vorgeschriebene Setup bezüglich der Konfiguration von Typescript und dem Linter. Melde dich wieder, falls es dann immer noch nicht geht.

Ihr verwendet nicht die EIA2-Konfigurationsdateien!

**Comment by luziagu** [comment]
Was ist damit gemeint Jirka? Vielleicht eine blöde frage, aber was ist das vorgeschriebene Setup?

**Comment by JirkaDellOro** [comment]
Siehe Punkt 6 in https://github.com/JirkaDellOro/EIA2-Inverted/wiki/L00_Preparation

**Comment by luziagu** [comment]
Punkt 6 ist bei mir aber der Fall. Beides ist installiert und in meiner Datei enthalten.

**Comment by JirkaDellOro** [comment]
Zumindest die tsconfig.json stimmt nicht mit der Vorlage aus dem EIA2-Inverted-Repository überein.

**Comment by luziagu** [comment]
Die Datei stimmt jetzt mit der aus dem EIA2-Inverted-Repository überein. Allerdings zeigt es mir jetzt nur noch Fehler in meinem Script an die davor nicht da waren. Woran liegt das und wie kann ich dieses Problem beheben, damit ich mit der eigentlichen Aufgabe fortfahren kann. 

Danke im Voraus. 


<img width="1365" alt="Bildschirmfoto 2020-05-12 um 12 08 51" src="https://user-images.githubusercontent.com/56430460/81672462-746cce80-944a-11ea-93dc-08a3ab6afd50.png">

Link zum Script: https://github.com/luziagu/EIA2/blob/master/Formular/script.ts
Link zum Repo: https://github.com/luziagu/EIA2/tree/master/Formular

**Comment by luziagu** [comment]
![IMG_4550](https://user-images.githubusercontent.com/56430460/81675592-56ee3380-944f-11ea-8145-0af2394fb5c6.jpg)

Das wird mir ebenso kurz angezeigt wenn ich >RunBuildTask starte.

**Comment by JirkaDellOro** [comment]
In tsconfig.json ist mit `"strictNullChecks": true` festgelegt, dass TypeScript dich warnen soll, wenn Du Gefahr läufst, mit undefinierten (`null`) Werten zu arbeiten. Anweisungen wie `document.querySelector("#addItem");` könnten durchaus ein `null` liefern, wenn das gesuchte Element nicht gefunden wird. Es gibt hier nun mehrere Möglichkeiten damit umzugehen.

1. Du bringst deinen Variablen bei, auch den Wert `null` annehmen zu können und prüfst, ob sie einen gültigen Wert haben, wenn Du etwas mit ihnen machst. Also z.B.
```typescript
let addButtonItem: HTMLElement | null; 
addButtonItem = document.querySelector("#addItem");
if (addButtonItem)
   addButtonItem.addEventListener("click", addNewRowShopping);
`` 

2. Du versicherst TypeScript dass Du weißt, dass querySelector ein gültiges Element liefern wird. Das machst Du mit einer Type-Assertion (<...>), woraufhin TypeScript dir die Kontrolle überlässt. z.B. so:
```typscript
    addButtonTask = <HTMLElement>document.querySelector("#addTask");
```

3. Du schaltest das Feature in der tsconfig-Datei ab, in dem Du den Wert `false` einträgst.

Lösung 1 ist die ganz brave und ausführliche, 2 ist akzeptabel, wenn Du sicher bist, 3 solltest Du nicht tun, weil TypeScript dir dann diesbezüglich in Zukunft nicht mehr helfen wird.

**Comment by luziagu** [comment]
Okay vielen Dank! :)

**Comment by luziagu** [comment]
Bei den selektierten Elementen hat das alles sehr gut funktioniert. 
Allerdings bekomme ich jetzt Probleme bei dem Klonen. Auch hier wird mir angezeigt "Object ist possible null". Wie kann ich dies umgehen? Ich habe erstes und zweites von oben ausprobiert, aber die Fehlermeldung bleibt dennoch. 

<img width="656" alt="Bildschirmfoto 2020-05-13 um 10 07 36" src="https://user-images.githubusercontent.com/56430460/81787772-d5a3a900-9501-11ea-9f9e-6684b73c2b65.png">

**Comment by JirkaDellOro** [comment]
Wo genau kommen die Fehler? cloneNode gibt einen Node zurück, null ist nicht vorgesehen. 

Fehlerquellen:
- Deine Deklaration von p_prime oben allerdings geschieht im if-Block und daher wird p_prime für das appendChild nicht mehr zur Verfügung stehen.
- getElementById kann null liefern, wenn das Element nicht gefunden wird. Daher solltest Du nicht gleich appendChild darauf ausführen. Wenn Du aber sicher bist kannst Du analog zu anderen Lösung folgendes schreiben:

`(<HTMLElement>document.getElementById(...)) . appendChild(...);`

Beachte die Klammersetzung! Es wird also zuächst behauptet, dass was auch immer von getElementById geliefert wird, als HTMLElement zu behandeln ist. Dann wird darauf appendChild ausgeführt.
