### ISSUE TITLE
Radio Button standardmäßig deaktiviert?

### ISSUE THREAD

**Issue by Majoo44** [JirkaDellOro/EIA2-Inverted#98]
Kann man standardmäßig keinen der x Radio Buttons ausgewählt haben? Wenn ja, passiert das dann im JS oder in HTML, und wie? Hab eben in Google nichts gefunden :o

**Comment by Plagiatus** [comment]
HTML: `checked` Attribut  
https://www.w3schools.com/tags/att_input_checked.asp

**Comment by Majoo44** [comment]
Schön von dir zu hören Lukas :P 
Danke, hat geklappt, habe einfach das "checked" bei input radio weggelassen
