### ISSUE TITLE
L03_Haushaltshilfe:Formular

### ISSUE THREAD

**Issue by maxbuchwald** [JirkaDellOro/EIA2-Inverted#99]
Bekomme in der Konsole die Meldung "Cannot read property 'getAttribute' of null" solange kein Produkt bei der Datalist "supermarket" eingegeben ist. 
Wie ich kann ich das beheben ohne dem input-Element ein value zu vergeben (wie bei der Datalist "Household help")?

Bei dem Stepper bekomme ich die gleiche Fehlermeldung. Mit dem Code aus der Lektion kann ich nicht auf den eingeben Wert zugreifen. Wie kann ich das beheben? 

![image](https://user-images.githubusercontent.com/32566080/81343375-2dcb4d00-90b5-11ea-8a9d-72d8c7c0b7be.png)

https://github.com/maxbuchwald/EIA2/tree/master/Aufgabe_03/Nachbarschaftshilfe

Danke im Vorraus

**Comment by JirkaDellOro** [comment]
Gerne helfen wir dir, dafür müssen wir aber
- dein Konzept einsehen, was der wichtigere Teil der Lösung ist, wo finden wir das?
- das Programm laufen lassen, um den Fehler zu provozieren und debuggen zu können. Wo ist der Link hierfür?

**Comment by maxbuchwald** [comment]
Das Konzept und den Code hatte ich bereits verliinkt. Hier aber nochmal die Links für das Program:

https://maxbuchwald.github.io/EIA2/Aufgabe_03/Nachbarschaftshilfe/index.html

https://maxbuchwald.github.io/EIA2/Aufgabe_03/Nachbarschaftshilfe/Coronahilfe_Konzept.html

https://github.com/maxbuchwald/EIA2/tree/master/Aufgabe_03/Nachbarschaftshilfe

**Comment by JirkaDellOro** [comment]
Das ist kein Konzept sondern lediglich der erste Schritt dorthin, ein Use-Case-Diagram.

**Comment by maxbuchwald** [comment]
Das UI-Diagram und Aktivitätsdiagram findest du wenn du runterscrollst. Oder habe ich einen Fehler gemacht?

**Comment by JirkaDellOro** [comment]
Nein ich.... wie doof. Das Abgabeformat als HTML war zu ungewöhnlich. Ich schaue es mir an.

**Comment by JirkaDellOro** [comment]
Es gibt kein Datalist-Event, fürchte ich. Wann und wie soll ein Shopping-Item bestellt werden. Im Scribble ist nichts vorgesehen, die Aktivitätsdiagramme deuten aber darauf hin, dass mehrere Items existieren können (was Teil der Aufgabe ist). Die Bedienung und Verwaltung ist nicht erkennbar...

**Comment by maxbuchwald** [comment]
Dennis konnte mir bei dem Problem weiter helfen. Hat sich soweit erledigt :)

**Comment by JirkaDellOro** [comment]
Bitte den Issue schließen, wenn er wirklich durch ist.

**Comment by KohlerAl** [comment]
Hallo, 
ich habe ein ähnliches Problem. Die Slider erzeugen bei mir einen Error in der Console. Theoretisch soll der Nutzer die Daten eingeben und dann auf einen Button klicken, um den Eintrag in die Liste hinzuzufügen. Das funktioniert auch, die Werte sind alle da und werden so angezeigt, wie ich es geplant habe. Trotzdem würde mich interessieren, was ich tun muss, um den Error zu verhindern. 
Hier sind die Links zu meiner Konzeption und zum Code:
https://kohleral.github.io/EIA2/L03_FormElements/L03_Haushaltshilfe/L03_UseCase.png
https://kohleral.github.io/EIA2/L03_FormElements/L03_Haushaltshilfe/L03_Haushaltshilfe_UI-Scribble.png
https://kohleral.github.io/EIA2/L03_FormElements/L03_Haushaltshilfe/L03_Haushaltshilfe_AD.svg
https://kohleral.github.io/EIA2/L03_FormElements/L03_Haushaltshilfe/Haushaltshilfe.html
LG Alida

**Comment by JirkaDellOro** [comment]
Meinst Du den?

Haushaltshilfe.ts:70 Uncaught TypeError: Cannot read property 'getAttribute' of null
    at HTMLButtonElement.handleChange (Haushaltshilfe.ts:70)

**Comment by KohlerAl** [comment]
Genau

**Comment by JirkaDellOro** [comment]
```typescript
        for (let entry of formData) {
            // Erstellen einer Variable mit dem Wert des Eintrags
            let select: string = "[value='" + entry[1] + "']";
            // Selektieren des HTML-Elements mit dem entsprechenden Wert
            let item: HTMLInputElement = <HTMLInputElement>document.querySelector(select); 
            // Suchen nach dem Preis-Attribut 
            let itemPrice: number = Number(item.getAttribute("price")); 
...
```

Du gehts alle Einträge von Formdata durch und holst dir das entsprechende Input-Element. Dann greifst Du bei jedem auf das Attribut "price" zu. Nicht alle haben aber dieses Attribut, der Supermarkt beispielsweise nicht. Du musst also Sonderbehandlungen vornehmen, wie bei den Drinks in der Cocktailbar.

PS: nenne die Variable besser um in `selector`, es ist furchtbar irritierend wenn `querySelector` nicht nach einem Select-Element sucht obwohl `select` als Parameter drinsteht...

**Comment by KohlerAl** [comment]
Danke für das Feedback :)

**Comment by KohlerAl** [comment]
Es funktioniert jetzt :) Danke nochmal
